
/********************************************************************20**

     Name:     EnodeB Application

     Type:     C include file

     Desc:     This file contains 
               

     File:     wr_umm_x2srcho.h

     Sid:      $SID$ 

     Prg:      Sriky 

*********************************************************************21*/
#include "wr.h"
#include "wr_cmn.h"
#ifndef __WR_UMM_X2SRCHO_H__
#define __WR_UMM_X2SRCHO_H__

#ifdef __cplusplus
extern "C" {
#endif

#define WR_UMM_X2_SRC_HANDLE_HO_FAIL(_transCb)\
{\
   _transCb->ueCb->hoTransId = 0;\
   _transCb->ueCb->x2ConCb.oldEnbUeX2apId = 0;\
   _transCb->ueCb->x2ConCb.newEnbUeX2apId = 0;\
   _transCb->ueCb->x2ConCb.peerId = 0;\
   _transCb->ueCb->hoType = WR_HO_TYPE_NONE;\
   _transCb->ueCb->mobCtrlState = WR_HO_NORMAL;\
}

/**
 * @brief
 *    This structure contains RAB information
 *
 * @details
 *    These are the structure members
 * -U8              erabId                  E-Rab Id
 * -U8              rbId                    DRB ID
 * -U8              rbDir                   Direction Of Bearer
 * -U8              qci                     Quality Channel Indicator
 * -U8              tnlCfgState             Tunnel Configuration State
 * -U8              expectedTnlRsp          Expected Tunnel Response
 * -U8              dlFwding                Indicating DL Data Forwarding is
 *                                          available or not
 * -U8              peerAddr                Destination Address
 * -U8              datFwdUlRemTunId        UL Remote Tunnel ID
 * -U8              datFwdDlRemTunId        DL Remote Tunnel ID
 * -U8              datFwdUlLclTunId        UL Local Tunnel Id
 * -U8              datFwdDlLclTunId        Dl Local Tunnel Id
 */
typedef struct wrUmmX2SrcHoRabInfo
{
   U8                        erabId;
   U8                        rbId;
   U8                        rbDir;
   U8                        qci;
   U8                        tnlCfgState;
   U8                        expectedTnlRsp;
   Bool                      dlFwding;
   CmTptAddr                 peerAddr;
   U32                       datFwdUlRemTunId; 
   U32                       datFwdDlRemTunId; 
   U32                       datFwdUlLclTunId; 
   U32                       datFwdDlLclTunId; 
   Bool                      isULDatFwdReq; /* Set to TRUE only if Targe trequested for UL Data Forwarding */
} WrUmmX2SrcHoRabInfo;
/**
 * @brief
 *    This structure contains Source Handover Transaction information
 *
 * @details
 *    These are the structure members
 * -U32                           state                  Transaction State
 * -U32                           crnti                  crnti of UE
 * -U32                           cellId                 cellId
 * -U32                           peerId
 * -U32                           old_eNB_UE_X2ap_Id     Old eNB UE X2ap ID
 *                                                       Generated by source eNB
 * -U32                           new_eNB_UE_X2ap_Id     New eNB UE X2ap ID
 * -WrUmmMsgCause                 cztCause               Cause Value given by HO
 *                                                       Decision module.
 * -WrEcgi                        ecgi                   Cell Global Identity 
 * -U8                            numOfRbInfo            Num of Rab
 * -WrUmmX2SrcHoRabInfo           *rbInfo                RAB Information
 * -TknStrOSXL                    srcToTgtCntr           Source To Target
 *                                                       Container
 * -CztE_RAB_Lst                  *cztE_RAB_Lst          Not Admited List.
 * -CztTgeteNBtoSrc_eNBTprntCont  *tgetToSrcTprntCont    Tgt To Src container  
 * -WrUmmIncMsg                   *msg                   Incoming Message
 *  U8                            henbGwCtxtRelRequired  Flag to indicate
 *                                                       if GW Cntxt Rel Ind
 *                                                       IE needs to be included
 *                                                       in UE CTXT rel message
 *                                  
 */
typedef struct wrUmmX2SrcHoTrans
{
   U32                           state;
   U32                           crnti;
   U32                           cellId;
   U32                           peerId;
   U32                           old_eNB_UE_X2ap_Id;
   U32                           new_eNB_UE_X2ap_Id;
   WrUmmMsgCause                 cztCause;
   WrEcgi                        ecgi;
   /* ccpu00126532 */
   U16                           targetPci;
   U32                           targetEarfcnDl;
   U8                            enbType;
   U8                            numOfRbInfo;
   WrUmmX2SrcHoRabInfo           *rbInfo;
   TknStrOSXL                    srcToTgtCntr;
   CztE_RAB_Lst                  *cztE_RAB_Lst;
   CztTgeteNBtoSrc_eNBTprntCont  *tgetToSrcTprntCont;
   WrUmmIncMsg                   *msg;
   /* X2_HO Changes for Falcon */
   Buffer                        *hoCmd;
   /* ccpu00126532 */
   /* Key derived from base key and Target PCI and Taret DL EARFCN values */
   U8                            kEnbStar[WR_KENB_KEY_LEN];
   /*ccpu00128988*/
#ifdef TENB_AS_SECURITY
   Bool                          isKenbKeyGenerated;
   Bool                          isRrcContrPrepared;
#endif
   WrUmmIncMsg                   *rrcContrMsg;
   /* CSG_DEV start */
   U32                           csgId; /* CSG ID */
   U8                            csgCellAccessMode; /* CSG Access Mode */
   /* CSG_DEV end */
   U8                            henbGwCtxtRelRequired;
} WrUmmX2SrcHoTrans;

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif  /* end of __WR_UMM_X2SRCHO_H__ */


/********************************************************************30**

           End of file:    $SID$

*********************************************************************31*/


/********************************************************************40**
  
        Notes:
  
*********************************************************************41*/

/********************************************************************50**

*********************************************************************51*/

   
/********************************************************************60**
  
        Revision history:
  
*********************************************************************61*/
  
/********************************************************************90**
 
     ver       pat    init                  description
------------ -------- ---- ----------------------------------------------
$SID$        ---      Sriky         1. initial release TotaleNodeB 1.1
*********************************************************************91*/
