#!/bin/sh
#
# PostInstallScript
#
# If present in an update package this script will be
# extracted and executed after the "inner tarball" is
# extracted to /mnt but before dbx_start is executed 
# to start the newly installed application package

echo "Running Post Install Script for V2.1+"

FLASH_DIR=/mnt
APP_DIR=/mnt/dbx
FLASH_DIR_CFG=$FLASH_DIR/config
ACTIVE_APP_PACKAGE=`cat $FLASH_DIR_CFG/app_package_active | tr -d "\n\r\t "`
KERNEL_DIR=$FLASH_DIR/install/kernel

# Try to make sure FAP leaves factory with both application banks fully populated
FACTORY=`grep 'hbs2-factory' /mnt/bank-active/etc/build-version.txt`
if [ "$FACTORY" ] ; then
	if [ ! -e $FLASH_DIR/bank-active/app_package_valid ] ; then
                cp -rf $FLASH_DIR/install/* /mnt/bank-active
        fi

        if [ "$ACTIVE_APP_PACKAGE" = 'AppImageA' ] ; then
                KERNEL=kernela
        else
		KERNEL=kernelb
	fi
	KERNEL_IMAGE=`ls $KERNEL_DIR/uImage*`

	/mnt/dbx/fap-flash $KERNEL $KERNEL_IMAGE
fi

# Check for correct u-boot version and update if necessary
UBOOT_IMAGE_VERSION=`cd $KERNEL_DIR && ls u-boot* | tr -cd '[[:digit:]]'`
UBOOT_IMAGE=`cd $KERNEL_DIR && ls u-boot*` 
INSTALLED_UBOOT_IMAGE_VERSION=`/mnt/dbx/fap-flash u-bootenvread ubootImageFileName | tr -cd '[[:digit:]]'`

echo "u-boot version in image is $UBOOT_IMAGE_VERSION"
echo "u-boot image is $UBOOT_IMAGE"
echo "installed u-boot version is $INSTALLED_UBOOT_IMAGE_VERSION"

if [ "$UBOOT_IMAGE" ] ; then
	if [ "$INSTALLED_UBOOT_IMAGE_VERSION" -a "$UBOOT_IMAGE_VERSION" ] ; then	
		if [ $UBOOT_IMAGE_VERSION -gt $INSTALLED_UBOOT_IMAGE_VERSION ] ; then 
			echo "Installed u-boot version is older than u-boot version in image."
			echo "Updating u-boot to $KERNEL_DIR/$UBOOT_IMAGE" 
			/mnt/dbx/fap-flash u-boot $KERNEL_DIR/$UBOOT_IMAGE
		else
			echo "Installed u-boot version is not older than u-boot version in image, not updating."
		fi
	else
		echo "Couldn't determine installed and/or image u-boot version(s)."
		echo "Updating u-boot to $KERNEL_DIR/$UBOOT_IMAGE"
		/mnt/dbx/fap-flash u-boot $KERNEL_DIR/$UBOOT_IMAGE
	fi	
else
	echo "Couldn't find a u-boot image!"
fi


# Modify "local config"
# 33554432 = 02 01 00 00
echo "SOFTWARE_RELEASE = 33619968" >> /tmp/software-release
mv -f /tmp/software-release /mnt/install/config/software-release

echo "Completed Post Install Script for V2.1+"
