#!/bin/csh 
#
# update all files
#
set PRROOT=/clearcase/tds/core_prd/crnt/voip/sctp/src 
set CMROOT=/clearcase/tds/core_prd/crnt/cm
set SCTPROOT=/clearcase/tds/core_prd/crnt/voip/sctp/src

if($#argv == 1) then
  if($1 == "-n") then
    set CMROOT=/clearcase/tds/core_prd/next/cm
    set PRROOT=/clearcase/tds/core_prd/next/voip/sctp/src
    set SCTPROOT=/clearcase/tds/core_prd/next/voip/sctp/src
  endif

  if($1 == "-view") then
    set CMROOT=/vobs/core_prd/cm
    set PRROOT=/vobs/core_prd/voip/sctp/src
    set SCTPROOT=/vobs/core_prd/voip/sctp/src
  endif
endif

chmod 755 *
cp $PRROOT/acc/* . 
cp $PRROOT/sample/* .
cp $PRROOT/??/* . 
cp $PRROOT/build/* . 
chmod 755  *

