#!/bin/csh 
#
# update common files
#
set CMROOT=/clearcase/tds/core_prd/crnt/cm
if($#argv == 1) then
if($1 == "-n") then
  set CMROOT=/clearcase/tds/core_prd/next/cm
endif

if($1 == "-view") then
set CMROOT=/vobs/core_prd/cm
endif
endif

cp $CMROOT/tech/cm_cm/src/cm_gen.c .
cp $CMROOT/tech/cm_cm/src/ss_ptsp.c .
cp $CMROOT/lib/cm_lib/src/cm_lib.c .
cp $CMROOT/lib/cm_lib/src/cm_lib.x .
cp $CMROOT/lib/timer/src/cm5.h .
cp $CMROOT/lib/timer/src/cm_bdy5.c .
cp $CMROOT/lib/timer/src/cm5.x .
cp $CMROOT/inf/cm_tpt/src/cm_tpt.x .
cp $CMROOT/inf/cm_tpt/src/cm_tpt.h .
cp $CMROOT/inf/cm_tpt/src/cm_tpt.c .
cp $CMROOT/lib/cm_llist/src/cm_llist.h .
cp $CMROOT/lib/cm_llist/src/cm_llist.c .
cp $CMROOT/lib/cm_llist/src/cm_llist.x .
cp $CMROOT/lib/cm_inet/src/cm_inet.h .
cp $CMROOT/lib/cm_inet/src/cm_inet.c .
cp $CMROOT/lib/cm_inet/src/cm_inet.x .
cp $CMROOT/lib/cm_hash/src/cm_hash.h .
cp $CMROOT/lib/cm_hash/src/cm_hash.c .
cp $CMROOT/lib/cm_hash/src/cm_hash.x .
cp $CMROOT/lib/mem/src/cm_mem.h .
cp $CMROOT/lib/mem/src/cm_mem.c .
cp $CMROOT/lib/mem/src/cm_mem.x .
cp $CMROOT/tech/cm_cm/src/gen.h .
cp $CMROOT/tech/cm_cm/src/gen.x .
cp $CMROOT/tech/cm_cm/src/ssi.h .
cp $CMROOT/tech/cm_cm/src/ssi.x .
cp $CMROOT/tech/cm_cm/src/cm_err.h .
cp $CMROOT/tech/cm_cm/src/envdep.h .
cp $CMROOT/tech/cm_cm/src/envind.h .
cp $CMROOT/tech/cm_cm/src/envopt.h .
cp $CMROOT/inf/sct/src/sct.h .
cp $CMROOT/inf/sct/src/sct.x .
cp $CMROOT/inf/sct/src/sct.c .
cp $CMROOT/inf/hit/src/hit.c .
cp $CMROOT/inf/hit/src/hit.x .
cp $CMROOT/inf/hit/src/hit.h .
cp $CMROOT/tech/cm_cm/src/sm_bdy1.c .
cp $CMROOT/tech/cm_cm/src/sm_ex_ms.c .
cp $CMROOT/inf/cm_dns/src/cm_dns.c .
cp $CMROOT/inf/cm_dns/src/cm_dns.x .
cp $CMROOT/inf/cm_dns/src/cm_dns.h .
cp $CMROOT/tech/cm_os/src/cm_os.c .
cp $CMROOT/tech/cm_os/src/cm_os.x .
cp $CMROOT/tech/cm_os/src/cm_os.h .
cp $CMROOT/inf/lsb/src/lsb.c .
cp $CMROOT/inf/lsb/src/lsb.x .
cp $CMROOT/inf/lsb/src/lsb.h .
