###############################################################################
#
# hbs2-solo-split makefile
#
# Copyright Radisys Limited
#
###############################################################################

build:
	$(MAKE) -C fap-bits
	$(MAKE) -C i686-bits

clean:
	$(MAKE) -C fap-bits clean
	$(MAKE) -C i686-bits clean

distro:
	$(MAKE) -C fap-bits distro
	$(MAKE) -C i686-bits distro
