#!/bin/sh
#
# PreInstallScript
#
# If present in an update package this script will be
# extracted and executed before the "inner tarball" is
# extracted to /mnt to install a new application package.

echo "Running pre-install script."

# FLASH_DIR=/mnt
# echo "Flash root is " $FLASH_DIR
# FLASH_DIR_CFG=$FLASH_DIR/config
# echo "System config directory is " $FLASH_DIR_CFG 

echo "Finished running pre-install script."


