#!/bin/sh
#
# StopAppsForUpdate

echo "Running script to stop (some) apps for sw update"

APP_FILES="ntp-client oam-rem service-api clogd"

for APP_FILE in $APP_FILES
do
  echo " Killing $APP_FILE ..."
  killall $APP_FILE 2> /dev/null
done


echo "StopAppsForUpdate script complete"
