
#ifndef __RV_BUILD_CONFIG_H__
#define __RV_BUILD_CONFIG_H__

#define RV_DEBUG

#define RV_SIP_AUTH_ON

#define RV_SIP_IMS_ON

#define RV_TOOL_TYPE	RV_TOOL_TYPE_GNU

#define RV_TOOL_VERSION	RV_TOOL_GNU_3_2

#define RV_OS_TYPE		RV_OS_TYPE_LINUX

#define RV_OS_VERSION	RV_OS_LINUX_REDHAT_9

#define RV_ARCH_ENDIAN	RV_ARCH_LITTLE_ENDIAN

#define RV_ARCH_BITS	RV_ARCH_BITS_32

#endif

