###############################################################################
#
# Makefile Options:
#
#  make [clean]
#
# Copyright Radisys Limited
#
###############################################################################

TOP = $(shell pwd)/../../../..

TARGET_NAME = threeway-comms-unittest

include $(TOP)/makefrags/unittest_sharedlibrary.mk
