# 3G-S1AP command file
#
# line syntax:
#  name <text string>
#  part <media part number> <text string>
#  file <file name>
#  options <options>
#
name S1AP
options 00
part 1000361-01 Product Files (sz)
file sz_db.c
file sz_dbr8.c
file sz_dbr9.c
file sz_dbr10.c
file sz_ex_ms.c
file sz.h
file sz_li.c
file sz_mi.c
file sz_ndb.c
file sz_ptmi.c
file sz_sm.c
file sz_smlimme.c
file sz_smuimme.c
file sz_tst.c
file sz_utils.c
file sz_err.h
file sz_ex_pt.c
file sz_id.c
file sz_mgmt.c
file sz_msgfn.c
file sz_ptli.c
file sz_ptui.c
file sz_smlienb.c
file sz_smuienb.c
file sz_tmr.c
file sz_ui.c
file sz.x
file sz.mak
part 1000361-02 Common Files (cm)
file lsz.h
file lsz.x
file lsz.c
file szt_asn.h
file szt_asn.x
file szt.c
file szt.h
file szt_pk.c
file szt_pk.x
file szt_unpk.c
file szt_unpk.x
file szt.x
file sct.h
file sct.x
file sct.c
file cm_tpt.h
file cm_tpt.x
file cm_tpt.c
file envopt.h 
file envdep.h
file envind.h
file gen.h
file gen.x
file ssi.h
file ssi.x
file sm_bdy1.c
file sm_ex_ms.c
file cm5.h
file cm5.x
file cm_lib.x
file cm_lib.c
file cm_hash.h
file cm_hash.x
file cm_hash.c
file cm_inet.h
file cm_inet.x
file cm_inet.c
file cm_dns.c
file cm_dns.h
file cm_dns.x
file cm_bdy5.c
file cm_mblk.h 
file cm_mblk.x 
file cm_mblk.c 
file cm_llist.h
file cm_llist.x
file cm_llist.c
file cm_mem.h
file cm_mem.x
file cm_mem.c
file cm_pint.h
file cm_pint.x
file cm_perr.h
file cm_pasn.h
file cm_pasn.x
file cm_pasn1.c
file cm_pasn2.c
file cm_pasn3.c
file cm_pasn4.c
file cm_err.h
file cm_tkns.h
file cm_tkns.x
file cm_tkns.c
file cm_gen.h
file cm_gen.c
file ss_ptsp.c
file cm_umts.c 
file cm_umts.h
file cm_umts.x
file cm_xta_checkfile.py
file cm_xta_cmdmap.py
file cm_xta_genattr.py
file cm_xta_gen_cmd.py
file cm_xta_gen_tc_num.py
file cm_xta_pyattr.py
file cm_xta_pycmd.py
file cm_xta_py.py
file cm_xta_tc_doc.py
file cm_xta_tc_xmldoc.py
file cm_xta_dum.c
file cm_xta_ex_ms.c
file cm_xta_flag.c
file cm_xta.h
file cm_xta_inthdl.c
file cm_xta_intreg.c
file cm_xta_intutl.c
file cm_xta_ipc.c
file cm_xta_ldfsm.c
file cm_xta_log.c
file cm_xta_master.c
file cm_xta_py.c
file cm_xta_py.x
file cm_xta_queue.c
file cm_xta_reg.c
file cm_xta_res.c
file cm_xta_slave.c
file cm_xta_tafsm.c
file cm_xta_tcfsm.c
file cm_xta_tgfsm.c
file cm_xta_tmr.c
file cm_xta_tst.c
file cm_xta_txn.c
file cm_xta.x
file cm_xta_xml.c
part 1000361-03 Sample Files (acc)
file cm_xta_app.h
file szac_flag.c
file szac_db.c
file szac_lhiutl.c
file szac_lsbreg.c
file szac_lszhdl.c
file szac_prof.c
file szac_sctutl.c
file szac_sctptui.c
file szac_szthdl.c
file szac_tst.c
file cm_xta_app.x
file szac_lhicb.c
file szac_lhi.x
file szac_lsbutl.c
file szac_lszreg.c
file szac_sctcb.c
file szac_sct.x
file szac_sztreg.c
file szac_acc.h
file szac_lhihdl.c
file szac_lsbcb.c
file szac_lsb.x
file szac_lszutl.c
file szac_scthdl.c
file szac_szld.c
file szac_sztutl.c
file szac_acc.x
file szac_lhireg.c
file szac_lsbhdl.c
file szac_lszcb.c
file szac_lsz.x
file szac_sctreg.c
file szac_sztcb.c
file szac_szt.x
file szac_cmd1.xml
file szac_tc1.xml
file szac_cmd2.xml
file szac_tg1.xml
part 1000361-04 Sample Files (sm)
file envopt.acc
file smszbdy1.c
file smsz_err.h
file smszexms.c
file smszptmi.c
file szac_sb_ex_ms.c
file uz_ex_ms.c
file uz_ptli.c
file uz.x
part 1000361-04 Documentation Files
file 1091361.41
file 1092361.41
file 1093361.41
file 1094361.41
file 1095361.41
file 1225361.41
file 1100031.110
file 1100036.16
file 1111001.312a
file 1111010.16
file 1100076.41
file 1111011.111a 
