#!/bin/sh
#
# $LastChangedRevision: 9010 $
#
# Report version headers from FPGA image files to stdout
#

FPGA=/mnt/bank-active/fpga

for F in `ls $FPGA/*.bgz` ; do

  echo $F
  gunzip -c $F | $FPGA/bitpeel - > /dev/null 2> /tmp/.report
  cat /tmp/.report
  md5sum $F
done

rm -f /tmp/.report

# END OF SCRIPT
