#!/bin/sh
#Compilation script for building openssl-0.9.8
#############################################################################################
mkdir `pwd`/../openssl-0.9.8/
mkdir `pwd`/../openssl-0.9.8/openssl-0.9.8rm/

make clean

./Configure linux-generic32 -DL_ENDIAN shared --openssldir=`pwd`/../openssl-0.9.8/openssl-0.9.8rm/

make LD=mipsel-unknown-linux-gnu-ld ARD="mipsel-unknown-linux-gnu-ar d" AR="mipsel-unknown-linux-gnu-ar r" CC=mipsel-unknown-linux-gnu-gcc RANLIB=mipsel-unknown-linux-gnu-ranlib

make

make install


