#!/bin/sh

#cd $OAM_LOGGING_DIR
# Include kernel messages by popular demand
#cp /var/log/messages env_messages.txt 2>/dev/null
#tar -cvf previouslogs.tar $OAM_LOGGING_DIR/*.txt
#gzip previouslogs.tar
#mkdir -p /mnt/log
#mv previouslogs.tar.gz /mnt/log/previouslogs.tar.gz
#rm -f env_messages.txt
reboot
