#!/bin/sh
#
# $LastChangedRevision$
#

if [ ! $1 ]; then
  echo "Usage: ./platform-summary <filename>"
  exit
fi

rm -f $1
touch $1

echo -e '\n### kernel' >> $1

echo -e '\n## uname' >> $1
uname -a >> $1

echo -e '\n## file contents' >> $1
for FILE in /etc/version;
do
    echo -e -n '\n# ' >> $1
    echo ${FILE} >> $1
    cat ${FILE} >> $1
done

echo -e '\n### software' >> $1

echo -e '\n## directory structure' >> $1
for DIR in /mnt /mnt/AppImageA /mnt/AppImageB;
do
    echo -e -n '\n# ' >> $1
    echo ${DIR} >> $1
    ls -l ${DIR} >> $1
done

echo -e '\n## integrity' >> $1
for DIR in /mnt/AppImageA/dbx /mnt/AppImageB/dbx;
do
    echo -e -n '\n# md5 ' >> $1
    echo ${DIR} >> $1
    md5sum ${DIR}/* >> $1
done

echo -e '\n# file contents' >> $1
for FILE in /mnt/config/app_package_active /mnt/config/app_package_update /mnt/config/app_package_fallback;
do
    echo -e -n '\n# ' >> $1
    echo ${FILE} >> $1
    cat ${FILE} >> $1
done


echo -e '\n### tpm' >> $1
                              
echo -n "BtchId " >> $1                                
/mnt/dbx/cli.sh -c tpm.get-batch-id 2>/dev/null >> $1  
echo -n "FapId  " >> $1                                
/mnt/dbx/cli.sh -c tpm.get-fap-id 2>/dev/null >> $1    
echo -n "FSVer  " >> $1                                
/mnt/dbx/cli.sh -c tpm.get-fs-version 2>/dev/null >> $1
/mnt/dbx/cli.sh -c tpm.info 2>/dev/null >> $1


echo -e '\n### configuration' >> $1

if [ -e /mnt/config/developer ];
then
    echo '!!!!! developer file found' >> $1
fi
exit
