#!/bin/sh
#
# PreInstallScript
#
# If present in an update package this script will be
# extracted and executed before the "inner tarball" is
# extracted to /mnt to install a new application package.

echo "Running pre-install script."

echo "Completed pre-install script."



