###############################################################################
#
# Makefile Options:
#
#  make [clean] [BUILD=<build>]
#
# Copyright Radisys Limited
#
###############################################################################

TOP = $(shell pwd)/../../..
PRODUCT = generic
include $(TOP)/makefrags/products.mk

TARGET_NAME = deserialise-file-store
TARGET_DIR = obj/$(HARDWARE)/$(BUILD)

LIB_DEPS = \
    $(TOP)/libs/common/system/obj/$(HARDWARE)/$(BUILD)/libthreeway-system

SYSTEM_LIBS = pthread

BFIN_UCLINUX_APP_STACK_SIZE = 0x10000

include $(TOP)/makefrags/application.mk
