#!/bin/sh
#
# $LastChangedRevision: 29307 $
#
# This script is called by dbxstart at start up or
# may be run on its own manually.
#

FLASH_DIR=/mnt
FLASH_DIR_APPS=$FLASH_DIR/dbx
FLASH_DIR_CFG=$FLASH_DIR/config
FLASH_DIR_FPGA=$FLASH_DIR/fpga
RUNTIME_DIR=/dbx
TRACE_DIR=/dbx/trace
HWTYPE=`$FLASH_DIR_APPS/mib-firkler -q HARDWARE_TYPE`

##############################################################################

if [ "$HWTYPE" == "5" ] ; then
  # Load REM FPGA image ready for apps
  $FLASH_DIR_APPS/load-fpgas rem
fi

cd $RUNTIME_DIR

# Start the logging daemon
if [ "$HWTYPE" != "5" ] ; then
  $FLASH_DIR_APPS/clogd
fi

# Export HOME so net-snmp can pick up /root/.snmp/3waysnmp.conf
export HOME=/root

# Disable old style firewall if present
if [ "$HWTYPE" == "5" ] ; then
  echo "disabling IP firewall"
  /bin/ipf pass in quick from any to any
  /bin/ipf pass out quick from any to any
fi

# Run script to reconfigure FAP for dual software banks if necessary,
# this only needs to be done once so remove after running.
if [ -f $FLASH_DIR_APPS/init-software-banks ]; then
   $FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/init-software-banks
   rm -f $FLASH_DIR_APPS/init-software-banks
fi

$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/post-kernel-boot-actions

$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/post-office --forever
sleep 1
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/watchdogd
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/oam-rem
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/l1 -msg
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/oam-snmp --eng-mode
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/oam
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/rrc
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/rrm
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/sw-update

# Execute script to create list of processes in dbx/trace
chmod +x ./get-proc-addr
./get-proc-addr &

# END OF SCRIPT
