<?xml version="1.0" encoding="UTF-8"?>
<mib xmlns:mib="http://www.Radisys.com/umts-fap/mib" xsl:version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns="http://www.w3.org/1999/xhtml">
 <noprocess><![CDATA[///////////////////////////////////////////////////////////////////////////////
//
// MibAttributeId.h
//
// IDs of all possible MIB attributes.
// THIS FILE IS AUTOGENERATED
//
// Copyright Radisys Limited
//
///////////////////////////////////////////////////////////////////////////////

#if (!defined(__MibAttributeId_h_) || defined(ENUM_GENERATE_STRINGS) || defined(ENUM_GENERATE_TABLE))

#if (!defined(ENUM_GENERATE_STRINGS) && !defined(ENUM_GENERATE_TABLE))
    #define __MibAttributeId_h_
#endif

///////////////////////////////////////////////////////////////////////////////
// System Includes
///////////////////////////////////////////////////////////////////////////////

#include <system/EnumToString.h>

///////////////////////////////////////////////////////////////////////////////
// Typedefs
///////////////////////////////////////////////////////////////////////////////

#define ParamId MibAttributeId

/**
 * Enumeration of MIB attribute IDs.
 *
 * Macro nastiness allows you to use e.g. MibAttributeIdToString(MIB_ATTR_ID_MCC)
 */]]></noprocess>

 <enumeration>
 <xsl:attribute name="name">MibAttributeId</xsl:attribute>
 <xsl:for-each select="//attributeDefs/attributeDef">
  <enumValue>PARAM_ID_<xsl:value-of select="translate(@name,'abcdefghijklmnopqrstuvwxyz','ABCDEFGHIJKLMNOPQRSTUVWXYZ')"/></enumValue>
 </xsl:for-each>
 <xsl:for-each select="//attributeDefs/attributeEnumDef">
  <enumValue>PARAM_ID_<xsl:value-of select="translate(@name,'abcdefghijklmnopqrstuvwxyz','ABCDEFGHIJKLMNOPQRSTUVWXYZ')"/></enumValue>
 </xsl:for-each>
 <enumValue>NUM_MIB_ATTR_IDS</enumValue>
 <enumValue>PARAM_ID_INVALID</enumValue>
 </enumeration>
 <noprocess><![CDATA[#endif]]></noprocess>
</mib>
