<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:mib="http://www.Radisys.com/umts-fap/mib" xsl:version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns="http://www.w3.org/1999/xhtml" version="1.0">
  <xsl:key name="attribute-definitions" match="attributeDef" use="@validator"/>
  <xsl:template match="/">
    <mib>

      <noprocess><![CDATA[///////////////////////////////////////////////////////////////////////////////
//
// MibValidators.cpp
//
// Instantiations of MIB validators.
// THIS FILE IS AUTOGENERATED
//
// Copyright Radisys Limited
//
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// System Includes
///////////////////////////////////////////////////////////////////////////////

#include <Radisys.h>

#include <mib-common/ValidatorU32.h>
#include <mib-common/ValidatorU32Array.h>
#include <mib-common/ValidatorS32.h>
#include <mib-common/ValidatorS32Array.h>
#include <mib-common/ValidatorString.h>
#include <mib-common/ValidatorStringArray.h>
]]>
<xsl:for-each select="mib:mib/attributeDefs/attributeDef[generate-id() = generate-id(key('attribute-definitions',@validator)[1])]">
#include &lt;mib-common/Validator<xsl:value-of select="@validator"/>.h&gt;
</xsl:for-each>

///////////////////////////////////////////////////////////////////////////////
// Global Validator Instances
///////////////////////////////////////////////////////////////////////////////

ValidatorU32 validatorU32;
ValidatorU32Array validatorU32ARRAY;
ValidatorU32 validatorENUM;
ValidatorU32Array validatorENUMARRAY;
ValidatorS32 validatorS32;
ValidatorS32Array validatorS32ARRAY;
ValidatorString validatorSTRING;
ValidatorStringArray validatorSTRINGARRAY;
<xsl:for-each select="mib:mib/attributeDefs/attributeDef[generate-id() = generate-id(key('attribute-definitions',@validator)[1])]">Validator<xsl:value-of select="@validator"/> validator<xsl:value-of select="@validator"/>;
</xsl:for-each>
</noprocess>
    </mib>

  </xsl:template>
</xsl:stylesheet>

