#!/bin/sh
#
# PostDownloadScript
#
# If present in an update package this script will be
# extracted and executed before any attempt is made to
# start installing the package, i.e. before the bulk of
# the update package is extracted and before any integrity
# or compatibility checking is performed on the package
# as a whole - use with caution!

echo "Running post-download script"

echo "Post-download script complete"