#!/bin/sh
#
# $LastChangedRevision: 26359 $
#
# This script is called by dbxstart at start up or
# may be run on its own manually.
#

FLASH_DIR=/mnt
FLASH_DIR_APPS=$FLASH_DIR/dbx
FLASH_DIR_CFG=$FLASH_DIR/config
FLASH_DIR_FPGA=$FLASH_DIR/fpga
RUNTIME_DIR=/dbx
TRACE_DIR=/dbx/trace

#
##############################################################################

# Load REM FPGA images
$FLASH_DIR_APPS/load-fpgas rem

cd $RUNTIME_DIR
# Export HOME so net-snmp can pick up /root/.snmp/3waysnmp.conf
export HOME=/root

echo "disabling IP firewall"
/bin/ipf pass in quick from any to any
/bin/ipf pass out quick from any to any

#$FLASH_DIR_APPS/mem-monitor &
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/post-office --forever
sleep 1

$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/post-kernel-boot-actions

$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/watchdogd --eng-mode
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/oam-rem
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/l1 -msg
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/oam
sleep 1
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/rrc
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/rrm
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/nas-hlr
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/nas-core
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/nas-ggsn
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/cs-user-plane
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/sw-update

# On 2008R1: Setup the tunnel to allow packet forwarding, unless using InterPeak
lsmod | grep -q ipnet
if [ "$?" = "1" ] ; then
  uname -r | grep -q "2008R1"
  if [ "$?" = "0" ] ; then

    # Load tun kernel module and create device node under /dev
    modprobe tun
    mdev -s

    # Turn on packet forwarding in the kernel
    echo "1" > /proc/sys/net/ipv4/ip_forward

    # Flush any old rules
    iptables -F
    iptables -t nat -F

    # Drop TCP headers with RST flag set
    iptables -A OUTPUT -p tcp --tcp-flags ALL RST -j DROP
    # Setup NAT for the local tunnel endpoints
    iptables -t nat -A POSTROUTING -s 10.0.0.0/8 -o eth0 -j MASQUERADE

    # Run the tunnel app
    $FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/tunnel -f 127.0.0.1
  fi
fi

$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/oam-snmp --eng-mode
$FLASH_DIR_APPS/run-app $FLASH_DIR_APPS/tenpin

# Execute script to create list of processes in dbx/trace
./get-proc-addr &
