#!/bin/sh
#

FLASH_DIR=/mnt
FLASH_DIR_CFG=$FLASH_DIR/config
FLASH_DIR_RADIO_CAL=$FLASH_DIR_CFG/radiocal
TX_RADIO_CAL_FILE=$FLASH_DIR_RADIO_CAL/adf4602_tx.cal
RX_RADIO_CAL_FILE=$FLASH_DIR_RADIO_CAL/adf4602_rx.cal

if [ ! -f $TX_RADIO_CAL_FILE ] ; then
    echo "Warning: Board specific radio Tx calibration data not found. Using defaults..."
fi
if [ ! -f $RX_RADIO_CAL_FILE ] ; then
    echo "Warning: Board specific radio Rx calibration data not found. Using defaults..."
fi
