#!/bin/sh
#
# $LastChangedRevision: 4131 $
#
# ./set-hbs2-ip-config <mac-address> <ip-address> <netmask> <route> <gateway>

mount -t jaffs2 /dev/mtdblock1 /mnt
mkdir -p /mnt/config
cd /mnt/config

echo $1 > eth0_mac_address
echo $2 > eth0_ip_address
echo $3 > eth0_net_mask
echo $4 > eth0_route
echo $5 > eth0_gateway
