#
#/********************************************************************20**
#
#     Name:    SIP 
#
#     Type:    Python File
#
#     Desc:    
#
#     File:    cm_xta_pycmd.py
#
#     Sid:      cm_xta_pycmd.py@@/main/26 - Tue Apr 10 12:26:14 2012
#
#     Prg:      
#
#*********************************************************************21*/
intCmdDict = {
   'tapa.timeout' : 'Expect    : No message',
   'tapa.delay' : 'Delay',
   #cm_xta_pycmd_py_001.main_6 loop changes starts
   'tapa.repeat.start' : 'Repeat Start',
   'tapa.repeat.end' : 'Repeat End',
   'tapa.repeat.start.lch.cfg' : 'Repeat Start LCH Cfg',
	#loop changes ends 
   'tapa.sip.delay' : 'SIP Delay',
   'tapa.sip.global.directive' : 'SIP Global Directive : Set',
   'tapa.global.directive' : 'Global Directive : Set',
   'tapa.directive' : 'Directive : Set',
   'tapa.memShow' : 'SSI Memory Info : Info show',
   'tapa.memLeak' : 'Memory leak info : Memory leak',
   'tapa.comment' : 'Comment',
   'tapa.mr.directive' : 'Message router Directive',
   'tapa.sip.directive' : 'SIP Directive : Set',
   'tapa.iuup.directive' : 'IUUP Directive : Set',
   'tapa.expect' : 'Expect',
   'tapa.expseq' : 'Expect a sequence of',
   'tapa.expopt' : 'Expect Optional',
   'tapa.expset' : 'Exp Set',
   'tapa.send' : 'Send',
   'tapa.sz.sct.delay'   : 'Delay if Sct interface is loosely coupled',
   'tapa.pdcp.delay' : 'PDCP Delay',
   'tapa.pdcp.global.directive' : 'PDCP Global Directive : Set',   'tapa.pdcp.directive' : 'PDCP Directive : Set',
   'tapa.pdcp.directive' : 'PDCP Directive : Set',
   'tapa.sot.cfgRegDom' : 'SOT Registrar domain configuration',
   'tapa.sot.cfgRegAuth' : 'SOT Registrar third party data base configuration',
   'tapa.sot.uncldPrim' : 'SOT SDK uncalled primitive invocation',
   'tapa.tfu.directive' : 'Sending Directive for TFU interface',
   'tapa.dcfi.stub' : 'Executing DCFI Stub'
}

# cm_xta_pycmd_py_001.main_3:  Updated simple commands for FTHA 
simpleCmdDict = {
   'tapa.rlu.datind'  : 'Sending Data Indication to upper layer from RLC',
   'tapa.rru.ccchdatind'  : 'Expecting data indication in the upper layer',
   'tapa.rru.ccchdatrsp'  : 'sending data response to RRC',
   'tapa.rru.dldcchdatreq'  : 'DL DCCH Message',
    'tapa.rlu.bndreq'  : 'Sending Bind request to RLU layer from RLC',
   'tapa.rlu.bndcfm'  : 'Sending Bind cfm to RLU layer from RLC',
  'tapa.rlu.unbndreq'  : 'Sending UnBind request to RLU layer from RLC',
  'tapa.cmk.bndreq' :  'Cmk Bind Request',
  'tapa.cmk.bndcfm'  :  'Cmk bind confirm',
  'tapa.cmk.ubndreq' :  'Cmk unbind request',
   'tapa.rlu.datreq'  : 'RLU Data Request',
   'tapa.crl.bndreq' :  'CRL Bind Request',
    'tapa.crl.bndcfm'  :  'CRL bind confirm',
    'tapa.crl.ubndreq' :  'CRL unbind request',
   'tapa.crl.cfgreq'  : 'CRL Configuration Request',
   'tapa.crl.cfgcfm'  : 'CRL Configuration Confirm',
   'tapa.crl.ueidchngreq'  : 'CRL UE Id Change request',
   'tapa.crl.ueidchngcfm'  : 'CRL UE Id Change confirm',
  'tapa.crl.countcreq'  : 'Sending Count-C request',
  'tapa.crl.countccfm'  : 'Sending Count-C confirm',
  'tapa.crl.suspendreq'  : 'Sending Suspend Req',
  'tapa.crl.suspendcfm'  : 'Sending Suspend Cfm',
  'tapa.crl.resumereq'  : 'Sending Resume Request',
  'tapa.crl.staind'  : 'Sending Status Indication ',
   'tapa.ctc.bndreq' :  'CTC Bind Request',
    'tapa.ctc.bndcfm'  :  'CTC bind confirm',
    'tapa.ctc.unbndreq' :  'CTC unbind request',
   'tapa.ctc.cfgreq'  : 'CTC Configuration Request',
   'tapa.ctc.cfgcfm'  : 'CTC Configuration Confirm',
   'tapa.ctc.relreq'  : 'CTC Release Request',
   'tapa.ctc.relocreq'  : 'CTC Relocation Request',
   'tapa.ctc.reloccfm'  : 'CTC Relocation Request',
   'tapa.ctc.ctxtreq'  : 'CTC ctxt request',
   'tapa.ctc.ctxtcfm'  : 'CTC Ctxt cfm',
   'tapa.cmk.cfgcfm' : 'CMK configuration Confirm', 
   'tapa.cmk.cfgreq'  : 'CMK Configuration Request',
   'tapa.cmk.countcreq'  : 'CMK Count-C request',
   'tapa.cmk.countccfm'  : 'CMK Count-C confirm',
   'tapa.rlu.datind'  : 'RLU Data Indication',
   'tapa.cmk.mesind'  : 'CMK Measurement Indication',
   'tapa.cmk.mesreq'  : 'CMK Measurement Request',
   'tapa.rru.bndreq'  : 'RRU Bind Request',
   'tapa.rru.bndcfm'  : 'RRU Bind Confirm',
   'tapa.rru.unbindreq'  : 'RRU UnBind Request',
   'tapa.rru.datreq'    : 'RRU Data Request',
   'tapa.rru.datind'  : 'RRU Data Indication',
   'tapa.rru.datrsp'  : 'RRU Data Response',
   'tapa.rru.datcfm'  : 'RRU Data Confirm',
   'tapa.rru.mbmsdatreq' : 'RRU MBMS Data request',
   'tapa.rru.mcchtxreq'  : 'RRU MCCH Tx request',
   'tapa.rru.encdatreq'  : 'RRU Encode Data Request',
   'tapa.rru.encdatcfm'  : 'RRU Encode Data Confirm',
   'tapa.rru.decdatreq'  : 'RRU Decode Data Request',
   'tapa.rru.decdatcfm'  : 'RRU Decode Data Confirm',
   'tapa.rru.errind'  : 'RRU Error Indication',
   'tapa.rru.uecfgreq'  : 'RRU UE Configuration Request',
   'tapa.rru.uecfgcfm'  : 'RRU UE Configuration Confirm',
   'tapa.rru.bmccfgreq'  : 'RRU BMC Configuration Request',
   'tapa.rru.bmccfgcfm'  : 'RRU BMC Configuration Confirm',
   'tapa.rru.measreq'  : 'RRU Measurement Request',
   'tapa.rru.measrprtind'  : 'RRU measurement Report Indication',
   'tapa.rru.statsureq'  : 'RRU Status Request',
   'tapa.rru.statuscfm'  : 'RRU Status Confirm',
   'tapa.rru.statusind'  : 'RRU Status Indication',
   'tapa.rru.ueidchngreq'  : 'RRU UE ID change Request',
   'tapa.rru.cncluereq'  : 'RRU Cancel UE Request',
   'tapa.rru.predefcfgreq'  : 'RRU Predefined Configuration Request',
   'tapa.rru.sccpchcfgreq'  : 'RRU SCCPCH Configuration Request',
   'tapa.rru.sccpchcfgcfm'  : 'RRU SCCPCH Configuration Confirm',
   'tapa.rru.deletetransreq'  : 'RRU Delete Transaction Request',
   'tapa.rru.countcind'  : 'RRU Count-C Indication',
   'tapa.rru.countcreq'  : 'RRU Count-C Request',
   'tapa.rru.relocprepreq' : 'RRU Reloc Prep req',
   'tapa.rru.relocprepcfm' : 'RRU Reloc Prep cfm',
   'tapa.rru.reloccmtreq' : 'RRU Reloc commit req',
   'tapa.rru.reloccmtcfm' : 'RRU Reloc commit cfm',
   'tapa.lrr.cfg.gen'  : 'General configuration request',
#cm_xta_pycmd_py_001.main_20: Updated for PSF-S1AP 1.1 Release
   'tapa.lyt.cfg.gen'  : 'General configuration request',
   'tapa.lyt.cfgcfm'  : 'S1AP configuration confirm',
   'tapa.lyt.cntrl.shutdown' : 'shutdown control request for PSF-S1AP',
   'tapa.lyt.cntrl.usta' : 'Unsolicited status Control Request for PSF-S1AP',
   'tapa.lyt.cntrl.trc' : 'Trace Control Request for PSF-S1AP',
   'tapa.lyt.cntrl.debug' : 'Debug Control Request for PSF-S1AP',
   'tapa.lyt.cntrlcfm' : 'Control Confirmation for PSF-S1AP',
   'tapa.lyt.sta.gen' : 'General Status request for PSF-S1AP',
   'tapa.lyt.stacfm' : 'Status Confirmation for PSF-S1AP',
   'tapa.lyt.sts.gen' : 'General Statistics Request for PSF-S1AP',
   'tapa.lyt.stscfm' : 'Statistics Confirmation for PSF-S1AP',
   'tapa.lyt.sts.rset' : 'Resource Set Statistics Request for PSF-S1AP',
   'tapa.lyt.staind' : 'Status indication for PSF-S1AP',
   'tapa.lyt.trcind' : 'Trace indication for PSF-S1AP',
   'tapa.pit.sendtosby' : 'PIT command to Send all updates to StandBy',
   'tapa.pit.dropall' : 'PIT command to Drop all updates',
   'tapa.pit.update.sby' : 'PIT Inbound Data request',
   'tapa.pit.confirm.actv' : 'PIT Inbound Data Confirm',
   'tapa.pit.update.actv' : 'PIT Outbound Data Request',
   'tapa.pit.confirm.sby' : 'PIT Outbound Data Confirm',
   'tapa.pit.sndupdmsg' : 'PIT send update message',
   'tapa.pit.exmupdatemsg' : 'PIT Command to Exam Update Message',
   'tapa.pit.dropupdmsg' : 'PIT Command to Drop Update Message',
   'tapa.pit.confirm.exmupdatemsg' : 'PIT Exam Update Message Confirm',
   'tapa.lrr.cfg.lsap'  : 'Lower Layer  Configuration request',
   'tapa.lrr.cfg.usap'  : 'Upper Layer  Configuration request',
   'tapa.lrr.cfg.prot'  : 'Protocol Configuration request',
   'tapa.lrr.cfg.cfm'  : 'Configuration Confirmation',
   'tapa.lrr.cntrl.lsap'  : 'Lower SAP Config Req',
   'tapa.lrr.cntrl.usap'  : 'Upper SAP Config Req',
   'tapa.lrr.cntrl.lsaptrc'  : 'Lower SAP trace',
   'tapa.lrr.cntrl.pnodetrc'  : 'Peer Node Trace',
   'tapa.lrr.cntrl.debug'  : 'Debug Control',
   'tapa.lrr.cntrl.shutdown'  : 'Shutdown',
   'tapa.lrr.cntrl.start'  : 'Start',
   'tapa.lrr.cntrl.usta'  : 'Unsolicited Status',
   'tapa.lrr.cntrlcfm'  : 'Control Confirmation',
   'tapa.lrr.sts.gen'  : 'General Statistics',
   'tapa.lrr.sts.peer'  : 'UE Statistics',
   'tapa.lrr.sts.cell'  : 'CELL Statistics',
   'tapa.lrr.stscfm'  : 'Statistics Confirm',
   'tapa.lrr.sta.sys'  : 'Sys Id status',
   'tapa.lrr.sta.usap'  : 'USAP status',
   'tapa.lrr.sta.gen'  : 'General status',
   'tapa.lrr.sta.lsap'  : 'LSAP status',
   'tapa.lrr.stacfm'  : 'Status confirmation',
   'tapa.lrr.staind'  : 'Status indication',
   'tapa.lrr.trcind'  : 'Trace indication',
   'tapa.lrr.mibreq'  : 'MIB Request',
   'tapa.lrr.mibcfm'  : 'MIB Confirmation',
   'tapa.lrr.audtreq'  : 'Audit Request',
   'tapa.lrr.audtcfm'  : 'Audit Confirmation',
   'tapa.re' : 'Validate Regular Expression',
   'tapa.sct.termcfm' : 'SCT Termination Confirm',
   'tapa.sot.ackind' : 'SOT ACK Indication',
   'tapa.sot.relind' : 'SOT Release Indication',
   'tapa.sct.endpopencfm' : 'SCT Endpoint Open Confirm',
   'CANCEL_R' : 'CANCEL RESPONSE',
   'tapa.zot.confirm.actv' : 'ZOT Inbound Data Confirm ',
   'UNKNOWN' : 'UNKNOWN',
   'tapa.lhi.sts.tsap' : 'TSAP Statistics for TUCL',
   'REGISTER' : 'REGISTER',
   'tapa.lzo.stacfm' : 'Status Confirmation for PSF-SIP',
   'tapa.lso.sts.tsap' : 'Tsap Statistics Request for SIP',
   'tapa.sct.bndreq' : 'SCT Bind Request',
   'tapa.sct.termind' : 'SCT Termination Indication',
   'tapa.sot.cimcfm' : 'SOT CIM Confirm',
   'INVITE_R_P' : 'INVITE PROV RESPONSE',
   'tapa.lzo.cntrl.trc' : 'Trace Control Request for PSF-SIP',
   'tapa.lhi.cntrl.shutdown' : 'Shutdown Control Request for TUCL',
   'tapa.sct.datind' : 'SCT Data Indication',
   'tapa.sot.any' : 'SOT ANY API',
   'tapa.sot.cancelind' : 'SOT Cancel Indication',
   'REFER_R' : 'REFER RESPONSE',
   'tapa.sht.sync.cntrlreq' : 'Control request to Synchronize',
   'tapa.lzo.staind' : 'Status indication for PSF-SIP',
   'tapa.lso.sta.endp' : 'Endpoint Status Request for SIP',
   'tapa.lso.sta.assoc' : 'Association Status Request for SIP',
   'tapa.sot.conreq' : 'SOT Connection Request',
   'tapa.sot.modreq' : 'SOT Modify Request',
   'tapa.sot.cimind' : 'SOT CIM Indication',
   'tapa.lzo.cntrl.shutdown' : 'Shutdown Control Request for PSF-SIP',
   'tapa.lso.sta.entity' : 'Entity Status Request for SIP',
   'tapa.lsb.sta.assoc' : 'SCTP Association Status Request',
   'tapa.lso.sta.tpt' : 'Transport Server Status Request for SIP',
   'tapa.sht.dispeer.cntrlreq' : 'Control request to Disable Peer SAP',
   'tapa.lsb.cfgcfm' : 'SCTP Config Confirm',
   'tapa.lso.sts.ssap' : 'Ssap Statistics Request for SIP',
   'INVITE' : 'INVITE',
   'MODIFY_R' : 'MODIFY RESPONSE',
   'SUBSCRIBE' : 'SUBSCRIBE',
   'tapa.invalid' : 'Invalid Command',
   'tapa.lsb.cfg.gen' : 'SCTP Gen Config Request',
   'tapa.lsb.sta.gen' : 'SCTP Gen Status Request',
   'tapa.lzo.sts.gen' : 'General Statistics Request for PSF-SIP',
   'tapa.lsb.cntrl.sctsap' : 'SCTP SSAP Control Request',
   'tapa.lso.cfg.tpt' : 'Transport Server Configuration Request for SIP',
   'tapa.sct.bndcfm' : 'SCT Bind Confirm',
   'tapa.sot.relrsp' : 'SOT Release Response',
   'COMET' : 'COMET',
   'tapa.lsb.sts.sctsap' : 'SCTP SSAP Statistics Request',
   'tapa.sot.auditreq' : 'SOT Audit Request',
   'ACK' : 'ACK',
   'SUBSCRIBE_R_P' : 'SUBSCRIBE PROV RESPONSE',
   'SIPANY' : 'SIPANY',
   'tapa.lsb.stscfm' : 'SCTP Statistics Confirm',
   'tapa.lso.cfg.entity' : 'Entity Configuration Request for SIP',
   'tapa.lsb.cntrl.tsap' : 'SCTP TSAP Control Request',
   'tapa.lhi.cfg.gen' : 'General Configuration Request for TUCL',
   'tapa.sot.anyrsp' : 'SOT ANY RSP',
   'BYE_R' : 'BYE RESPONSE',
   'tapa.lsb.cntrlcfm' : 'SCTP Control Confirm',
   'tapa.sot.concfm' : 'SOT Connection Confirm',
   'tapa.sot.modcfm' : 'SOT Modify Confirm',
   'tapa.lso.cntrl.shutdown' : 'ShutDown Control Request for SIP',
   'tapa.sct.stareq' : 'SCT Sctp Status Request',
   'SIPANYREQ' : 'SIPANYREQ',
   'tapa.lhi.cntrl.trc' : 'Trace Control Request for TUCL',
   'tapa.lso.cntrl.gssap' : 'Group Ssap Control Request for SIP',
   'tapa.sot.camreq' : 'SOT CAM Request',
   'tapa.lzo.sts.rset' : 'Resource Set Statistics Request for PSF-SIP',
   'tapa.lso.cfg.addendp' : 'Add Endpoint Configuration Request for SIP',
   'tapa.sot.cimrsp' : 'SOT CIM Response',
   'tapa.lso.cntrl.tpt' : 'TPT Control Request for SIP',
   'tapa.sct.assocreq' : 'SCT Association Request',
   'tapa.sct.setprireq' : 'SCT Set Primary Address Request',
   'tapa.sot.conind' : 'SOT Connection Indication',
   'tapa.sot.modind' : 'SOT Modify Indication',
   'tapa.lsb.cntrl.shutdown' : 'SCTP Shutdown Control Request',
   'tapa.sot.bndreq' : 'SOT Bind Request',
   'tapa.sot.transreq' : 'SOT Trans Request',
   'tapa.lso.sta.sys' : 'System Status Request for SIP',
   'tapa.sot.auditcfm' : 'SOT Audit Confirm',
   'tapa.sct.hbeatreq' : 'SCT Heart Beat Request',
   'tapa.hit.discreq' : 'HIT Disconnect Request',
   'tapa.sht.cntrlcfm' : 'Control confirm from layer to System Agent',
   'tapa.lsb.cfg.tsap' : 'SCTP TSAP Config Request',
   'tapa.lso.cntrl.usta' : 'Unsloicited Status Control Request for SIP',
   'tapa.lzo.cntrlcfm' : 'Control Confirmation for PSF-SIP',
   'tapa.lso.cntrl.cache' : 'Cache Control Request for SIP',
   'tapa.cst.decompressreq' : 'CST De-Compress Request',
   'SUBSCRIBE_R' : 'SUBSCRIBE RESPONSE',
   'UNKNOWN_R' : 'UNKNOWN RESPONSE',
   'tapa.lhi.cntrl.tsap' : 'TSAP Control Request for TUCL',
   'MESSAGE_R' : 'MESSAGE RESPONSE',
   'tapa.hit.servopenreq' : 'HIT Server Open Request',
   'tapa.sct.stacfm' : 'SCT Sctp Status Confirm',
   'tapa.hit.udatreq' : 'HIT Udp Data Request',
   'tapa.sot.camcfm' : 'SOT CAM Confirm',
   'tapa.lzo.sta.gen' : 'General Status request for PSF-SIP',
   'tapa.lso.sta.cache' : 'Cache Status Request for SIP',
   'SIPERROR' : 'SIPERROR',
   'tapa.sct.assoccfm' : 'SCT Association Confirm',
   'tapa.sct.setpricfm' : 'SCT Set Primary Address Confirm',
   'tapa.lzo.cfgcfm' : 'Configuration Confirmation for PSF-SIP',
   'tapa.sot.bndcfm' : 'SOT Bind Confirm',
   'tapa.sot.transcfm' : 'SOT Trans Confirm',
   'tapa.sct.staind' : 'SCT Sctp Status Indication',
   'UPDATE' : 'UPDATE',
   'tapa.lzo.cfg.gen' : 'General Configuration Request for PSF-SIP',
   'tapa.lzo.stscfm' : 'Statistics Confirmation for PSF-SIP',
   'tapa.sct.hbeatcfm' : 'SCT Heart Beat Confirm',
   'tapa.hit.disccfm' : 'HIT Disconnection Confirm',
   'tapa.sot.camind' : 'SOT CAM Indication',
   'tapa.lhi.trcind' : 'Trace Indication for TUCL',
   'tapa.sot.conrsp' : 'SOT Connection Response',
   'tapa.sot.modrsp' : 'SOT Modify Response',
   'tapa.zot.dropall' : 'ZOT command to Drop all updates ',
   'tapa.sct.assocind' : 'SCT Association Indication',
   'tapa.sct.assocind1' : 'SCT Association Indication', 
   'tapa.sht.abort.cntrlreq' : 'Control request to Abort',
   'tapa.cst.decompresscfm' : 'CST De-Compress Confirm',
   'tapa.sot.transind' : 'SOT Trans Indication',
   'tapa.lhi.stacfm' : 'Status Confirmation for TUCL',
   'tapa.hit.discind' : 'HIT Disconnection Indication',
   'tapa.lso.sts.gen' : 'General Statistics Request for SIP',
   'tapa.sot.proxyreq' : 'SOT Proxy Request',
   'INFO' : 'INFO',
   'CIMINFO' : 'CIMINFO',
   'MESSAGE' : 'MESSAGE',
   'tapa.lhi.staind' : 'Unsolicited Indication for TUCL ',
   'tapa.lso.trcind' : 'Trace Indication for SIP',
   'tapa.lso.acntreq' : 'Accounting Request for SIP',
   'tapa.hit.ubndreq' : 'HIT Unbind Request',
   'tapa.sot.cnstreq' : 'SOT Connection Status Request',
   'tapa.sot.ubndreq' : 'SOT Unbind Request',
   'tapa.hit.udatind' : 'HIT Udp Data Indication',
   'BYE' : 'BYE',
   'tapa.lsb.sta.tsap' : 'SCTP TSAP Status Request',
   'tapa.hit.conreq' : 'HIT Connection Request',
   'tapa.lhi.cntrlcfm' : 'Control Confirmation for TUCL',
   'tapa.lso.stacfm' : 'Status Confirmation for SIP',
   'tapa.sot.errind' : 'SOT Error Indication',
   'tapa.sdk.errind' : 'SDK Error Indication',
   'INVITE_R' : 'INVITE RESPONSE',
   'tapa.lsb.cntrl.debug' : 'SCTP Debug Control Request',
   'tapa.lso.cntrlcfm' : 'Control Confirmation for SIP',
   'SIPANYRSP' : 'SIPANYRSP',
   'tapa.lzo.shcntrlcfm' : 'Control confirm from layer to System Agent',
   'tapa.hit.datreq' : 'HIT Tcp Data Request',
   'tapa.sot.camrsp' : 'SOT CAM Response',
   'SIPREL_R' : 'SIPREL_R',
   'tapa.lsb.cntrl.trc' : 'SCTP Trace Control Request',
   'tapa.lsb.sta.sctsap' : 'SCTP SSAP Status Request',
   'COMET_R' : 'COMET RESPONSE',
   'PRACK' : 'PRACK',
   'tapa.sct.assocrsp' : 'SCT Association Response',
   'tapa.lhi.cfg.tsap' : 'Tsap Configuration Request for TUCL',
   'tapa.lso.staind' : 'Status Indication for SIP',
   'tapa.hit.flcind' : 'HIT Flow Control Indication',
   'tapa.sot.transrsp' : 'SOT Trans Response',
   'tapa.lso.cfg.tsap' : 'TSAP Configuration Request for SIP',
   'tapa.lso.cntrl.debug' : 'Debug Control Request for SIP',
   'tapa.sot.proxycfm' : 'SOT Proxy Confirm',
   'SIPREL' : 'SIPREL',
   'tapa.lso.acntcfm' : 'Accounting Confirmation for SIP',
   'NOTIFY_R' : 'NOTIFY RESPONSE',
   'OPTIONS_R' : 'OPTIONS RESPONSE',
   'MODIFY_R_P' : 'MODIFY PROV RESPONSE',
   'tapa.lsb.cfg.sctsap' : 'SCTP SSAP Config Request',
   'tapa.lso.cntrl.tsap' : 'Tsap Control Request for SIP',
   'tapa.hit.concfm' : 'HIT Connection Confirm',
   'tapa.sot.proxyind' : 'SOT Proxy Indication',
   'tapa.sht.standby.cntrlreq' : 'Control request to Go Standby',
   'tapa.zot.sendtosby' : 'ZOT command to Send all updates to StandBy ',
   'tapa.zot.update.sby' : 'ZOT Inbound Data request ',
   'tapa.lso.cntrl.acnt' : 'Account Control Request for SIP',
   'tapa.lso.sts.entity' : 'Entity Statistics Request for SIP',
   'tapa.lso.acntind' : 'Accounting Indication for SIP',
   'tapa.sot.cnstind' : 'SOT Connection Status Indication',
   'OPTIONS' : 'OPTIONS',
   'tapa.lso.cfg.ssap' : 'SSAP Configuration Request for SIP',
   'tapa.lsb.sta.sys' : 'SCTP System Status Request',
   'tapa.lso.cntrl.trc' : 'Trace Control Request for SIP',
   'tapa.lso.sta.gen' : 'General Status Request for SIP',
   'tapa.hit.conind' : 'HIT Connection Indication',
   'UPDATE_R' : 'UPDATE RESPONSE',
   'tapa.sht.active.cntrlreq' : 'Control request to Go Active ',
   'tapa.sht.shutdown.cntrlreq' : 'Control request to ShutDown',
#cm_xta_pycmd_py_001.main_20: Updated for PSF-S1AP 1.1 Release
   'tapa.sht.usta.cntrlreq' : 'Control request to enable USTA',
   'tapa.shtlsz.cntrlreq':'SHT Control request',
   'tapa.lsb.sts.tsap' : 'SCTP TSAP Statistics Request',
   'tapa.sct.endpclosereq' : 'SCT Endpoint Close Request',
   'tapa.hit.bndreq' : 'HIT Bind Request',
   'tapa.lhi.sta.sys' : 'System Status Request for TUCL',
   'tapa.hit.datind' : 'HIT Tcp Data Indication',
   'tapa.lso.cfg.gen' : 'General Configuration Request for SIP',
   'tapa.lso.cntrl.ssap' : 'Ssap Control Request for SIP',
   'tapa.lsb.trcind' : 'SCTP Trace Indication',
   'INFO_R' : 'INFO RESPONSE',
   'CIMINFO_R' : 'CIMINFO RESPONSE',
   'tapa.lsb.stacfm' : 'SCTP Status Confirm',
   'tapa.cst.compressreq' : 'CST Compress Request',
   'CANCEL' : 'CANCEL',
   'tapa.lhi.cfgcfm' : 'Configuration Confirmation for TUCL',
   'tapa.sot.ackreq' : 'SOT ACK Request',
   'tapa.sot.relreq' : 'SOT Release Request',
   'tapa.sot.proxyrsp' : 'SOT Proxy Response',
   'tapa.lzo.cntrl.usta' : 'Unsolicited status Control Request for PSF-SIP',
   'tapa.lzo.cntrl.debug' : 'Debug Control Request for PSF-SIP',
   'tapa.lsb.sta.dta' : 'SCTP Destination transport address Status Request',
   'tapa.lhi.stscfm' : 'Statistics Confirmation for TUCL',
   'tapa.lhi.sta.tsap' : 'TSAP Status Request for TUCL',
   'tapa.lsb.cntrl.usta' : 'SCTP UnSolicited Control Request',
   'tapa.lso.cfg.endp' : 'Endpoint Configuration Request for SIP',
   'tapa.sct.endpclosecfm' : 'SCT Endpoint Close Confirm',
   'tapa.hit.bndcfm' : 'HIT Bind Confirm',
   'tapa.lsb.staind' : 'SCTP Status Indication',
   'tapa.lso.sta.tsap' : 'Tsap Status Request for SIP',
   'tapa.sot.refreshind' : 'SOT Refresh Indication',
   'MODIFY' : 'MODIFY',
   'tapa.lhi.cntrl.debug' : 'Debug Control Request for TUCL',
   'tapa.lso.cntrl.entity' : 'Entity Control Request for SIP',
   'tapa.sct.termreq' : 'SCT Termination Request',
   'tapa.hit.conrsp' : 'HIT Connection Response',
   'tapa.sot.anyreq' : 'SOT ANY REQ',
   'tapa.sct.endpopenreq' : 'SCT Endpoint Open Request',
   'tapa.sct.datreq' : 'SCT Sctp Data Request',
   'SIPAUDIT' : 'SIPAUDIT',
   'tapa.lso.cntrl.endp' : 'Endpoint Control Request for SIP',
   'tapa.lso.cntrl.assoc' : 'Association Control Request for SIP',
   'tapa.sot.cancelreq' : 'SOT Cancel Request',
   'REGISTER_R' : 'REGISTER RESPONSE',
   'tapa.lso.cfg.addtpt' : 'Add Transport Server Configuration Request for SIP',
   'tapa.lhi.cfg.ctxt' : 'Context Configuration Request for TUCL',
   'tapa.lso.cfgcfm' : 'Configuration Confirmation for SIP',
   'tapa.sct.flcind' : 'SCT Sctp Flowcontrol Indication',
   'REFER' : 'REFER',
   'tapa.lsb.sts.gen' : 'SCTP Gen Statistics Request',
   'tapa.sot.cimreq' : 'SOT CIM Request',
   'NOTIFY' : 'NOTIFY',
   'SIPREFRESH' : 'SIPREFRESH',
   'tapa.zot.confirm.sby' : 'ZOT Outbound Data Confirm ',
   'tapa.lso.stscfm' : 'Statistics Confirmation for SIP',
   'tapa.cst.compresscfm' : 'CST Compress Confirm',
   'tapa.cst.open' : 'CST Compress Open', #cm_xta_pycmd_py_001.main_
   'tapa.cst.close' : 'CST Compress Close',
   'PRACK_R' : 'PRACK RESPONSE',
   'tapa.zot.update.actv' : 'ZOT Outbound Data Request ',
   'tapa.lhi.sts.gen' : 'General Statistics for TUCL',
   'tapa.lso.sta.ssap' : 'Ssap Status Request for SIP',
   'tapa.sot.relcfm' : 'SOT Release Confirm',
   'tapa.lhi.cntrl.usta' : 'Unsolicited Status Control Request for TUCL',
   'tapa.sht.warmstart.cntrlreq' : 'Control request to Perform Warm Start',
   'tapa.lzo.trcind' : 'Trace indication for PSF-SIP',
   'PUBLISH' : 'PUBLISH',
   'PUBLISH_R' : 'PUBLISH RESPONSE',
   'tapa.aqu.bndreq' : 'AQU Bind Request',
   'tapa.aqu.bndcfm' : 'AQU Bind Confirm',
   'tapa.aqu.ubndreq' : 'AQU Unbind Request',
   'tapa.aqu.dmmsgreq' : 'AQU Diameter Message Request',
   'tapa.aqu.dmmsgind' : 'AQU Diameter Message Indication',
   'tapa.aqu.dmmsgrsp' : 'AQU Diameter Message Response',
   'tapa.aqu.dmmsgcfm' : 'AQU Diameter Message Confirm',
   'tapa.aqu.errind'  : 'AQU Error Indication',
   'tapa.aqu.rmvtxreq' : 'AQU Remove Transaction Request',
   'tapa.aqu.rmvtxcfm' : 'AQU Remove Transaction Confirm',
   'tapa.aqu.peerdownind' : 'AQU Peer Down Indication',
   'tapa.aqu.peerupind' : 'AQU Peer Up Indication',
   'tapa.aqu.flcind' : 'AQU Flow Control Indication',
   'tapa.hit.bndreq' : 'HIT Bind Request',
   'tapa.hit.ubndreq': 'HIT Unbind Request',
   'tapa.hit.servopenreq' : 'HIT Server Open Request',
   'tapa.hit.conreq' : 'HIT Connection Request',
   'tapa.hit.conrsp' : 'HIT Connection Response',
   'tapa.hit.datreq' : 'HIT Tcp Data Request',
   'tapa.hit.udatreq' : 'HIT Udp Data Request',
   'tapa.hit.discreq' : 'HIT Disconnect Request',
   'tapa.hit.conind' : 'HIT Connection Indication',
   'tapa.hit.concfm' : 'HIT Connection Confirm',
   'tapa.hit.bndcfm' : 'HIT Bind Confirm',
   'tapa.hit.datind' : 'HIT Tcp Data Indication',
   'tapa.hit.udatind' : 'HIT Udp Data Indication',
   'tapa.hit.discind' : 'HIT Disconnection Indication',
   'tapa.hit.disccfm' : 'HIT Disconnection Confirm',
   'tapa.hit.flcind' : 'HIT Flow Control Indication',
   'tapa.sct.bndreq' : 'SCT Bind Request',
   'tapa.sct.endpopenreq' : 'SCT Endpoint Open Request',
   'tapa.sct.endpclosereq' : 'SCT Endpoint Close Request',
   'tapa.sct.assocreq' : 'SCT Association Request',
   'tapa.sct.assocrsp' : 'SCT Association Response',
   'tapa.sct.termreq' : 'SCT Termination Request',
   'tapa.sct.setprireq': 'SCT Set Primary Address Request',
   'tapa.sct.hbeatreq' : 'SCT Heart Beat Request',
   'tapa.sct.datreq' : 'SCT Sctp Data Request',
   'tapa.sct.stareq' : 'SCT Sctp Status Request',
   'tapa.sct.bndcfm' : 'SCT Bind Confirm',
   'tapa.sct.endpopencfm' : 'SCT Endpoint Open Confirm',
   'tapa.sct.endpclosecfm' : 'SCT Endpoint Close Confirm',
   'tapa.sct.assocind' : 'SCT Association Indication',
   'tapa.sct.assoccfm' : 'SCT Association Confirm',
   'tapa.sct.termind' : 'SCT Termination Indication',
   'tapa.sct.termcfm' : 'SCT Termination Confirm',
   'tapa.sct.setpricfm':'SCT Set Primary Address Confirm',
   'tapa.sct.hbeatcfm' : 'SCT Heart Beat Confirm',
   'tapa.sct.datind' : 'SCT Data Indication',
   'tapa.sct.stacfm' : 'SCT Sctp Status Confirm',
   'tapa.sct.staind' : 'SCT Sctp Status Indication',
   'tapa.sct.flcind' : 'SCT Flow Control Indication',
   'tapa.lhi.sts.tsap' : 'TSAP Statistics for TUCL',
   'tapa.lhi.cntrl.shutdown' : 'Shutdown Control Request for TUCL',
   'tapa.lhi.cfg.gen' : 'General Configuration Request for TUCL',
   'tapa.lhi.cntrl.trc' : 'Trace Control Request for TUCL',
   'tapa.lhi.cntrl.tsap' : 'TSAP Control Request for TUCL',
   'tapa.lhi.trcind' : 'Trace Indication for TUCL',
   'tapa.lhi.stacfm' : 'Status Confirmation for TUCL',
   'tapa.lhi.staind' : 'Unsolicited Indication for TUCL ',
   'tapa.lhi.cntrlcfm' : 'Control Confirmation for TUCL',
   'tapa.lhi.cfg.tsap' : 'Tsap Configuration Request for TUCL',
   'tapa.lhi.sta.sys' : 'System Status Request for TUCL',
   'tapa.lhi.cfgcfm' : 'Configuration Confirmation for TUCL',
   'tapa.lhi.stscfm' : 'Statistics Confirmation for TUCL',
   'tapa.lhi.sta.tsap' : 'TSAP Status Request for TUCL',
   'tapa.lhi.cntrl.debug' : 'Debug Control Request for TUCL',
   'tapa.lhi.cfg.ctxt' : 'Context Configuration Request for TUCL',
   'tapa.lhi.cntrl.usta' : 'Unsolicited Status Control Request for TUCL',
   'tapa.lhi.sts.gen' : 'General Statistics for TUCL',
   'tapa.lsb.sta.assoc' : 'SCTP Association Status Request',
   'tapa.lsb.cfgcfm' : 'SCTP Config Confirm',
   'tapa.lsb.cfg.gen' : 'SCTP Gen Config Request',
   'tapa.lsb.sta.gen' : 'SCTP Gen Status Request',
   'tapa.lsb.cntrl.sctsap' : 'SCTP SSAP Control Request',
   'tapa.lsb.sts.sctsap' : 'SCTP SSAP Statistics Request',
   'tapa.lsb.stscfm' : 'SCTP Statistics Confirm',
   'tapa.lsb.cntrl.tsap' : 'SCTP TSAP Control Request',
   'tapa.lsb.cntrlcfm' : 'SCTP Control Confirm',
   'tapa.lsb.cntrl.shutdown' : 'SCTP Shutdown Control Request',
   'tapa.lsb.cfg.tsap' : 'SCTP TSAP Config Request',
   'tapa.lsb.sta.tsap' : 'SCTP TSAP Status Request',
   'tapa.lsb.cntrl.debug' : 'SCTP Debug Control Request',
   'tapa.lsb.cntrl.trc' : 'SCTP Trace Control Request',
   'tapa.lsb.sta.sctsap' : 'SCTP SSAP Status Request',
   'tapa.lsb.cfg.sctsap' : 'SCTP SSAP Config Request',
   'tapa.lsb.sta.sys' : 'SCTP System Status Request',
   'tapa.lsb.sts.tsap' : 'SCTP TSAP Statistics Request',
   'tapa.lsb.trcind' : 'SCTP Trace Indication',
   'tapa.lsb.stacfm' : 'SCTP Status Confirm',
   'tapa.lsb.sta.dta' : 'SCTP Destination transport address Status Request',
   'tapa.lsb.cntrl.usta' : 'SCTP UnSolicited Control Request',
   'tapa.lsb.staind' : 'SCTP Status Indication',
   'tapa.lsb.sts.gen' : 'SCTP Gen Statistics Request',
   'tapa.laq.cfg.gen' : 'General Configuration Request for Diameter',
   'tapa.laq.cfg.lsap' : 'Lower SAP Configuration Request for Diameter',
   'tapa.laq.cfg.usap' : 'Upper SAP Configuration Request for Diameter',
   'tapa.laq.cfg.prot' : 'Protocol Configuration Request for Diameter',
   'tapa.laq.cfg.peer' : 'Peer Configuration Request for Diameter',
   'tapa.laq.cfg.realm' : 'Realm Configuration Request for Diameter',
   'tapa.laq.cfg.dm': 'Application Specific DM Configuration Request for Diameter',
    'tapa.laq.cfg.avp': 'Application Specific AVP Configuration Request for Diameter',
    'tapa.laq.cfgcfm': 'Configuration Confirmation for Diameter',
    'tapa.laq.cntrl.usta': 'Unsolicited Status Control Request for Diameter',
    'tapa.laq.cntrl.trc' : 'Trace Control Request for Diameter',
    'tapa.laq.cntrl.debug': 'Debug Control Request for Diameter',
    'tapa.laq.cntrl.lsap': 'Tsap Control Request for Diameter',
    'tapa.laq.cntrl.usap': 'Usap Control Request for Diameter',
    'tapa.laq.cntrl.peer': 'Peer Control Request for Diameter',
    'tapa.laq.cntrl.realm' : 'Realm Control Request for Diameter',
    'tapa.laq.cntrl.shutdown': 'ShutDown Control Request for Diameter',
    'tapa.laq.cntrl.start' : 'Start Control Request for Diameter',
    'tapa.laq.cntrlcfm':'Control Confirmation for Diameter',
    'tapa.laq.sts.gen': 'General Statistics Request for Diameter',
    'tapa.laq.sts.peer': 'Peer Statistics Request for Diameter',
    'tapa.laq.sts.lsap': 'LSap Statistics Request for Diameter',
    'tapa.laq.sts.usap': 'USap Statistics Request for Diameter',
    'tapa.laq.stscfm' : 'Statistics Confirmation for Diameter',
    'tapa.laq.sta.sys' : 'System ID Status Request for Diameter',
    'tapa.laq.sta.usap' : 'Upper Sap Status Request for Diameter',
    'tapa.laq.sta.gen':'General Status Request for Diameter',
    'tapa.laq.sta.lsap': 'Lower Sap Status Request for Diameter',
    'tapa.laq.sta.peer' : 'Peer Status Request for Diameter',
    'tapa.laq.stacfm' : 'Status Confirmation for Diameter',
    'tapa.laq.staind': 'Status Indication for Diameter',
    'tapa.laq.trcind': 'Trace Indication for Diameter',
    'tapa.laq.probe.peer' :'Peer Probe Request for Diameter',
    'tapa.laq.probe.realm': 'Realm Probe Request for Diameter',
    'tapa.laq.probe.avp' : 'AVP Probe Request for Diameter',
    'tapa.laq.probe.dm': 'DM Probe Request for Diameter',
    'tapa.laq.probecfm': 'Probe Confirm for Diameter',
   'tapa.ltc.cfg.gen'       : 'General Configuration Request for pdcp',
   'tapa.ltc.cfg.ctcsap'    :'CTC SAP Configuration Request for pdcp',
   'tapa.ltc.cfgcfm.ctcsap' :'CTC SAP Configuration Confirm for pdcp',
   'tapa.ltc.cfg.tcusap'    :'TCU SAP Configuration Request for pdcp',
   'tapa.ltc.cfgcfm.tcusap' :'TCU SAP Configuration Confirm for pdcp',
   'tapa.ltc.cfg.rlusap'    :'RLU SAP Configuration Request for pdcp',
   'tapa.ltc.cfgcfm.rlusap' :'RLU SAP Configuration Confirm for pdcp',
   'tapa.ltc.cfgcfm'        :'Configuration Confirmation for pdcp',
   'tapa.ltc.cntrl.usta'    :'Unsloicited Status Control Request for PDCP',
   'tapa.ltc.cntrl.trc'     :'Trace Control Request for PDCP',
   'tapa.ltc.cntrl.rlusap'  :'Control request for pdcp Lower Sap',
   'tapa.ltc.cntrl.shutdown':'ShutDown Control Request for pdcp',
   'tapa.ltc.cntrlcfm'     : 'Control Confirmation for pdcp',
   'tapa.ltc.sta.gen'      : 'General Status Request for PDCP',
   'tapa.ltc.sta.ctcsap'   : 'Ctc Sap Status Request for PDCP',
   'tapa.ltc.sta.tcusap'   : 'Tcu Sap Status Request for PDCP',
   'tapa.ltc.sta.rlusap'   : 'Rlu Sap Status Request for PDCP',
   'tapa.ltc.sta.sys'      : 'System Status Request for pdcp',
   'tapa.ltc.stacfm'       : 'pdcp  Status Confirm',
   'tapa.ltc.staind'       : 'Status Indication for PDCP' ,
   'tapa.ltc.trcind'       : 'Trace Indication for PDCP' , 
   'tapa.ltc.sts.gen'      : 'General Statistics Request for PDCP', 
   'tapa.ltc.sts.ctcsap'   : 'Ctc Sap Statistics Request for PDCP',
   'tapa.ltc.sts.tcusap'   : 'Tcu Sap Statistics Request for PDCP',
   'tapa.ltc.sts.rlusap'   : 'Rlu Sap Statistics Request for PDCP', 
   'tapa.ltc.stscfm'       : 'Statistics Confirmation for PDCP',
   'tapa.ctc.snreq'        : 'CTC sequence number request',
   'tapa.ctc.ubndreq'      : 'CTC UnBind request',
   'tapa.ctc.bndcfm'       : 'CTC Bind confirm',
   'tapa.ctc.cfgreq'       : 'CTC Config request',
   'tapa.ctc.cfgcfm'       : 'CTC Config confirm',
   'tapa.ctc.bndreq'       : 'CTC Bind request',
   'tapa.ctc.ctxtreq'      : 'CTC context request',
   'tapa.ctc.ctxtcfm'      : 'CTC context confirm',
   'tapa.ctc.relreq'       : 'CTC release request',
   'tapa.ctc.relocreq'     : 'CTC relocation request',
   'tapa.ctc.reloccfm'     : 'CTC relocation confirm',
   'tapa.tcu.bndreq'       : 'TCU Bind Request',
   'tapa.tcu.ubndreq'      : 'TCU UnBind request',
   'tapa.tcu.bndcfm'       : 'TCU Bind confirm',
   'tapa.tcu.datreq'       : 'TCU Data request',
   'tapa.tcu.datind'       : 'TCU Data indication',
   'tapa.rlu.datcfm'       : 'RLU Data Confirm',
   'tapa.rlu.bndreq'       : 'RLU Bind request',
   'tapa.rlu.ubndreq'      : 'RLU UnBind request',
   'tapa.rlu.bndcfm'       : 'RLU Bind confirm',
   'tapa.rlu.datreq'       : 'RLU Data request',
   'tapa.rlu.datind'       : 'RLU Data indication',
   'tapa.rlu.mbmsdatreq'   : 'RLU MBMS Data request',
    'tapa.laq.probecfm': 'Probe Confirm for Diameter',
    #  Support for the FTHA Integration 
    'tapa.lsg.cfg.gen': 'General Configuration Request for System Manager',
    'tapa.lsg.cfgcfm': 'Configuration Confirmation for System Manager',
    'tapa.lsg.cntrl.enablenode' : 'Enable Node Control Request for System Manager',
   'tapa.lsg.cfg.entity' : 'Entity Configuration Request for System Manager',
   'tapa.lsg.cntrl.disablenode' : 'Disable Node Control Request for System Manager',
   'tapa.lsg.cntrl.swapnode' : 'Swap Node Control Request for System Manager',
   'tapa.lsg.cntrlcfm' : 'Control Confirmation for System Manager',
   'tapa.lsg.cntrl.abort' : 'Abort Control Request for System Manager',
#cm_xta_pycmd_py_001.main_20: Updated for PSF-S1AP 1.1 Release
   'tapa.lsg.cntrl.debug' : 'Debug Control Request for System Manager',
   'tapa.lmr.cntrlcfm' : 'Control Confirmation for PSF-SIP',
   'tapa.lmr.cfg.gen' : 'General Configuration Request for PSF-SIP',
   'tapa.lmr.cfgcfm' : 'Configuration Confirmation for PSF-SIP',
   'tapa.lmr.cntrl.shutdown' : 'Shutdown Control Request for PSF-SIP',
   'tapa.lmr.cntrlcfm' : 'Control Confirmation for PSF-SIP',
   'tapa.lsh.cfg.gen' : 'SCTP Gen Config Request',
   'tapa.lsh.cfgcfm' : 'SCTP Config Confirm',
   'tapa.lsh.stscfm' : 'SCTP Statistics Confirm',
   'tapa.lsh.cntrlcfm' : 'SCTP Control Confirm',
   'tapa.lsh.cntrl.trc' : 'SCTP Trace Control Request',
   'tapa.lsh.sts.gen' : 'SCTP Gen Statistics Request',
	# Adding simple commands for RPT
   'tapa.lhr.cfg.gen' : 'General Configuration Request for RTP',
   'tapa.lhr.cfg.ssap' : 'Ssap Configuration Request for RTP',
   'tapa.lhr.cfg.tsap' : 'Tsap Configuration Request for RTP',
   'tapa.lhr.cfgcfm' : 'Configuration Confirmation for RTP',
   'tapa.lhr.cntrl.usta' : 'Unsolicited Status Control Request for RTP',
   'tapa.lhr.cntrl.trc' : 'Trace Control Request for RTP',
   'tapa.lhr.cntrl.tsap' : 'TSAP Control Request for RTP',
   'tapa.lhr.cntrl.ssap' : 'SSAP Control Request for RTP',
   'tapa.lhr.cntrl.debug' : 'Debug Control Request for RTP',
   'tapa.lhr.cntrl.shutdown' : 'Shutdown Control Request for RTP',
   'tapa.lhr.cntrlcfm' : 'Control Confirmation for RTP',
   'tapa.lhr.sts.sess' : 'Session Statistics for RTP',
   'tapa.lhr.sts.tsap' : 'TSAP Statistics for RTP',
   'tapa.lhr.sts.ssap' : 'SSAP Statistics for RTP',
   'tapa.lhr.stscfm' : 'Statistics Confirmation for RTP',
   'tapa.lhr.sta.sys' : 'System Status Request for RTP',
   'tapa.lhr.sta.tsap' : 'TSAP Status Request for RTP',
   'tapa.lhr.sta.ssap' : 'SSAP Status Request for RTP',
   'tapa.lhr.stacfm' : 'Status Confirmation for RTP',
   'tapa.lhr.staind' : 'Unsolicited Indication for RTP',
   'tapa.lhr.trcind' : 'Trace Indication for RTP',
   'tapa.hrt.bnd.req' : 'Bind Request to RTP',
   'tapa.hrt.bnd.cfm' : 'Handels bind confirmation from RTP',
   'tapa.hrt.ubnd.req' : 'Unbind Request to RTP',
   'tapa.hrt.sess.req' : 'Session Creation Request to RTP',
   'tapa.hrt.sess.cfm' : 'Handels Session Confirmation from RTP',
   'tapa.hrt.rel.req' : 'Release session request to RTP',
   'tapa.hrt.rel.cfm' : 'Session Release confirmation form RTP',
	#Added for Dummy RTP
   'tapa.dhrt.hdlbnd.req' : 'Handel Bind Request to Dummy RTP',
   'tapa.daal.bnd.req' : 'Handel Bind Request to Dummy AAL2',
   'tapa.aal.dat.req' : 'Handel Data Request to Dummy AAL2',
   'tapa.aal.dat.ind' : 'Handel Data Indication to Dummy AAL2',
   'tapa.daal.bnd.cfm' : 'Handel Bind Comfirm to Dummy AAL2',
   'tapa.daal.ubnd.req' : 'Handel UNBind Request to Dummy AAL2',
   'tapa.dhrt.hdlbnd.cfm' : 'Handel bind confirmation for Dummy RTP',
   'tapa.dhrt.hdlubnd.req' : 'Handel Unbind Request for Dummy RTP',
   'tapa.dhrt.hdlsess.req' : 'Handel Session Creation Request for Dummy RTP',
   'tapa.dhrt.hdlsess.ind' : 'Handel Session indication for Dummy RTP',
   'tapa.dhrt.hdlsess.rsp' : 'Handels Session Response for Dummy RTP',
   'tapa.dhrt.hdlsess.cfm' : 'Handels Session Confirmation for RTP',
   'tapa.dhrt.hdlrel.req' : 'Handel session release request for Dummy RTP ',
   'tapa.dhrt.hdlrel.ind' : 'Handel Session release indication for Dummy RTP',
   'tapa.dhrt.hdlrel.rsp' : 'Handel Session release response  for Dummy RTP',
   'tapa.dhrt.hdlrel.cfm' : 'Handel Session release confirmation for Dummy RTP',
   'tapa.dhrt.hdludat.req' : 'Unit Data Request for Dummy RTP',
   'tapa.dhrt.hdludat.ind' : 'Unit Data Indication for Dummy RTP',
	#Added Simple commands for GTP 
   'tapa.lgt.cfg.gen' : 'General Configuration for GTP',
   'tapa.lgt.cfg.extgen' : 'Extended General Configuration for GTP',
   'tapa.lgt.cfg.ggusap' : 'GGU SAP Configuration for GTP',
   'tapa.lgt.cfg.tsap' : 'TSAP Configuration for GTP',
   'tapa.lgt.cfg.server' : 'Server Configuration for GTP',
   'tapa.lgt.cfgcfm' : 'Configuration Confirmation for GTP',
   'tapa.lgt.cntrl.usta' : 'Control Request for GTP',
   'tapa.lgt.cntrl.trc' : 'Trace Control Request for GTP',
   'tapa.lgt.cntrl.tsap' : 'TSAP Control Request for GTP',
   'tapa.lgt.cntrl.ggusap' : 'GGU SAP Control Request for GTP',
   'tapa.lgt.cntrl.server' : 'Server Control Request for GTP',
   'tapa.lgt.cntrl.debug' : 'Debug Control Request for GTP',
   'tapa.lgt.cntrl.shutdown' : 'ShutDown Control Request for GTP',
   'tapa.lgt.cntrlcfm' : 'Control Confirmation from GTP',
   'tapa.lgt.sts.gen' : 'General Statistics Request for GTP',
   'tapa.lgt.sts.ggusap' : 'GGU Statistics Request for GTP',
   'tapa.lgt.stscfm' : 'Statistics Confirmation for GTP',
   'tapa.lgt.sta.sys' : 'System Status Request for GTP',
   'tapa.lgt.sta.tsap' : 'TSAP Status Request for GTP',
   'tapa.lgt.sta.ggusap' : 'GGU Status Request for GTP',
   'tapa.lgt.sta.gen' : 'General Status Request for GTP',
   'tapa.lgt.sta.con' : 'Connection Status Request for GTP',
   'tapa.lgt.stacfm' : 'Status Confirmation for GTP',
   'tapa.lgt.staind' : 'Status Indication for GTP',
   'tapa.lgt.trcind' : 'Trace Indication for GTP',
   'tapa.ggu.bnd.req' : 'Bind Request for GTP',
   'tapa.ggu.bnd.cfm' : 'Bind Confirmation for GTP',
   'tapa.ggu.ubnd.req' : 'Unbind request for GTP',
   'tapa.ggu.lcltnlmgmt.req' : 'Local Tunnel Management Request for GTP',
   'tapa.ggu.lcltnlmgmt.cfm' : 'Local Tunnel Management Confirmation for GTP',
   'tapa.ggu.sta.ind' : 'Status Indication for GTP',
   'tapa.ggu.lcldel.req' : 'Local Tunnel deletion request for GTP',
   'tapa.ggu.lcldel.cfm' : 'Local Tunnel deletion confirmation for GTP',
	#Added for Dummy RTP
   'tapa.dggu.hdlbnd.req' : 'Handle Bind Request to dummy GTP',
   'tapa.dggu.hdlbnd.cfm' : 'Handle Bind Confirmation from dummy GTP',
   'tapa.dggu.hdlubnd.req' : 'Handle Ubind Request from dummy GTP',
   'tapa.dggu.hdllcltnlmgmt.req' : 'Handle Local Tunnel Management Request to dummy GTP',
   'tapa.dggu.hdllcltnlmgmt.cfm' : 'Handle Local Tunnel Management Confirmation from dummy GTP',
   'tapa.dggu.hdllcldel.req' : 'Handle Local Tunnel Management Request to dummy GTP',
   'tapa.dggu.hdllcldel.cfm' : 'Handle Local Tunnel Management Cfm from  dummy GTP',
   'tapa.dggu.hdludat.req' : 'Handle Data Request to  dummy GTP',
   'tapa.dggu.hdludat.ind' : 'Handle Data Indication from  dummy GTP',
   'tapa.dggu.hdlflc.ind' : 'Handle Flow Control Indication from  dummy GTP',
	#Added Simple commands for IUUP
   'tapa.llx.cfg.gen' : 'General Configuration Request for LX',
   'tapa.llx.cfg.usap' : 'Usap Configuration Request for LX',
   'tapa.llx.cfg.tsap' : 'Tsap Configuration Request for LX',
   'tapa.llx.cfgcfm' : 'Configuration Confirmation for LX',
   'tapa.llx.cntrl.usta' : 'Unsolicited Status Control Request for LX',
   'tapa.llx.cntrl.trc' : 'Trace Control Request for LX',
   'tapa.llx.cntrl.tsap' : 'TSAP Control Request for LX',
   'tapa.llx.cntrl.usap' : 'USAP Control Request for LX',
   'tapa.llx.cntrl.debug' : 'Debug Control Request for LX',
   'tapa.llx.cntrl.shutdown' : 'Shutdown Control Request for LX',
   'tapa.llx.cntrlcfm' : 'Control Confirmation for LX',
   'tapa.llx.sts.gen' : 'General Statistics for LX',
   'tapa.llx.sts.inst' : 'Inst Statistics for LX',
   'tapa.llx.sts.tsap' : 'TSAP Statistics for LX',
   'tapa.llx.sts.usap' : 'USAP Statistics for LX',
   'tapa.llx.stscfm' : 'Statistics Confirmation for LX',
   'tapa.llx.sta.sys' : 'System Status Request for LX',
   'tapa.llx.sta.gen' : 'General Status Request for LX',
   'tapa.llx.sta.tsap' : 'TSAP Status Request for LX',
   'tapa.llx.sta.usap' : 'USAP Status Request for LX',
   'tapa.llx.sta.inst' : 'Inst Status Request for LX',
   'tapa.llx.stacfm' : 'Status Confirmation for LX',
   'tapa.llx.staind' : 'Unsolicited Indication for LX',
   'tapa.llx.trcind' : 'Trace Indication for LX',
   'tapa.lxt.bndreq' : 'LXT Bind Request',
   'tapa.lxt.bndcfm' : 'LXT Bind Confirm',
   'tapa.lxt.ubndreq' : 'LXT Unbind Request',
   'tapa.lxt.inst.cfg.req' : 'LXT Instance Configuration Request',
   'tapa.lxt.inst.cfg.cfm' : 'LXT Instance Configuration confirmation',
   'tapa.lxt.udatreq' : 'LXT Unit Data Request',
   'tapa.lxt.udatind' : 'LXT Unit Data Indication',
   'tapa.lxt.datreq' : 'LXT Data Request',
   'tapa.lxt.datind' : 'LXT Data Indication',
   'tapa.lxt.stareq' : 'LXT Status Request',
   'tapa.lxt.staind' : 'LXT Status Indication',
   'tapa.lxt.starsp' : 'LXT Status respons',
   'tapa.lxt.stacfm' : 'LXT Status Confirmation',
   'tapa.lxt.errind' : 'LXT Error Indication',
   'tapa.lsh.sts.gen' : 'SCTP Gen Statistics Request',
   'tapa.lsz.cfg.gen'   : 'General Configuration Request for S1AP',
   'tapa.lsz.test.invalid'   : 'To test the invalid cases',
   'tapa.lsz.cfg.lsap'  :  'Sct Sap Configuration Request for S1AP',
   'tapa.lsz.cfg.usap'  :  'Szt Sap Configuration Request for S1AP',
   'tapa.lsz.cfg.prot'  :  'Protocol Configuration Request for S1AP',
   'tapa.lsz.cfg.peer'  :  'Peer Configuration Request for S1AP',
   'tapa.lsz.cfgcfm'    :  'Configuration Confirmation for S1AP',
   'tapa.lsz.sts.req'   :  'Statistics Request for S1AP',
   'tapa.lsz.stscfm'    :  'Statistics Confirmation for S1AP',
   'tapa.lsz.sta.req'   :  'Status Request for S1AP',
   'tapa.lsz.stacfm'    :  'Status Confirmation for S1AP',
   'tapa.lsz.staInd'    :  'Status Indication for S1AP',
   'tapa.lsz.trcInd'    :  'Trace Indication for S1AP',
   'tapa.lsz.cntrl.uSap'   :  'Szt Sap Control Request for S1AP',
   'tapa.lsz.cntrl.lSap'   :  'Sct Sap Control Request for S1AP',
   'tapa.lsz.cntrl.lSapTrc'   :  'Sct Sap Trace Control Request for S1AP',
   'tapa.lsz.cntrl.pNodeTrc'  :  'Peer Node Trace Control Request for S1AP',
   'tapa.lsz.cntrl.debug'  :  'Debug Control Request for S1AP',
   'tapa.lsz.cntrl.peer'   :  'Control Request for S1AP',
   'tapa.lsz.cntrl.usta'   :  'Unsloicited Status Control Request for S1AP',
   'tapa.lsz.cntrlcfm'  :  'Control Confirm from S1AP',
   'tapa.lsz.cntrl.shutdown'  :'ShutDown Control Request for S1AP',
   'tapa.szt.bndreq' : 'SZT Bind Request',
   'tapa.szt.bndcfm' : 'SZT Bind Confirm',
   'tapa.szt.ubndreq'   : 'SZT Unbind Request',
   'tapa.szt.audreq'  : 'SZT Audit Request',
   'tapa.szt.audcfm'  : 'SZT Audit Confirm',
   'tapa.szt.flcind'  : 'SZT Flow Control Indication',
   'tapa.szt.staind' : 'SZT Status Indication',
   'tapa.szt.errind' : 'SZT Error Indication',
   'tapa.szt.udatreq'   : 'Connection-less Data Request',
   'tapa.szt.udatind'   : 'Connection-less Data Indication',
   'tapa.szt.conreq' : 'Associated Logical Connection Creation Request',
   'tapa.szt.conind' : 'Associated Logical Connection Creation Indication',
   'tapa.szt.conrsp' : 'Associated Logical Connection Creation Response',
   'tapa.szt.concfm' : 'Associated Logical Connection Creation Confirmation',
   'tapa.szt.relreq' : 'Associated Logical Connection Release Request',
   'tapa.szt.relind' : 'Associated Logical Connection Release Indicaiton',
   'tapa.szt.BldUnsucOutComeMsg' : 'Associated Logical Connection BldUnsucOutComeMsg',
   'tapa.szt.relrsp' : 'Associated Logical Connection Release Reply',
   'tapa.szt.relcfm' : 'Associated Logical Connection Release Confirmation',
   'tapa.szt.datreq' : 'Associated Signalling Data Request',
   'tapa.szt.datind' : 'Associated Signalling Data Indication',
   'tapa.szt.encreq' : 'Encode S1AP Message Request',
   'tapa.szt.enccfm' : 'Encode S1AP Message Confirmation',
   'tapa.szt.decreq' : 'Decode S1AP Message Request',
   'tapa.szt.deccfm' : 'Decode S1AP Message Confirmation',
#cm_xta_pycmd_py_001.main_24 Added for S1 Abort request support by UI 
   'tapa.szt.aborts1req' : 'Abort S1 Setup Request',
   'tapa.szt.aborts1cfm' : 'Abort S1 Setup Confirmation',
   'tapa.szt.clearMmeCb' : 'Clear MME Cb',
   'tapa.szt.assocind' : 'S1AP Peer Assoc Indication',
#cm_xta_pycmd_py_001.main_20: Updated for PSF-S1AP 1.1 Release
   'tapa.szt.assocrsp' : 'S1AP Peer Assoc Response',
   'tapa.oam.cntrvalreq' : 'OAM L3 Counter Req',
   'tapa.oam.cntrvalrsp' : 'OAM L3 Counter Value Response',
   'tapa.oam.cntrclrreq' : 'OAM L3 Counter Clear Req',
   'tapa.oam.cntrclrrsp' : 'OAM L3 Counter Clear Rsponse',
   
   'tapa.czt.bmpind' : 'X2AP bmp indication',
   'tapa.czt.gpreq'  : 'X2AP General Procedure Request',
   'tapa.czt.gprsp'  : 'X2AP General Procedure Response',
   'tapa.czt.gpind'  : 'X2AP General Procedure indication',
   'tapa.czt.bmpreq' : 'X2AP bmp request',
   'tapa.czt.bmprsp' : 'X2AP bmp response',
   'tapa.czt.bmpcfm' : 'X2AP bmp confirm', 
   'tapa.czt.relreq' : 'X2AP Local Release Request',
   'tapa.czt.staind' : 'X2AP Status Indication',
   'tapa.czt.errind' : 'X2AP Error Indication',

   'tapa.lyt.shcntrlcfm' : 'S1AP-PSF LM SHT Control CFM',
   'tapa.sht.lytcntrl.req' : 'S1AP Sht Control request',
   'tapa.sht.lytcntrlcfm' : 'S1AP Sht Control cfm',
   'tapa.sht.lszcntrl.req' : 'S1AP SHT Control Request',
   'tapa.sht.lszcntrlcfm' : 'S1AP SHT Control Request',
#TotaleNodeB Application Acceptance
#Radisys1_S
   'tapa.lwr.cztcfg' : 'Czt ReCfg Request',
#Radisys1_E
   'tapa.lwr.cfgreq' : 'TotaleNodeB Cfg Request',
   'tapa.lwr.recfgreq' : 'TotaleNodeB ReCfg Request',
   'tapa.lwr.dyncfgreq' : 'TotaleNodeB Dyn Cfg Request',
   'tapa.lwr.multidyncfgreq' : 'Multiple TotaleNodeB Dyn Cfg Request',
   'tapa.lwr.cfgcfm' : 'TotaleNodeB Cfg Confirmation',
   'tapa.lwr.dyncfgcfm' : 'TotaleNodeB Dyn Cfg Confirmation',
   'tapa.lwr.s1init.cntrl.req' : 'TotaleNodeB S1 Init Cntrl Req',
   'tapa.lwr.x2init.cntrl.req' : 'TotaleNodeB x2 Init Cntrl Req',
   'tapa.lwr.cellup.cntrl.req' : 'TotaleNodeB Cell Up Cntrl Req',
   'tapa.lwr.cntrlcfm' : 'TotaleNodeB cntrl Confirmation',
   'tapa.nhu.cellcfgreq' : 'TotaleNodeB Cell Cfg Req to NHU',
   'tapa.nhu.cellcfgcfm' : 'TotaleNodeB Cell Cfg Cfm from RRC to App',
   'tapa.rgr.cfgreq'     : 'TotaleNodeB SCHD Cfg Req to RGR',
   'tapa.rgr.cfgreq.cfg.enb'     : 'TotaleNodeB SCHD Enodeb Cfg Req to RGR',
   'tapa.rgr.cfgreq.cfg.ue'     : 'TotaleNodeB SCHD Ue Cfg Req to RGR',
   'tapa.rgr.cfgCfm'     : 'TotaleNodeB RGR cfg Cfm to App',
   'tapa.ctf.cfgreq'     : 'TotaleNodeB CTF cfg Req to PHY',
   'tapa.ctf.cfgcfm'     : 'TotaleNodeB CTF cfg CFM to App',
   'tapa.ctf.eNBStopInd'     : 'TotaleNodeB CTF eNB Stop Indication to App',
   'tapa.rgr.sicfgreq'   : 'TotaleNodeB RGR cfg Req to MAC SCHD',
   'tapa.rgr.sicfgcfm'   : 'TotaleNodeB RGR SI Cfm to App from SCHD',
   'tapa.rgr.warningsicfgreq'   : 'TotaleNodeB RGR Warning SI cfg Req to MAC SCHD',
   'tapa.rgr.warningsicfgcfm'   : 'TotaleNodeB RGR Warning SI Cfm to App from SCHD',
   'tapa.rgr.warningsistopreq'  : 'TotaleNodeB RGR Warning SI STOP Req to MAC SCHD',
   'tapa.rgr.ttireq'     : 'TotaleNodeB RGR TTI IND to app from MAC',
   'tapa.rgr.uesta.ind'  : 'TotaleNodeB RGR UE STA IND to app from MAC', 
   'tapa.rgr.sib7.val'   : 'TotaleNodeB RGR SIB7 Vaidation from APP to MAC', 
   'tapa.rgr.sib8.val'   : 'TotaleNodeB RGR SIB8 Vaidation from APP to MAC', 
   'tapa.rgr.sib3.val'   : 'TotaleNodeB RGR SIB3 Vaidation from APP to MAC', 
   'tapa.nhu.datind'     : 'TotaleNodeB Nhu dat indication to App from NHU',
   'tapa.nhu.datreq'     : 'TotaleNodeB Nhu dat request to NHU from App',
   'tapa.nhu.datrsp'     : 'TotaleNodeB Nhu dat response from App to NHU',
   'tapa.nhu.sdustareq'  : 'TotaleNodeB Nhu SDU Status Request',
   'tapa.nhu.sdustacfm'  : 'TotaleNodeB Nhu SDU Status Confirm',
   'tapa.nhu.datresumereq'  : 'TotaleNodeB Nhu Data Resume Request', #udaka
   'tapa.nhu.datresumecfm'  : 'TotaleNodeB Nhu Date Resume Confirm',
   'tapa.nhu.cfgcfm'     : 'TotaleNodeB Nhu Cfg Cfm to App from NHU',
   'tapa.nhu.cfgreq'     : 'TotaleNodeB Nhu Cfg requst to NHU from App',
   'tapa.nhu.encodereq'  : 'TotaleNodeB Nhu encode request to NHU from App',
   'tapa.nhu.decodereq'  : 'TotaleNodeB Nhu decode request to NHU from App',
   'tapa.nhu.decodecfm'  : 'TotaleNodeB Nhu decode Cfm to App from NHU',
   'tapa.nhu.encodecfm'  : 'TotaleNodeB Nhu encode Cfm to App from NHU',
   'tapa.nhu.pdcpdatafwdreq':'PDCP Data Forward Request',
   'tapa.nhu.mcelldatrsp' : 'TotaleNodeB Nhu dat response from App to NHU for Multi cell',
   'tapa.nhu.staticreset': 'To reset the static varaible in NHU Dat Request',
   'tapa.nhu.datcfm'     : 'TotaleNodeB Nhu dat Cfm to App from NHU',
   'tapa.nhu.cncluereq'  : 'TotaleNodeB Nhu Cancel UE Request to NHU from APP',
   'tapa.lwr.shutdownreq'  : 'TotaleNodeB Lwr ShutDown Request to APP from LM',
   'tapa.infoshow'       : 'show memory',
   'tapa.lwr.fullreset.req' : 'Full reset',
#EGTP 
   'tapa.egt.egutnlmgmtreq' : 'TotaleNodeB EGT tunnel Management request from App to EGT',
   'tapa.egt.egutnlmgmtcfm' : 'TotaleNodeB EGT tunnel Management Cfm from EGT to App',
   'tapa.egt.egudatreq'     : 'EGTP-U data request',
   'tapa.egt.egudatind'     : 'EGT-U data indication',
#PDCP
   'tapa.pju.datind'     : 'PDCP',
   'tapa.pju.datfwdind'  : 'PJU Data Forward Indication',
   'tapa.pju.datreq'     : 'PJU Data Request',
   'tapa.pju.datfwdreq'  : 'PJU Data Forward Request',
   'tapa.lrm.cpuloadind' : 'CPU load Indication',
   'tapa.lrm.cellUpInd' : 'LRM Cell Up indication',
   'tapa.rmu.ueadmitrsp' : 'UE Admit Response',
   'tapa.rmu.fsmstaind' : 'FSM Status Indication',
   'tapa.rmu.uerelind'  : 'UE Release Indication',
   'tapa.lrm.genCfgCfm' : 'Generic Config confirm',
   'tapa.invalid' : 'Invalid Command',
   'tapa.lrm.cellcfgreq' : 'Cell config Request',
   'tapa.lrm.sapCfgReq' : 'SAP Config Request',
   'tapa.lrm.lsapCfgReq' : 'Lower SAP Config Request',
   'tapa.rmu.initconextsetupreq' : 'UE ICS Request',
   'tapa.rmu.uerelreq' : 'UE Release Request',
   'tapa.lrm.sapCfgCfm' : 'SAP Config Confirm',
   'tapa.rmu.crntirecfgreq' : 'UE Crnti Reconfiguration Request',
   'tapa.rmu.uerecfgrsp' : 'UE Reconfiguration Response',
   'tapa.rmu.uerecfgreq' : 'UE Reconfiguration Request',
   'tapa.re' : 'Validate Regular Expression',
   'tapa.rmu.mmeovldstart' : 'MME Overload Start Indication',
   'tapa.rmu.mmeovldstop' : 'MME Overload Stop Indication',
   'tapa.lrm.enbCfgReq' : 'eNB Config Request',
   'tapa.rmu.ueadmitreq' : 'UE Admit Request',
   'tapa.rmu.uerelrsp' : 'UE Release Response',
   'tapa.rmu.erabrecfgreq' : 'UE ERAB Reconfiguration Request',
   'tapa.rmu.uecaprecfgreq' : 'UE Capacity Reconfiguration Request',
   'tapa.rmu.scellrecfgreq' : 'UE Scell Addtion Reconfig Request',
   'tapa.lrm.enbCfgCfm' : 'eNB Config Confirm',
   'tapa.lrm.cellcfgCfm' : 'Cell Config Confirm',
   'tapa.lrm.genCfgReq' : 'Generic Config Request',
   'tapa.rmu.cellrecfgind' : 'Cell Reconfig Indication',
   'tapa.rmu.fsmstatusind' : 'FSM Status Indication',
   'tapa.rmu.uehoreq' :  'UE HO Request',
   'tapa.rmu.uehorsp' :  'UE HO Response',
   'tapa.rgm.prbind' : 'PRB Usage Indication',
   'tapa.lrm.enbCtrlReq' : 'eNB Control Request',
   'tapa.lrm.enbCtrlCfm' : 'eNB Control Confirm',
   'tapa.rgm.prbCfgReq' : 'PRB report Cfg Request',
   'tapa.rgm.bndReq' : 'LRM Bind Request',
   'tapa.rgm.bndCfm' : 'LRM Bind Confirm',

   'tapa.uemeas.eutraA1Evnt' : ' To trigger A1 Evnt ' ,
   'tapa.uemeas.eutraA2Evnt' : ' To trigger A2 Evnt ',
   'tapa.uemeas.eutraHoA3Evnt' : ' To trigger A3 Evnt for Handover ',
   'tapa.uemeas.eutraAnrA3Evnt' : 'To trigger A3 Evnt for ANR ',
   'tapa.uemeas.eutraA4Evnt' : ' To trigger A4 Evnt ',
   'tapa.uemeas.eutraHoA5Evnt' : ' To trigger A5 Evnt for Handover ',
   'tapa.uemeas.eutraAnrA5Evnt' : ' To trigger A5 Evnt for ANR ',
   'tapa.uemeas.utraB1Evnt' : ' To trigger B1 Evnt for UTRA ',
   'tapa.uemeas.cdmaB1Evnt' : ' To trigger B1 Evnt for CDMA ',
   'tapa.uemeas.utraHoB2Evnt' : ' To trigger B2 Evnt for UTRA Handover ',
   'tapa.uemeas.utraAnrB2Evnt' : ' To trigger B2 Evnt for UTRA ANR ',
   'tapa.uemeas.cdmaHoB2Evnt' : ' To trigger B2 Evnt for CDMA Handover ',
   'tapa.uemeas.cdmaAnrB2Evnt' : ' To trigger B2 Evnt for CDMA ANR ',
   'tapa.uemeas.eutraRptStrngCells' : ' To trigger Report Strongest Cells for EUTRA ',
   'tapa.uemeas.eutraRptCGI' : ' To trigger Report CGI for EUTRA ',
   'tapa.uemeas.utraRptStrngCells' : ' To trigger Report Strongest Cells for UTRA ',
   'tapa.uemeas.utraRptCGI' : ' To trigger Report CGI for UTRA ',
   'tapa.uemeas.cdmaRptStrngCells' : ' To trigger Report Strongest Cells for CDMA ',
   'tapa.uemeas.cdmaRptCGI' : ' To trigger Report CGI for CDMA ',
   'tapa.uemeas.perf' : ' To perform Measurement ',
#SON   
   'tapa.nlu.newNghReq' : ' New Neighbor Request to SON ',
   'tapa.nlu.pciModIndCfm' : ' PCI Modify Cfm Ind to SON ',
   'tapa.uemeas.perf':'Cdma Report CGI',
   'tapa.uemeas.chkBlkCLst' : 'Checks the EUTRA Black listed cells',
   'tapa.uemeas.chkWhtCLst':'Checks the EUTRA White listed cells',
   'tapa.uemeas.chkUtraCLst':'Checks the UTRA Listed cells',
   'tapa.uemeas.chkNoIntrRatMeasObj':'Checks that UTRA/CDMA measurement object are not configured',
   'tapa.uemeas.rptCfgIntrRat':'Checks Inter RAT Report Configuration parameters',
   'tapa.lwr.scell.cntrl.req':'Scell Addition/deletion/Act/Deact commnad',
}

#Code added to parse product specific py files
import glob

pycmdList = glob.glob("*ac_pycmd.py")
for elm in pycmdList :
    mo = __import__(elm[:-3])

    intCmdDict.update(mo.intCmdDict)
    simpleCmdDict.update(mo.simpleCmdDict)


#/********************************************************************30**
#
#         End of file:     cm_xta_pycmd.py@@/main/26 - Tue Apr 10 12:26:14 2012
#
#*********************************************************************31*/
#
#
#/********************************************************************40**
#
#        Notes:
#
#*********************************************************************41*/
#
#/********************************************************************50**
#
#*********************************************************************51*/
#
#
#/********************************************************************60**
#
#        Revision history:
#
#*********************************************************************61*/
#
#/********************************************************************90**
#
#     ver       pat    init                  description
#------------ -------- ---- ----------------------------------------------
#            cm_xta_pycmd_py_001.main_  rr
#/main/3      ---      sy  1. Update of sid field
#/main/4      cm_xta_pycmd_py_001.main_3  sk  1. Updated simple commands for FTHA
#/main/5      ---      rd   1. Correcting the SID line
#/main/6      ---      rb   1. Updated for PDCP Software release 1.1 
#/main/7      ---      mr   1. RRC commands Addition. RRC Rel 2.0
#/main/8      ---      aj  1. Added the support for FTHA Integration
#/main/9      ---      rb   1. Updated for RRC Release 2.1
#/main/10     ---      mn   1. Loop changes 
#/main/11     ---      rer  1. Added UEidChngCfm
#/main/12     ---      rb   1. Added RRC commands.
#/main/13     ---      nk   1. Updated for IuUP release
#/main/14     ---      sy   1. Updated for SIP sdk release 1.1.
#/main/16     ---      pc   1. Updated for IuUP release
#/main/18     ---      pc   1. Updated for EGTP release 1.1
#/main/19     ---      st   1. Updated for LTE MAC release 1.1
#/main/20     ---      gm   1. rr013.202 patch for MAC Count-C Support
#/main/21   cm_xta_pycmd_py_001.main_20  pka  1. Updated for PSF-S1AP 1.1 Release
#/main/25      cm_xta_pycmd_py_001.main_24  va   1. Updated for S1 Abort request support by UI
#*********************************************************************91*/

