/**********************************************************************

     Name:     LTE RRC Layer

     Type:     C include file

     Desc:     Defines required by RRC

     File:     nhu_asn.h

     Sid:      nhac_asn.h@@/main/TeNB_Main_BR/tenb_main_ccb/1 - Wed Jul 22 20:18:11 2015

     Prg:      pparande

**********************************************************************/

#ifndef __NHACASNH__
#define __NHACASNH__ 
/* nhu_asn_h_001.main_2: Addded new macros REl9 upgrade*/

namespace NH_ASN_H_R9
{
#define NHUCHKUNPKPTR(func, val, ptr, mBuf) {\
   S16 ret;\
   if ((ret = func(val, mBuf, ptr)) != ROK)\
      RETVALUE(ret);\
}
#define Nhuid_Invalid 0xffffffff

#define SOUNDINGRS_UL_CONFIGCMN_RELEASE 0
#define SOUNDINGRS_UL_CONFIGCMN_SETUP 1

#define SUBFRAMEALLOCN_ONEFRAME 0
#define SUBFRAMEALLOCN_FOURFRAMES 1

#define FOLLOWINGARFCNS_EXPLICITLSTOFARFCNS 0
#define FOLLOWINGARFCNS_EQUALLYSPACEDARFCNS 1
#define FOLLOWINGARFCNS_VARIABLEBITMAPOFARFCNS 2

#define CDMA_SYSTIME_SYNCHRONOUSSYSTIME 0
#define CDMA_SYSTIME_ASYNCHRONOUSSYSTIME 1

#define MEMBER_SIB2 0
#define MEMBER_SIB3 1
#define MEMBER_SIB4 2
#define MEMBER_SIB5 3
#define MEMBER_SIB6 4
#define MEMBER_SIB7 5
#define MEMBER_SIB8 6
#define MEMBER_SIB9 7
#define MEMBER_SIB10 8
#define MEMBER_SIB11 9
#define MEMBER_SIB12_V920 10
#define MEMBER_SIB13_V920 11

#define CRITICALEXTNS_SYSTEMINFO_R8 0

#define C1_SYSTEMINFO 0
#define C1_SYSTEMINFOBLOCKTYP1 1
#define BCCH_DL_SCH_MSGTYP_C1 0
#define BCCH_DL_SCH_MSGTYP_MESSAGECLASSEXTN 1
#define PLMN_ID_R9_PLMN_IDX_R9 0
#define PLMN_ID_R9_EXPLICITVALUE_R9 1

#define C26_MBSFNAREACFG_R9 0
#define MCCH_MSGTYP_C26 0
#define MCCH_MSGTYP_MESSAGECLASSEXTN 1

#define PAGUE_IDENTITY_S_TMSI 0
#define PAGUE_IDENTITY_IMSI 1

#define C2_PAGING 0
#define PCCH_MSGTYP_C2 0
#define PCCH_MSGTYP_MESSAGECLASSEXTN 1

#define RLC_CONFIG_AM 0
#define RLC_CONFIG_UM_BI_DIRECTIONAL 1
#define RLC_CONFIG_UM_UNI_DIRECTIONAL_UL 2
#define RLC_CONFIG_UM_UNI_DIRECTIONAL_DL 3

#define RLC_CONFIG_EXPLICITVALUE 0
#define RLC_CONFIG_DEFAULTVALUE 1
#define LOGICALCHANNELCONFIG_EXPLICITVALUE 0
#define LOGICALCHANNELCONFIG_DEFAULTVALUE 1
#define HEADERCOMPRESSION_NOTUSED 0
#define HEADERCOMPRESSION_ROHC 1

#define LONGDRX_CYCLESTARTOFFSET_SF10 0
#define LONGDRX_CYCLESTARTOFFSET_SF20 1
#define LONGDRX_CYCLESTARTOFFSET_SF32 2
#define LONGDRX_CYCLESTARTOFFSET_SF40 3
#define LONGDRX_CYCLESTARTOFFSET_SF64 4
#define LONGDRX_CYCLESTARTOFFSET_SF80 5
#define LONGDRX_CYCLESTARTOFFSET_SF128 6
#define LONGDRX_CYCLESTARTOFFSET_SF160 7
#define LONGDRX_CYCLESTARTOFFSET_SF256 8
#define LONGDRX_CYCLESTARTOFFSET_SF320 9
#define LONGDRX_CYCLESTARTOFFSET_SF512 10
#define LONGDRX_CYCLESTARTOFFSET_SF640 11
#define LONGDRX_CYCLESTARTOFFSET_SF1024 12
#define LONGDRX_CYCLESTARTOFFSET_SF1280 13
#define LONGDRX_CYCLESTARTOFFSET_SF2048 14
#define LONGDRX_CYCLESTARTOFFSET_SF2560 15
#define DRX_CONFIG_RELEASE 0
#define DRX_CONFIG_SETUP 1
#define PHR_CONFIG_RELEASE 0
#define PHR_CONFIG_SETUP 1

#define SPS_CONFIGDL_RELEASE 0
#define SPS_CONFIGDL_SETUP 1

#define SPS_CONFIGUL_RELEASE 0
#define SPS_CONFIGUL_SETUP 1

#define ACKNACKREPETITION_RELEASE 0
#define ACKNACKREPETITION_SETUP 1

#define TPC_IDX_INDEXOFFORMAT3 0
#define TPC_IDX_INDEXOFFORMAT3A 1

#define TPC_PDCCH_CONFIG_RELEASE 0
#define TPC_PDCCH_CONFIG_SETUP 1

#define CQI_FORMATINDICATORPERIODIC_WIDEBANDCQI 0
#define CQI_FORMATINDICATORPERIODIC_SUBBANDCQI 1
#define CQI_REPORTPERIODIC_RELEASE 0
#define CQI_REPORTPERIODIC_SETUP 1
#define SOUNDINGRS_UL_CONFIGDEDICATED_RELEASE 0
#define SOUNDINGRS_UL_CONFIGDEDICATED_SETUP 1

#define CODEBOOKSUBSETRESTRN_N2TXANTENNA_TM3 0
#define CODEBOOKSUBSETRESTRN_N4TXANTENNA_TM3 1
#define CODEBOOKSUBSETRESTRN_N2TXANTENNA_TM4 2
#define CODEBOOKSUBSETRESTRN_N4TXANTENNA_TM4 3
#define CODEBOOKSUBSETRESTRN_N2TXANTENNA_TM5 4
#define CODEBOOKSUBSETRESTRN_N4TXANTENNA_TM5 5
#define CODEBOOKSUBSETRESTRN_N2TXANTENNA_TM6 6
#define CODEBOOKSUBSETRESTRN_N4TXANTENNA_TM6 7
#define UE_TRANSMITANTENNASELECTION_RELEASE 0
#define UE_TRANSMITANTENNASELECTION_SETUP 1
#define SCHEDULINGRQSTCONFIG_RELEASE 0
#define SCHEDULINGRQSTCONFIG_SETUP 1

#define CODEBOOKSUBSETRESTRN_V920_N2TXANTENNA_TM8_R9 0
#define CODEBOOKSUBSETRESTRN_V920_N4TXANTENNA_TM8_R9 1

#define ANTENNAINFO_EXPLICITVALUE 0
#define ANTENNAINFO_DEFAULTVALUE 1

#define RLF_TMRSANDCONSTS_R9_RELEASE 0
#define RLF_TMRSANDCONSTS_R9_SETUP 1

#define MAC_MAINCONFIG_EXPLICITVALUE 0
#define MAC_MAINCONFIG_DEFAULTVALUE 1

#define C13_RRCCONREESTB_R8 0
#define C13_SPARE7 1
#define C13_SPARE6 2
#define C13_SPARE5 3
#define C13_SPARE4 4
#define C13_SPARE3 5
#define C13_SPARE2 6
#define C13_SPARE1 7
#define CRITICALEXTNS_C13 0
#define CRITICALEXTNS_RRCCONREESTBREJ_R8 0

#define C14_RRCCONREJ_R8 0
#define C14_SPARE3 1
#define C14_SPARE2 2
#define C14_SPARE1 3
#define CRITICALEXTNS_C14 0
#define C16_RRCCONSETUP_R8 0
#define C16_SPARE7 1
#define C16_SPARE6 2
#define C16_SPARE5 3
#define C16_SPARE4 4
#define C16_SPARE3 5
#define C16_SPARE2 6
#define C16_SPARE1 7
#define CRITICALEXTNS_C16 0
#define C3_RRCCONREESTB 0
#define C3_RRCCONREESTBREJ 1
#define C3_RRCCONREJ 2
#define C3_RRCCONSETUP 3
#define DL_CCCH_MSGTYP_C3 0
#define DL_CCCH_MSGTYP_MESSAGECLASSEXTN 1
#define CRITICALEXTNS_CSFBPARAMSRSPCDMA2000_R8 0

#define DEDICATEDINFOTYP_DEDICATEDINFONAS 0
#define DEDICATEDINFOTYP_DEDICATEDINFOCDMA2000_1XRTT 1
#define DEDICATEDINFOTYP_DEDICATEDINFOCDMA2000_HRPD 2

#define C8_DLINFOTFR_R8 0
#define C8_SPARE3 1
#define C8_SPARE2 2
#define C8_SPARE1 3
#define CRITICALEXTNS_C8 0
#define C9_HANDOVERFROMEUTRAPREPRQST_R8 0
#define C9_SPARE3 1
#define C9_SPARE2 2
#define C9_SPARE1 3
#define CRITICALEXTNS_C9 0
#define SI_ORPSI_GERAN_SI 0
#define SI_ORPSI_GERAN_PSI 1

#define TARGETRAT_TYP_GERAN 0

#define PURPOSE_HANDOVER 0
#define PURPOSE_CELLCHANGEORDER 1

#define PURPOSE_HANDOVER 0
#define PURPOSE_CELLCHANGEORDER 1
#define PURPOSE_E_CSFB_R9 2

#define C11_MOBILITYFROMEUTRACMD_R8 0
#define C11_MOBILITYFROMEUTRACMD_R9 1
#define C11_SPARE2 2
#define C11_SPARE1 3
#define CRITICALEXTNS_C11 0 
#define CELLSTOADDMODLST_CELLSTOADDMODLSTUTRA_FDD 0
#define CELLSTOADDMODLST_CELLSTOADDMODLSTUTRA_TDD 1
#define CELLFORWHICHTOREPORTCGI_UTRA_FDD 0
#define CELLFORWHICHTOREPORTCGI_UTRA_TDD 1
#define MEASOBJECT_MEASOBJECTEUTRA 0
#define MEASOBJECT_MEASOBJECTUTRA 1
#define MEASOBJECT_MEASOBJECTGERAN 2
#define MEASOBJECT_MEASOBJECTCDMA2000 3

#define THRESHOLDEUTRA_THRESHOLD_RSRP 0
#define THRESHOLDEUTRA_THRESHOLD_RSRQ 1

#define EVENTID_EVENTA1 0
#define EVENTID_EVENTA2 1
#define EVENTID_EVENTA3 2
#define EVENTID_EVENTA4 3
#define EVENTID_EVENTA5 4
#define TRIGGERTYP_EVENT 0
#define TRIGGERTYP_PERIODICAL 1
#define THRESHOLDUTRA_UTRA_RSCP 0
#define THRESHOLDUTRA_UTRA_ECN0 1

#define B1_THRESHOLD_B1_THRESHOLDUTRA 0
#define B1_THRESHOLD_B1_THRESHOLDGERAN 1
#define B1_THRESHOLD_B1_THRESHOLDCDMA2000 2
#define B2_THRESHOLD2_B2_THRESHOLD2UTRA 0
#define B2_THRESHOLD2_B2_THRESHOLD2GERAN 1
#define B2_THRESHOLD2_B2_THRESHOLD2CDMA2000 2
#define EVENTID_EVENTB1 0
#define EVENTID_EVENTB2 1
#define TRIGGERTYP_EVENT 0
#define TRIGGERTYP_PERIODICAL 1
#define REPORTCONFIG_REPORTCONFIGEUTRA 0
#define REPORTCONFIG_REPORTCONFIGINTERRAT 1

#define GAPOFFSET_GP0 0
#define GAPOFFSET_GP1 1
#define MEASGAPCONFIG_RELEASE 0
#define MEASGAPCONFIG_SETUP 1
#define SPEEDSTATEPARS_RELEASE 0
#define SPEEDSTATEPARS_SETUP 1

#define HANDOVERTYP_INTRALTE 0
#define HANDOVERTYP_INTERRAT 1

#define C12_RRCCONRECFGN_R8 0
#define C12_SPARE7 1
#define C12_SPARE6 2
#define C12_SPARE5 3
#define C12_SPARE4 4
#define C12_SPARE3 5
#define C12_SPARE2 6
#define C12_SPARE1 7
#define CRITICALEXTNS_C12 0
#define REDIRECTEDCARRIERINFO_EUTRA 0
#define REDIRECTEDCARRIERINFO_GERAN 1
#define REDIRECTEDCARRIERINFO_UTRA_FDD 2
#define REDIRECTEDCARRIERINFO_UTRA_TDD 3
#define REDIRECTEDCARRIERINFO_CDMA2000_HRPD 4
#define REDIRECTEDCARRIERINFO_CDMA2000_1XRTT 5

#define CELLINFOLST_R9_GERAN_R9 0
#define CELLINFOLST_R9_UTRA_FDD_R9 1
#define CELLINFOLST_R9_UTRA_TDD_R9 2

#define C15_RRCCONRLS_R8 0
#define C15_SPARE3 1
#define C15_SPARE2 2
#define C15_SPARE1 3
#define CRITICALEXTNS_C15 0
#define C18_SECURITYMODECMD_R8 0
#define C18_SPARE3 1
#define C18_SPARE2 2
#define C18_SPARE1 3
#define CRITICALEXTNS_C18 0
#define C19_UECAPENQUIRY_R8 0
#define C19_SPARE3 1
#define C19_SPARE2 2
#define C19_SPARE1 3
#define CRITICALEXTNS_C19 0
#define C7_COUNTERCHECK_R8 0
#define C7_SPARE3 1
#define C7_SPARE2 2
#define C7_SPARE1 3
#define CRITICALEXTNS_C7 0
#define C28_UEINFORQST_R9 0
#define C28_SPARE3 1
#define C28_SPARE2 2
#define C28_SPARE1 3
#define CRITICALEXTNS_C28 0
#define C4_CSFBPARAMSRSPCDMA2000 0
#define C4_DLINFOTFR 1
#define C4_HANDOVERFROMEUTRAPREPRQST 2
#define C4_MOBILITYFROMEUTRACMD 3
#define C4_RRCCONRECFGN 4
#define C4_RRCCONRLS 5
#define C4_SECURITYMODECMD 6
#define C4_UECAPENQUIRY 7
#define C4_COUNTERCHECK 8
#define C4_UEINFORQST_R9 9
#define C4_SPARE6 10
#define C4_SPARE5 11
#define C4_SPARE4 12
#define C4_SPARE3 13
#define C4_SPARE2 14
#define C4_SPARE1 15
#define DL_DCCH_MSGTYP_C4 0
#define DL_DCCH_MSGTYP_MESSAGECLASSEXTN 1
#define CRITICALEXTNS_RRCCONREESTBRQST_R8 0

#define INITUE_IDENTITY_S_TMSI 0
#define INITUE_IDENTITY_RANDOMVALUE 1

#define CRITICALEXTNS_RRCCONRQST_R8 0

#define C5_RRCCONREESTBRQST 0
#define C5_RRCCONRQST 1
#define UL_CCCH_MSGTYP_C5 0 
#define UL_CCCH_MSGTYP_MESSAGECLASSEXTN 1
#define CRITICALEXTNS_CSFBPARAMSRQSTCDMA2000_R8 0

#define PHYSCELLID_FDD 0
#define PHYSCELLID_TDD 1

#define CELLGLOBALIDCDMA2000_CELLGLOBALID1XRTT 0
#define CELLGLOBALIDCDMA2000_CELLGLOBALIDHRPD 1

#define MEASRESULTNEIGHCELLS_MEASRESULTLSTEUTRA 0
#define MEASRESULTNEIGHCELLS_MEASRESULTLSTUTRA 1
#define MEASRESULTNEIGHCELLS_MEASRESULTLSTGERAN 2
#define MEASRESULTNEIGHCELLS_MEASRESULTSCDMA2000 3

#define C10_MEASUREMENTREPORT_R8 0
#define C10_SPARE7 1
#define C10_SPARE6 2
#define C10_SPARE5 3
#define C10_SPARE4 4
#define C10_SPARE3 5
#define C10_SPARE2 6
#define C10_SPARE1 7
#define CRITICALEXTNS_C10 0
#define CRITICALEXTNS_RRCCONRECFGNCOMPL_R8 0

#define CRITICALEXTNS_RRCCONREESTBCOMPL_R8 0

#define C17_RRCCONSETUPCOMPL_R8 0
#define C17_SPARE3 1
#define C17_SPARE2 2
#define C17_SPARE1 3
#define CRITICALEXTNS_C17 0
#define CRITICALEXTNS_SECURITYMODECOMPL_R8 0

#define CRITICALEXTNS_SECURITYMODEFAIL_R8 0

#define C20_UECAPINFO_R8 0
#define C20_SPARE7 1
#define C20_SPARE6 2
#define C20_SPARE5 3
#define C20_SPARE4 4
#define C20_SPARE3 5
#define C20_SPARE2 6
#define C20_SPARE1 7
#define CRITICALEXTNS_C20 0
#define C21_ULHOVRPREPTFR_R8 0
#define C21_SPARE3 1
#define C21_SPARE2 2
#define C21_SPARE1 3
#define CRITICALEXTNS_C21 0
#define DEDICATEDINFOTYP_DEDICATEDINFONAS 0
#define DEDICATEDINFOTYP_DEDICATEDINFOCDMA2000_1XRTT 1
#define DEDICATEDINFOTYP_DEDICATEDINFOCDMA2000_HRPD 2

#define C25_ULINFOTFR_R8 0
#define C25_SPARE3 1
#define C25_SPARE2 2
#define C25_SPARE1 3
#define CRITICALEXTNS_C25 0
#define CRITICALEXTNS_COUNTERCHECKRSP_R8 0

#define C29_UEINFORSP_R9 0
#define C29_SPARE3 1
#define C29_SPARE2 2
#define C29_SPARE1 3
#define CRITICALEXTNS_C29 0
#define CARRIERFREQ_R9_EUTRA_R9 0
#define CARRIERFREQ_R9_UTRA_R9 1

#define C27_PROXIMITYIND_R9 0
#define C27_SPARE3 1
#define C27_SPARE2 2
#define C27_SPARE1 3
#define CRITICALEXTNS_C27 0
#define C6_CSFBPARAMSRQSTCDMA2000 0
#define C6_MEASUREMENTREPORT 1
#define C6_RRCCONRECFGNCOMPL 2
#define C6_RRCCONREESTBCOMPL 3
#define C6_RRCCONSETUPCOMPL 4
#define C6_SECURITYMODECOMPL 5
#define C6_SECURITYMODEFAIL 6
#define C6_UECAPINFO 7
#define C6_ULHOVRPREPTFR 8
#define C6_ULINFOTFR 9
#define C6_COUNTERCHECKRSP 10
#define C6_UEINFORSP_R9 11
#define C6_PROXIMITYIND_R9 12
#define C6_SPARE3 13
#define C6_SPARE2 14
#define C6_SPARE1 15
#define UL_DCCH_MSGTYP_C6 0
#define UL_DCCH_MSGTYP_MESSAGECLASSEXTN 1
#define NhumaxBands 64
#define NhumaxCDMA_BandClass 32
#define NhumaxCellBlack 16
#define NhumaxCellInfoGERAN_r9 32
#define NhumaxCellInfoUTRA_r9 16
#define NhumaxCellInter 16
#define NhumaxCellIntra 16
#define NhumaxCellMeas 32
#define NhumaxCellReport 8
#define NhumaxDRB 11
#define NhumaxEARFCN 65535
#define NhumaxFreq 8
#define NhumaxGERAN_SI 10
#define NhumaxGNFG 16
#define NhumaxMBSFN_Allocns 8
#define NhumaxMBSFN_Area 8
#define NhumaxMeasId 32
#define NhumaxObjectId 32
#define NhumaxPageRec 16
#define NhumaxPhysCellIdRange_r9 4
#define NhumaxPNOffset 511
#define NhumaxPMCH_PerMBSFN 15
#define NhumaxRAT_Capabilities 8
#define NhumaxReportConfigId 32
#define NhumaxSessionPerPMCH 29
#define NhumaxSessionPerPMCH_1 28
#define NhumaxSIB 32
#define NhumaxSIB_1 31
#define NhumaxSI_Msg 32
#define NhumaxUTRA_FDD_Carrier 16
#define NhumaxUTRA_TDD_Carrier 16

#define SPEEDSTATEPARS_RELEASE 0
#define SPEEDSTATEPARS_SETUP 1

#define PHYSCELLIDUTRA_FDD 0
#define PHYSCELLIDUTRA_TDD 1
#define MEMBER_PHYSCELLIDEUTRA 0
#define MEMBER_PHYSCELLIDUTRA 1
#define MEMBER_PHYSCELLIDGERAN 2
#define MEMBER_PHYSCELLIDCDMA2000 3

#define C22_HANDOVERCMD_R8 0
#define C22_SPARE7 1
#define C22_SPARE6 2
#define C22_SPARE5 3
#define C22_SPARE4 4
#define C22_SPARE3 5
#define C22_SPARE2 6
#define C22_SPARE1 7
#define CRITICALEXTNS_C22 0
#define C23_HANDOVERPREPINFO_R8 0
#define C23_SPARE7 1
#define C23_SPARE6 2
#define C23_SPARE5 3
#define C23_SPARE4 4
#define C23_SPARE3 5
#define C23_SPARE2 6
#define C23_SPARE1 7
#define CRITICALEXTNS_C23 0
#define C24_UERADIOACCESSCAPINFO_R8 0
#define C24_SPARE7 1
#define C24_SPARE6 2
#define C24_SPARE5 3
#define C24_SPARE4 4
#define C24_SPARE3 5
#define C24_SPARE2 6
#define C24_SPARE1 7
#define CRITICALEXTNS_C24 0
#define NhumaxReestabInfo 32

#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1
}

 namespace NH_ASN_H_R11
{
#define NHUCHKUNPKPTR(func, val, ptr, mBuf) {\
   S16 ret;\
   if ((ret = func(val, mBuf, ptr)) != ROK)\
      RETVALUE(ret);\
}
#define Nhuid_Invalid 0xffffffff

#define SOUNDINGRS_UL_CONFIGCMN_RELEASE 0
#define SOUNDINGRS_UL_CONFIGCMN_SETUP 1

#define SUBFRAMEALLOCN_ONEFRAME 0
#define SUBFRAMEALLOCN_FOURFRAMES 1

#define FOLLOWINGARFCNS_EXPLICITLSTOFARFCNS 0
#define FOLLOWINGARFCNS_EQUALLYSPACEDARFCNS 1
#define FOLLOWINGARFCNS_VARIABLEBITMAPOFARFCNS 2

#define CDMA_SYSTIME_SYNCHRONOUSSYSTIME 0
#define CDMA_SYSTIME_ASYNCHRONOUSSYSTIME 1

#define MEMBER_SIB2 0
#define MEMBER_SIB3 1
#define MEMBER_SIB4 2
#define MEMBER_SIB5 3
#define MEMBER_SIB6 4
#define MEMBER_SIB7 5
#define MEMBER_SIB8 6
#define MEMBER_SIB9 7
#define MEMBER_SIB10 8
#define MEMBER_SIB11 9
#define MEMBER_SIB12_V920 10
#define MEMBER_SIB13_V920 11

#define CRITICALEXTNS_SYSTEMINFO_R8 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C1_SYSTEMINFO 0
#define C1_SYSTEMINFOBLOCKTYP1 1
#define BCCH_DL_SCH_MSGTYP_C1 0
#define BCCH_DL_SCH_MSGTYP_MESSAGECLASSEXTN 1

#define PLMN_ID_R9_PLMN_IDX_R9 0
#define PLMN_ID_R9_EXPLICITVALUE_R9 1

#define C26_MBSFNAREACFG_R9 0
#define C2_MBMSCOUNTINGRQST_R10 0
#define LATER_C2 0
#define LATER_MESSAGECLASSEXTN 1
#define MCCH_MSGTYP_C26 0
#define MCCH_MSGTYP_LATER 1

#define PAGUE_IDENTITY_S_TMSI 0
#define PAGUE_IDENTITY_IMSI 1

#define C2_PAGING 0
#define PCCH_MSGTYP_C2 0
#define PCCH_MSGTYP_MESSAGECLASSEXTN 1

#define RLC_CONFIG_AM 0
#define RLC_CONFIG_UM_BI_DIRECTIONAL 1
#define RLC_CONFIG_UM_UNI_DIRECTIONAL_UL 2
#define RLC_CONFIG_UM_UNI_DIRECTIONAL_DL 3

#define RLC_CONFIG_EXPLICITVALUE 0
#define RLC_CONFIG_DEFAULTVALUE 1
#define LOGICALCHANNELCONFIG_EXPLICITVALUE 0
#define LOGICALCHANNELCONFIG_DEFAULTVALUE 1

#define HEADERCOMPRESSION_NOTUSED 0
#define HEADERCOMPRESSION_ROHC 1

#define LONGDRX_CYCLESTARTOFFSET_SF10 0
#define LONGDRX_CYCLESTARTOFFSET_SF20 1
#define LONGDRX_CYCLESTARTOFFSET_SF32 2
#define LONGDRX_CYCLESTARTOFFSET_SF40 3
#define LONGDRX_CYCLESTARTOFFSET_SF64 4
#define LONGDRX_CYCLESTARTOFFSET_SF80 5
#define LONGDRX_CYCLESTARTOFFSET_SF128 6
#define LONGDRX_CYCLESTARTOFFSET_SF160 7
#define LONGDRX_CYCLESTARTOFFSET_SF256 8
#define LONGDRX_CYCLESTARTOFFSET_SF320 9
#define LONGDRX_CYCLESTARTOFFSET_SF512 10
#define LONGDRX_CYCLESTARTOFFSET_SF640 11
#define LONGDRX_CYCLESTARTOFFSET_SF1024 12
#define LONGDRX_CYCLESTARTOFFSET_SF1280 13
#define LONGDRX_CYCLESTARTOFFSET_SF2048 14
#define LONGDRX_CYCLESTARTOFFSET_SF2560 15
#define DRX_CONFIG_RELEASE 0
#define DRX_CONFIG_SETUP 1

#define PHR_CONFIG_RELEASE 0
#define PHR_CONFIG_SETUP 1

#define TWOANTENNAPORTACTIVATED_R10_RELEASE 0
#define TWOANTENNAPORTACTIVATED_R10_SETUP 1
#define SPS_CONFIGDL_RELEASE 0
#define SPS_CONFIGDL_SETUP 1

#define SPS_CONFIGUL_RELEASE 0
#define SPS_CONFIGUL_SETUP 1

#define ACKNACKREPETITION_RELEASE 0
#define ACKNACKREPETITION_SETUP 1

#define TPC_IDX_INDEXOFFORMAT3 0
#define TPC_IDX_INDEXOFFORMAT3A 1

#define TPC_PDCCH_CONFIG_RELEASE 0
#define TPC_PDCCH_CONFIG_SETUP 1

#define CQI_FORMATINDICATORPERIODIC_WIDEBANDCQI 0
#define CQI_FORMATINDICATORPERIODIC_SUBBANDCQI 1
#define CQI_REPORTPERIODIC_RELEASE 0
#define CQI_REPORTPERIODIC_SETUP 1

#define SOUNDINGRS_UL_CONFIGDEDICATED_RELEASE 0
#define SOUNDINGRS_UL_CONFIGDEDICATED_SETUP 1

#define CODEBOOKSUBSETRESTRN_N2TXANTENNA_TM3 0
#define CODEBOOKSUBSETRESTRN_N4TXANTENNA_TM3 1
#define CODEBOOKSUBSETRESTRN_N2TXANTENNA_TM4 2
#define CODEBOOKSUBSETRESTRN_N4TXANTENNA_TM4 3
#define CODEBOOKSUBSETRESTRN_N2TXANTENNA_TM5 4
#define CODEBOOKSUBSETRESTRN_N4TXANTENNA_TM5 5
#define CODEBOOKSUBSETRESTRN_N2TXANTENNA_TM6 6
#define CODEBOOKSUBSETRESTRN_N4TXANTENNA_TM6 7
#define UE_TRANSMITANTENNASELECTION_RELEASE 0
#define UE_TRANSMITANTENNASELECTION_SETUP 1

#define SCHEDULINGRQSTCONFIG_RELEASE 0
#define SCHEDULINGRQSTCONFIG_SETUP 1

#define CODEBOOKSUBSETRESTRN_V920_N2TXANTENNA_TM8_R9 0
#define CODEBOOKSUBSETRESTRN_V920_N4TXANTENNA_TM8_R9 1

#define UE_TRANSMITANTENNASELECTION_RELEASE 0
#define UE_TRANSMITANTENNASELECTION_SETUP 1

#define CQI_REPORTAPERIODIC_R10_RELEASE 0
#define CQI_REPORTAPERIODIC_R10_SETUP 1

#define CQI_FORMATINDICATORPERIODIC_R10_WIDEBANDCQI_R10 0
#define CQI_FORMATINDICATORPERIODIC_R10_SUBBANDCQI_R10 1
#define CSI_CONFIGIDX_R10_RELEASE 0
#define CSI_CONFIGIDX_R10_SETUP 1
#define CQI_REPORTPERIODIC_R10_RELEASE 0
#define CQI_REPORTPERIODIC_R10_SETUP 1

#define SUBFRAMEPATTERNTDD_R10_SUBFRAMECONFIG1_5_R10 0
#define SUBFRAMEPATTERNTDD_R10_SUBFRAMECONFIG0_R10 1
#define SUBFRAMEPATTERNTDD_R10_SUBFRAMECONFIG6_R10 2
#define MEASSUBFRMPATTERN_R10_SUBFRAMEPATTERNFDD_R10 0
#define MEASSUBFRMPATTERN_R10_SUBFRAMEPATTERNTDD_R10 1

#define CSI_SUBFRMPATTERNCONFIG_R10_RELEASE 0
#define CSI_SUBFRMPATTERNCONFIG_R10_SETUP 1

#define CSI_RS_R10_RELEASE 0
#define CSI_RS_R10_SETUP 1
#define ZEROTXPOWERCSI_RS_R10_RELEASE 0
#define ZEROTXPOWERCSI_RS_R10_SETUP 1

#define TWOANTENNAPORTACTIVATEDPUCCH_FORMAT3_R10_RELEASE 0
#define TWOANTENNAPORTACTIVATEDPUCCH_FORMAT3_R10_SETUP 1
#define N1PUCCH_AN_CS_R10_RELEASE 0
#define N1PUCCH_AN_CS_R10_SETUP 1
#define PUCCH_FORMAT_R10_FORMAT3_R10 0
#define PUCCH_FORMAT_R10_CHANNELSELECTION_R10 1

#define SRS_ACTIVATEAP_R10_RELEASE 0
#define SRS_ACTIVATEAP_R10_SETUP 1
#define SOUNDINGRS_UL_CONFIGDEDICATEDAPERIODIC_R10_RELEASE 0
#define SOUNDINGRS_UL_CONFIGDEDICATEDAPERIODIC_R10_SETUP 1

#define ANTENNAINFO_EXPLICITVALUE 0
#define ANTENNAINFO_DEFAULTVALUE 1
#define ANTENNAINFO_R10_EXPLICITVALUE_R10 0
#define ANTENNAINFO_R10_DEFAULTVALUE 1
#define ADDITIONALSPECTRUMEMISSIONCA_R10_RELEASE 0
#define ADDITIONALSPECTRUMEMISSIONCA_R10_SETUP 1

#define RLF_TMRSANDCONSTS_R9_RELEASE 0
#define RLF_TMRSANDCONSTS_R9_SETUP 1

#define MEASSUBFRMPATTERNPCELL_R10_RELEASE 0
#define MEASSUBFRMPATTERNPCELL_R10_SETUP 1

#define MAC_MAINCONFIG_EXPLICITVALUE 0
#define MAC_MAINCONFIG_DEFAULTVALUE 1

#define C13_RRCCONREESTB_R8 0
#define C13_SPARE7 1
#define C13_SPARE6 2
#define C13_SPARE5 3
#define C13_SPARE4 4
#define C13_SPARE3 5
#define C13_SPARE2 6
#define C13_SPARE1 7
#define CRITICALEXTNS_C13 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define CRITICALEXTNS_RRCCONREESTBREJ_R8 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C14_RRCCONREJ_R8 0
#define C14_SPARE3 1
#define C14_SPARE2 2
#define C14_SPARE1 3
#define CRITICALEXTNS_C14 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C16_RRCCONSETUP_R8 0
#define C16_SPARE7 1
#define C16_SPARE6 2
#define C16_SPARE5 3
#define C16_SPARE4 4
#define C16_SPARE3 5
#define C16_SPARE2 6
#define C16_SPARE1 7
#define CRITICALEXTNS_C16 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C3_RRCCONREESTB 0
#define C3_RRCCONREESTBREJ 1
#define C3_RRCCONREJ 2
#define C3_RRCCONSETUP 3
#define DL_CCCH_MSGTYP_C3 0
#define DL_CCCH_MSGTYP_MESSAGECLASSEXTN 1

#define CRITICALEXTNS_CSFBPARAMSRSPCDMA2000_R8 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define DEDICATEDINFOTYP_DEDICATEDINFONAS 0
#define DEDICATEDINFOTYP_DEDICATEDINFOCDMA2000_1XRTT 1
#define DEDICATEDINFOTYP_DEDICATEDINFOCDMA2000_HRPD 2

#define C8_DLINFOTFR_R8 0
#define C8_SPARE3 1
#define C8_SPARE2 2
#define C8_SPARE1 3
#define CRITICALEXTNS_C8 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C9_HANDOVERFROMEUTRAPREPRQST_R8 0
#define C9_SPARE3 1
#define C9_SPARE2 2
#define C9_SPARE1 3
#define CRITICALEXTNS_C9 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define SI_ORPSI_GERAN_SI 0
#define SI_ORPSI_GERAN_PSI 1

#define TARGETRAT_TYP_GERAN 0

#define PURPOSE_HANDOVER 0
#define PURPOSE_CELLCHANGEORDER 1

#define PURPOSE_HANDOVER 0
#define PURPOSE_CELLCHANGEORDER 1
#define PURPOSE_E_CSFB_R9 2

#define C11_MOBILITYFROMEUTRACMD_R8 0
#define C11_MOBILITYFROMEUTRACMD_R9 1
#define C11_SPARE2 2
#define C11_SPARE1 3
#define CRITICALEXTNS_C11 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define MEASSUBFRMPATTERNCONFIGNEIGH_R10_RELEASE 0
#define MEASSUBFRMPATTERNCONFIGNEIGH_R10_SETUP 1

#define CELLSTOADDMODLST_CELLSTOADDMODLSTUTRA_FDD 0
#define CELLSTOADDMODLST_CELLSTOADDMODLSTUTRA_TDD 1
#define CELLFORWHICHTOREPORTCGI_UTRA_FDD 0
#define CELLFORWHICHTOREPORTCGI_UTRA_TDD 1

#define MEASOBJECT_MEASOBJECTEUTRA 0
#define MEASOBJECT_MEASOBJECTUTRA 1
#define MEASOBJECT_MEASOBJECTGERAN 2
#define MEASOBJECT_MEASOBJECTCDMA2000 3

#define THRESHOLDEUTRA_THRESHOLD_RSRP 0
#define THRESHOLDEUTRA_THRESHOLD_RSRQ 1

#define EVENTID_EVENTA1 0
#define EVENTID_EVENTA2 1
#define EVENTID_EVENTA3 2
#define EVENTID_EVENTA4 3
#define EVENTID_EVENTA5 4
#define EVENTID_EVENTA6_R10 5
#define TRIGGERTYP_EVENT 0
#define TRIGGERTYP_PERIODICAL 1

#define THRESHOLDUTRA_UTRA_RSCP 0
#define THRESHOLDUTRA_UTRA_ECN0 1

#define B1_THRESHOLD_B1_THRESHOLDUTRA 0
#define B1_THRESHOLD_B1_THRESHOLDGERAN 1
#define B1_THRESHOLD_B1_THRESHOLDCDMA2000 2
#define B2_THRESHOLD2_B2_THRESHOLD2UTRA 0
#define B2_THRESHOLD2_B2_THRESHOLD2GERAN 1
#define B2_THRESHOLD2_B2_THRESHOLD2CDMA2000 2
#define EVENTID_EVENTB1 0
#define EVENTID_EVENTB2 1
#define TRIGGERTYP_EVENT 0
#define TRIGGERTYP_PERIODICAL 1

#define REPORTCONFIG_REPORTCONFIGEUTRA 0
#define REPORTCONFIG_REPORTCONFIGINTERRAT 1

#define GAPOFFSET_GP0 0
#define GAPOFFSET_GP1 1
#define MEASGAPCONFIG_RELEASE 0
#define MEASGAPCONFIG_SETUP 1

#define SPEEDSTATEPARS_RELEASE 0
#define SPEEDSTATEPARS_SETUP 1

#define HANDOVERTYP_INTRALTE 0
#define HANDOVERTYP_INTERRAT 1

#define SCHEDULINGCELLINFO_R10_OWN_R10 0
#define SCHEDULINGCELLINFO_R10_OTHER_R10 1

#define C12_RRCCONRECFGN_R8 0
#define C12_SPARE7 1
#define C12_SPARE6 2
#define C12_SPARE5 3
#define C12_SPARE4 4
#define C12_SPARE3 5
#define C12_SPARE2 6
#define C12_SPARE1 7
#define CRITICALEXTNS_C12 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define REDIRECTEDCARRIERINFO_EUTRA 0
#define REDIRECTEDCARRIERINFO_GERAN 1
#define REDIRECTEDCARRIERINFO_UTRA_FDD 2
#define REDIRECTEDCARRIERINFO_UTRA_TDD 3
#define REDIRECTEDCARRIERINFO_CDMA2000_HRPD 4
#define REDIRECTEDCARRIERINFO_CDMA2000_1XRTT 5
#define REDIRECTEDCARRIERINFO_UTRA_TDD_R10 6

#define CELLINFOLST_R9_GERAN_R9 0
#define CELLINFOLST_R9_UTRA_FDD_R9 1
#define CELLINFOLST_R9_UTRA_TDD_R9 2
#define CELLINFOLST_R9_UTRA_TDD_R10 3

#define C15_RRCCONRLS_R8 0
#define C15_SPARE3 1
#define C15_SPARE2 2
#define C15_SPARE1 3
#define CRITICALEXTNS_C15 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C18_SECURITYMODECMD_R8 0
#define C18_SPARE3 1
#define C18_SPARE2 2
#define C18_SPARE1 3
#define CRITICALEXTNS_C18 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C19_UECAPENQUIRY_R8 0
#define C19_SPARE3 1
#define C19_SPARE2 2
#define C19_SPARE1 3
#define CRITICALEXTNS_C19 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C7_COUNTERCHECK_R8 0
#define C7_SPARE3 1
#define C7_SPARE2 2
#define C7_SPARE1 3
#define CRITICALEXTNS_C7 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C28_UEINFORQST_R9 0
#define C28_SPARE3 1
#define C28_SPARE2 2
#define C28_SPARE1 3
#define CRITICALEXTNS_C28 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define AREACFG_R10_CELLGLOBALIDLST_R10 0
#define AREACFG_R10_TRACKINGAREACODELST_R10 1

#define C31_LOGGEDMEASUREMENTCFG_R10 0
#define C31_SPARE3 1
#define C31_SPARE2 2
#define C31_SPARE1 3
#define CRITICALEXTNS_C31 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define SUBFRAMECONFIGPATTERN_R10_SUBFRAMECONFIGPATTERNFDD_R10 0
#define SUBFRAMECONFIGPATTERN_R10_SUBFRAMECONFIGPATTERNTDD_R10 1
#define TYPE01_R10_NRB6_R10 0
#define TYPE01_R10_NRB15_R10 1
#define TYPE01_R10_NRB25_R10 2
#define TYPE01_R10_NRB50_R10 3
#define TYPE01_R10_NRB75_R10 4
#define TYPE01_R10_NRB100_R10 5
#define TYPE2_R10_NRB6_R10 0
#define TYPE2_R10_NRB15_R10 1
#define TYPE2_R10_NRB25_R10 2
#define TYPE2_R10_NRB50_R10 3
#define TYPE2_R10_NRB75_R10 4
#define TYPE2_R10_NRB100_R10 5
#define RESOURCEBLOCKASSIGNMENT_R10_TYPE01_R10 0
#define RESOURCEBLOCKASSIGNMENT_R10_TYPE2_R10 1
#define DEMODULATIONRS_R10_INTERLEAVING_R10 0
#define DEMODULATIONRS_R10_NOINTERLEAVING_R10 1
#define TDD_CHANNELSELECTIONMULTIPLEXINGBUNDLING 0
#define TDD_FALLBACKFORFORMAT3 1
#define PUCCH_CONFIG_R10_TDD 0
#define PUCCH_CONFIG_R10_FDD 1

#define C33_RNRECFGN_R10 0
#define C33_SPARE3 1
#define C33_SPARE2 2
#define C33_SPARE1 3
#define CRITICALEXTNS_C33 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C4_CSFBPARAMSRSPCDMA2000 0
#define C4_DLINFOTFR 1
#define C4_HANDOVERFROMEUTRAPREPRQST 2
#define C4_MOBILITYFROMEUTRACMD 3
#define C4_RRCCONRECFGN 4
#define C4_RRCCONRLS 5
#define C4_SECURITYMODECMD 6
#define C4_UECAPENQUIRY 7
#define C4_COUNTERCHECK 8
#define C4_UEINFORQST_R9 9
#define C4_LOGGEDMEASUREMENTCFG_R10 10
#define C4_RNRECFGN_R10 11
#define C4_SPARE4 12
#define C4_SPARE3 13
#define C4_SPARE2 14
#define C4_SPARE1 15
#define DL_DCCH_MSGTYP_C4 0
#define DL_DCCH_MSGTYP_MESSAGECLASSEXTN 1

#define CRITICALEXTNS_RRCCONREESTBRQST_R8 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define INITUE_IDENTITY_S_TMSI 0
#define INITUE_IDENTITY_RANDOMVALUE 1

#define CRITICALEXTNS_RRCCONRQST_R8 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C5_RRCCONREESTBRQST 0
#define C5_RRCCONRQST 1
#define UL_CCCH_MSGTYP_C5 0
#define UL_CCCH_MSGTYP_MESSAGECLASSEXTN 1

#define CRITICALEXTNS_CSFBPARAMSRQSTCDMA2000_R8 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define PHYSCELLID_FDD 0
#define PHYSCELLID_TDD 1

#define CELLGLOBALIDCDMA2000_CELLGLOBALID1XRTT 0
#define CELLGLOBALIDCDMA2000_CELLGLOBALIDHRPD 1

#define LOCATIONCOORDINATES_R10_ELLIPSOID_POINT_R10 0
#define LOCATIONCOORDINATES_R10_ELLIPSOIDPOINTWITHALTITUDE_R10 1

#define MEASRESULTNEIGHCELLS_MEASRESULTLSTEUTRA 0
#define MEASRESULTNEIGHCELLS_MEASRESULTLSTUTRA 1
#define MEASRESULTNEIGHCELLS_MEASRESULTLSTGERAN 2
#define MEASRESULTNEIGHCELLS_MEASRESULTSCDMA2000 3

#define C10_MEASUREMENTREPORT_R8 0
#define C10_SPARE7 1
#define C10_SPARE6 2
#define C10_SPARE5 3
#define C10_SPARE4 4
#define C10_SPARE3 5
#define C10_SPARE2 6
#define C10_SPARE1 7
#define CRITICALEXTNS_C10 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define CRITICALEXTNS_RRCCONRECFGNCOMPL_R8 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define CRITICALEXTNS_RRCCONREESTBCOMPL_R8 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C17_RRCCONSETUPCOMPL_R8 0
#define C17_SPARE3 1
#define C17_SPARE2 2
#define C17_SPARE1 3
#define CRITICALEXTNS_C17 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define CRITICALEXTNS_SECURITYMODECOMPL_R8 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define CRITICALEXTNS_SECURITYMODEFAIL_R8 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C20_UECAPINFO_R8 0
#define C20_SPARE7 1
#define C20_SPARE6 2
#define C20_SPARE5 3
#define C20_SPARE4 4
#define C20_SPARE3 5
#define C20_SPARE2 6
#define C20_SPARE1 7
#define CRITICALEXTNS_C20 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C21_ULHOVRPREPTFR_R8 0
#define C21_SPARE3 1
#define C21_SPARE2 2
#define C21_SPARE1 3
#define CRITICALEXTNS_C21 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define DEDICATEDINFOTYP_DEDICATEDINFONAS 0
#define DEDICATEDINFOTYP_DEDICATEDINFOCDMA2000_1XRTT 1
#define DEDICATEDINFOTYP_DEDICATEDINFOCDMA2000_HRPD 2

#define C25_ULINFOTFR_R8 0
#define C25_SPARE3 1
#define C25_SPARE2 2
#define C25_SPARE1 3
#define CRITICALEXTNS_C25 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define CRITICALEXTNS_COUNTERCHECKRSP_R8 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define FAILEDPCELLID_R10_CELLGLOBALID_R10 0
#define FAILEDPCELLID_R10_PCI_ARFCN_R10 1

#define C29_UEINFORSP_R9 0
#define C29_SPARE3 1
#define C29_SPARE2 2
#define C29_SPARE1 3
#define CRITICALEXTNS_C29 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define CARRIERFREQ_R9_EUTRA_R9 0
#define CARRIERFREQ_R9_UTRA_R9 1

#define C27_PROXIMITYIND_R9 0
#define C27_SPARE3 1
#define C27_SPARE2 2
#define C27_SPARE1 3
#define CRITICALEXTNS_C27 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C34_RNRECFGNCOMPL_R10 0
#define C34_SPARE3 1
#define C34_SPARE2 2
#define C34_SPARE1 3
#define CRITICALEXTNS_C34 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C32_COUNTINGRSP_R10 0
#define C32_SPARE3 1
#define C32_SPARE2 2
#define C32_SPARE1 3
#define CRITICALEXTNS_C32 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define RSTD_INTERFREQIND_R10_START 0
#define RSTD_INTERFREQIND_R10_STOP 1

#define C30_INTERFREQRSTDMEASUREMENTIND_R10 0
#define C30_SPARE3 1
#define C30_SPARE2 2
#define C30_SPARE1 3
#define CRITICALEXTNS_C30 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C6_CSFBPARAMSRQSTCDMA2000 0
#define C6_MEASUREMENTREPORT 1
#define C6_RRCCONRECFGNCOMPL 2
#define C6_RRCCONREESTBCOMPL 3
#define C6_RRCCONSETUPCOMPL 4
#define C6_SECURITYMODECOMPL 5
#define C6_SECURITYMODEFAIL 6
#define C6_UECAPINFO 7
#define C6_ULHOVRPREPTFR 8
#define C6_ULINFOTFR 9
#define C6_COUNTERCHECKRSP 10
#define C6_UEINFORSP_R9 11
#define C6_PROXIMITYIND_R9 12
#define C6_RNRECFGNCOMPL_R10 13
#define C6_MBMSCOUNTINGRSP_R10 14
#define C6_INTERFREQRSTDMEASUREMENTIND_R10 15
#define UL_DCCH_MSGTYP_C6 0
#define UL_DCCH_MSGTYP_MESSAGECLASSEXTN 1
#define NhumaxBandComb_r10 128
#define NhumaxBands 64
#define NhumaxBandwidthClass_r10 16
#define NhumaxBandwidthCombSet_r10 32
#define NhumaxCDMA_BandClass 32
#define NhumaxCellBlack 16
#define NhumaxCellInfoGERAN_r9 32
#define NhumaxCellInfoUTRA_r9 16
#define NhumaxFreqUTRA_TDD_r10 6
#define NhumaxCellInter 16
#define NhumaxCellIntra 16
#define NhumaxCellLstGERAN 3
#define NhumaxCellMeas 32
#define NhumaxCellReport 8
#define NhumaxDRB 11
#define NhumaxEARFCN 65535
#define NhumaxFreq 8
#define NhumaxGERAN_SI 10
#define NhumaxGNFG 16
#define NhumaxLogMeasReport_r10 520
#define NhumaxMBSFN_Allocns 8
#define NhumaxMBSFN_Area 8
#define NhumaxMBSFN_Area_1 7
#define NhumaxMeasId 32
#define NhumaxMultiBands 8
#define NhumaxObjectId 32
#define NhumaxPageRec 16
#define NhumaxPhysCellIdRange_r9 4
#define NhumaxPNOffset 511
#define NhumaxPMCH_PerMBSFN 15
#define NhumaxRAT_Capabilities 8
#define NhumaxReportConfigId 32
#define NhumaxRSTD_Freq_r10 3
#define NhumaxSCell_r10 4
#define NhumaxServCell_r10 5
#define NhumaxServiceCount 16
#define NhumaxServiceCount_1 15
#define NhumaxSessionPerPMCH 29
#define NhumaxSessionPerPMCH_1 28
#define NhumaxSIB 32
#define NhumaxSIB_1 31
#define NhumaxSI_Msg 32
#define NhumaxSimultaneousBands_r10 64
#define NhumaxUTRA_FDD_Carrier 16
#define NhumaxUTRA_TDD_Carrier 16

#define SPEEDSTATEPARS_RELEASE 0
#define SPEEDSTATEPARS_SETUP 1

#define PHYSCELLIDUTRA_FDD 0
#define PHYSCELLIDUTRA_TDD 1
#define MEMBER_PHYSCELLIDEUTRA 0
#define MEMBER_PHYSCELLIDUTRA 1
#define MEMBER_PHYSCELLIDGERAN 2
#define MEMBER_PHYSCELLIDCDMA2000 3
#define NhumaxLogMeas_r10 4060

#define C22_HANDOVERCMD_R8 0
#define C22_SPARE7 1
#define C22_SPARE6 2
#define C22_SPARE5 3
#define C22_SPARE4 4
#define C22_SPARE3 5
#define C22_SPARE2 6
#define C22_SPARE1 7
#define CRITICALEXTNS_C22 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C23_HANDOVERPREPINFO_R8 0
#define C23_SPARE7 1
#define C23_SPARE6 2
#define C23_SPARE5 3
#define C23_SPARE4 4
#define C23_SPARE3 5
#define C23_SPARE2 6
#define C23_SPARE1 7
#define CRITICALEXTNS_C23 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1

#define C24_UERADIOACCESSCAPINFO_R8 0
#define C24_SPARE7 1
#define C24_SPARE6 2
#define C24_SPARE5 3
#define C24_SPARE4 4
#define C24_SPARE3 5
#define C24_SPARE2 6
#define C24_SPARE1 7
#define CRITICALEXTNS_C24 0
#define CRITICALEXTNS_CRITICALEXTNSFUTURE 1
#define NhumaxReestabInfo 32

}
#endif
/**********************************************************************
         End of file:     nhac_asn.h@@/main/TeNB_Main_BR/tenb_main_ccb/1 - Wed Jul 22 20:18:11 2015
**********************************************************************/
/**********************************************************************

        Revision history:

**********************************************************************/
/********************************************************************90**

     ver       pat    init                  description
------------ -------- ---- ----------------------------------------------
/main/1      ---                 chebli        1. RRC LTE Initial Release.
/main/3      ---      nhu_asn_h_001.main_2 sbalakrishna  1. Updated for Release of 3.1.
*********************************************************************91*/
