/*
 * AUTOMATICALLY GENERATED CODE:
 * DO NOT EDIT !
 */

{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.LTECell.{16}.X_TIP_COM_TAC",
	READ_WRITE, U_INT, "0", "65535", false, NO_NOTIFICATION, false, Immediate,	"1",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_RAN_NEIGH_LIST_LTE_CELL.{15}",	PARAM_ID_LTE_X_RADISYS_NEIGH_LIST_LTE_CELL_TAC },
{"Device.Services.FAPService.{2}.X_TIP.COM.CellConfig.LTE.RAN.MAC.DRX.LongDRXCycleGBR",
	READ_WRITE, U_INT, "2560", "2560", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_LONG_DRX_CYCLE_GBR },
{"Device.Services.FAPService.{2}.X_TIP.COM.CellConfig.LTE.RAN.MAC.DRX.LongDRXCycleNonGBR",
	READ_WRITE, U_INT, "2560", "2560", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_LONG_DRX_CYCLE_NON_GBR },
