/*
 * AUTOMATICALLY GENERATED CODE:
 * DO NOT EDIT !
 */

{"Device.FaultMgmt.SupportedAlarmNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"146",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0",	PARAM_ID_ALARM_SUPPORTED_ENTRIES },
{"Device.FaultMgmt.MaxCurrentAlarmEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0",	PARAM_ID_ALARM_MAX_CURRENT_ENTRIES },
{"Device.FaultMgmt.CurrentAlarmNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"0",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0",	PARAM_ID_ALARM_CURRENT_ENTRIES },
{"Device.FaultMgmt.HistoryEventNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"0",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0",	PARAM_ID_ALARM_HISTORY_ENTRIES },
{"Device.FaultMgmt.ExpeditedEventNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"0",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0",	PARAM_ID_ALARM_EXPEDITED_ENTRIES },
{"Device.FaultMgmt.QueuedEventNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"0",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0",	PARAM_ID_ALARM_QUEUED_ENTRIES },
{"Device.FaultMgmt.SupportedAlarm.{146}.EventType",
	READ_ONLY, STRING, "0", "64", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_SUPPORTED_ALARM.{145}",	PARAM_ID_ALARM_EVENT_TYPE },
{"Device.FaultMgmt.SupportedAlarm.{146}.ProbableCause",
	READ_ONLY, STRING, "0", "64", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_SUPPORTED_ALARM.{145}",	PARAM_ID_ALARM_PROBABLE_CAUSE },
{"Device.FaultMgmt.SupportedAlarm.{146}.SpecificProblem",
	READ_ONLY, STRING, "0", "128", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_SUPPORTED_ALARM.{145}",	PARAM_ID_ALARM_SPECIFIC_PROBLEM },
{"Device.FaultMgmt.SupportedAlarm.{146}.PerceivedSeverity",
	READ_ONLY, STRING, "0", "13", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_SUPPORTED_ALARM.{145}",	PARAM_ID_ALARM_PERCEIVED_SEVERITY },
{"Device.FaultMgmt.SupportedAlarm.{146}.ReportingMechanism",
	READ_WRITE, STRING, "8", "11", false, NO_NOTIFICATION, false, Immediate,	"0 Expedited",	GROUP_ID_INVALID,	"FAP.0.TR196_SUPPORTED_ALARM.{145}",	PARAM_ID_ALARM_REPORTING_MECHANISM },
{"Device.FaultMgmt.CurrentAlarm.{50}.AlarmIdentifier",
	READ_ONLY, STRING, "0", "64", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_CURRENT_ALARM.{49}",	PARAM_ID_ALARM_IDENTIFIER },
{"Device.FaultMgmt.CurrentAlarm.{50}.AlarmRaisedTime",
	READ_ONLY, DATE_TIME, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_CURRENT_ALARM.{49}",	PARAM_ID_ALARM_RAISED_TIME },
{"Device.FaultMgmt.CurrentAlarm.{50}.ManagedObjectInstance",
	READ_ONLY, STRING, "0", "512", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_CURRENT_ALARM.{49}",	PARAM_ID_MANAGED_OBJECT_INSTANCE },
{"Device.FaultMgmt.CurrentAlarm.{50}.EventType",
	READ_ONLY, STRING, "0", "64", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_CURRENT_ALARM.{49}",	PARAM_ID_ALARM_EVENT_TYPE },
{"Device.FaultMgmt.CurrentAlarm.{50}.ProbableCause",
	READ_ONLY, STRING, "0", "64", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_CURRENT_ALARM.{49}",	PARAM_ID_ALARM_PROBABLE_CAUSE },
{"Device.FaultMgmt.CurrentAlarm.{50}.SpecificProblem",
	READ_ONLY, STRING, "0", "128", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_CURRENT_ALARM.{49}",	PARAM_ID_ALARM_SPECIFIC_PROBLEM },
{"Device.FaultMgmt.CurrentAlarm.{50}.PerceivedSeverity",
	READ_ONLY, STRING, "5", "13", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_CURRENT_ALARM.{49}",	PARAM_ID_ALARM_PERCEIVED_SEVERITY },
{"Device.FaultMgmt.CurrentAlarm.{50}.AdditionalText",
	READ_ONLY, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_CURRENT_ALARM.{49}",	PARAM_ID_ALARM_ADDITIONAL_TEXT },
{"Device.FaultMgmt.CurrentAlarm.{50}.AdditionalInformation",
	READ_ONLY, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_CURRENT_ALARM.{49}",	PARAM_ID_ALARM_ADDITIONAL_INFORMATION },
{"Device.FaultMgmt.HistoryEvent.{150}.EventTime",
	READ_ONLY, DATE_TIME, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_HISTORY_EVENT.{149}",	PARAM_ID_ALARM_EVENT_TIME },
{"Device.FaultMgmt.HistoryEvent.{150}.AlarmIdentifier",
	READ_ONLY, STRING, "0", "64", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_HISTORY_EVENT.{149}",	PARAM_ID_ALARM_IDENTIFIER },
{"Device.FaultMgmt.HistoryEvent.{150}.NotificationType",
	READ_ONLY, STRING, "8", "12", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_HISTORY_EVENT.{149}",	PARAM_ID_ALARM_NOTIFICATION_TYPE },
{"Device.FaultMgmt.HistoryEvent.{150}.ManagedObjectInstance",
	READ_ONLY, STRING, "0", "512", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_HISTORY_EVENT.{149}",	PARAM_ID_MANAGED_OBJECT_INSTANCE },
{"Device.FaultMgmt.HistoryEvent.{150}.EventType",
	READ_ONLY, STRING, "0", "64", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_HISTORY_EVENT.{149}",	PARAM_ID_ALARM_EVENT_TYPE },
{"Device.FaultMgmt.HistoryEvent.{150}.ProbableCause",
	READ_ONLY, STRING, "0", "64", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_HISTORY_EVENT.{149}",	PARAM_ID_ALARM_PROBABLE_CAUSE },
{"Device.FaultMgmt.HistoryEvent.{150}.SpecificProblem",
	READ_ONLY, STRING, "0", "128", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_HISTORY_EVENT.{149}",	PARAM_ID_ALARM_SPECIFIC_PROBLEM },
{"Device.FaultMgmt.HistoryEvent.{150}.PerceivedSeverity",
	READ_ONLY, STRING, "5", "13", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_HISTORY_EVENT.{149}",	PARAM_ID_ALARM_PERCEIVED_SEVERITY },
{"Device.FaultMgmt.HistoryEvent.{150}.AdditionalText",
	READ_ONLY, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_HISTORY_EVENT.{149}",	PARAM_ID_ALARM_ADDITIONAL_TEXT },
{"Device.FaultMgmt.HistoryEvent.{150}.AdditionalInformation",
	READ_ONLY, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_HISTORY_EVENT.{149}",	PARAM_ID_ALARM_ADDITIONAL_INFORMATION },
{"Device.FaultMgmt.ExpeditedEvent.{50}.EventTime",
	READ_ONLY, DATE_TIME, "", "", false, ACTIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_EXPEDITED_EVENT.{49}",	PARAM_ID_ALARM_EVENT_TIME },
{"Device.FaultMgmt.ExpeditedEvent.{50}.AlarmIdentifier",
	READ_ONLY, STRING, "0", "64", false, PASSIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.TR196_EXPEDITED_EVENT.{49}",	PARAM_ID_ALARM_IDENTIFIER },
{"Device.FaultMgmt.ExpeditedEvent.{50}.NotificationType",
	READ_ONLY, STRING, "8", "12", false, PASSIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_EXPEDITED_EVENT.{49}",	PARAM_ID_ALARM_NOTIFICATION_TYPE },
{"Device.FaultMgmt.ExpeditedEvent.{50}.ManagedObjectInstance",
	READ_ONLY, STRING, "0", "512", false, PASSIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_EXPEDITED_EVENT.{49}",	PARAM_ID_MANAGED_OBJECT_INSTANCE },
{"Device.FaultMgmt.ExpeditedEvent.{50}.EventType",
	READ_ONLY, STRING, "0", "64", false, PASSIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_EXPEDITED_EVENT.{49}",	PARAM_ID_ALARM_EVENT_TYPE },
{"Device.FaultMgmt.ExpeditedEvent.{50}.ProbableCause",
	READ_ONLY, STRING, "0", "64", false, PASSIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_EXPEDITED_EVENT.{49}",	PARAM_ID_ALARM_PROBABLE_CAUSE },
{"Device.FaultMgmt.ExpeditedEvent.{50}.SpecificProblem",
	READ_ONLY, STRING, "0", "128", false, PASSIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_EXPEDITED_EVENT.{49}",	PARAM_ID_ALARM_SPECIFIC_PROBLEM },
{"Device.FaultMgmt.ExpeditedEvent.{50}.PerceivedSeverity",
	READ_ONLY, STRING, "5", "13", false, PASSIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_EXPEDITED_EVENT.{49}",	PARAM_ID_ALARM_PERCEIVED_SEVERITY },
{"Device.FaultMgmt.ExpeditedEvent.{50}.AdditionalText",
	READ_ONLY, STRING, "0", "256", false, PASSIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_EXPEDITED_EVENT.{49}",	PARAM_ID_ALARM_ADDITIONAL_TEXT },
{"Device.FaultMgmt.ExpeditedEvent.{50}.AdditionalInformation",
	READ_ONLY, STRING, "0", "256", false, PASSIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.TR196_EXPEDITED_EVENT.{49}",	PARAM_ID_ALARM_ADDITIONAL_INFORMATION },
{"Device.FaultMgmt.QueuedEvent.{50}.AlarmIdentifier",
	READ_ONLY, STRING, "0", "64", false, PASSIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.QUEUED_EVENT.{49}",	PARAM_ID_ALARM_IDENTIFIER },
{"Device.FaultMgmt.QueuedEvent.{50}.NotificationType",
	READ_ONLY, STRING, "8", "12", false, PASSIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.QUEUED_EVENT.{49}",	PARAM_ID_ALARM_NOTIFICATION_TYPE },
{"Device.FaultMgmt.QueuedEvent.{50}.ManagedObjectInstance",
	READ_ONLY, STRING, "0", "512", false, PASSIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.QUEUED_EVENT.{49}",	PARAM_ID_MANAGED_OBJECT_INSTANCE },
{"Device.FaultMgmt.QueuedEvent.{50}.EventType",
	READ_ONLY, STRING, "0", "64", false, PASSIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.QUEUED_EVENT.{49}",	PARAM_ID_ALARM_EVENT_TYPE },
{"Device.FaultMgmt.QueuedEvent.{50}.ProbableCause",
	READ_ONLY, STRING, "0", "64", false, PASSIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.QUEUED_EVENT.{49}",	PARAM_ID_ALARM_PROBABLE_CAUSE },
{"Device.FaultMgmt.QueuedEvent.{50}.SpecificProblem",
	READ_ONLY, STRING, "0", "128", false, PASSIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.QUEUED_EVENT.{49}",	PARAM_ID_ALARM_SPECIFIC_PROBLEM },
{"Device.FaultMgmt.QueuedEvent.{50}.PerceivedSeverity",
	READ_ONLY, STRING, "5", "13", false, PASSIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.QUEUED_EVENT.{49}",	PARAM_ID_ALARM_PERCEIVED_SEVERITY },
{"Device.FaultMgmt.QueuedEvent.{50}.AdditionalText",
	READ_ONLY, STRING, "0", "256", false, PASSIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.QUEUED_EVENT.{49}",	PARAM_ID_ALARM_ADDITIONAL_TEXT },
{"Device.FaultMgmt.QueuedEvent.{50}.AdditionalInformation",
	READ_ONLY, STRING, "0", "256", false, PASSIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.QUEUED_EVENT.{49}",	PARAM_ID_ALARM_ADDITIONAL_INFORMATION },
