/*
 * AUTOMATICALLY GENERATED CODE:
 * DO NOT EDIT !
 */

{"Device.RootDataModelVersion",
	READ_ONLY, STRING, "0", "32", false, ACTIVE_NOTIFICATION, true, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_TR069_ROOT_DATA_MODEL },
{"Device.DeviceInfo.Manufacturer",
	READ_ONLY, STRING, "0", "64", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_MANUFACTURER },
{"Device.DeviceInfo.ManufacturerOUI",
	READ_ONLY, STRING, "0", "6", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_OUI_OF_MANUFACTURER },
{"Device.DeviceInfo.ModelName",
	READ_ONLY, STRING, "0", "64", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_MODEL_NAME },
{"Device.DeviceInfo.Description",
	READ_ONLY, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_DEVICE_DESCRIPTION },
{"Device.DeviceInfo.ProductClass",
	READ_ONLY, STRING, "0", "64", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_PRODUCT_CLASS },
{"Device.DeviceInfo.SerialNumber",
	READ_ONLY, STRING, "0", "64", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LONG_SERIAL_NUMBER },
{"Device.DeviceInfo.HardwareVersion",
	READ_ONLY, STRING, "0", "64", false, ACTIVE_NOTIFICATION, true, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_TR069_HW_VERSION_STRING },
{"Device.DeviceInfo.SoftwareVersion",
	READ_ONLY, STRING, "0", "64", false, ACTIVE_NOTIFICATION, true, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_TR069_SW_VERSION_STRING },
{"Device.DeviceInfo.ProvisioningCode",
	READ_WRITE, STRING, "0", "64", false, ACTIVE_NOTIFICATION, true, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_TR069_PROVISIONING_CODE },
{"Device.DeviceInfo.UpTime",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_UP_TIME },
{"Device.DeviceInfo.FirstUseDate",
	READ_ONLY, DATE_TIME, "", "", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_FIRST_USE_DATE },
{"Device.ManagementServer.URL",
	READ_WRITE, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_MANAGEMENT_SERVER },
{"Device.ManagementServer.Username",
	READ_WRITE, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_MANAGEMENT_USERNAME },
{"Device.ManagementServer.Password",
	READ_WRITE, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_MANAGEMENT_PASSWORD },
{"Device.ManagementServer.PeriodicInformEnable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_PERIODIC_INFORM_ENABLED },
{"Device.ManagementServer.PeriodicInformInterval",
	READ_WRITE, U_INT, "1", "", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_PERIODIC_INFORM_INTERVAL },
{"Device.ManagementServer.ParameterKey",
	READ_ONLY, STRING, "0", "32", false, ACTIVE_NOTIFICATION, true, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_TR069_HMS_PARAMETER_KEY },
{"Device.ManagementServer.ConnectionRequestURL",
	READ_ONLY, STRING, "0", "256", false, ACTIVE_NOTIFICATION, true, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_TR069_CONNECTION_REQUEST_URL },
{"Device.ManagementServer.ConnectionRequestUsername",
	READ_WRITE, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_TR069_CONNECTION_REQUEST_USERNAME },
{"Device.ManagementServer.ConnectionRequestPassword",
	READ_WRITE, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_TR069_CONNECTION_REQUEST_PASSWORD },
{"Device.ManagementServer.CWMPRetryMinimumWaitInterval",
	READ_WRITE, U_INT, "1", "65535", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_TR069_SESSION_RETRY_INTERVAL },
{"Device.ManagementServer.CWMPRetryIntervalMultiplier",
	READ_WRITE, U_INT, "1000", "65535", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_TR069_SESSION_RETRY_MULTIPLIER },
{"Device.ManagementServer.UDPConnectionRequestAddress",
	READ_ONLY, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_UDP_CONN_REQ_ADDR },
{"Device.ManagementServer.STUNEnable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_STUN_ENABLE },
{"Device.ManagementServer.STUNServerAddress",
	READ_WRITE, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_STUN_SERVER_ADDRESS },
{"Device.ManagementServer.STUNServerPort",
	READ_WRITE, U_INT, "0", "65535", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_STUN_SERVER_PORT },
{"Device.ManagementServer.STUNUsername",
	READ_WRITE, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_STUN_USERNAME },
{"Device.ManagementServer.STUNPassword",
	READ_WRITE, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_STUN_PASSWORD },
{"Device.ManagementServer.STUNMinimumKeepAlivePeriod",
	READ_WRITE, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_STUN_MIN_KEEPALIVE_PERIOD },
{"Device.ManagementServer.NATDetected",
	READ_ONLY, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"FAP",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_NAT_DETECTED },
{"Device.ManagementServer.AliasBasedAddressing",
	READ_ONLY, BOOLEAN, "", "", false, ACTIVE_NOTIFICATION, true, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_TR069_ALIAS_BASED_ADDRESSING },
{"Device.GatewayInfo.ManufacturerOUI",
	READ_ONLY, STRING, "0", "6", false, ACTIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_GATEWAYINFO_MANUFACTURER_OUI },
{"Device.GatewayInfo.ProductClass",
	READ_ONLY, STRING, "0", "64", false, ACTIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_GATEWAYINFO_PRODUCT_CLASS },
{"Device.GatewayInfo.SerialNumber",
	READ_ONLY, STRING, "0", "64", false, ACTIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_GATEWAYINFO_SERIAL_NUMBER },
{"Device.Time.Enable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"FALSE",	GROUP_ID_BOOLEAN,	"FAP.0",	PARAM_ID_NTP_ENABLE },
{"Device.Time.Status",
	READ_ONLY, STRING, "5", "25", false, NO_NOTIFICATION, false, Immediate,	"Disabled",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_NTP_STATUS },
{"Device.Time.NTPServer1",
	READ_WRITE, STRING, "0", "64", false, NO_NOTIFICATION, false, Immediate,	"0.0.0.0",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_NTP_SERVER_1 },
{"Device.Time.NTPServer2",
	READ_WRITE, STRING, "0", "64", false, NO_NOTIFICATION, false, Immediate,	"0.0.0.0",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_NTP_SERVER_2 },
{"Device.Time.NTPServer3",
	READ_WRITE, STRING, "0", "64", false, NO_NOTIFICATION, false, Immediate,	"0.0.0.0",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_NTP_SERVER_3 },
{"Device.Time.NTPServer4",
	READ_WRITE, STRING, "0", "64", false, NO_NOTIFICATION, false, Immediate,	"0.0.0.0",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_NTP_SERVER_4 },
{"Device.Time.NTPServer5",
	READ_WRITE, STRING, "0", "64", false, NO_NOTIFICATION, false, Immediate,	"0.0.0.0",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_NTP_SERVER_5 },
{"Device.Time.CurrentLocalTime",
	READ_ONLY, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_NTP_CURRENTLOCALTIME },
{"Device.Time.LocalTimeZone",
	READ_WRITE, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"EST+5",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_NTP_LOCAL_TIME_ZONE },
{"Device.IP.IPv4Capable",
	READ_ONLY, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"FALSE",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_IPV4_CAPABLE },
{"Device.IP.IPv4Enable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"FALSE",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_IPV4_ENABLED },
{"Device.IP.IPv4Status",
	READ_ONLY, STRING, "5", "8", false, NO_NOTIFICATION, false, Immediate,	"FALSE",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_IPV4_STATUS },
{"Device.IP.IPv6Capable",
	READ_ONLY, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"FALSE",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_IPV6_CAPABLE },
{"Device.IP.IPv6Enable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"FALSE",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_IPV6_ENABLED },
{"Device.IP.IPv6Status",
	READ_ONLY, STRING, "5", "8", false, NO_NOTIFICATION, false, Immediate,	"FALSE",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_IPV6_STATUS },
{"Device.IP.InterfaceNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_IP_NUM_INTERFACES },
{"Device.IP.ActivePortNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_IP_NUM_ACTIVE_PORTS },
{"Device.IP.Interface.{1}.Enable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_ENABLED },
{"Device.IP.Interface.{1}.IPv4Enable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_IPV4_ENABLED },
{"Device.IP.Interface.{1}.IPv6Enable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_IPV6_ENABLED },
{"Device.IP.Interface.{1}.ULAEnable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_ULA_ENABLED },
{"Device.IP.Interface.{1}.Status",
	READ_ONLY, STRING, "2", "14", false, NO_NOTIFICATION, false, Immediate,	"Down",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_STATUS },
{"Device.IP.Interface.{1}.Name",
	READ_ONLY, STRING, "0", "64", false, NO_NOTIFICATION, false, Immediate,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_NAME },
{"Device.IP.Interface.{1}.Reset",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_RESET },
{"Device.IP.Interface.{1}.Type",
	READ_ONLY, STRING, "6", "8", false, NO_NOTIFICATION, false, Immediate,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_TYPE },
{"Device.IP.Interface.{1}.Loopback",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"1",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_LOOPBACK },
{"Device.IP.Interface.{1}.IPv4AddressNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"1",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_NUM_IPV4_ADDRESSES },
{"Device.IP.Interface.{1}.IPv6AddressNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"2",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_NUM_IPV6_ADDRESSES },
{"Device.IP.Interface.{1}.IPv6PrefixNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"1",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_NUM_IPV6_PREFIXES },
{"Device.IP.Interface.{1}.IPv4Address.{1}.Enable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0.IP_INTERFACE_IPV4_ADDRESS.0",	PARAM_ID_IP_INTERFACE_IPV4_ADDRESS_ENABLED },
{"Device.IP.Interface.{1}.IPv4Address.{1}.Status",
	READ_ONLY, STRING, "5", "19", false, NO_NOTIFICATION, false, Immediate,	"Disabled",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0.IP_INTERFACE_IPV4_ADDRESS.0",	PARAM_ID_IP_INTERFACE_IPV4_ADDRESS_STATUS },
{"Device.IP.Interface.{1}.IPv4Address.{1}.IPAddress",
	READ_WRITE, STRING, "0", "15", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0.IP_INTERFACE_IPV4_ADDRESS.0",	PARAM_ID_IP_INTERFACE_IPV4_ADDRESS },
{"Device.IP.Interface.{1}.IPv4Address.{1}.SubnetMask",
	READ_WRITE, STRING, "0", "15", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0.IP_INTERFACE_IPV4_ADDRESS.0",	PARAM_ID_IP_INTERFACE_IPV4_SUBNET_MASK },
{"Device.IP.Interface.{1}.IPv4Address.{1}.AddressingType",
	READ_ONLY, STRING, "4", "6", false, NO_NOTIFICATION, false, Immediate,	"Static",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0.IP_INTERFACE_IPV4_ADDRESS.0",	PARAM_ID_IP_INTERFACE_IPV4_ADDRESSING_TYPE },
{"Device.IP.Interface.{2}.IPv6Address.{2}.Enable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"false",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0.IP_INTERFACE_IPV6_ADDRESS.{1}",	PARAM_ID_IP_INTERFACE_IPV6_ENABLE },
{"Device.IP.Interface.{2}.IPv6Address.{2}.Status",
	READ_ONLY, STRING, "5", "19", false, NO_NOTIFICATION, false, Immediate,	"Disabled",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0.IP_INTERFACE_IPV6_ADDRESS.{1}",	PARAM_ID_IP_INTERFACE_IPV6_STATUS },
{"Device.IP.Interface.{2}.IPv6Address.{2}.IPAddressStatus",
	READ_ONLY, STRING, "7", "12", false, NO_NOTIFICATION, false, Immediate,	"Invalid",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0.IP_INTERFACE_IPV6_ADDRESS.{1}",	PARAM_ID_IP_INTERFACE_IPV6_ADDRESS_STATUS },
{"Device.IP.Interface.{2}.IPv6Address.{2}.Alias",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0.IP_INTERFACE_IPV6_ADDRESS.{1}",	PARAM_ID_IP_INTERFACE_IPV6_ALIAS },
{"Device.IP.Interface.{2}.IPv6Address.{2}.IPAddress",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0.IP_INTERFACE_IPV6_ADDRESS.{1}",	PARAM_ID_IP_INTERFACE_IPV6_ADDRESS },
{"Device.IP.Interface.{2}.IPv6Address.{2}.Origin",
	READ_ONLY, STRING, "3", "14", false, NO_NOTIFICATION, false, Immediate,	"Static",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0.IP_INTERFACE_IPV6_ADDRESS.{1}",	PARAM_ID_IP_INTERFACE_IPV6_ORIGIN },
{"Device.IP.Interface.{2}.IPv6Address.{2}.Prefix",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0.IP_INTERFACE_IPV6_ADDRESS.{1}",	PARAM_ID_IP_INTERFACE_IPV6_PREFIX },
{"Device.IP.Interface.{2}.IPv6Address.{2}.PreferredLifetime",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"9999-12-31T23:59:59Z",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0.IP_INTERFACE_IPV6_ADDRESS.{1}",	PARAM_ID_IP_INTERFACE_IPV6_PREFFERED_LIFE_TIME },
{"Device.IP.Interface.{2}.IPv6Address.{2}.ValidLifetime",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"9999-12-31T23:59:59Z",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0.IP_INTERFACE_IPV6_ADDRESS.{1}",	PARAM_ID_IP_INTERFACE_IPV6_VALID_LIFE_TIME },
{"Device.IP.Interface.{2}.IPv6Address.{2}.Anycast",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"false",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0.IP_INTERFACE_IPV6_ADDRESS.{1}",	PARAM_ID_IP_INTERFACE_IPV6_ANYCAST },
{"Device.IP.Interface.{1}.Stats.BytesSent",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_BYTES_SENT },
{"Device.IP.Interface.{1}.Stats.BytesReceived",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_BYTES_RECEIVED },
{"Device.IP.Interface.{1}.Stats.PacketsSent",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_PACKETS_SENT },
{"Device.IP.Interface.{1}.Stats.PacketsReceived",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_PACKETS_RECEIVED },
{"Device.IP.Interface.{1}.Stats.ErrorsSent",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_ERRORS_SENT },
{"Device.IP.Interface.{1}.Stats.ErrorsReceived",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_ERRORS_RECEIVED },
{"Device.IP.Interface.{1}.Stats.UnicastPacketsSent",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_UNICAST_PACKETS_SENT },
{"Device.IP.Interface.{1}.Stats.UnicastPacketsReceived",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_UNICAST_PACKETS_RECEIVED },
{"Device.IP.Interface.{1}.Stats.DiscardPacketsSent",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_DISCARD_PACKETS_SENT },
{"Device.IP.Interface.{1}.Stats.DiscardPacketsReceived",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_DISCARD_PACKETS_RECEIVED },
{"Device.IP.Interface.{1}.Stats.MulticastPacketsSent",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_MULTICAST_PACKETS_SENT },
{"Device.IP.Interface.{1}.Stats.MulticastPacketsReceived",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_MULTICAST_PACKETS_RECEIVED },
{"Device.IP.Interface.{1}.Stats.BroadcastPacketsSent",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_BROADCAST_PACKETS_SENT },
{"Device.IP.Interface.{1}.Stats.BroadcastPacketsReceived",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_BROADCAST_PACKETS_RECEIVED },
{"Device.IP.Interface.{1}.Stats.UnknownProtoPacketsReceived",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.IP_INTERFACE.0",	PARAM_ID_IP_INTERFACE_UNKNOWN_PROTO_PACKETS_RECEIVED },
{"Device.IP.Diagnostics.IPPing.DiagnosticsState",
	READ_WRITE, STRING, "4", "27", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_IP_DIAGNOSTICS_IP_PING_STATE },
{"Device.IP.Diagnostics.IPPing.DiagnosticsState",
	READ_WRITE, STRING, "4", "27", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_IP_DIAGNOSTICS_TRACEROUTE_STATE },
{"Device.IP.Diagnostics.IPPing.RouteHopsNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_IP_DIAGNOSTICS_TRACEROUTE_HOPS_NUM_ENTRIES },
{"Device.IP.Diagnostics.TraceRoute.DiagnosticsState",
	READ_WRITE, STRING, "4", "27", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_IP_DIAGNOSTICS_TRACEROUTE_STATE },
{"Device.IP.Diagnostics.TraceRoute.RouteHopsNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_IP_DIAGNOSTICS_TRACEROUTE_HOPS_NUM_ENTRIES },
{"Device.IP.Diagnostics.DownloadDiagnostics.DiagnosticsState",
	READ_WRITE, STRING, "4", "27", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_IP_DIAGNOSTICS_DOWNLOAD_STATE },
{"Device.IP.Diagnostics.UploadDiagnostics.DiagnosticsState",
	READ_WRITE, STRING, "4", "27", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_IP_DIAGNOSTICS_UPLOAD_STATE },
{"Device.IP.Diagnostics.UDPEchoConfig.Enable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_IP_DIAGNOSTICS_UDP_ECHO_ENABLED },
