/*
 * AUTOMATICALLY GENERATED CODE:
 * DO NOT EDIT !
 */

{"Device.Services.FAPService.{2}.Capabilities.GPSEquipped",
	READ_ONLY, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_GPS_EQUIPPED },
{"Device.Services.FAPService.{2}.Capabilities.MaxTxPower",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_MAX_TX_POWER },
{"Device.Services.FAPService.{2}.Capabilities.SupportedSystems",
	READ_ONLY, STRING, "3", "8", false, NO_NOTIFICATION, false, OnReboot,	"LTE",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_SUPPORTED_SYSTEMS },
{"Device.Services.FAPService.{2}.Capabilities.Beacon",
	READ_ONLY, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_BEACON },
{"Device.Services.FAPService.{2}.Capabilities.LTE.DuplexMode",
	READ_WRITE, STRING, "7", "7", false, NO_NOTIFICATION, false, OnReboot,	"FDDMode",	GROUP_ID_ENUM,	"FAP.0",	PARAM_ID_DUPLEX_MODE },
{"Device.Services.FAPService.{2}.Capabilities.LTE.BandsSupported",
	READ_ONLY, U_INT, "33", "40", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_LIST,	"FAP.0",	PARAM_ID_BANDS_SUPPORTED },
{"Device.Services.FAPService.{2}.Capabilities.LTE.NNSFSupported",
	READ_ONLY, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"TRUE",	GROUP_ID_BOOLEAN,	"FAP.0",	PARAM_ID_LTE_NNSF_SUPPORTED },
{"Device.Services.FAPService.{2}.Capabilities.LTE.UMTSRxSupported",
	READ_ONLY, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_BOOLEAN,	"FAP.0",	PARAM_ID_UMTS_RX_SUPPORTED },
{"Device.Services.FAPService.{2}.Capabilities.LTE.UMTSRxBandsSupported",
	READ_ONLY, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"TRUE",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_UMTS_BAND_SUPPORTED },
{"Device.Services.FAPService.{2}.Capabilities.LTE.GSMRxSupported",
	READ_ONLY, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"TRUE",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_GSM_RX_SUPPORTED },
{"Device.Services.FAPService.{2}.Capabilities.LTE.GSMRxBandsSupported",
	READ_ONLY, STRING, "6", "8", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_GSM_RX_BANDS_SUPPORTED },
{"Device.Services.FAPService.{2}.Capabilities.LTE.CDMA2000RxSupported",
	READ_ONLY, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"TRUE",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_CDMA2K_RX_SUPPORTED },
{"Device.Services.FAPService.{2}.Capabilities.LTE.CDMA2000RxBandsSupported",
	READ_ONLY, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"TRUE",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LTE_CDMA2K_RX_BANDS_SUPPORTED },
{"Device.Services.FAPService.{2}.FAPControl.SelfConfigEvents",
	READ_WRITE, STRING, "10", "10", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LTE_SELF_CONFIG_EVENTS },
{"Device.Services.FAPService.{2}.FAPControl.LTE.OpState",
	READ_ONLY, BOOLEAN, "", "", false, ACTIVE_NOTIFICATION, true, OnReboot,	"FALSE",	GROUP_ID_BOOLEAN,	"FAP.0",	PARAM_ID_LTE_RFTX_OP_STATE },
{"Device.Services.FAPService.{2}.FAPControl.LTE.AdminState",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"FALSE",	GROUP_ID_BOOLEAN,	"FAP.0",	PARAM_ID_LTE_FAP_ADMIN_STATE },
{"Device.Services.FAPService.{2}.FAPControl.LTE.RFTxStatus",
	READ_ONLY, BOOLEAN, "", "", false, ACTIVE_NOTIFICATION, true, OnReboot,	"FALSE",	GROUP_ID_BOOLEAN,	"FAP.0",	PARAM_ID_LTE_RFTX_OP_STATE },
{"Device.Services.FAPService.{2}.FAPControl.LTE.PMConfig",
	READ_WRITE, STRING, "0", "256", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LTE_PM_CONFIG },
{"Device.Services.FAPService.{2}.FAPControl.LTE.Gateway.SecGWServer1",
	READ_WRITE, STRING, "0", "64", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_LIST,	"FAP.0",	PARAM_ID_LTE_SEC_GW_SERVER_1 },
{"Device.Services.FAPService.{2}.FAPControl.LTE.Gateway.SecGWServer2",
	READ_WRITE, STRING, "0", "64", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_LIST,	"FAP.0",	PARAM_ID_LTE_SEC_GW_SERVER_2 },
{"Device.Services.FAPService.{2}.FAPControl.LTE.Gateway.SecGWServer3",
	READ_WRITE, STRING, "0", "64", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_LIST,	"FAP.0",	PARAM_ID_LTE_SEC_GW_SERVER_3 },
{"Device.Services.FAPService.{2}.FAPControl.LTE.Gateway.S1SigLinkServerList",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_LIST,	"FAP.0",	PARAM_ID_LTE_SIGLINK_SERVER_LIST },
{"Device.Services.FAPService.{2}.FAPControl.LTE.Gateway.S1ConnectionMode",
	READ_WRITE, STRING, "3", "3", false, NO_NOTIFICATION, false, Immediate,	"One",	GROUP_ID_ENUM,	"FAP.0",	PARAM_ID_LTE_S1CON_MODE },
{"Device.Services.FAPService.{2}.FAPControl.LTE.Gateway.S1SigLinkPort",
	READ_WRITE, U_INT, "", "65535", false, NO_NOTIFICATION, false, OnReboot,	"36412",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LTE_S1SIG_LINK_PORT },
{"Device.Services.FAPService.{2}.AccessMgmt.LTE.AccessMode",
	READ_WRITE, STRING, "11", "13", false, NO_NOTIFICATION, false, OnReboot,	"Open Access",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LTE_ACCESS_MODE },
{"Device.Services.FAPService.{2}.AccessMgmt.LTE.MaxUEsServed",
	READ_WRITE, INT, "-1", "", false, NO_NOTIFICATION, false, OnReboot,	"-1",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_MAX_UE_SERVED },
{"Device.Services.FAPService.{2}.AccessMgmt.LTE.MaxCSGMembers",
	READ_WRITE, INT, "-1", "", false, NO_NOTIFICATION, false, OnReboot,	"-1",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LTE_MAX_CSG_MEMBERS },
{"Device.Services.FAPService.{2}.AccessMgmt.LTE.MaxNonCSGMembers",
	READ_WRITE, INT, "-1", "", false, NO_NOTIFICATION, false, OnReboot,	"-1",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LTE_MAX_NON_CSG_MEMBERS },
{"Device.Services.FAPService.{2}.AccessMgmt.LTE.MaxResourceNonCSGMembers",
	READ_WRITE, U_INT, "0", "100", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LTE_MAX_NON_CSG_RESOURCE },
{"Device.Services.FAPService.{2}.AccessMgmt.LTE.CSGID",
	READ_WRITE, U_INT, "", "134217727", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LTE_CSG_ID },
{"Device.Services.FAPService.{2}.AccessMgmt.LTE.HNBName",
	READ_WRITE, STRING, "0", "48", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LTE_HOME_NODEB_NAME },
{"Device.Services.FAPService.{2}.CellConfig.LTE.TunnelNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_NUM_TUNNEL_ENTRIES },
{"Device.Services.FAPService.{2}.CellConfig.LTE.Tunnel.{10}.TunnelRef",
	READ_WRITE, STRING, "0", "256", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{9}",	PARAM_ID_LTE_TUNNEL_REF },
{"Device.Services.FAPService.{2}.CellConfig.LTE.Tunnel.{10}.PLMNID",
	READ_WRITE, STRING, "0", "256", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{9}",	PARAM_ID_LTE_TUNNEL_PLMNID },
{"Device.Services.FAPService.{2}.CellConfig.LTE.EPC.AllowedCipheringAlgorithmList",
	READ_WRITE, STRING, "4", "8", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_ENUM,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_CIPHERING_ALGO_LIST },
{"Device.Services.FAPService.{2}.CellConfig.LTE.EPC.AllowedIntegrityProtectionAlgorithmList",
	READ_WRITE, STRING, "8", "8", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_ENUM,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_INTEGRITY_ALGO_LIST },
{"Device.Services.FAPService.{2}.CellConfig.LTE.EPC.TAC",
	READ_WRITE, U_INT, "0", "65535", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_TAC },
{"Device.Services.FAPService.{2}.CellConfig.LTE.EPC.EAID",
	READ_WRITE, U_INT, "0", "16777216", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_EAID },
{"Device.Services.FAPService.{2}.CellConfig.LTE.EPC.MaxPLMNListEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_MAX_PLMN_ENTRIES },
{"Device.Services.FAPService.{2}.CellConfig.LTE.EPC.PLMNListNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"6",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_NUM_OF_PLMN_ENTRIES },
{"Device.Services.FAPService.{2}.CellConfig.LTE.EPC.PLMNList.{6}.Enable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"TRUE",	GROUP_ID_ENABLE,	"FAP.0.FAP_LTE.{5}.LTE_CELL_PLMN_LIST.{5}",	PARAM_ID_LTE_EPC_PLMN_ENABLE },
{"Device.Services.FAPService.{2}.CellConfig.LTE.EPC.PLMNList.{6}.IsPrimary",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"false",	GROUP_ID_BOOLEAN,	"FAP.0.FAP_LTE.{5}.LTE_CELL_PLMN_LIST.{5}",	PARAM_ID_LTE_OAM_PRIMARY_PLMN },
{"Device.Services.FAPService.{2}.CellConfig.LTE.EPC.PLMNList.{6}.PLMNID",
	READ_WRITE, STRING, "0", "6", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_KEY,	"FAP.0.FAP_LTE.{5}.LTE_CELL_PLMN_LIST.{5}",	PARAM_ID_LTE_OAM_PLMNID },
{"Device.Services.FAPService.{2}.CellConfig.LTE.EPC.PLMNList.{6}.CellReservedForOperatorUse",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_BOOLEAN,	"FAP.0.FAP_LTE.{5}.LTE_CELL_PLMN_LIST.{5}",	PARAM_ID_LTE_OAM_CELL_RESERVE_FOR_OPERATOR },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Common.CellIdentity",
	READ_WRITE, U_INT, "0", "268435455", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_CELL_IDENTITY },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.S1U.GTPUEchoInterval",
	READ_WRITE, U_INT, "60", "0", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_GTPU_ECHO_INTERVAL },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RF.EARFCNDL",
	READ_WRITE, U_INT, "0", "65535", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_EARFCNDL_LIST },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RF.EARFCNUL",
	READ_WRITE, U_INT, "0", "65535", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_EARFCNUL_LIST },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RF.FreqBandIndicator",
	READ_WRITE, U_INT, "1", "40", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_FREQ_BAND_INDICATOR },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RF.DLBandwidth",
	READ_WRITE, U_INT, "100", "100", false, NO_NOTIFICATION, false, OnReboot,	"n6",	GROUP_ID_ENUM,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_DL_BANDWIDTH },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RF.ULBandwidth",
	READ_WRITE, U_INT, "100", "100", false, NO_NOTIFICATION, false, OnReboot,	"n6",	GROUP_ID_ENUM,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_UL_BANDWIDTH },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RF.ReferenceSignalPower",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_REFERNCE_SIG_POWER },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RF.PhyCellID",
	READ_WRITE, STRING, "", "", false, ACTIVE_NOTIFICATION, false, Immediate,	"",	GROUP_ID_LIST,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_PHY_CELLID_LIST },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RF.PSCHPowerOffset",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_PSCH_POWER_OFFSET },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RF.SSCHPowerOffset",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_SSCH_POWER_OFFSET },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RF.PBCHPowerOffset",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_PBCH_POWER_OFFSET },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.AntennaInfo.AntennaPortsCount",
	READ_ONLY, U_INT, "4", "4", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_ANTENNA_PORTS_COUNT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PDSCH.Pb",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_PB },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PDSCH.Pa",
	READ_WRITE, INT, "300", "300", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_PA },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.SRS.SRSEnabled",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_SRS_ENA },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.SRS.SRSBandwidthConfig",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_SRS_BANDWIDTH_CFG },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.SRS.SRSMaxUpPTS",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_SRS_MAX_UP_PTS },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.SRS.AckNackSRSSimultaneousTransmission",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_ACK_NACK_SRS_TRNASMISSION },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PRACH.RootSequenceIndex",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_PRACH_ROOT_SEQUENCE_INDEX_LIST },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PRACH.ConfigurationIndex",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_PRACH_CONFIG_INDEX_LIST },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PRACH.HighSpeedFlag",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_BOOLEAN,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_HIGH_SPEED_FLAG },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PRACH.ZeroCorrelationZoneConfig",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_PRACH_ZERO_CORRELATIONZONE_CONFIG_LIST },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PRACH.FreqOffset",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_PRACH_FREQ_OFFSET_LIST },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PUCCH.DeltaPUCCHShift",
	READ_WRITE, STRING, "3", "3", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_DELTA_PUCCH_SHIFT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PUCCH.NRBCQI",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_NRBCQI },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PUCCH.NCSAN",
	READ_ONLY, U_INT, "0", "7", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_NCSAN },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PUCCH.N1PUCCHAN",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_N1PUCCHAN },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PUCCH.CQIPUCCHResourceIndex",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_CQI_PUCCH_RESOURCE_IDX },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PUCCH.K",
	READ_ONLY, U_INT, "1", "4", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_K },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PUSCH.NSB",
	READ_WRITE, U_INT, "1", "4", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_NSB },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PUSCH.HoppingMode",
	READ_WRITE, STRING, "13", "21", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_HOPPING_MODE },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PUSCH.HoppingOffset",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_HOPPING_OFFSET },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PUSCH.Enable64QAM",
	READ_ONLY, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_ENA_64QAM },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PUSCH.ULRS.GroupHoppingEnabled",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_GROUP_HOPPING_ENA },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PUSCH.ULRS.GroupAssignmentPUSCH",
	READ_ONLY, U_INT, "0", "29", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_GROUP_ASSIGNMENT_PUSCH },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PUSCH.ULRS.SequenceHoppingEnabled",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_SEQ_HOPPING_ENA },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.PUSCH.ULRS.CyclicShift",
	READ_ONLY, U_INT, "0", "7", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_CYCLIC_SHIFT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.ULPowerControl.P0NominalPUSCH",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_PO_NOMINAL_PUSCH },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.ULPowerControl.Alpha",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_ALPHA },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.ULPowerControl.P0NominalPUCCH",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_PO_NOMINAL_PUCCH },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.ULPowerControl.DeltaFPUCCHFormat1",
	READ_ONLY, INT, "2", "2", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_DELTAF_PUCCH_FRMT1 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.ULPowerControl.DeltaFPUCCHFormat1b",
	READ_ONLY, U_INT, "5", "5", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_DELTAF_PUCCH_FRMT1B },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.ULPowerControl.DeltaFPUCCHFormat2",
	READ_ONLY, INT, "0", "2", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_DELTAF_PUCCH_FRMT2 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.ULPowerControl.DeltaFPUCCHFormat2a",
	READ_ONLY, INT, "2", "2", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_DELTAF_PUCCH_FRMT2A },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.ULPowerControl.DeltaFPUCCHFormat2b",
	READ_ONLY, INT, "2", "2", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_DELTAF_PUCCH_FRMT2B },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.ULPowerControl.DeltaPreambleMsg3",
	READ_ONLY, INT, "-1", "6", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_DELTA_PREAMBLE_MSG3 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.TDDFrame.SubFrameAssignment",
	READ_WRITE, U_INT, "0", "6", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_TDD_SUBFRAME_ASSIGNMENT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.PHY.TDDFrame.SpecialSubframePatterns",
	READ_WRITE, U_INT, "0", "8", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_TDD_SPECIAL_SUB_FRAME_PATTERNS },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.MAC.RACH.NumberOfRaPreambles",
	READ_WRITE, U_INT, "4", "64", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_NUM_OF_RAPREAMBLES },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.MAC.RACH.SizeOfRaGroupA",
	READ_WRITE, U_INT, "4", "60", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_SIZE_OF_RAGROUP_A },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.MAC.RACH.MessageSizeGroupA",
	READ_WRITE, U_INT, "256", "256", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_MSG_SIZE_GROUP_A },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.MAC.RACH.MessagePowerOffsetGroupB",
	READ_WRITE, INT, "18", "18", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_POWER_OFFSET_GROUP_B },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.MAC.RACH.PowerRampingStep",
	READ_WRITE, U_INT, "6", "6", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_POWER_RAMPING },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.MAC.RACH.PreambleInitialReceivedTargetPower",
	READ_WRITE, INT, "-120", "-90", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_PREAMBLE_INIT_TARGET_POWER },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.MAC.RACH.PreambleTransMax",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_PREAMBLE_TRANS_MAX },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.MAC.RACH.ResponseWindowSize",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_RSP_WINDOW_SIZE },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.MAC.RACH.ContentionResolutionTimer",
	READ_WRITE, U_INT, "8", "64", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_CONTENTION_RESOLUTION_TMR },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.MAC.RACH.MaxHARQMsg3Tx",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_MAX_HARQ_MSG3_TX },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.MAC.DRX.DRXEnabled",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_BOOLEAN,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_DRX_ENABLE },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.MAC.DRX.OnDurationTimer",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_ON_DURATION_TIMER },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.MAC.DRX.DRXInactivityTimer",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_DRX_INACTIVITY_TIMER },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.MAC.DRX.DRXRetransmissionTimer",
	READ_WRITE, U_INT, "33", "33", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_DRX_RETRANSMISSION_TIMER },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.MAC.ULSCH.MaxHARQTx",
	READ_ONLY, U_INT, "28", "28", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_MAX_HARQ_TX },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.MAC.ULSCH.PeriodicBSRTimer",
	READ_ONLY, U_INT, "2560", "2560", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_PERIODIC_BSR_TIMER },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.MAC.ULSCH.RetxBSRTimer",
	READ_ONLY, U_INT, "10240", "10240", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_RETX_BSR_TIMER },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.MAC.ULSCH.TTIBundling",
	READ_ONLY, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_BOOLEAN,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_TTI_BUNDLING },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RLC.SRB1.DefaultConfiguration",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_DEFAULT_CFG_SRB1 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RLC.SRB1.TPollRetransmit",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_TPOLL_RE_TRANSMIT_SRB1 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RLC.SRB1.PollPDU",
	READ_WRITE, U_INT, "256", "256", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_POLL_PDU_SRB1 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RLC.SRB1.PollByte",
	READ_WRITE, U_INT, "3000", "3000", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_POLL_BYTE_SRB1 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RLC.SRB1.MaxRetxThreshold",
	READ_WRITE, U_INT, "32", "32", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_MAX_RE_TX_THRESHOLD_SRB1 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RLC.SRB1.TReordering",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_T_REORDERING_SRB1 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RLC.SRB1.TStatusProhibit",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_TSTATUS_PROHIBIT_SRB1 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RLC.SRB2.DefaultConfiguration",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_DEFAULT_CFG_SRB2 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RLC.SRB2.TPollRetransmit",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_TPOLL_RE_TRANSMIT_SRB2 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RLC.SRB2.PollPDU",
	READ_WRITE, U_INT, "256", "256", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_POLL_PDU_SRB2 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RLC.SRB2.PollByte",
	READ_WRITE, U_INT, "3000", "3000", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_POLL_BYTE_SRB2 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RLC.SRB2.MaxRetxThreshold",
	READ_WRITE, U_INT, "32", "32", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_MAX_RE_TX_THRESHOLD_SRB2 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RLC.SRB2.TReordering",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_T_REORDERING_SRB2 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RLC.SRB2.TStatusProhibit",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_TSTATUS_PROHIBIT_SRB2 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RRCTimers.T300",
	READ_WRITE, U_INT, "2000", "2000", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_T300 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RRCTimers.T301",
	READ_WRITE, U_INT, "2000", "2000", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_T301 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RRCTimers.T302",
	READ_WRITE, U_INT, "2000", "2000", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_T302 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RRCTimers.T304EUTRA",
	READ_WRITE, U_INT, "2000", "2000", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_T304EUTRA },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RRCTimers.T304IRAT",
	READ_WRITE, U_INT, "8000", "8000", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_T304IRAT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RRCTimers.T310",
	READ_WRITE, U_INT, "2000", "2000", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_T310 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RRCTimers.T311",
	READ_WRITE, U_INT, "30000", "30000", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_T311 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RRCTimers.T320",
	READ_WRITE, U_INT, "180", "180", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_T320 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RRCTimers.N310",
	READ_WRITE, U_INT, "20", "20", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_N310 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.RRCTimers.N311",
	READ_WRITE, U_INT, "10", "10", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_N311 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.CellRestriction.CellBarred",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_BOOLEAN,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_CELL_BARRED },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.CellRestriction.CellReservedForOperatorUse",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_BOOLEAN,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_CELL_RESERVE_FOR_OPERATOR },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.CellRestriction.BarringForEmergency",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_BOOLEAN,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_BARRING_FOR_EMERGENCY },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.Common.Qhyst",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_QHYST },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.Common.QHystSFMedium",
	READ_WRITE, INT, "0", "0", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_QHYST_SF_MEDIUM },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.Common.QHystSFHigh",
	READ_WRITE, INT, "0", "0", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_QHYST_SF_HIGH },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.Common.TEvaluation",
	READ_WRITE, U_INT, "240", "240", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_T_EVALUATION },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.Common.THystNormal",
	READ_WRITE, U_INT, "240", "240", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_THYST_NORMAL },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.Common.NCellChangeMedium",
	READ_WRITE, U_INT, "1", "16", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_NUM_CELL_CHANGE_MEDIUM },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.Common.NCellChangeHigh",
	READ_WRITE, U_INT, "1", "16", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_NUM_CELL_CHANGE_HIGH },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IntraFreq.QRxLevMinSIB1",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_QRX_LEVEL_MIN_SIB1 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IntraFreq.QRxLevMinSIB3",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_QRX_LEVEL_MIN_SIB3 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IntraFreq.QRxLevMinOffset",
	READ_WRITE, U_INT, "1", "8", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_QRX_LEVEL_MIN_OFFSET },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IntraFreq.SIntraSearch",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_SINTRA_SEARCH },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IntraFreq.TReselectionEUTRA",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_T_RESELECTION_EUTRA },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IntraFreq.SNonIntraSearch",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_S_NON_INTRA_SEARCH },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IntraFreq.CellReselectionPriority",
	READ_WRITE, U_INT, "0", "7", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_CELL_RESELECTION_PRIORITY },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IntraFreq.PMax",
	READ_WRITE, INT, "-30", "33", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_PMAX },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IntraFreq.ThreshServingLow",
	READ_WRITE, U_INT, "0", "31", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_THRESH_SERVING_LOW },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IntraFreq.TReselectionEUTRASFMedium",
	READ_WRITE, U_INT, "100", "100", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_TRESELECTION_EUTRAS_MED },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IntraFreq.TReselectionEUTRASFHigh",
	READ_WRITE, U_INT, "100", "100", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_TRESELECTION_EUTRAS_HIGH },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.InterFreq.MaxCarrierEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_MAX_CARRIER_ENTRIES_IDLE },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.InterFreq.CarrierNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"8",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_NUM_CARRIER_ENTRIES_IDLE },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.InterFreq.Carrier.{8}.Enable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"FALSE",	GROUP_ID_ENABLE,	"FAP.0.FAP_LTE.{7}.LTE_RAN_MOB_IDLE_MODE_INTER_FREQ_CARRIER.{7}",	PARAM_ID_LTE_INTER_FREQ_ENABLE },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.InterFreq.Carrier.{8}.EUTRACarrierARFCN",
	READ_WRITE, U_INT, "0", "65535", false, NO_NOTIFICATION, false, Immediate,	"3108",	GROUP_ID_KEY,	"FAP.0.FAP_LTE.{7}.LTE_RAN_MOB_IDLE_MODE_INTER_FREQ_CARRIER.{7}",	PARAM_ID_LTE_INTER_FREQ_DL_EARFCN },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.InterFreq.Carrier.{8}.QRxLevMinSIB5",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"0",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{7}.LTE_RAN_MOB_IDLE_MODE_INTER_FREQ_CARRIER.{7}",	PARAM_ID_LTE_INTER_FREQ_QRX_LEVEL_MIN },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.InterFreq.Carrier.{8}.QOffsetFreq",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"18",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{7}.LTE_RAN_MOB_IDLE_MODE_INTER_FREQ_CARRIER.{7}",	PARAM_ID_LTE_INTER_FREQ_QOFFSETFREQ },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.InterFreq.Carrier.{8}.TReselectionEUTRA",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, Immediate,	"1",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{7}.LTE_RAN_MOB_IDLE_MODE_INTER_FREQ_CARRIER.{7}",	PARAM_ID_LTE_INTER_FREQ_TRESELECTION_EUTRA },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.InterFreq.Carrier.{8}.CellReselectionPriority",
	READ_WRITE, U_INT, "0", "7", false, NO_NOTIFICATION, false, Immediate,	"7",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{7}.LTE_RAN_MOB_IDLE_MODE_INTER_FREQ_CARRIER.{7}",	PARAM_ID_LTE_INTER_FREQ_CELL_RESELECT_PRIORITY },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.InterFreq.Carrier.{8}.ThreshXHigh",
	READ_WRITE, U_INT, "0", "31", false, NO_NOTIFICATION, false, Immediate,	"31",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{7}.LTE_RAN_MOB_IDLE_MODE_INTER_FREQ_CARRIER.{7}",	PARAM_ID_LTE_INTER_FREQ_THRESHOLD_XHIGH },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.InterFreq.Carrier.{8}.ThreshXLow",
	READ_WRITE, U_INT, "0", "31", false, NO_NOTIFICATION, false, Immediate,	"31",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{7}.LTE_RAN_MOB_IDLE_MODE_INTER_FREQ_CARRIER.{7}",	PARAM_ID_LTE_INTER_FREQ_THRESHOLD_XLOW },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.InterFreq.Carrier.{8}.PMax",
	READ_WRITE, INT, "-30", "33", false, NO_NOTIFICATION, false, Immediate,	"1",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{7}.LTE_RAN_MOB_IDLE_MODE_INTER_FREQ_CARRIER.{7}",	PARAM_ID_LTE_INTER_FREQ_PMAX },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.InterFreq.Carrier.{8}.TReselectionEUTRASFMedium",
	READ_WRITE, U_INT, "100", "100", false, NO_NOTIFICATION, false, Immediate,	"25",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{7}.LTE_RAN_MOB_IDLE_MODE_INTER_FREQ_CARRIER.{7}",	PARAM_ID_LTE_INTER_FREQ_TRESELECTION_EUTRA_SF_MED },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.InterFreq.Carrier.{8}.TReselectionEUTRASFHigh",
	READ_WRITE, U_INT, "100", "100", false, NO_NOTIFICATION, false, Immediate,	"25",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{7}.LTE_RAN_MOB_IDLE_MODE_INTER_FREQ_CARRIER.{7}",	PARAM_ID_LTE_INTER_FREQ_TRESELECTION_EUTRA_SF_HIGH },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.UTRA.TReselectionUTRA",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_T_RESELECTION_UTRA },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.UTRA.TReselectionUTRASFMedium",
	READ_WRITE, U_INT, "100", "100", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_T_RESELECTION_UTRA_SF_MED },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.UTRA.TReselectionUTRASFHigh",
	READ_WRITE, U_INT, "100", "100", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_T_RESELECTION_UTRA_SF_HIGH },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.UTRA.MaxUTRANFDDFreqEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_MAX_UTRANFDD_FREQ_ENTRIES },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.UTRA.UTRANFDDFreqNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_NUM_UTRA_NEIGH_FREQ_ENTRIES },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.UTRA.UTRANFDDFreq.{16}.Enable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_ENABLE,	"FAP.0.FAP_LTE.{15}.UTRA_UTRAN_FDD_FREQ.{15}",	PARAM_ID_LTE_UTRA_FDD_ENABLE_IRAT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.UTRA.UTRANFDDFreq.{16}.UTRACarrierARFCN",
	READ_WRITE, U_INT, "0", "16383", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_KEY,	"FAP.0.FAP_LTE.{15}.UTRA_UTRAN_FDD_FREQ.{15}",	PARAM_ID_LTE_UTRA_FDD_CARRIER_ARFCN },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.UTRA.UTRANFDDFreq.{16}.QRxLevMin",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"-60",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.UTRA_UTRAN_FDD_FREQ.{15}",	PARAM_ID_LTE_UTRA_Q_RX_LEV_MIN_IRAT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.UTRA.UTRANFDDFreq.{16}.QQualMin",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.UTRA_UTRAN_FDD_FREQ.{15}",	PARAM_ID_LTE_UTRA_Q_QUAL_MIN_IRAT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.UTRA.UTRANFDDFreq.{16}.CellReselectionPriority",
	READ_WRITE, U_INT, "0", "7", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.UTRA_UTRAN_FDD_FREQ.{15}",	PARAM_ID_LTE_UTRA_CELL_RESELECT_PRIORITY_IRAT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.UTRA.UTRANFDDFreq.{16}.ThreshXHigh",
	READ_WRITE, U_INT, "0", "31", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.UTRA_UTRAN_FDD_FREQ.{15}",	PARAM_ID_LTE_UTRA_THRESH_XHIGH_IRAT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.UTRA.UTRANFDDFreq.{16}.ThreshXLow",
	READ_WRITE, U_INT, "0", "31", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.UTRA_UTRAN_FDD_FREQ.{15}",	PARAM_ID_LTE_UTRA_THRESH_XLOW_IRAT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.UTRA.UTRANFDDFreq.{16}.PMaxUTRA",
	READ_WRITE, INT, "-50", "33", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.UTRA_UTRAN_FDD_FREQ.{15}",	PARAM_ID_LTE_UTRA_PMAX },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.GERAN.TReselectionGERAN",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_GERAN_T_RESEL },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.GERAN.TReselectionGERANSFMedium",
	READ_WRITE, U_INT, "100", "100", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_GERAN_T_RESEL_SF_MED },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.GERAN.TReselectionGERANSFHigh",
	READ_WRITE, U_INT, "100", "100", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_GERAN_T_RESEL_SF_HIGH },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.GERAN.MaxGERANFreqGroupEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_GERAN_MAX_FREQ_ENTRIES },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.GERAN.GERANFreqGroupNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"16",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_GERAN_NUM_FREQ_ENTRIES },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.GERAN.GERANFreqGroup.{16}.Enable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_ENABLE,	"FAP.0.FAP_LTE.{15}.LTE_INTER_RAT_GERAN_NEIGHBOR_FREQ_LIST.{15}",	PARAM_ID_LTE_GERAN_FREQ_ENABLE },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.GERAN.GERANFreqGroup.{16}.BandIndicator",
	READ_WRITE, STRING, "6", "7", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_INTER_RAT_GERAN_NEIGHBOR_FREQ_LIST.{15}",	PARAM_ID_LTE_GERAN_FREQ_BAND_INDICATOR },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.GERAN.GERANFreqGroup.{16}.BCCHARFCN",
	READ_WRITE, U_INT, "0", "1023", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_KEY,	"FAP.0.FAP_LTE.{15}.LTE_INTER_RAT_GERAN_NEIGHBOR_FREQ_LIST.{15}",	PARAM_ID_LTE_GERAN_FREQ_BCCH_ARFCN },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.GERAN.GERANFreqGroup.{16}.QRxLevMin",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_INTER_RAT_GERAN_NEIGHBOR_FREQ_LIST.{15}",	PARAM_ID_LTE_GERAN_FREQ_QRX_LEV_MIN },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.GERAN.GERANFreqGroup.{16}.CellReselectionPriority",
	READ_WRITE, U_INT, "0", "7", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_INTER_RAT_GERAN_NEIGHBOR_FREQ_LIST.{15}",	PARAM_ID_LTE_GERAN_FREQ_CELL_RESEL_PRIOR },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.GERAN.GERANFreqGroup.{16}.ThreshXHigh",
	READ_WRITE, U_INT, "0", "31", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_INTER_RAT_GERAN_NEIGHBOR_FREQ_LIST.{15}",	PARAM_ID_LTE_GERAN_FREQ_THRESHX_HIGH },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.GERAN.GERANFreqGroup.{16}.ThreshXLow",
	READ_WRITE, U_INT, "0", "31", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_INTER_RAT_GERAN_NEIGHBOR_FREQ_LIST.{15}",	PARAM_ID_LTE_GERAN_FREQ_THRESHX_LOW },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.CDMA2000.SearchWindowSize",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_CDMA2K_SEARCH_WINDOW_SIZE },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.CDMA2000.TReselectionCDMA2000",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_CDMA2K_T_RESEL_CDMA2K },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.CDMA2000.TReselectionCDMA2000SFMedium",
	READ_WRITE, U_INT, "100", "100", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_CDMA2K_T_RESEL_CDMA2K_SF_MED },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.CDMA2000.TReselectionCDMA2000SFHigh",
	READ_WRITE, U_INT, "100", "100", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_CDMA2K_T_RESEL_CDMA2K_SF_HIGH },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.CDMA2000.MaxCDMA2000BandEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_CDMA2K_MAX_CDMA2K_BAND },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.CDMA2000.CDMA2000BandNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_CDMA2K_NUM_CDMA2K_BAND },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.CDMA2000.CDMA2000Band.{32}.BandClass",
	READ_WRITE, U_INT, "0", "17", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{31}",	PARAM_ID_LTE_CDMA2K_BAND_CLASS },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.CDMA2000.CDMA2000Band.{32}.CellReselectionPriority",
	READ_WRITE, U_INT, "0", "7", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{31}",	PARAM_ID_LTE_CDMA2K_CELL_RESEL_PRIOR },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.CDMA2000.CDMA2000Band.{32}.ThreshXHigh",
	READ_WRITE, U_INT, "0", "63", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{31}",	PARAM_ID_LTE_CDMA2K_THRESH_X_HIGH },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.IdleMode.IRAT.CDMA2000.CDMA2000Band.{32}.ThreshXLow",
	READ_WRITE, U_INT, "0", "63", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{31}",	PARAM_ID_LTE_CDMA2K_THRESH_X_LOW },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.FilterCoefficientRSRP",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_FILTER_COEFFICIENT_RSRP },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.FilterCoefficientRSRQ",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_FILTER_COEFFICIENT_RSRQ },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.A1ThresholdRSRP",
	READ_WRITE, U_INT, "0", "97", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_A1_THRESHOLD_RSRP },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.A1ThresholdRSRQ",
	READ_WRITE, U_INT, "0", "34", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_A1_THRESHOLD_RSRQ },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.A2ThresholdRSRP",
	READ_WRITE, U_INT, "0", "97", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_A2_THRESHOLD_RSRP },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.A2ThresholdRSRQ",
	READ_WRITE, U_INT, "0", "34", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_A2_THRESHOLD_RSRQ },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.A3Offset",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_A3_OFFSET },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.A5Threshold1RSRP",
	READ_WRITE, U_INT, "0", "97", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_INTER_A5_THRESHOLD_1_RSRP },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.A5Threshold1RSRQ",
	READ_WRITE, U_INT, "0", "34", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_A5_THRESHOLD_1_RSRQ },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.A5Threshold2RSRP",
	READ_WRITE, U_INT, "0", "97", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_INTER_A5_THRESHOLD_2_RSRP },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.A5Threshold2RSRQ",
	READ_WRITE, U_INT, "0", "34", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_A5_THRESHOLD_2_RSRQ },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.Hysteresis",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_HYSTERESIS },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.TimeToTrigger",
	READ_WRITE, U_INT, "5120", "5120", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_TIME_TO_TRIGGER },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.TriggerQuantity",
	READ_WRITE, STRING, "4", "4", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_TRIGGER_QUANTITY },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.ReportQuantity",
	READ_WRITE, STRING, "4", "21", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_REPORT_QUANTITY },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.MaxReportCells",
	READ_ONLY, U_INT, "1", "8", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_MAX_REPORT_CELLS },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.ReportInterval",
	READ_WRITE, U_INT, "3600000", "3600000", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_REPORT_INTERVAL },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.ReportAmount",
	READ_WRITE, U_INT, "64", "64", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_REPORT_AMOUNT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.IRAT.QoffsettUTRA",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_QOFFSET_UTRA },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.IRAT.FilterCoefficientUTRA",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_FILTER_COEFFICIENT_UTRA },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.IRAT.MeasQuantityUTRAFDD",
	READ_WRITE, STRING, "10", "10", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_MEAS_QUANTITY_UTRA_FDD },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.IRAT.QoffsetGERAN",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_GERAN_Q_OFFSET },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.IRAT.FilterCoefficientGERAN",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_GERAN_FILTER_COEFF },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.IRAT.MeasQuantityCDMA2000",
	READ_WRITE, STRING, "13", "28", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_MEAS_QUANTITY_CDMA2000 },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.IRAT.B2Threshold2UTRARSCP",
	READ_WRITE, INT, "-5", "91", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_B2_THRESHOLD2_UTRA_RSCP },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.IRAT.B2Threshold2UTRAEcN0",
	READ_WRITE, U_INT, "0", "49", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_B2_THRESHOLD2_UTRA_ECNO },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.IRAT.B2Threshold2GERAN",
	READ_WRITE, U_INT, "0", "63", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_B2_THRESHOLD2_GERAN },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.IRAT.Hysteresis",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_HYSTERESIS_IRAT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.IRAT.TimeToTrigger",
	READ_WRITE, U_INT, "5120", "5120", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_TIME_TO_TRIGGER_IRAT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.IRAT.MaxReportCells",
	READ_ONLY, U_INT, "1", "8", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_MAX_REPORT_CELLS_IRAT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.IRAT.ReportInterval",
	READ_WRITE, U_INT, "3600000", "3600000", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_REPORT_INTERVAL_IRAT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.Mobility.ConnMode.IRAT.ReportAmount",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_REPORT_AMOUNT_IRAT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.MaxLTECellEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_MAX_LTE_CELL },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.LTECellNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"16",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_CELL_ENTRIES },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.LTECell.{16}.Enable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"TRUE",	GROUP_ID_ENABLE,	"FAP.0.FAP_LTE.{15}.LTE_RAN_NEIGH_LIST_LTE_CELL.{15}",	PARAM_ID_LTE_NEIGH_LIST_LTE_CELL_ENABLE },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.LTECell.{16}.MustInclude",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"false",	GROUP_ID_BOOLEAN,	"FAP.0.FAP_LTE.{15}.LTE_RAN_NEIGH_LIST_LTE_CELL.{15}",	PARAM_ID_LTE_NEIGH_LIST_LTE_CELL_MUST_INCLUDE },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.LTECell.{16}.PLMNID",
	READ_WRITE, STRING, "0", "6", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_KEY,	"FAP.0.FAP_LTE.{15}.LTE_RAN_NEIGH_LIST_LTE_CELL.{15}",	PARAM_ID_LTE_NEIGH_LIST_LTE_CELL_PLMNID },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.LTECell.{16}.CID",
	READ_WRITE, U_INT, "1", "268435455", false, NO_NOTIFICATION, false, Immediate,	"1",	GROUP_ID_KEY,	"FAP.0.FAP_LTE.{15}.LTE_RAN_NEIGH_LIST_LTE_CELL.{15}",	PARAM_ID_LTE_NEIGH_LIST_LTE_CELL_CID },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.LTECell.{16}.EUTRACarrierARFCN",
	READ_WRITE, U_INT, "0", "65535", false, NO_NOTIFICATION, false, Immediate,	"0",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_RAN_NEIGH_LIST_LTE_CELL.{15}",	PARAM_ID_LTE_NEIGH_LIST_LTE_CELL_EARFCN },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.LTECell.{16}.PhyCellID",
	READ_WRITE, U_INT, "0", "503", false, NO_NOTIFICATION, false, Immediate,	"0",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_RAN_NEIGH_LIST_LTE_CELL.{15}",	PARAM_ID_LTE_NEIGH_LIST_LTE_CELL_PHY_CELLID },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.LTECell.{16}.QOffset",
	READ_WRITE, INT, "8", "24", false, NO_NOTIFICATION, false, Immediate,	"0",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_RAN_NEIGH_LIST_LTE_CELL.{15}",	PARAM_ID_LTE_NEIGH_LIST_LTE_CELL_QOFFSET },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.LTECell.{16}.CIO",
	READ_WRITE, INT, "8", "24", false, NO_NOTIFICATION, false, Immediate,	"0",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_RAN_NEIGH_LIST_LTE_CELL.{15}",	PARAM_ID_LTE_NEIGH_LIST_LTE_CELL_CIO },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.LTECell.{16}.RSTxPower",
	READ_WRITE, INT, "-127", "255", false, NO_NOTIFICATION, false, Immediate,	"-127",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_RAN_NEIGH_LIST_LTE_CELL.{15}",	PARAM_ID_LTE_NEIGH_LIST_LTE_CELL_RS_TX_POWER },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.LTECell.{16}.Blacklisted",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"FALSE",	GROUP_ID_BOOLEAN,	"FAP.0.FAP_LTE.{15}.LTE_RAN_NEIGH_LIST_LTE_CELL.{15}",	PARAM_ID_LTE_NEIGH_LIST_LTE_CELL_BLACK_LISTED },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.MaxUMTSEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"32",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_MAX_UMTS_ENTRIES },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.MaxGSMEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_GERAN_MAX_CELL_ENTRIES },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.UMTSNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"16",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_NUM_UTRA_NEIGH_CELLS_ENTRIES },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.GSMNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"16",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_GERAN_NUM_CELL_ENTRIES },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.UMTS.{16}.Enable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_ENABLE,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_CELL_ENABLE },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.UMTS.{16}.PLMNID",
	READ_WRITE, STRING, "0", "6", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_KEY,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_CELL_PLMNID },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.UMTS.{16}.RNCID",
	READ_WRITE, U_INT, "0", "65535", false, NO_NOTIFICATION, false, OnReboot,	"10",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_CELL_RNCID },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.UMTS.{16}.CID",
	READ_WRITE, U_INT, "1", "65535", false, NO_NOTIFICATION, false, OnReboot,	"1",	GROUP_ID_KEY,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_CELL_CID_IRAT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.UMTS.{16}.LAC",
	READ_WRITE, U_INT, "0", "65535", false, NO_NOTIFICATION, false, OnReboot,	"50",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_CELL_LAC },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.UMTS.{16}.RAC",
	READ_WRITE, U_INT, "0", "255", false, NO_NOTIFICATION, false, OnReboot,	"50",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_CELL_RAC },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.UMTS.{16}.UARFCNUL",
	READ_WRITE, U_INT, "0", "16383", false, NO_NOTIFICATION, false, OnReboot,	"9763",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_CELL_UARFCNUL },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.UMTS.{16}.UARFCNDL",
	READ_WRITE, U_INT, "0", "16383", false, NO_NOTIFICATION, false, OnReboot,	"10713",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_CELL_UARFCNDL },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.UMTS.{16}.PCPICHScramblingCode",
	READ_WRITE, U_INT, "0", "511", false, NO_NOTIFICATION, false, OnReboot,	"10",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_CELL_PCPICH_SC },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.UMTS.{16}.PCPICHTxPower",
	READ_WRITE, INT, "-100", "500", false, NO_NOTIFICATION, false, OnReboot,	"50",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_CELL_PCPICH_TX_POWER },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.GSM.{16}.Enable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"false",	GROUP_ID_ENABLE,	"FAP.0.FAP_LTE.{15}.LTE_INTER_RAT_GERAN_NEIGHBOR_CELL_LIST.{15}",	PARAM_ID_LTE_GERAN_CELL_ENABLE },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.GSM.{16}.PLMNID",
	READ_WRITE, STRING, "0", "6", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_KEY,	"FAP.0.FAP_LTE.{15}.LTE_INTER_RAT_GERAN_NEIGHBOR_CELL_LIST.{15}",	PARAM_ID_LTE_GERAN_CELL_PLMNID },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.GSM.{16}.LAC",
	READ_WRITE, U_INT, "0", "65535", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_KEY,	"FAP.0.FAP_LTE.{15}.LTE_INTER_RAT_GERAN_NEIGHBOR_CELL_LIST.{15}",	PARAM_ID_LTE_GERAN_CELL_LAC },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.GSM.{16}.BSIC",
	READ_WRITE, U_INT, "0", "255", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_INTER_RAT_GERAN_NEIGHBOR_CELL_LIST.{15}",	PARAM_ID_LTE_GERAN_CELL_BSIC },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.GSM.{16}.CI",
	READ_WRITE, U_INT, "0", "65535", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_KEY,	"FAP.0.FAP_LTE.{15}.LTE_INTER_RAT_GERAN_NEIGHBOR_CELL_LIST.{15}",	PARAM_ID_LTE_GERAN_CELL_CI },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.GSM.{16}.BandIndicator",
	READ_WRITE, STRING, "6", "7", false, NO_NOTIFICATION, false, OnReboot,	"GSM850",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_INTER_RAT_GERAN_NEIGHBOR_CELL_LIST.{15}",	PARAM_ID_LTE_GERAN_CELL_BAND_INDICATOR },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborList.InterRATCell.GSM.{16}.BCCHARFCN",
	READ_WRITE, U_INT, "0", "1023", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_INTER_RAT_GERAN_NEIGHBOR_CELL_LIST.{15}",	PARAM_ID_LTE_GERAN_CELL_BCCH_ARFCN },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.MaxLTECellEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_OAM_NEIGH_EUTRA_IN_USE_MAX_LTE_CELL },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.LTECellNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_OAM_NEIGH_EUTRA_IN_USE_CELL_ENTRIES },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.LTECell.{32}.PLMNID",
	READ_ONLY, STRING, "0", "6", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{31}.LTE_NEIGH_EUTRA_IN_USE.{31}",	PARAM_ID_LTE_OAM_NEIGH_EUTRA_IN_USE_CELL_PLMNID },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.LTECell.{32}.CID",
	READ_ONLY, U_INT, "1", "268435455", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{31}.LTE_NEIGH_EUTRA_IN_USE.{31}",	PARAM_ID_LTE_OAM_NEIGH_EUTRA_IN_USE_CELL_CID },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.LTECell.{32}.EUTRACarrierARFCN",
	READ_ONLY, U_INT, "0", "65535", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{31}.LTE_NEIGH_EUTRA_IN_USE.{31}",	PARAM_ID_LTE_OAM_NEIGH_EUTRA_IN_USE_CELL_DL_EARFCN },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.LTECell.{32}.PhyCellID",
	READ_ONLY, U_INT, "0", "503", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{31}.LTE_NEIGH_EUTRA_IN_USE.{31}",	PARAM_ID_LTE_OAM_NEIGH_EUTRA_IN_USE_CELL_PCI },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.LTECell.{32}.QOffset",
	READ_ONLY, INT, "8", "24", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{31}.LTE_NEIGH_EUTRA_IN_USE.{31}",	PARAM_ID_LTE_OAM_NEIGH_EUTRA_IN_USE_CELL_QOFFSET },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.LTECell.{32}.CIO",
	READ_ONLY, INT, "8", "24", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{31}.LTE_NEIGH_EUTRA_IN_USE.{31}",	PARAM_ID_LTE_OAM_NEIGH_EUTRA_IN_USE_CELL_CIO },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.LTECell.{32}.RSTxPower",
	READ_ONLY, INT, "-60", "50", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{31}.LTE_NEIGH_EUTRA_IN_USE.{31}",	PARAM_ID_LTE_OAM_NEIGH_EUTRA_IN_USE_CELL_RS_TX_POWER },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.LTECell.{32}.Blacklisted",
	READ_ONLY, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{31}.LTE_NEIGH_EUTRA_IN_USE.{31}",	PARAM_ID_LTE_OAM_NEIGH_EUTRA_IN_USE_CELL_BLACKLISTED },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.MaxUMTSEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"16",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_MAX_UMTS_IN_USE_ENTRIES },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.MaxGSMEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_GERAN_MAX_CELL_IN_USE_ENTRIES },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.UMTSNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"32",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_UMTS_IN_USE_NUMBER_OF_ENTRIES },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.GSMNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.FAP_LTE.{2}",	PARAM_ID_LTE_GERAN_NUM_CELL_IN_USE_ENTRIES },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.UMTS.{16}.PLMNID",
	READ_ONLY, STRING, "0", "6", false, NO_NOTIFICATION, false, OnReboot,	"001020",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR_IN_USE.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_IN_USE_CELL_PLMNID },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.UMTS.{16}.RNCID",
	READ_ONLY, U_INT, "0", "65535", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR_IN_USE.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_IN_USE_CELL_RNCID },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.UMTS.{16}.CID",
	READ_ONLY, U_INT, "1", "65535", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR_IN_USE.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_IN_USE_CELL_CID_IRAT },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.UMTS.{16}.LAC",
	READ_ONLY, U_INT, "0", "65535", false, NO_NOTIFICATION, false, OnReboot,	"50",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR_IN_USE.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_IN_USE_CELL_LAC },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.UMTS.{16}.RAC",
	READ_ONLY, U_INT, "0", "255", false, NO_NOTIFICATION, false, OnReboot,	"50",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR_IN_USE.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_IN_USE_CELL_RAC },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.UMTS.{16}.URA",
	READ_ONLY, U_INT, "0", "65535", false, NO_NOTIFICATION, false, OnReboot,	"100",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR_IN_USE.{15}",	PARAM_ID_INVALID },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.UMTS.{16}.UARFCNUL",
	READ_ONLY, U_INT, "0", "16383", false, NO_NOTIFICATION, false, OnReboot,	"9763",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR_IN_USE.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_IN_USE_CELL_UARFCNUL },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.UMTS.{16}.UARFCNDL",
	READ_ONLY, U_INT, "0", "16383", false, NO_NOTIFICATION, false, OnReboot,	"10713",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR_IN_USE.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_IN_USE_CELL_UARFCNDL },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.UMTS.{16}.PCPICHScramblingCode",
	READ_ONLY, U_INT, "0", "511", false, NO_NOTIFICATION, false, OnReboot,	"86",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR_IN_USE.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_IN_USE_CELL_PCPICH_SC },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.UMTS.{16}.PCPICHTxPower",
	READ_ONLY, INT, "-100", "500", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{15}.LTE_UMTS_NEIGHBOR_IN_USE.{15}",	PARAM_ID_LTE_OAM_NEIGHBOUR_UTRA_IN_USE_CELL_PCPICH_IN_USE_TX_POWER },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.GSM.{32}.PLMNID",
	READ_ONLY, STRING, "0", "6", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{31}.LTE_INTER_RAT_GERAN_NEIGHBOR_CELL_IN_USE_LIST.{31}",	PARAM_ID_LTE_GERAN_CELL_IN_USE_PLMNID },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.GSM.{32}.LAC",
	READ_ONLY, U_INT, "0", "65535", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{31}.LTE_INTER_RAT_GERAN_NEIGHBOR_CELL_IN_USE_LIST.{31}",	PARAM_ID_LTE_GERAN_CELL_IN_USE_LAC },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.GSM.{32}.BSIC",
	READ_ONLY, U_INT, "0", "255", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{31}.LTE_INTER_RAT_GERAN_NEIGHBOR_CELL_IN_USE_LIST.{31}",	PARAM_ID_LTE_GERAN_CELL_IN_USE_BSIC },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.GSM.{32}.CI",
	READ_ONLY, U_INT, "0", "65535", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{31}.LTE_INTER_RAT_GERAN_NEIGHBOR_CELL_IN_USE_LIST.{31}",	PARAM_ID_LTE_GERAN_CELL_IN_USE_CI },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.GSM.{32}.BandIndicator",
	READ_ONLY, STRING, "6", "7", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{31}.LTE_INTER_RAT_GERAN_NEIGHBOR_CELL_IN_USE_LIST.{31}",	PARAM_ID_LTE_GERAN_CELL_IN_USE_BAND_INDICATOR },
{"Device.Services.FAPService.{2}.CellConfig.LTE.RAN.NeighborListInUse.InterRATCell.GSM.{32}.BCCHARFCN",
	READ_ONLY, U_INT, "0", "1023", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.FAP_LTE.{31}.LTE_INTER_RAT_GERAN_NEIGHBOR_CELL_IN_USE_LIST.{31}",	PARAM_ID_LTE_GERAN_CELL_IN_USE_BCCH_ARFCN },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.InServiceHandling",
	READ_WRITE, STRING, "7", "9", false, NO_NOTIFICATION, false, OnReboot,	"Delayed",	GROUP_ID_INVALID,	"FAP.0.REM_UMTS_WCDMA.0",	PARAM_ID_IN_SERVICE_HANDLING },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.ScanOnBoot",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.REM_UMTS_WCDMA.0",	PARAM_ID_WCDMA_REM_SCAN_ON_BOOT },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.ScanPeriodically",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_INVALID,	"FAP.0.REM_UMTS_WCDMA.0",	PARAM_ID_PERIODIC_SCAN_MODE },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.PeriodicInterval",
	READ_WRITE, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"86400",	GROUP_ID_INVALID,	"FAP.0.REM_UMTS_WCDMA.0",	PARAM_ID_PERIODIC_INTERVAL },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.PeriodicTime",
	READ_WRITE, DATE_TIME, "", "", false, NO_NOTIFICATION, false, OnReboot,	"0001-01-01T03:15:30",	GROUP_ID_INVALID,	"FAP.0.REM_UMTS_WCDMA.0",	PARAM_ID_PERIODIC_TIME },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.REMPLMNList",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_UMTS_WCDMA.0",	PARAM_ID_WCDMA_REM_SCAN_PLMN_LIST },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.REMBandList",
	READ_WRITE, STRING, "0", "64", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_UMTS_WCDMA.0",	PARAM_ID_UMTS_REM_SCAN_BAND_LIST },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.UARFCNDLList",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_UMTS_WCDMA.0",	PARAM_ID_REM_SCAN_UARFCN_LIST },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.ScanTimeout",
	READ_WRITE, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"90",	GROUP_ID_INVALID,	"FAP.0.REM_UMTS_WCDMA.0",	PARAM_ID_WCDMA_SCAN_TIMEOUT },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.ScanStatus",
	READ_ONLY, STRING, "5", "13", false, PASSIVE_NOTIFICATION, false, OnReboot,	"Indeterminate",	GROUP_ID_INVALID,	"FAP.0.REM_UMTS_WCDMA.0",	PARAM_ID_WCDMA_REM_SCAN_STATUS },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.ErrorDetails",
	READ_ONLY, STRING, "0", "256", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_UMTS_WCDMA.0",	PARAM_ID_ERROR_DETAILS },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.LastScanTime",
	READ_ONLY, DATE_TIME, "", "", false, ACTIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_UMTS_WCDMA.0",	PARAM_ID_WCDMA_LAST_REM_SCAN_TIME },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.MaxCellEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"64",	GROUP_ID_INVALID,	"FAP.0.REM_UMTS_WCDMA.0",	PARAM_ID_MAX_CELL_ENTRIES },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.CellNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, PASSIVE_NOTIFICATION, false, OnReboot,	"64",	GROUP_ID_INVALID,	"FAP.0.REM_UMTS_WCDMA.0",	PARAM_ID_NUM_CELL_ENTRIES },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.Cell.{16}.RF.UARFCNDL",
	READ_ONLY, U_INT, "0", "16383", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_SCANNED_WCDMA_CELL.{15}",	PARAM_ID_UARFCN_DL },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.Cell.{16}.RF.CPICHRSCP",
	READ_ONLY, INT, "-120", "-25", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_SCANNED_WCDMA_CELL.{15}",	PARAM_ID_CPICH_RSCP },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.Cell.{16}.RF.CPICHEcNo",
	READ_ONLY, INT, "-48", "0", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_SCANNED_WCDMA_CELL.{15}",	PARAM_ID_CPICH_ECNO },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.Cell.{16}.RF.RSSI",
	READ_ONLY, INT, "-100", "-25", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_SCANNED_WCDMA_CELL.{15}",	PARAM_ID_RSSI },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.Cell.{16}.RF.PrimaryScramblingCode",
	READ_ONLY, U_INT, "0", "511", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_SCANNED_WCDMA_CELL.{15}",	PARAM_ID_PRIM_SC },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.Cell.{16}.BCCH.PLMNType",
	READ_ONLY, STRING, "7", "7", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_SCANNED_WCDMA_CELL.{15}",	PARAM_ID_PLMN_TYPE },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.Cell.{16}.BCCH.PLMNID",
	READ_ONLY, STRING, "0", "6", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_SCANNED_WCDMA_CELL.{15}",	PARAM_ID_PLMN_ID },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.Cell.{16}.BCCH.LAC",
	READ_ONLY, U_INT, "0", "65535", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_SCANNED_WCDMA_CELL.{15}",	PARAM_ID_LAC },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.Cell.{16}.BCCH.RAC",
	READ_ONLY, U_INT, "0", "255", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_SCANNED_WCDMA_CELL.{15}",	PARAM_ID_RAC },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.Cell.{16}.BCCH.CellID",
	READ_ONLY, U_INT, "", "268435455", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_SCANNED_WCDMA_CELL.{15}",	PARAM_ID_CELL_IDENTITY },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.Cell.{16}.BCCH.PCPICHTxPower",
	READ_ONLY, INT, "-10", "50", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_SCANNED_WCDMA_CELL.{15}",	PARAM_ID_PCPICH_TXPOWER },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.Cell.{16}.BCCH.CSGIndicator",
	READ_ONLY, BOOLEAN, "", "", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_SCANNED_WCDMA_CELL.{15}",	PARAM_ID_CSG_INDICATOR },
{"Device.Services.FAPService.{2}.REM.UMTS.WCDMA.Cell.{16}.BCCH.CSGID",
	READ_ONLY, U_INT, "", "134217727", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_SCANNED_WCDMA_CELL.{15}",	PARAM_ID_CSG_ID },
{"Device.Services.FAPService.{2}.REM.LTE.InServiceHandling",
	READ_WRITE, STRING, "7", "9", false, NO_NOTIFICATION, false, OnReboot,	"Delayed",	GROUP_ID_INVALID,	"FAP.0.REM_LTE.0",	PARAM_ID_LTE_IN_SERVICE_HANDLING },
{"Device.Services.FAPService.{2}.REM.LTE.ScanOnBoot",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_REM_SCAN_ON_BOOT,	"FAP.0.REM_LTE.0",	PARAM_ID_LTE_REM_SCAN_ON_BOOT },
{"Device.Services.FAPService.{2}.REM.LTE.ScanPeriodically",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_REM_SCAN_PERIODICALLY,	"FAP.0.REM_LTE.0",	PARAM_ID_LTE_PERIODIC_SCAN_MODE },
{"Device.Services.FAPService.{2}.REM.LTE.PeriodicInterval",
	READ_WRITE, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"86400",	GROUP_ID_INVALID,	"FAP.0.REM_LTE.0",	PARAM_ID_LTE_PERIODIC_INTERVAL },
{"Device.Services.FAPService.{2}.REM.LTE.PeriodicTime",
	READ_WRITE, DATE_TIME, "", "", false, NO_NOTIFICATION, false, OnReboot,	"0001-01-01T03:15:30",	GROUP_ID_INVALID,	"FAP.0.REM_LTE.0",	PARAM_ID_LTE_PERIODIC_TIME },
{"Device.Services.FAPService.{2}.REM.LTE.REMPLMNList",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_LIST,	"FAP.0.REM_LTE.0",	PARAM_ID_LTE_REM_SCAN_PLMN_LIST },
{"Device.Services.FAPService.{2}.REM.LTE.REMBandList",
	READ_WRITE, STRING, "0", "64", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_LIST,	"FAP.0.REM_LTE.0",	PARAM_ID_LTE_REM_SCAN_BAND_LIST },
{"Device.Services.FAPService.{2}.REM.LTE.EUTRACarrierARFCNDLList",
	READ_WRITE, STRING, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_LIST,	"FAP.0.REM_LTE.0",	PARAM_ID_LTE_REM_SCAN_ARFCN_LIST },
{"Device.Services.FAPService.{2}.REM.LTE.ScanTimeout",
	READ_WRITE, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"90",	GROUP_ID_INVALID,	"FAP.0.REM_LTE.0",	PARAM_ID_LTE_SCAN_TIMEOUT },
{"Device.Services.FAPService.{2}.REM.LTE.ScanStatus",
	READ_ONLY, STRING, "5", "13", false, PASSIVE_NOTIFICATION, false, OnReboot,	"Indeterminate",	GROUP_ID_INVALID,	"FAP.0.REM_LTE.0",	PARAM_ID_LTE_REM_SCAN_STATUS },
{"Device.Services.FAPService.{2}.REM.LTE.ErrorDetails",
	READ_ONLY, STRING, "0", "256", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_LTE.0",	PARAM_ID_LTE_ERROR_DETAILS },
{"Device.Services.FAPService.{2}.REM.LTE.LastScanTime",
	READ_ONLY, DATE_TIME, "", "", false, ACTIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.REM_LTE.0",	PARAM_ID_LTE_LAST_REM_SCAN_TIME },
{"Device.Services.FAPService.{2}.REM.LTE.MaxCellEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"16",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0",	PARAM_ID_LTE_MAX_REM_ENTRIES },
{"Device.Services.FAPService.{2}.REM.LTE.CellNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, PASSIVE_NOTIFICATION, false, OnReboot,	"0",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0",	PARAM_ID_LTE_NUM_REM_ENTRIES },
{"Device.Services.FAPService.{2}.REM.LTE.MaxCarrierMeasEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.REM_LTE.0",	PARAM_ID_LTE_MAX_CARRIER_ENTRIES },
{"Device.Services.FAPService.{2}.REM.LTE.CarrierMeasNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_MULTIPLE_INSTANCE_MIB_OBJECT,	"FAP.0.REM_LTE.0",	PARAM_ID_LTE_NUM_CARRIER_ENTRIES },
{"Device.Services.FAPService.{2}.REM.LTE.Cell.{16}.RF.EUTRACarrierARFCN",
	READ_ONLY, U_INT, "0", "65535", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.LTE_REM_SCANNED_CELL.{15}",	PARAM_ID_LTE_REM_SCANNED_EARFCN },
{"Device.Services.FAPService.{2}.REM.LTE.Cell.{16}.RF.PhyCellID",
	READ_ONLY, U_INT, "0", "503", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.LTE_REM_SCANNED_CELL.{15}",	PARAM_ID_LTE_REM_SCANNED_PCI },
{"Device.Services.FAPService.{2}.REM.LTE.Cell.{16}.RF.RSRP",
	READ_ONLY, INT, "-140", "-44", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.LTE_REM_SCANNED_CELL.{15}",	PARAM_ID_LTE_REM_SCANNED_RSRP },
{"Device.Services.FAPService.{2}.REM.LTE.Cell.{16}.RF.RSRQ",
	READ_ONLY, INT, "-240", "0", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.LTE_REM_SCANNED_CELL.{15}",	PARAM_ID_LTE_REM_SCANNED_RSRQ },
{"Device.Services.FAPService.{2}.REM.LTE.Cell.{16}.RF.RSSI",
	READ_ONLY, INT, "-110", "-19", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.LTE_REM_SCANNED_CELL.{15}",	PARAM_ID_LTE_REM_SCANNED_RSSI },
{"Device.Services.FAPService.{2}.REM.LTE.Cell.{16}.BCCH.DLBandwidth",
	READ_ONLY, U_INT, "100", "100", false, PASSIVE_NOTIFICATION, false, OnReboot,	"n6",	GROUP_ID_ENUM,	"FAP.0.LTE_REM_SCANNED_CELL.{15}",	PARAM_ID_LTE_REM_SCANNED_DL_BANDWIDTH },
{"Device.Services.FAPService.{2}.REM.LTE.Cell.{16}.BCCH.ULBandwidth",
	READ_ONLY, U_INT, "100", "100", false, PASSIVE_NOTIFICATION, false, OnReboot,	"n6",	GROUP_ID_ENUM,	"FAP.0.LTE_REM_SCANNED_CELL.{15}",	PARAM_ID_LTE_REM_SCANNED_UL_BANDWIDTH },
{"Device.Services.FAPService.{2}.REM.LTE.Cell.{16}.BCCH.RSTxPower",
	READ_ONLY, INT, "-60", "50", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.LTE_REM_SCANNED_CELL.{15}",	PARAM_ID_LTE_REM_SCANNED_RS_TX_POWER },
{"Device.Services.FAPService.{2}.REM.LTE.Cell.{16}.BCCH.TAC",
	READ_ONLY, U_INT, "", "65535", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.LTE_REM_SCANNED_CELL.{15}",	PARAM_ID_LTE_REM_SCANNED_TAC },
{"Device.Services.FAPService.{2}.REM.LTE.Cell.{16}.BCCH.CellID",
	READ_ONLY, U_INT, "", "268435455", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.LTE_REM_SCANNED_CELL.{15}",	PARAM_ID_LTE_REM_SCANNED_CELL_IDENTITY },
{"Device.Services.FAPService.{2}.REM.LTE.Cell.{16}.BCCH.CellBarred",
	READ_ONLY, BOOLEAN, "", "", false, PASSIVE_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_BOOLEAN,	"FAP.0.LTE_REM_SCANNED_CELL.{15}",	PARAM_ID_LTE_REM_SCANNED_CELL_BARRED },
{"Device.Services.FAPService.{2}.REM.LTE.Cell.{16}.BCCH.MaxPLMNListEntries",
	READ_ONLY, U_INT, "", "", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.LTE_REM_SCANNED_CELL.{15}",	PARAM_ID_LTE_REM_SCANNED_MAX_PLMN_ENTRIES },
{"Device.Services.FAPService.{2}.REM.LTE.Cell.{16}.BCCH.PLMNListNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, PASSIVE_NOTIFICATION, false, OnReboot,	"10",	GROUP_ID_INVALID,	"FAP.0.LTE_REM_SCANNED_CELL.{15}",	PARAM_ID_LTE_REM_SCANNED_NUM_OF_PLMN_ENTRIES },
{"Device.Services.FAPService.{2}.REM.LTE.Cell.{6}.BCCH.PLMNList.{6}.PLMNID",
	READ_ONLY, STRING, "0", "6", false, PASSIVE_NOTIFICATION, false, OnReboot,	"",	GROUP_ID_INVALID,	"FAP.0.LTE_REM_SCANNED_CELL.{5}",	PARAM_ID_LTE_REM_SCANNED_PLMNID },
{"Device.Services.FAPService.{2}.REM.LTE.Cell.{6}.BCCH.PLMNList.{6}.CellReservedForOperatorUse",
	READ_ONLY, BOOLEAN, "", "", false, PASSIVE_NOTIFICATION, false, OnReboot,	"FALSE",	GROUP_ID_BOOLEAN,	"FAP.0.LTE_REM_SCANNED_CELL.{5}",	PARAM_ID_LTE_REM_SCANNED_CELL_RESERVE_FOR_OPERATOR },
{"Device.Services.FAPService.{2}.Transport.SCTP.HBInterval",
	READ_WRITE, U_INT, "1", "", false, NO_NOTIFICATION, false, OnReboot,	"30",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LTE_SCTP_HRTBEAT_INTERVAL },
{"Device.Services.FAPService.{2}.Transport.SCTP.MaxAssociationRetransmits",
	READ_WRITE, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"10",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LTE_SCTP_MAX_ASSOC_RETX },
{"Device.Services.FAPService.{2}.Transport.SCTP.MaxInitRetransmits",
	READ_WRITE, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"8",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LTE_SCTP_MAX_INIT_RETX },
{"Device.Services.FAPService.{2}.Transport.SCTP.MaxPathRetransmits",
	READ_WRITE, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"5",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LTE_SCTP_MAX_PATH_RETX },
{"Device.Services.FAPService.{2}.Transport.SCTP.RTOInitial",
	READ_WRITE, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"3000",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LTE_SCTP_RTO_INITIAL },
{"Device.Services.FAPService.{2}.Transport.SCTP.RTOMax",
	READ_WRITE, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"6000",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LTE_SCTP_RTO_MAX },
{"Device.Services.FAPService.{2}.Transport.SCTP.RTOMin",
	READ_WRITE, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"1000",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LTE_SCTP_RTO_MIN },
{"Device.Services.FAPService.{2}.Transport.SCTP.ValCookieLife",
	READ_WRITE, U_INT, "", "", false, NO_NOTIFICATION, false, OnReboot,	"60000",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_LTE_SCTP_COOKIE_LIFE },
