/*
 * AUTOMATICALLY GENERATED CODE:
 * DO NOT EDIT !
 */

{"Device.FAP.Tunnel.CryptoProfileNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"0",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_FAP_TUNNEL_CRYPTO_NUM_ENTRIES },
{"Device.FAP.Tunnel.IKESANumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_FAP_TUNNEL_IKE_SA_NUM_ENTRIES },
{"Device.FAP.Tunnel.ChildSANumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_FAP_TUNNEL_CHLD_SA_NUM_ENTRIES },
{"Device.FAP.Tunnel.MaxVirtualInterfaces",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_FAP_TUNNEL_MAX_VIRTUAL_INTF },
{"Device.FAP.Tunnel.VirtualInterfaceNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_FAP_TUNNEL_NUM_VIRTUAL_INTF },
{"Device.FAP.Tunnel.UseForCWMP",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_FAP_TUNNEL_USE_FOR_CWMP },
{"Device.FAP.Tunnel.MaxChildSAPerIKE",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_FAP_TUNNEL_MAX_CHLD_SA_PER_IKE },
{"Device.FAP.Tunnel.MaxIKESessions",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_FAP_TUNNEL_MAX_IKE_SESSIONS },
{"Device.FAP.Tunnel.CryptoProfile.{2}.Enable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"false",	GROUP_ID_INVALID,	"FAP.0.CRYPTO_PROFILES.{1}",	PARAM_ID_CRYPTO_PROFILE_ENABLED },
{"Device.FAP.Tunnel.CryptoProfile.{2}.AuthMethod",
	READ_WRITE, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.CRYPTO_PROFILES.{1}",	PARAM_ID_CRYPTO_PATH },
{"Device.FAP.Tunnel.CryptoProfile.{2}.MaxChildSA",
	READ_WRITE, U_INT, "10", "10", false, NO_NOTIFICATION, false, Immediate,	"2",	GROUP_ID_INVALID,	"FAP.0.CRYPTO_PROFILES.{1}",	PARAM_ID_CRYPTO_MAX_CHILD_SA },
{"Device.FAP.Tunnel.CryptoProfile.{2}.IKEEncrypt",
	READ_WRITE, STRING, "7", "8", false, NO_NOTIFICATION, false, Immediate,	"AES-CBC",	GROUP_ID_INVALID,	"FAP.0.CRYPTO_PROFILES.{1}",	PARAM_ID_CRYPTO_IKE_CIPHER_ALGO },
{"Device.FAP.Tunnel.CryptoProfile.{2}.IKEPRF",
	READ_WRITE, STRING, "9", "16", false, NO_NOTIFICATION, false, Immediate,	"HMAC-SHA1",	GROUP_ID_INVALID,	"FAP.0.CRYPTO_PROFILES.{1}",	PARAM_ID_CRYPTO_IKE_PRF },
{"Device.FAP.Tunnel.CryptoProfile.{2}.IKEIntegrity",
	READ_WRITE, STRING, "12", "15", false, NO_NOTIFICATION, false, Immediate,	"HMAC-SHA1-96",	GROUP_ID_INVALID,	"FAP.0.CRYPTO_PROFILES.{1}",	PARAM_ID_CRYPTO_IKE_INTG_ALGO },
{"Device.FAP.Tunnel.CryptoProfile.{2}.IKEDH",
	READ_WRITE, STRING, "4", "4", false, NO_NOTIFICATION, false, Immediate,	"2048",	GROUP_ID_INVALID,	"FAP.0.CRYPTO_PROFILES.{1}",	PARAM_ID_CRYPTO_IKE_DH },
{"Device.FAP.Tunnel.CryptoProfile.{2}.ESPEncrypt",
	READ_WRITE, STRING, "4", "8", false, NO_NOTIFICATION, false, Immediate,	"AES-CBC",	GROUP_ID_INVALID,	"FAP.0.CRYPTO_PROFILES.{1}",	PARAM_ID_CRYPTO_ESP_CIPHER_ALGO },
{"Device.FAP.Tunnel.CryptoProfile.{2}.ESPIntegrity",
	READ_WRITE, STRING, "12", "15", false, NO_NOTIFICATION, false, Immediate,	"HMAC-SHA1-96",	GROUP_ID_INVALID,	"FAP.0.CRYPTO_PROFILES.{1}",	PARAM_ID_CRYPTO_ESP_INTG_ALGO },
{"Device.FAP.Tunnel.CryptoProfile.{2}.IPsecWindowSize",
	READ_WRITE, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"0",	GROUP_ID_INVALID,	"FAP.0.CRYPTO_PROFILES.{1}",	PARAM_ID_CRYPTO_IPSEC_WINDOW_SIZE },
{"Device.FAP.Tunnel.CryptoProfile.{2}.IKERekeyLifetime",
	READ_WRITE, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.CRYPTO_PROFILES.{1}",	PARAM_ID_CRYPTO_IKE_REKEY_LIFETIME },
{"Device.FAP.Tunnel.CryptoProfile.{2}.IPsecRekeyLifetimeByte",
	READ_WRITE, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.CRYPTO_PROFILES.{1}",	PARAM_ID_CRYPTO_IKE_REKEY_LIFETIME_BYTE },
{"Device.FAP.Tunnel.CryptoProfile.{2}.IPsecRekeyLifetimeTime",
	READ_WRITE, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"",	GROUP_ID_INVALID,	"FAP.0.CRYPTO_PROFILES.{1}",	PARAM_ID_CRYPTO_IKE_REKEY_LIFETIME_TIME },
{"Device.FAP.Tunnel.CryptoProfile.{2}.DPDTimer",
	READ_WRITE, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"300",	GROUP_ID_INVALID,	"FAP.0.CRYPTO_PROFILES.{1}",	PARAM_ID_CRYPTO_DPD_TIMER },
{"Device.FAP.Tunnel.CryptoProfile.{2}.NATTKeepaliveTimer",
	READ_WRITE, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"180",	GROUP_ID_INVALID,	"FAP.0.CRYPTO_PROFILES.{1}",	PARAM_ID_CRYPTO_NAT_KEEP_ALIVE_TIMER },
{"Device.FAP.Tunnel.CryptoProfile.{2}.SecMaxFragSize",
	READ_WRITE, U_INT, "256", "1400", false, NO_NOTIFICATION, false, Immediate,	"1200",	GROUP_ID_INVALID,	"FAP.0.CRYPTO_PROFILES.{1}",	PARAM_ID_CRYPTO_SEC_MAX_FRAG_SIZE },
{"Device.FAP.Tunnel.CryptoProfile.{2}.SecDFBit",
	READ_WRITE, STRING, "2", "3", false, NO_NOTIFICATION, false, Immediate,	"Off",	GROUP_ID_INVALID,	"FAP.0.CRYPTO_PROFILES.{1}",	PARAM_ID_CRYPTO_SEC_DF_BIT },
{"Device.FAP.PerfMgmt.ConfigNumberOfEntries",
	READ_ONLY, U_INT, "", "", false, NO_NOTIFICATION, false, Immediate,	"1",	GROUP_ID_INVALID,	"FAP.0",	PARAM_ID_PM_CONFIG_NUMBER_OF_ENTRIES },
{"Device.FAP.PerfMgmt.Config.{1}.Enable",
	READ_WRITE, BOOLEAN, "", "", false, NO_NOTIFICATION, false, Immediate,	"0",	GROUP_ID_BOOLEAN,	"FAP.0.PERF_MGMT.{0}",	PARAM_ID_PM_UPLOAD_ENABLE },
{"Device.FAP.PerfMgmt.Config.{1}.URL",
	READ_WRITE, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"0",	GROUP_ID_INVALID,	"FAP.0.PERF_MGMT.{0}",	PARAM_ID_PM_URL },
{"Device.FAP.PerfMgmt.Config.{1}.Username",
	READ_WRITE, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"0",	GROUP_ID_INVALID,	"FAP.0.PERF_MGMT.{0}",	PARAM_ID_PM_USERNAME },
{"Device.FAP.PerfMgmt.Config.{1}.Password",
	READ_WRITE, STRING, "0", "256", false, NO_NOTIFICATION, false, Immediate,	"0",	GROUP_ID_INVALID,	"FAP.0.PERF_MGMT.{0}",	PARAM_ID_PM_PASSWORD },
{"Device.FAP.PerfMgmt.Config.{1}.PeriodicUploadInterval",
	READ_WRITE, U_INT, "1", "", false, NO_NOTIFICATION, false, Immediate,	"0",	GROUP_ID_INVALID,	"FAP.0.PERF_MGMT.{0}",	PARAM_ID_PM_PERIODIC_UPLOAD_INTERVAL },
{"Device.FAP.PerfMgmt.Config.{1}.PeriodicUploadTime",
	READ_WRITE, DATE_TIME, "", "", false, NO_NOTIFICATION, false, Immediate,	"0",	GROUP_ID_INVALID,	"FAP.0.PERF_MGMT.{0}",	PARAM_ID_PM_PERIODIC_UPLOAD_TIME },
