#!/bin/sh

if [ ! $TOP ]; then
  echo "TOP must be set."
  exit
fi

if [ ! $OUTPUT_DIR_APPS ]; then
  echo "OUTPUT_DIR_APPS must be set."
  exit
fi

STOP_APPS_FILE=$OUTPUT_DIR_APPS/stop-apps

echo "#!/bin/sh" > $STOP_APPS_FILE

echo "" >> $STOP_APPS_FILE

echo "APP_FILES=\"${APP_FILES}\"" >> $STOP_APPS_FILE

echo "" >> $STOP_APPS_FILE

cat $TOP/products/fap/hbs2/etc/stop-apps-base-script >> $STOP_APPS_FILE

chmod +x $STOP_APPS_FILE
