#!/bin/bash

if [ "$WITH_GDBS" == "y" ] ; then
  echo "Copying .gdb files for all apps."
  GDB_FILES=`echo $FAP_APPS | sed 's/\([^ ]*\) */\1.gdb /g'`
  cp $CP_OPTIONS $GDB_FILES $OUTPUT_DIR_GDB
  tar -czf $OUTPUT_DIR/$GDBS_FILE_NAME $OUTPUT_DIR_GDB/*.gdb 
fi
