///////////////////////////////////////////////////////////////////////////////
//
// NsnPerformanceMeasuremeent.h
//
// Copyright � 3Way Networks Ltd
//
///////////////////////////////////////////////////////////////////////////////

#ifndef __NsnPerformanceMeasurement_h_
#define __NsnPerformanceMeasurement_h_

///////////////////////////////////////////////////////////////////////////////
// System Includes
///////////////////////////////////////////////////////////////////////////////

#include <string>
#include <map>
#include <boost/any.hpp>
using boost::any_cast;

#include <system/Filename.h>
#include <platform/KpiTypes.h>
#include <system/KpiAggregator.h>

///////////////////////////////////////////////////////////////////////////////
// Local Includes
///////////////////////////////////////////////////////////////////////////////

using namespace std;
//using namespace threeway;

///////////////////////////////////////////////////////////////////////////////
// Classes
///////////////////////////////////////////////////////////////////////////////

namespace tr069
{



class NsnPm : public KpiAggregator
   {
      public:

         typedef enum  NsnPmCounterId_tag
         {

            UNUSED = 0,
#ifdef THREE_G_KPI
            Fap01_NumberOfAttemptedRabEstablishmentsForCsVoicePerFap = 1,
            Fap01_NumberOfAttemptedRabEstablishmentsForCsUdiPerFap = 2,
            Fap01_NumberOfAttemptedRabEstablishmentsForCsStreamingPerFap = 3,
            Fap01_NumberOfAttemptedRabEstablishmentsForPsConversationalPerFap = 4,
            Fap01_NumberOfAttemptedRabEstablishmentsForPsInteractivePerFap = 5,
            Fap01_NumberOfAttemptedRabEstablishmentsForPsBackgroundPerFap = 6,
            Fap01_NumberOfAttemptedRabEstablishmentsForPsStreamingPerFap = 7,

            Fap02_NumberOfSuccessfulRabEstablishmentsForCsVoicePerFap = 8,
            Fap02_NumberOfSuccessfulRabEstablishmentsForCsUdiPerFap = 9,
            Fap02_NumberOfSuccessfulRabEstablishmentsForCsStreamingPerFap = 10,
            Fap02_NumberOfSuccessfulRabEstablishmentsForPsConversationalPerFap = 11,
            Fap02_NumberOfSuccessfulRabEstablishmentsForPsInteractivePerFap = 12,
            Fap02_NumberOfSuccessfulRabEstablishmentsForPsBackgroundPerFap = 13,
            Fap02_NumberOfSuccessfulRabEstablishmentsForPsStreamingPerFap = 14,

            Fap03_NumberOfUnsuccessfulRabEstablishmentsDueToRadioInterfaceFailureForCsTrafficPerFap = 15,
            Fap03_NumberOfUnsuccessfulRabEstablishmentsDueToDadioInterfaceMessageFailureForCsTrafficPerFap = 16,
            Fap03_NumberOfUnsuccessfulRabEstablishmentsDueToRabParameterFailureForCsTrafficPerFap = 17,
            Fap03_NumberOfUnsuccessfulRabEstablishmentsDueToIuTransportConnectionFailureForCsTrafficPerFap = 18,
            Fap03_NumberOfUnsuccessfulRabEstablishmentsDueToNoResourceAvailableForCsTrafficPerFap = 19,
            Fap03_NumberOfUnsuccessfulRabEstablishmentsDueToOtherReasonsForCsTrafficPerFap = 20,
            Fap03_NumberOfUnsuccessfulRabEstablishmentsDueToRadioInterfaceFailureForPsTrafficPerFap = 21,
            Fap03_NumberOfUnsuccessfulRabEstablishmentsDueToDadioInterfaceMessageFailureForPsTrafficPerFap = 22,
            Fap03_NumberOfUnsuccessfulRabEstablishmentsDueToRabParameterFailureForPsTrafficPerFap = 23,
            Fap03_NumberOfUnsuccessfulRabEstablishmentsDueToIuTransportConnectionFailureForPsTrafficPerFap = 24,
            Fap03_NumberOfUnsuccessfulRabEstablishmentsDueToNoResourceAvailableForPsTrafficPerFap = 25,
            Fap03_NumberOfUnsuccessfulRabEstablishmentsDueToRelocationInProgessForPsTrafficPerFap = 26,
            Fap03_NumberOfUnsuccessfulRabEstablishmentsDueToOtherReasonsForPsTrafficPerFap = 27,

            Fap04_NumberOfAttemptedRabReleasesDueToNormalReleaseForCsTrafficPerFap = 28,
            Fap04_NumberOfAttemptedRabReleasesDueToUtranGeneratedReasonForCsTrafficPerFap = 29,
            Fap04_NumberOfAttemptedRabReleasesDueToCnGeneratedReasonForCsTrafficPerFap = 30,
            Fap04_NumberOfAttemptedRabReleasesDueToOtherReasonsForCsTrafficPerFap = 31,
            Fap04_NumberOfAttemptedRabReleasesDueToNormalReleaseForPsTrafficPerFap = 32,
            Fap04_NumberOfAttemptedRabReleasesDueToUtranGeneratedReasonForPsTrafficPerFap = 33,
            Fap04_NumberOfAttemptedRabReleasesDueToCnGeneratedReasonForPsTrafficPerFap = 34,
            Fap04_NumberOfAttemptedRabReleasesDueToOtherReasonsForPsTrafficPerFap = 35,

            Fap05_NumberOfAttemptedIuSignallingConnectionEstablishmentsForCsTrafficPerFap = 36,
            Fap05_NumberOfAttemptedIuSignallingConnectionEstablishmentsForPsTrafficPerFap = 37,

            Fap06_NumberOfSuccessfulIuSignallingConnectionEstablishmentsForCsTrafficPerFap = 38,
            Fap06_NumberOfSuccessfulIuSignallingConnectionEstablishmentsForPsTrafficPerFap = 39,

            Fap07_NumberOfIuReleaseCommandsDueToNormalReleaseForCsTrafficPerFap = 40,
            Fap07_NumberOfIuReleaseCommandsDueToUtranGeneratedReasonForCsTrafficPerFap = 41,
            Fap07_NumberOfIuReleaseCommandsDueToCnGeneratedReasonForCsTrafficPerFap = 42,
            Fap07_NumberOfIuReleaseCommandsDueToOtherReasonsForCsTrafficPerFap = 43,
            Fap07_NumberOfIuReleaseCommandsDueToNormalReleaseForPsTrafficPerFap = 44,
            Fap07_NumberOfIuReleaseCommandsDueToUtranGeneratedReasonForPsTrafficPerFap = 45,
            Fap07_NumberOfIuReleaseCommandsDueToCnGeneratedReasonForPsTrafficPerFap = 46,
            Fap07_NumberOfIuReleaseCommandsDueToOtherReasonsForPsTrafficPerFap = 47,

            Fap08_NumberOfIuReleaseRequestsDueToLostRadioLinkForCsTraffic = 48,
            Fap08_NumberOfIuReleaseRequestsDueToRabPreemptionForCsTraffic = 49,
            Fap08_NumberOfIuReleaseRequestsDueToRadioInterfaceFailureForCsTraffic = 50,
            Fap08_NumberOfIuReleaseRequestsDueToUserInactivityForCsTraffic = 51,
            Fap08_NumberOfIuReleaseRequestsDueToIuUserPlaneFailureForCsTraffic = 52,
            Fap08_NumberOfIuReleaseRequestsDueToUeInitiatedReleaseForCsTraffic = 53,
            Fap08_NumberOfIuReleaseRequestsDueToDirectedRetryForCsTraffic = 54,
            Fap08_NumberOfIuReleaseRequestsDueOamInterventionForCsTraffic = 55,
            Fap08_NumberOfIuReleaseRequestsDueToOtherReasonsForCsTraffic = 56,
            Fap08_NumberOfIuReleaseRequestsDueToLostRadioLinkForPsTraffic = 57,
            Fap08_NumberOfIuReleaseRequestsDueToRabPreemptionForPsTraffic = 58,
            Fap08_NumberOfIuReleaseRequestsDueToRadioInterfaceFailureForPsTraffic = 59,
            Fap08_NumberOfIuReleaseRequestsDueToUserInactivityForPsTraffic = 60,
            Fap08_NumberOfIuReleaseRequestsDueToIuUserPlaneFailureForPsTraffic = 61,
            Fap08_NumberOfIuReleaseRequestsDueToUeInitiatedReleaseForPsTraffic = 62,
            Fap08_NumberOfIuReleaseRequestsDueToDirectedRetryForPsTraffic = 63,
            Fap08_NumberOfIuReleaseRequestsDueOamInterventionForPsTraffic = 64,
            Fap08_NumberOfIuReleaseRequestsDueToOtherReasonsForPsTraffic = 65,

            Fap09_NumberOfAttemptedRbEstablishmentsForR99 = 66,
            Fap09_NumberOfAttemptedRbEstablishmentsForHsdpa = 67,
            Fap09_NumberOfAttemptedRbEstablishmentsForHsupa = 68,

            Fap10_NumberOfSuccessfulRbEstablishmentsForR99 = 69,
            Fap10_NumberOfSuccessfulRbEstablishmentsForHsdpa = 70,
            Fap10_NumberOfSuccessfulRbEstablishmentsForHsupa = 71,

            Fap11_NumberOfUnsuccessfulRbEstablishmentsDueToPhysicalChannelFailureForR99 = 72,
            Fap11_NumberOfUnsuccessfulRbEstablishmentsDueToProtocolErrorForR99 = 73,
            Fap11_NumberOfUnsuccessfulRbEstablishmentsDueToCellUpdateOccurredForR99 = 74,
            Fap11_NumberOfUnsuccessfulRbEstablishmentsDueToConfigurationFailureForR99 = 75,
            Fap11_NumberOfUnsuccessfulRbEstablishmentsDueToNoReplyForR99 = 76,
            Fap11_NumberOfUnsuccessfulRbEstablishmentsDueToOtherCausesForR99 = 77,
            Fap11_NumberOfUnsuccessfulRbEstablishmentsDueToPhysicalChannelFailureForHsdpa = 78,
            Fap11_NumberOfUnsuccessfulRbEstablishmentsDueToProtocolErrorForHsdpa = 79,
            Fap11_NumberOfUnsuccessfulRbEstablishmentsDueToCellUpdateOccurredForHsdpa = 80,
            Fap11_NumberOfUnsuccessfulRbEstablishmentsDueToConfigurationFailureForHsdpa = 81,
            Fap11_NumberOfUnsuccessfulRbEstablishmentsDueToNoReplyForHsdpa = 82,
            Fap11_NumberOfUnsuccessfulRbEstablishmentsDueToOtherCausesForHsdpa = 83,
            Fap11_NumberOfUnsuccessfulRbEstablishmentsDueToPhysicalChannelFailureForHsupa = 84,
            Fap11_NumberOfUnsuccessfulRbEstablishmentsDueToProtocolErrorForHsupa = 85,
            Fap11_NumberOfUnsuccessfulRbEstablishmentsDueToCellUpdateOccurredForHsupa = 86,
            Fap11_NumberOfUnsuccessfulRbEstablishmentsDueToConfigurationFailureForHsupa = 87,
            Fap11_NumberOfUnsuccessfulRbEstablishmentsDueToNoReplyForHsupa = 88,
            Fap11_NumberOfUnsuccessfulRbEstablishmentsDueToOtherCausesForHsupa = 89,

            Fap12_NumberOfReceivedRlcPdusInAmUplink = 90,
            Fap12_NumberOfReceivedRlcPdusInTmUplink = 91,
            Fap12_NumberOfReceivedRlcPdusInUmUplink = 92,
            Fap12_NumberOfTransmittedRlcPdusInAmDownlink = 93,
            Fap12_NumberOfTransmittedRlcPdusInTmDownlink = 94,
            Fap12_NumberOfTransmittedRlcPdusInUmDownlink = 95,

            Fap13_NumberOfMissingOrInvalidRlcPdusUplink = 96,
            Fap13_NumberOfRetransmittedRlcPdusDownlink = 97,

            Fap14_MeanRlcUserDataThroughputInAmUplink = 98,
            Fap14_MeanRlcUserDataThroughputInTmUplink = 99,
            Fap14_MeanRlcUserDataThroughputInUmUplink = 100,
            Fap14_MeanRlcUserDataThroughputInAmDownlink = 101,
            Fap14_MeanRlcUserDataThroughputInTmDownlink = 102,
            Fap14_MeanRlcUserDataThroughputInUmDownlink = 103,

            Fap15_MeanReceivedBlocksInUplinkWithoutCrcErrors = 104,
            Fap15_MeanReceivedBlocksInUplinkWithCrcErrors = 105,

            Fap16_UserDataVolumeOnIuInterfaceUplinkForCs = 106,
            Fap16_UserDataVolumeOnIuInterfaceUplinkForPs = 107,
            Fap16_UserDataVolumeOnIuInterfaceDownlinkForCs = 108,
            Fap16_UserDataVolumeOnIuInterfaceDownlinkForPs = 109,

            Fap17_NumberOfAttemptedRrcConnectionEstablishments = 110,

            Fap18_NumberOfSuccessfulRrcConnectionEstablishments = 111,

            Fap19_NumberOfUnsuccessfulRrcConnectionEstablishmentsDueToCongestion = 112,
            Fap19_NumberOfUnsuccessfulRrcConnectionEstablishmentsDueToUnspecified = 113,
            Fap19_NumberOfUnsuccessfulRrcConnectionEstablishmentsDueToNoReply = 114,
            Fap19_NumberOfUnsuccessfulRrcConnectionEstablishmentsDueToOtherCauses = 115,

            Fap20_NumberOfAttemptedRrcConnectionReestablishments = 116,

            Fap21_NumberOfSuccessfulRrcConnectionReestablishments = 117,

            Fap22_NumberOfUnsuccessfulRrcConnectionReestablishmentsDueToNoReply = 118,
            Fap22_NumberOfUnsuccessfulRrcConnectionReestablishmentsDueToOtherCauses = 119,

            Fap23_NumberOfCellUpdateDueToCellReselection = 120,
            Fap23_NumberOfCellUpdateDueToPeriodicalCellUpdate = 121,
            Fap23_NumberOfCellUpdateDueToUplinkDataTransmission = 122,
            Fap23_NumberOfCellUpdateDueToPagingResponse = 123,
            Fap23_NumberOfCellUpdateDueToReenteredServiceArea = 124,
            Fap23_NumberOfCellUpdateDueToRadioLinkFailure = 125,
            Fap23_NumberOfCellUpdateDueToRlcUnrecoverableError = 126,
            Fap23_NumberOfCellUpdateDueToOtherCauses = 127,

            Fap24_NumberOfAttemptedAccessControlAuthentications = 128,

            Fap25_NumberOfSuccessfulAccessControlAuthentications = 129,

            Fap26_NumberOfUnsuccessfulAccessControlAuthenticationsDueToImsiNotAuthorised = 130,
            Fap26_NumberOfUnsuccessfulAccessControlAuthenticationsDueToUnknownImsi = 131,
            Fap26_NumberOfUnsuccessfulAccessControlAuthenticationsDueToOtherReasonse = 132,

            Fap27_NumberOfAccessControlTriggeredRelocationAttempts = 133,

            Fap28_NumberOfAttemptedAccessControlTriggeredIdentityRequests = 134,

            Fap29_NumberOfSuccessfulAccessControlTriggeredIdentityRequests = 135,

            Fap30_NumberOfAttemptedRelocationPreparationsForOutgoingIntraRatHandovers = 136,
            Fap30_NumberOfAttemptedRelocationPreparationsForOutgoingInterRatHandovers = 137,

            Fap31_NumberOfSuccessfulRelocationPreparationsForOutgoingIntraRatHandovers = 138,
            Fap31_NumberOfSuccessfulRelocationPreparationsForOutgoingInterRatHandovers = 139,

            Fap32_NumberOfUnsuccessfulRelocationPreparationsForOutgoingIntraRatHandoversDueToTrelocAllocExpiry = 140,
            Fap32_NumberOfUnsuccessfulRelocationPreparationsForOutgoingIntraRatHandoversDueToRelocationCancelled = 141,
            Fap32_NumberOfUnsuccessfulRelocationPreparationsForOutgoingIntraRatHandoversDueToRelocationFailure = 142,
            Fap32_NumberOfUnsuccessfulRelocationPreparationsForOutgoingIntraRatHandoversDueToNoReply = 143,
            Fap32_NumberOfUnsuccessfulRelocationPreparationsForOutgoingIntraRatHandoversDueToOterCauses = 144,
            Fap32_NumberOfUnsuccessfulRelocationPreparationsForOutgoingInterRatHandoversDueToTrelocAllocExpiry = 145,
            Fap32_NumberOfUnsuccessfulRelocationPreparationsForOutgoingInterRatHandoversDueToToRelocationCancelled = 146,
            Fap32_NumberOfUnsuccessfulRelocationPreparationsForOutgoingInterRatHandoversDueToRelocationFailure = 147,
            Fap32_NumberOfUnsuccessfulRelocationPreparationsForOutgoingInterRatHandoversDueToNoReply = 148,
            Fap32_NumberOfUnsuccessfulRelocationPreparationsForOutgoingInterRatHandoversDueToOterCauses = 149,

            Fap33_NumberOfAttemptedOutgoingIntraRatHandoversForCs = 150,
            Fap33_NumberOfAttemptedOutgoingIntraRatHandoversForPs = 151,
            Fap33_NumberOfAttemptedOutgoingInterRatHandoversForCs = 152,
            Fap33_NumberOfAttemptedOutgoingInterRatHandoversForPs = 153,

            Fap34_NumberOfSuccessfulOutgoingIntraRatHandoversForCs = 154,
            Fap34_NumberOfSuccessfulOutgoingIntraRatHandoversForPs = 155,
            Fap34_NumberOfSuccessfulOutgoingInterRatHandoversForCs = 156,
            Fap34_NumberOfSuccessfulOutgoingInterRatHandoversForPs = 157,

            Fap35_NumberOfUnsuccessfulOutgoingIntraRatHandoversForCsDueToConfigurationUnacceptable = 158,
            Fap35_NumberOfUnsuccessfulOutgoingIntraRatHandoversForCsDueToPhysicalChannelFailure = 159,
            Fap35_NumberOfUnsuccessfulOutgoingIntraRatHandoversForCsDueToProtocolError = 160,
            Fap35_NumberOfUnsuccessfulOutgoingIntraRatHandoversForCsDueToOtherCauses = 161,
            Fap35_NumberOfUnsuccessfulOutgoingIntraRatHandoversForPsDueToConfigurationUnacceptable = 162,
            Fap35_NumberOfUnsuccessfulOutgoingIntraRatHandoversForPsDueToPhysicalChannelFailure = 163,
            Fap35_NumberOfUnsuccessfulOutgoingIntraRatHandoversForPsDueToProtocolError = 164,
            Fap35_NumberOfUnsuccessfulOutgoingIntraRatHandoversForPsDueToOtherCauses = 165,
            Fap35_NumberOfUnsuccessfulOutgoingInterRatHandoversForCsDueToConfigurationUnacceptable = 166,
            Fap35_NumberOfUnsuccessfulOutgoingInterRatHandoversForCsDueToPhysicalChannelFailure = 167,
            Fap35_NumberOfUnsuccessfulOutgoingInterRatHandoversForCsDueToProtocolError = 168,
            Fap35_NumberOfUnsuccessfulOutgoingInterRatHandoversForCsDueToOtherCauses = 169,
            Fap35_NumberOfUnsuccessfulOutgoingInterRatHandoversForPsDueToConfigurationUnacceptable = 170,
            Fap35_NumberOfUnsuccessfulOutgoingInterRatHandoversForPsDueToPhysicalChannelFailure = 171,
            Fap35_NumberOfUnsuccessfulOutgoingInterRatHandoversForPsDueToProtocolError = 172,
            Fap35_NumberOfUnsuccessfulOutgoingInterRatHandoversForPsDueToOtherCauses = 173,

            Fap36_NumberOfIpReconnectionsDueToFapSwitchedOn = 174,
            Fap36_TotalNumberOfReceivedIpOctets = 175,

            Fap37_TotalNumberOfReceivedIpOctets = 176,
            Fap37_TotalNumberOfTransmittedIpOctets = 177,

            Fap38_IuInterfaceAvailabilityTime = 178,
            Fap38_IuInterfaceOutageTime = 179,

            Fap39_NumberOfScansWhereNoMacroCellWasDetected = 180,
            Fap39_NumberOfScansWhereAtLeastOneMacroCellWasDetected = 181,
#endif
            //Add  new PM counter id for 3G Here
            //LTE PM counter id start from here
            CsfbCdma2000DualRxTxRedir,
            CsfbCdma2000DualRxTxDlnas,
            HOFromeNBFullRecfg,
            RRCConnreestabFullRecfg,
            RRCAttConnEstabEmergency,
            RRCAttConnEstabHiPrioAccess,
            RRCAttConnEstabMtAccess,
            RRCAttConnEstabMoSignal,
            RRCAttConnEstabMoData,
            RRCAttConnEstabDeToAccess, 
            RRCAttConnEstabSum,
            RRCSuccConnEstabEmergency,
            RRCSuccConnEstabHiPrioAccess,
            RRCSuccConnEstabMtAccess,
            RRCSuccConnEstabMoSignal,
            RRCSuccConnEstabMoData,
            RRCSuccConnEstabDeToAccess,
            RRCSuccConnEstabSum,
            RRCFailConnEstabEmergency,
            RRCFailConnEstabHiPrioAccess,
            RRCFailConnEstabMtAccess,
            RRCFailConnEstabMoSignal,
            RRCFailConnEstabMoData,
            RRCFailConnEstabDeToAccess,
            RRCFailConnEstabSum, 	 
            RRCFailConnEstabDegradedRadioEmergency,
            RRCFailConnEstabDegradedRadioHiPrioAccess,
            RRCFailConnEstabDegradedRadioMtAccess,
            RRCFailConnEstabDegradedRadioMoSignal,
            RRCFailConnEstabDegradedRadioMoData,
            RRCFailConnEstabDegradedRadioDeToAccess,
            RRCFailConnEstabDegradedRadioSum,
            RRCConnReEstabAttReconfFail,
            RRCConnReEstabAttHoFail,
            RRCConnReEstabAttOther,
            RRCConnReEstabAttSum,
            RRCConnReEstabSuccReconfFail,
            RRCConnReEstabSuccHoFail,
            RRCConnReEstabSuccOther,
            RRCConnReEstabSuccSum,
            RRCConnReEstabFailReconfFail,
            RRCConnReEstabFailHoFail,
            RRCConnReEstabFailOther,
            RRCConnReEstabFailSum,
            RRCConnMean,
            RRCConnMax,
            RRCConnEstabTimeMeanEmergency,
            RRCConnEstabTimeMeanHighPriorityAccess,
            RRCConnEstabTimeMeanMTAccess,      
            RRCConnEstabTimeMeanMOSignalling,
            RRCConnEstabTimeMeanMOData,     
            RRCConnEstabTimeMeanDelayTolAccess,     
            RRCConnEstabTimeMaxEmergency,
            RRCConnEstabTimeMaxHighPriorityAccess,
            RRCConnEstabTimeMaxMTAcess,
            RRCConnEstabTimeMaxMOSignalling,
            RRCConnEstabTimeMaxMOData,      
            RRCConnEstabTimeMaxDelayTolAccess,      
            UNCNTXRelReqSum,
            UEContextRelSuccNbr,
            ERABEstabInitAttNbrQCI1,
            ERABEstabInitAttNbrQCI2,
            ERABEstabInitAttNbrQCI3,
            ERABEstabInitAttNbrQCI4,
            ERABEstabInitAttNbrQCI5,
            ERABEstabInitAttNbrQCI6,
            ERABEstabInitAttNbrQCI7,
            ERABEstabInitAttNbrQCI8,
            ERABEstabInitAttNbrQCI9,
            ERABEstabInitAttNbrQCISum,
            ERABEstabInitSuccNbrQCI1,
            ERABEstabInitSuccNbrQCI2,
            ERABEstabInitSuccNbrQCI3,
            ERABEstabInitSuccNbrQCI4,
            ERABEstabInitSuccNbrQCI5,
            ERABEstabInitSuccNbrQCI6,
            ERABEstabInitSuccNbrQCI7,
            ERABEstabInitSuccNbrQCI8,
            ERABEstabInitSuccNbrQCI9,
            ERABEstabInitSuccNbrQCISum,
            ERABEstabInitFailNbrSum,
            ERABEstabAttrNbrQCI1,
            ERABEstabAttrNbrQCI2,
            ERABEstabAttrNbrQCI3,
            ERABEstabAttrNbrQCI4,
            ERABEstabAttrNbrQCI5,
            ERABEstabAttrNbrQCI6,
            ERABEstabAttrNbrQCI7,
            ERABEstabAttrNbrQCI8,
            ERABEstabAttrNbrQCI9,
            ERABEstabAttrNbrQCISum,
            ERABEstabSuccNbrQCI1,
            ERABEstabSuccNbrQCI2,
            ERABEstabSuccNbrQCI3,
            ERABEstabSuccNbrQCI4,
            ERABEstabSuccNbrQCI5,
            ERABEstabSuccNbrQCI6,
            ERABEstabSuccNbrQCI7,
            ERABEstabSuccNbrQCI8,
            ERABEstabSuccNbrQCI9,
            ERABEstabSuccNbrQCISum,
            ERABEstabFailNbrRadioResourcesNotAvailable,
            ERABEstabFailNbrFailureInRadioInterfaceProcedure,
            ERABEstabFailNbrInvalidQoSCombinations,
            ERABEstabFailNbrMultipleERABIDInstances,
            ERABEstabFailNbrNotSupportedQCIValue, 
            ERABEstabFailNbrS1IntraSystemHandoverTriggered,
            ERABEstabFailNbrS1InterSystemHandoverTriggered,
            ERABEstabFailNbrX2HandoverTriggered,
            ERABEstabFailNbrSum,
            ERABEstabTimeMeanQCI1,
            ERABEstabTimeMeanQCI2,
            ERABEstabTimeMeanQCI3,
            ERABEstabTimeMeanQCI4,
            ERABEstabTimeMeanQCI5,
            ERABEstabTimeMeanQCI6,
            ERABEstabTimeMeanQCI7,
            ERABEstabTimeMeanQCI8,
            ERABEstabTimeMeanQCI9,
            ERABEstabTimeMaxQCI1,
            ERABEstabTimeMaxQCI2,
            ERABEstabTimeMaxQCI3,
            ERABEstabTimeMaxQCI4,
            ERABEstabTimeMaxQCI5,
            ERABEstabTimeMaxQCI6,
            ERABEstabTimeMaxQCI7,
            ERABEstabTimeMaxQCI8,
            ERABEstabTimeMaxQCI9,
            ERABRelEnbNbrQCI1,
            ERABRelEnbNbrQCI2,
            ERABRelEnbNbrQCI3,
            ERABRelEnbNbrQCI4,
            ERABRelEnbNbrQCI5,
            ERABRelEnbNbrQCI6,
            ERABRelEnbNbrQCI7,
            ERABRelEnbNbrQCI8,
            ERABRelEnbNbrQCI9,
            ERABRelEnbNbrQCISum,
            ERABRelEnbNbrRadioResourcesNotAvailable,
            ERABRelEnbNbrReduceLoadInServingCell,
            ERABRelEnbNbrFailureInTheRadioInterfaceProcedure,
            ERABRelEnbNbrReleaseDueToEUTRANGeneratedReasons,
            ERABRelEnbNbrUserInactivity,
            ERABRelEnbNbrRadioConnectionWithUELost,
            ERABRelEnbNbrOAMIntervention,
            ERABRelAttNbrQCI1,
            ERABRelAttNbrQCI2,
            ERABRelAttNbrQCI3,
            ERABRelAttNbrQCI4,
            ERABRelAttNbrQCI5,
            ERABRelAttNbrQCI6,
            ERABRelAttNbrQCI7,
            ERABRelAttNbrQCI8,
            ERABRelAttNbrQCI9,
            ERABRelAttNbrQCISum,
            ERABRelSuccNbrQCI1,
            ERABRelSuccNbrQCI2,
            ERABRelSuccNbrQCI3,
            ERABRelSuccNbrQCI4,
            ERABRelSuccNbrQCI5,
            ERABRelSuccNbrQCI6,
            ERABRelSuccNbrQCI7,
            ERABRelSuccNbrQCI8,
            ERABRelSuccNbrQCI9,
            ERABRelSuccNbrQCISum,
            ERABRelFailNbrUnknownERABId,
            ERABRelFailNbrHOFailureInTargetSystem,
            ERABRelFailNbrUnknownAreAlreadyAllocatedMmeUeS1apId,
            ERABRelFailNbrUnknownAreAlreadyAllocatedeNBUeS1apId,
            ERABRelFailNbrSum,
            ERABRelActNbrQCISum,
            ERABModQoSAttNbrQCI1,
            ERABModQoSAttNbrQCI2,
            ERABModQoSAttNbrQCI3,
            ERABModQoSAttNbrQCI4,
            ERABModQoSAttNbrQCI5,
            ERABModQoSAttNbrQCI6,
            ERABModQoSAttNbrQCI7,
            ERABModQoSAttNbrQCI8,
            ERABModQoSAttNbrQCI9,
            ERABModQoSAttNbrQCISum,
            ERABModQoSSuccNbrQCI1,
            ERABModQoSSuccNbrQCI2,
            ERABModQoSSuccNbrQCI3,
            ERABModQoSSuccNbrQCI4,
            ERABModQoSSuccNbrQCI5,
            ERABModQoSSuccNbrQCI6,
            ERABModQoSSuccNbrQCI7,
            ERABModQoSSuccNbrQCI8,
            ERABModQoSSuccNbrQCI9,
            ERABModQoSSuccNbrQCISum,
            ERABModQoSFailNbrUnknownERABId,
            ERABModQoSFailNbrMultipleERABIdInstances,
            ERABModQoSFailNbrRadioResourcesNotAvailable,
            ERABModQoSFailNbrFailureInTheRadioInterfaceProcedure,
            ERABModQoSFailNbrInvalidQoSCombination,
            ERABModQoSFailNbrSum,
            ERABSessionTimeUE,
            ERABUsageNbrMeanQCISum,
            ERABUsageNbrMaxQCISum,
            HOToeNBAttSum,
            HOToeNBSuccSum,
            HOToeNBFailSum,
            HOFromeNBAttSum,
            HOFromeNBSuccSum,
            HOFromeNBFailSum,
	    HOFromeNBSuccSumAfterReEst,
            HOToUtranAttToUtranCell_Sum,
            HOToUtranSuccToUtranCell_Sum,
            HOToUtranFailToUtranCell_Sum,
            HOToGeranAttToGeranCell_Sum,
            HOToGeranSuccToGeranCell_Sum,
            HOToGeranFailToGeranCell_Sum,
            HOInterEnbOutPrepAtt,
            HOIntraFreqOutAtt,
            HOIntraFreqOutSucc,
            HOInterFreqMeasGapOutAtt,
            HOInterFreqMeasGapOutSucc,
            HOInterFreqNoMeasGapOutAtt,
            HOInterFreqNoMeasGapOutSucc,
            HODrxOutAtt,
            HODrxOutSucc,
            HoNoDrxOutAtt,
            HONoDrxOutSucc,
            DRBPdcpSduBitrateDlQCI1,
            DRBPdcpSduBitrateDlQCI2,
            DRBPdcpSduBitrateDlQCI3,
            DRBPdcpSduBitrateDlQCI4,
            DRBPdcpSduBitrateDlQCI5,
            DRBPdcpSduBitrateDlQCI6,
            DRBPdcpSduBitrateDlQCI7,
            DRBPdcpSduBitrateDlQCI8,
            DRBPdcpSduBitrateDlQCI9,
            DRBPdcpSduBitrateDlQCISum,
            DRBPdcpSduBitrateDlMax,
            DRBPdcpSduBitrateUlQCI1,
            DRBPdcpSduBitrateUlQCI2,
            DRBPdcpSduBitrateUlQCI3,
            DRBPdcpSduBitrateUlQCI4,
            DRBPdcpSduBitrateUlQCI5,
            DRBPdcpSduBitrateUlQCI6,
            DRBPdcpSduBitrateUlQCI7,
            DRBPdcpSduBitrateUlQCI8,
            DRBPdcpSduBitrateUlQCI9,
            DRBPdcpSduBitrateUlQCISum,
            DRBPdcpSduBitrateUlMax,
            SRBPdcpSduBitrateDl,
            SRBPdcpSduBitrateUl,
            DRBPdcpSduDelayDlQCI1,
            DRBPdcpSduDelayDlQCI2,
            DRBPdcpSduDelayDlQCI3,
            DRBPdcpSduDelayDlQCI4,
            DRBPdcpSduDelayDlQCI5,
            DRBPdcpSduDelayDlQCI6,
            DRBPdcpSduDelayDlQCI7,
            DRBPdcpSduDelayDlQCI8,
            DRBPdcpSduDelayDlQCI9,
            DRBPdcpSduDelayDlQCISum,
            DRBPdcpSduDropRateDlQCI1,
            DRBPdcpSduDropRateDlQCI2,
            DRBPdcpSduDropRateDlQCI3,
            DRBPdcpSduDropRateDlQCI4,
            DRBPdcpSduDropRateDlQCI5,
            DRBPdcpSduDropRateDlQCI6,
            DRBPdcpSduDropRateDlQCI7,
            DRBPdcpSduDropRateDlQCI8,
            DRBPdcpSduDropRateDlQCI9,
            DRBPdcpSduDropRateDlQCISum,
            DRBPdcpSduAirLossRateDlQCI1,
            DRBPdcpSduAirLossRateDlQCI2,
            DRBPdcpSduAirLossRateDlQCI3,
            DRBPdcpSduAirLossRateDlQCI4,
            DRBPdcpSduAirLossRateDlQCI5,
            DRBPdcpSduAirLossRateDlQCI6,
            DRBPdcpSduAirLossRateDlQCI7,
            DRBPdcpSduAirLossRateDlQCI8,
            DRBPdcpSduAirLossRateDlQCI9,
            DRBPdcpSduAirLossRateDlQCISum,
            DRBPdcpSduLossRateUlQCI1,
            DRBPdcpSduLossRateUlQCI2,
            DRBPdcpSduLossRateUlQCI3,
            DRBPdcpSduLossRateUlQCI4,
            DRBPdcpSduLossRateUlQCI5,
            DRBPdcpSduLossRateUlQCI6,
            DRBPdcpSduLossRateUlQCI7,
            DRBPdcpSduLossRateUlQCI8,
            DRBPdcpSduLossRateUlQCI9,
            DRBPdcpSduLossRateUlQCISum,
            DRBIPThpDlQCI1,
            DRBIPThpDlQCI2,
            DRBIPThpDlQCI3,
            DRBIPThpDlQCI4,
            DRBIPThpDlQCI5,
            DRBIPThpDlQCI6,
            DRBIPThpDlQCI7,
            DRBIPThpDlQCI8,
            DRBIPThpDlQCI9,
            DRBIPThpUlQCI1,
            DRBIPThpUlQCI2,
            DRBIPThpUlQCI3,
            DRBIPThpUlQCI4,
            DRBIPThpUlQCI5,
            DRBIPThpUlQCI6,
            DRBIPThpUlQCI7,
            DRBIPThpUlQCI8,
            DRBIPThpUlQCI9,
            RRUPrbDlQCI1,
            RRUPrbDlQCI2,
            RRUPrbDlQCI3,
            RRUPrbDlQCI4,
            RRUPrbDlQCI5,
            RRUPrbDlQCI6,
            RRUPrbDlQCI7,
            RRUPrbDlQCI8,
            RRUPrbDlQCI9,	
            RRUPrbDlQCISum,
            RRUPrbTotDl,
            RRUPrbUlQCI1,
            RRUPrbUlQCI2,
            RRUPrbUlQCI3,
            RRUPrbUlQCI4,
            RRUPrbUlQCI5,
            RRUPrbUlQCI6,
            RRUPrbUlQCI7,
            RRUPrbUlQCI8,
            RRUPrbUlQCI9,
            RRUPrbUlQCISum,
            RRUPrbTotUl,
            RRURachPreambleDedMean,
            RRURachPreambleAMean,
            RRURachPreambleBMean,
            L2AvgCpuUsageCore0,     
            L2AvgCpuUsageCore1,     
            L2AvgCpuUsageCore2,     
            L2AvgCpuUsageCore3,     
            L2AvgCpuUsageCore4,     
            L2AvgCpuUsageCore5,     
            L2AvgCpuUsageCore6,     
            L2AvgCpuUsageCore7,     
            L2AvgCpuUsageCore8,     
            L2AvgCpuUsageCore9,     
            L2MaxCpuUsageCore0,     
            L2MaxCpuUsageCore1,     
            L2MaxCpuUsageCore2,     
            L2MaxCpuUsageCore3,     
            L2MaxCpuUsageCore4,     
            L2MaxCpuUsageCore5,     
            L2MaxCpuUsageCore6,     
            L2MaxCpuUsageCore7,     
            L2MaxCpuUsageCore8,     
            L2MaxCpuUsageCore9,     
      CPUHSsiReg0Pool0Size,     
      CPUHSsiReg0Pool0ToTalAvailable,
      CPUHSsiReg0Pool0CrntUsed,
      CPUHSsiReg0Pool0MaxUsed,
      CPUHSsiReg0Pool1Size,     
      CPUHSsiReg0Pool1ToTalAvailable,
      CPUHSsiReg0Pool1CrntUsed,
      CPUHSsiReg0Pool1MaxUsed,
      CPUHSsiReg0Pool2Size,     
      CPUHSsiReg0Pool2ToTalAvailable,
      CPUHSsiReg0Pool2CrntUsed,
      CPUHSsiReg0Pool2MaxUsed,
      CPUHSsiReg0Pool3Size,     
      CPUHSsiReg0Pool3ToTalAvailable,
      CPUHSsiReg0Pool3CrntUsed,
      CPUHSsiReg0Pool3MaxUsed,
      CPUHSsiReg0Pool4Size,     
      CPUHSsiReg0Pool4ToTalAvailable,
      CPUHSsiReg0Pool4CrntUsed,
      CPUHSsiReg0Pool4MaxUsed,
      CPUHSsiReg0Pool5Size,     
      CPUHSsiReg0Pool5ToTalAvailable,
      CPUHSsiReg0Pool5CrntUsed,
      CPUHSsiReg0Pool5MaxUsed,
      CPUHSsiReg1Pool0Size,     
      CPUHSsiReg1Pool0ToTalAvailable,
      CPUHSsiReg1Pool0CrntUsed,
      CPUHSsiReg1Pool0MaxUsed,
      CPUHSsiReg1Pool1Size,     
      CPUHSsiReg1Pool1ToTalAvailable,
      CPUHSsiReg1Pool1CrntUsed,
      CPUHSsiReg1Pool1MaxUsed,
      CPUHSsiReg1Pool2Size,     
      CPUHSsiReg1Pool2ToTalAvailable,
      CPUHSsiReg1Pool2CrntUsed,
      CPUHSsiReg1Pool2MaxUsed,
      CPUHSsiReg1Pool3Size,     
      CPUHSsiReg1Pool3ToTalAvailable,
      CPUHSsiReg1Pool3CrntUsed,
      CPUHSsiReg1Pool3MaxUsed,
      CPUHSsiReg1Pool4Size,     
      CPUHSsiReg1Pool4ToTalAvailable,
      CPUHSsiReg1Pool4CrntUsed,
      CPUHSsiReg1Pool4MaxUsed,
      CPUHSsiReg1Pool5Size,     
      CPUHSsiReg1Pool5ToTalAvailable,
      CPUHSsiReg1Pool5CrntUsed,
      CPUHSsiReg1Pool5MaxUsed,
      CPUHSsiReg2Pool0Size,     
      CPUHSsiReg2Pool0ToTalAvailable,
      CPUHSsiReg2Pool0CrntUsed,
      CPUHSsiReg2Pool0MaxUsed,
      CPUHSsiReg2Pool1Size,     
      CPUHSsiReg2Pool1ToTalAvailable,
      CPUHSsiReg2Pool1CrntUsed,
      CPUHSsiReg2Pool1MaxUsed,
      CPUHSsiReg2Pool2Size,     
      CPUHSsiReg2Pool2ToTalAvailable,
      CPUHSsiReg2Pool2CrntUsed,
      CPUHSsiReg2Pool2MaxUsed,
      CPUHSsiReg2Pool3Size,     
      CPUHSsiReg2Pool3ToTalAvailable,
      CPUHSsiReg2Pool3CrntUsed,
      CPUHSsiReg2Pool3MaxUsed,
      CPUHSsiReg2Pool4Size,     
      CPUHSsiReg2Pool4ToTalAvailable,
      CPUHSsiReg2Pool4CrntUsed,
      CPUHSsiReg2Pool4MaxUsed,
      CPUHSsiReg2Pool5Size,     
      CPUHSsiReg2Pool5ToTalAvailable,
      CPUHSsiReg2Pool5CrntUsed,
      CPUHSsiReg2Pool5MaxUsed,
      CPUHSsiReg3Pool0Size,     
      CPUHSsiReg3Pool0ToTalAvailable,
      CPUHSsiReg3Pool0CrntUsed,
      CPUHSsiReg3Pool0MaxUsed,
      CPUHSsiReg3Pool1Size,     
      CPUHSsiReg3Pool1ToTalAvailable,
      CPUHSsiReg3Pool1CrntUsed,
      CPUHSsiReg3Pool1MaxUsed,
      CPUHSsiReg3Pool2Size,     
      CPUHSsiReg3Pool2ToTalAvailable,
      CPUHSsiReg3Pool2CrntUsed,
      CPUHSsiReg3Pool2MaxUsed,
      CPUHSsiReg3Pool3Size,     
      CPUHSsiReg3Pool3ToTalAvailable,
      CPUHSsiReg3Pool3CrntUsed,
      CPUHSsiReg3Pool3MaxUsed,
      CPUHSsiReg3Pool4Size,     
      CPUHSsiReg3Pool4ToTalAvailable,
      CPUHSsiReg3Pool4CrntUsed,
      CPUHSsiReg3Pool4MaxUsed,
      CPUHSsiReg3Pool5Size,     
      CPUHSsiReg3Pool5ToTalAvailable,
      CPUHSsiReg3Pool5CrntUsed,
      CPUHSsiReg3Pool5MaxUsed,
      CPUHSsiReg4Pool0Size,     
      CPUHSsiReg4Pool0ToTalAvailable,
      CPUHSsiReg4Pool0CrntUsed,
      CPUHSsiReg4Pool0MaxUsed,
      CPUHSsiReg4Pool1Size,     
      CPUHSsiReg4Pool1ToTalAvailable,
      CPUHSsiReg4Pool1CrntUsed,
      CPUHSsiReg4Pool1MaxUsed,
      CPUHSsiReg4Pool2Size,     
      CPUHSsiReg4Pool2ToTalAvailable,
      CPUHSsiReg4Pool2CrntUsed,
      CPUHSsiReg4Pool2MaxUsed,
      CPUHSsiReg4Pool3Size,     
      CPUHSsiReg4Pool3ToTalAvailable,
      CPUHSsiReg4Pool3CrntUsed,
      CPUHSsiReg4Pool3MaxUsed,
      CPUHSsiReg4Pool4Size,     
      CPUHSsiReg4Pool4ToTalAvailable,
      CPUHSsiReg4Pool4CrntUsed,
      CPUHSsiReg4Pool4MaxUsed,
      CPUHSsiReg4Pool5Size,     
      CPUHSsiReg4Pool5ToTalAvailable,
      CPUHSsiReg4Pool5CrntUsed,
      CPUHSsiReg4Pool5MaxUsed,
      CPUHSsiReg5Pool0Size,     
      CPUHSsiReg5Pool0ToTalAvailable,
      CPUHSsiReg5Pool0CrntUsed,
      CPUHSsiReg5Pool0MaxUsed,
      CPUHSsiReg5Pool1Size,     
      CPUHSsiReg5Pool1ToTalAvailable,
      CPUHSsiReg5Pool1CrntUsed,
      CPUHSsiReg5Pool1MaxUsed,
      CPUHSsiReg5Pool2Size,     
      CPUHSsiReg5Pool2ToTalAvailable,
      CPUHSsiReg5Pool2CrntUsed,
      CPUHSsiReg5Pool2MaxUsed,
      CPUHSsiReg5Pool3Size,     
      CPUHSsiReg5Pool3ToTalAvailable,
      CPUHSsiReg5Pool3CrntUsed,
      CPUHSsiReg5Pool3MaxUsed,
      CPUHSsiReg5Pool4Size,     
      CPUHSsiReg5Pool4ToTalAvailable,
      CPUHSsiReg5Pool4CrntUsed,
      CPUHSsiReg5Pool4MaxUsed,
      CPUHSsiReg5Pool5Size,     
      CPUHSsiReg5Pool5ToTalAvailable,
      CPUHSsiReg5Pool5CrntUsed,
      CPUHSsiReg5Pool5MaxUsed,          
      CPUHSharedRegPool0Size,     
      CPUHSharedRegPool0ToTalAvailable,
      CPUHSharedRegPool0CrntUsed,
      CPUHSharedRegPool0MaxUsed,
      CPUHSharedRegPool1Size,     
      CPUHSharedRegPool1ToTalAvailable,
      CPUHSharedRegPool1CrntUsed,
      CPUHSharedRegPool1MaxUsed,
      CPUHSharedRegPool2Size,     
      CPUHSharedRegPool2ToTalAvailable,
      CPUHSharedRegPool2CrntUsed,
      CPUHSharedRegPool2MaxUsed,
      CPUHSharedRegPool3Size,     
      CPUHSharedRegPool3ToTalAvailable,
      CPUHSharedRegPool3CrntUsed,
      CPUHSharedRegPool3MaxUsed,
      CPUHSharedRegPool4Size,     
      CPUHSharedRegPool4ToTalAvailable,
      CPUHSharedRegPool4CrntUsed,
      CPUHSharedRegPool4MaxUsed,
      CPUHSharedRegPool5Size,     
      CPUHSharedRegPool5ToTalAvailable,
      CPUHSharedRegPool5CrntUsed,
      CPUHSharedRegPool5MaxUsed,
      CPULSsiReg0Pool0Size,     
      CPULSsiReg0Pool0ToTalAvailable,
      CPULSsiReg0Pool0CrntUsed,
      CPULSsiReg0Pool0MaxUsed,
      CPULSsiReg0Pool1Size,     
      CPULSsiReg0Pool1ToTalAvailable,
      CPULSsiReg0Pool1CrntUsed,
      CPULSsiReg0Pool1MaxUsed,
      CPULSsiReg0Pool2Size,     
      CPULSsiReg0Pool2ToTalAvailable,
      CPULSsiReg0Pool2CrntUsed,
      CPULSsiReg0Pool2MaxUsed,
      CPULSsiReg0Pool3Size,     
      CPULSsiReg0Pool3ToTalAvailable,
      CPULSsiReg0Pool3CrntUsed,
      CPULSsiReg0Pool3MaxUsed,
      CPULSsiReg0Pool4Size,     
      CPULSsiReg0Pool4ToTalAvailable,
      CPULSsiReg0Pool4CrntUsed,
      CPULSsiReg0Pool4MaxUsed,
      CPULSsiReg0Pool5Size,     
      CPULSsiReg0Pool5ToTalAvailable,
      CPULSsiReg0Pool5CrntUsed,
      CPULSsiReg0Pool5MaxUsed,
      CPULSsiReg1Pool0Size,     
      CPULSsiReg1Pool0ToTalAvailable,
      CPULSsiReg1Pool0CrntUsed,
      CPULSsiReg1Pool0MaxUsed,
      CPULSsiReg1Pool1Size,     
      CPULSsiReg1Pool1ToTalAvailable,
      CPULSsiReg1Pool1CrntUsed,
      CPULSsiReg1Pool1MaxUsed,
      CPULSsiReg1Pool2Size,     
      CPULSsiReg1Pool2ToTalAvailable,
      CPULSsiReg1Pool2CrntUsed,
      CPULSsiReg1Pool2MaxUsed,
      CPULSsiReg1Pool3Size,     
      CPULSsiReg1Pool3ToTalAvailable,
      CPULSsiReg1Pool3CrntUsed,
      CPULSsiReg1Pool3MaxUsed,
      CPULSsiReg1Pool4Size,     
      CPULSsiReg1Pool4ToTalAvailable,
      CPULSsiReg1Pool4CrntUsed,
      CPULSsiReg1Pool4MaxUsed,
      CPULSsiReg1Pool5Size,     
      CPULSsiReg1Pool5ToTalAvailable,
      CPULSsiReg1Pool5CrntUsed,
      CPULSsiReg1Pool5MaxUsed,
      CPULSsiReg2Pool0Size,     
      CPULSsiReg2Pool0ToTalAvailable,
      CPULSsiReg2Pool0CrntUsed,
      CPULSsiReg2Pool0MaxUsed,
      CPULSsiReg2Pool1Size,     
      CPULSsiReg2Pool1ToTalAvailable,
      CPULSsiReg2Pool1CrntUsed,
      CPULSsiReg2Pool1MaxUsed,
      CPULSsiReg2Pool2Size,     
      CPULSsiReg2Pool2ToTalAvailable,
      CPULSsiReg2Pool2CrntUsed,
      CPULSsiReg2Pool2MaxUsed,
      CPULSsiReg2Pool3Size,     
      CPULSsiReg2Pool3ToTalAvailable,
      CPULSsiReg2Pool3CrntUsed,
      CPULSsiReg2Pool3MaxUsed,
      CPULSsiReg2Pool4Size,     
      CPULSsiReg2Pool4ToTalAvailable,
      CPULSsiReg2Pool4CrntUsed,
      CPULSsiReg2Pool4MaxUsed,
      CPULSsiReg2Pool5Size,     
      CPULSsiReg2Pool5ToTalAvailable,
      CPULSsiReg2Pool5CrntUsed,
      CPULSsiReg2Pool5MaxUsed,
      CPULSsiReg3Pool0Size,     
      CPULSsiReg3Pool0ToTalAvailable,
      CPULSsiReg3Pool0CrntUsed,
      CPULSsiReg3Pool0MaxUsed,
      CPULSsiReg3Pool1Size,     
      CPULSsiReg3Pool1ToTalAvailable,
      CPULSsiReg3Pool1CrntUsed,
      CPULSsiReg3Pool1MaxUsed,
      CPULSsiReg3Pool2Size,     
      CPULSsiReg3Pool2ToTalAvailable,
      CPULSsiReg3Pool2CrntUsed,
      CPULSsiReg3Pool2MaxUsed,
      CPULSsiReg3Pool3Size,     
      CPULSsiReg3Pool3ToTalAvailable,
      CPULSsiReg3Pool3CrntUsed,
      CPULSsiReg3Pool3MaxUsed,
      CPULSsiReg3Pool4Size,     
      CPULSsiReg3Pool4ToTalAvailable,
      CPULSsiReg3Pool4CrntUsed,
      CPULSsiReg3Pool4MaxUsed,
      CPULSsiReg3Pool5Size,     
      CPULSsiReg3Pool5ToTalAvailable,
      CPULSsiReg3Pool5CrntUsed,
      CPULSsiReg3Pool5MaxUsed,
      CPULSsiReg4Pool0Size,     
      CPULSsiReg4Pool0ToTalAvailable,
      CPULSsiReg4Pool0CrntUsed,
      CPULSsiReg4Pool0MaxUsed,
      CPULSsiReg4Pool1Size,     
      CPULSsiReg4Pool1ToTalAvailable,
      CPULSsiReg4Pool1CrntUsed,
      CPULSsiReg4Pool1MaxUsed,
      CPULSsiReg4Pool2Size,     
      CPULSsiReg4Pool2ToTalAvailable,
      CPULSsiReg4Pool2CrntUsed,
      CPULSsiReg4Pool2MaxUsed,
      CPULSsiReg4Pool3Size,     
      CPULSsiReg4Pool3ToTalAvailable,
      CPULSsiReg4Pool3CrntUsed,
      CPULSsiReg4Pool3MaxUsed,
      CPULSsiReg4Pool4Size,     
      CPULSsiReg4Pool4ToTalAvailable,
      CPULSsiReg4Pool4CrntUsed,
      CPULSsiReg4Pool4MaxUsed,
      CPULSsiReg4Pool5Size,     
      CPULSsiReg4Pool5ToTalAvailable,
      CPULSsiReg4Pool5CrntUsed,
      CPULSsiReg4Pool5MaxUsed,
      CPULSsiReg5Pool0Size,     
      CPULSsiReg5Pool0ToTalAvailable,
      CPULSsiReg5Pool0CrntUsed,
      CPULSsiReg5Pool0MaxUsed,
      CPULSsiReg5Pool1Size,     
      CPULSsiReg5Pool1ToTalAvailable,
      CPULSsiReg5Pool1CrntUsed,
      CPULSsiReg5Pool1MaxUsed,
      CPULSsiReg5Pool2Size,     
      CPULSsiReg5Pool2ToTalAvailable,
      CPULSsiReg5Pool2CrntUsed,
      CPULSsiReg5Pool2MaxUsed,
      CPULSsiReg5Pool3Size,     
      CPULSsiReg5Pool3ToTalAvailable,
      CPULSsiReg5Pool3CrntUsed,
      CPULSsiReg5Pool3MaxUsed,
      CPULSsiReg5Pool4Size,     
      CPULSsiReg5Pool4ToTalAvailable,
      CPULSsiReg5Pool4CrntUsed,
      CPULSsiReg5Pool4MaxUsed,
      CPULSsiReg5Pool5Size,     
      CPULSsiReg5Pool5ToTalAvailable,
      CPULSsiReg5Pool5CrntUsed,
      CPULSsiReg5Pool5MaxUsed,
      CPULSharedRegPool0Size,     
      CPULSharedRegPool0ToTalAvailable,
      CPULSharedRegPool0CrntUsed,
      CPULSharedRegPool0MaxUsed,
      CPULSharedRegPool1Size,     
      CPULSharedRegPool1ToTalAvailable,
      CPULSharedRegPool1CrntUsed,
      CPULSharedRegPool1MaxUsed,
      CPULSharedRegPool2Size,     
      CPULSharedRegPool2ToTalAvailable,
      CPULSharedRegPool2CrntUsed,
      CPULSharedRegPool2MaxUsed,
      CPULSharedRegPool3Size,     
      CPULSharedRegPool3ToTalAvailable,
      CPULSharedRegPool3CrntUsed,
      CPULSharedRegPool3MaxUsed,
      CPULSharedRegPool4Size,     
      CPULSharedRegPool4ToTalAvailable,
      CPULSharedRegPool4CrntUsed,
      CPULSharedRegPool4MaxUsed,
      CPULSharedRegPool5Size,     
      CPULSharedRegPool5ToTalAvailable,
      CPULSharedRegPool5CrntUsed,
      CPULSharedRegPool5MaxUsed,
             L3AvgCpuUsageCore0,     
            L3AvgCpuUsageCore1,     
            L3AvgCpuUsageCore2,     
            L3AvgCpuUsageCore3,     
            L3AvgCpuUsageCore4,     
            L3AvgCpuUsageCore5,     
            L3AvgCpuUsageCore6,     
            L3AvgCpuUsageCore7,     
            L3AvgCpuUsageCore8,     
            L3AvgCpuUsageCore9,     
            L3MaxCpuUsageCore0,     
            L3MaxCpuUsageCore1,     
            L3MaxCpuUsageCore2,     
            L3MaxCpuUsageCore3,     
            L3MaxCpuUsageCore4,     
            L3MaxCpuUsageCore5,     
            L3MaxCpuUsageCore6,     
            L3MaxCpuUsageCore7,     
            L3MaxCpuUsageCore8,     
            L3MaxCpuUsageCore9,     
            RRUCellUnavailableTimeManualIntervention,
            RRUCellUnavailableTimeFault,
            RRUCellUnavailableTimeSum,
            S1SIGConnEstabAtt,
            S1SIGConnEstabSucc,
            PAGDiscardedNbr,
            CSGAttInboundMobility,
            CSGSuccInboundMobility,
            CSGFailedInboundMobilitySum,
            CSGUeAttachedMean,
            EQPTMeanProcessorUsageProcessorID,
            EQPTPeakProcessorUsageProcessorID,
            HOInterEnbOutAttHoDesfrRadioReas,
            HOInterEnbOutAttRadNwTMCriHo,
            HOInterEnbOutAttRadNwResOptHo,
            HOInterEnbOutAttRadNwRedLdinServCell,
            HOInterEnbOutSuccHoDesfrRadioReas,
            HOInterEnbOutSucctRadNwTMCriHo,
            HOInterEnbOutSuccRadNwResOptHo,
            HOInterEnbOutSuccRadNwRedLdinServCell,
            HOOutAttTargetHoDesfrRadioReas,
            HOOutAttTargetRadNwTMCriHo,
            HOOutAttTargetRadNwResOptHo,
            HOOutAttTargetRadNwRedLdinServCell,
            HOOutAttTargetSum,
            HOOutSuccTargetHoDesfrRadioReas,
            HOOutSuccTargetRadNwTMCriHo,
            HOOutSuccTargettRadNwResOptHo,
            HOOutSuccTargetRadNwRedLdinServCell,
            HOOutSuccTargetSum,
            TBTotNbrDl,
            TBErrNbrDl,
            TBTotNbrUl,
            TBErrNbrUl,
            DRBUEActiveDlQCI1,
            DRBUEActiveDlQCI2,
            DRBUEActiveDlQCI3,
            DRBUEActiveDlQCI4,
            DRBUEActiveDlQCI5,
            DRBUEActiveDlQCI6,
            DRBUEActiveDlQCI7,
            DRBUEActiveDlQCI8,
            DRBUEActiveDlQCI9,
            DRBUEActiveDlQCISum,
            DRBUEActiveUlQCI1,
            DRBUEActiveUlQCI2,
            DRBUEActiveUlQCI3,
            DRBUEActiveUlQCI4,
            DRBUEActiveUlQCI5,
            DRBUEActiveUlQCI6,
            DRBUEActiveUlQCI7,
            DRBUEActiveUlQCI8,
            DRBUEActiveUlQCI9,
            DRBUEActiveUlQCISum,
            RRCConnEstabFaileNBCauseCongestion,
            RRCConnEstabFaileNBCauseUnspecified,
            CSFBAttSum,
            CSFBSuccSum,
            CSFBFailSum,
            CSFBCdma2000DualrxWithoutRedirSum,
            CSFBCdma2000RedirSum,
            CSFBCDMA2000WithoutPshoSuccSum,
            CSFBCDMA2000WithoutPshoFailSum,
            CSFBCDMA2000WithoutPshoAttSum,
            CSFBCDMA2000WithoutPshoFailRedirSuccSum,
            InterRatUtraAttSum,
            InterRatUtraSuccSum,
            InterRatUtraFailSum,
            InterRatUtraHandOverExeAttCause1,
            InterRatUtraHandOverExeAttCause2,
            InterRatUtraHandOverExeAttCause3,
            InterRatUtraHandOverExeAttCause4,
            InterRatUtraHandOverExeSuccCause1,
            InterRatUtraHandOverExeSuccCause2,
            InterRatUtraHandOverExeSuccCause3,
            InterRatUtraHandOverExeSuccCause4,
            InterRatUtraHandOverExeFailCause1,
            InterRatUtraHandOverExeFailCause2,
            InterRatUtraHandOverExeFailCause3,
            InterRatUtraHandOverExeFailCause4, 	
            InterRatUtraSrvccAttmptSum,
            InterRatUtraSrvccSuccSum,
            InterRatUtraSrvccFailSum,
            InterRatGeranSrvccAttmptSum,
            InterRatGeranSrvccSuccSum,
            InterRatGeranSrvccFailSum,
            CsfbGeranAttmptSum,
            CsfbGeranSuccSum,
            CsfbGeranSuccWithRedir,
            CsfbGeranSuccCCO,
            CsfbGeranFail,
            CsfbIratMobLAI1,
            CsfbIratMobLAI2,
            CsfbIratMobLAI3,
            CsfbIratMobLAI4,
            CsfbIratMobLAI5,
            CsfbIratMobLAI6,
            CsfbIratMobLAI7,
            CsfbIratMobLAI8,
            CsfbIratMobLAI9,
            CsfbIratMobLAI10,
            CsfbIratMobLAI11,
            CsfbIratMobLAI12,
            CsfbIratMobLAI13,
            CsfbIratMobLAI14,
            CsfbIratMobLAI15,
            CsfbIratMobLAI16,
            CsfbIratMobLAI17,
            CsfbIratMobLAI18,
            CsfbIratMobLAI19,
            CsfbIratMobLAI20,
            CsfbIratMobLAI21,
            CsfbIratMobLAI22,
            CsfbIratMobLAI23,
            CsfbIratMobLAI24,
            CsfbIratMobLAI25,
            CsfbIratMobLAI26,
            CsfbIratMobLAI27,
            CsfbIratMobLAI28,
            CsfbIratMobLAI29,
            CsfbIratMobLAI30,
            CsfbIratMobLAI31,
            CsfbIratMobLAI32,
            CsfbIratMobLAIOTH,
            CsfbGeranCCOWithNACC,
            CsfbGeranRedirWithSI,
            CSFBUTRATotalAttempts,
            CSFBUTRASuccessfulAttempts,
            CSFBUTRAFailureAttempts,
            CSFBUTRAWithRedirWithSI,
            CSFBUTRAWithoutRedir,
            LteRimProcedureAttempts,
            LteRimProcedureSuccessfulAttempts,
            LteRimProcedureFailureAttempts,

            // Add new PM counter id for LTE here
               S1apRnUnSpecified,
               S1ApRnTx2RelocoverallExpiry,
               S1apRnSucessFulHandover,
               S1apRnReleaseDueToEutranGeneratedReason,
               S1ApRnHandoverCancelled,
               S1ApRnPartialHandover,
               S1ApRnHoFailureInTargetEpcEnbOrTargetSystem,
               S1ApRnHoTargetNotAllowed,
               S1ApRnTs1RelocverallExpiry,
               S1ApRnTs1RelocprepExpiry,
               S1ApRnCellNotAvailable,
               S1ApRnUnknownTarget,
               S1ApRnNoRadioResourcesAvailableInTargetCell,
               S1ApRnUnknownMmeUeS1apId,
               S1ApRnUnknownEnbUeS1ApId,
               S1ApRnUnknownPairUeS1ApId,
               S1ApRnHandoverDesirableForRadioReason,
               S1ApRnTimeCriticalHandover,
               S1ApRnResourceOptimisationHandover,
               S1ApRnReduceLoadInServingCell,
               S1ApRnUserInactivity,
               S1ApRnRadioConnectionWithUeLost,
               S1ApRnLoadBalancingTauRequired,
               S1ApRnCsFallbackTrigered,
               S1ApRnUeNotAvailableForPsService,
               S1ApRnRadioResourcesNotAvailable,
               S1ApRnFailureInRadioInterfaceProcedure,
               S1ApRnInvalidQosCombination,
               S1ApRnInterratRedirection,
               S1ApRnInteractionWithOtherProcedure,
               S1ApRnUnknownERabId,
               S1ApRnMultipleERabIdInstances,
               S1ApRnEncryptionAndOrIntegrityProtectionAlgosNotSupported,
               S1ApRnS1IntraSystemHandoverTriggered,
               S1ApRnX2HandoverTrigerred,
               S1ApRnRedirectionTowards1XRtt,
               S1ApRnNotSupportedQciValue,
               S1ApRnInvalidCsgId,
               S1ApNasNormalRelease,
               S1ApNasAuthFail,
               S1ApNasDetach,
               S1ApNasUnspecified,
               S1ApNasCsgSubsExp,
               lastNsnPmCounterId
         } NsnPmCounterId;



         NsnPm( shared_ptr<threeway::KpiLogFileMgr> kpiLogFileMgr, u32 kpiReportDuration, u32 m_perodicUploadPhaseAllignInMin, u32 collectionPeriodInSecs );
         ~NsnPm() {}

         u32 CollateResults( bool IsReqAfterReboot );

         void GenerateFile( const Filename & filename );

      private:

         typedef struct PmDescription_tag
         {
            const char * pmName;
            NsnPmCounterId pmId;
            KpiId    kpiId;
         } PmDescription;

         static const PmDescription m_pmList[];
         static const size_t m_pmListLength;
         u32 m_perodicUploadInterval;
         u32 m_perodicUploadPhaseAllignInMin;
         u32 m_collectionPeriodInSecs;
         threeway::TimeWrap m_endOfLastReportDuration;
         threeway::TimeWrap m_startOfLastReportDuration;
   };
}

#endif
