///////////////////////////////////////////////////////////////////////////////
//
// Tr069ParameterValueChange_fsm_interface.h
//
// Autogenerated from Tr069ParameterValueChange.fsm
//
// Fsm Interface Class
//
// Copyright radisys Limited
//
///////////////////////////////////////////////////////////////////////////////

#ifndef __Tr069ParameterValueChange_fsm_interface_h_
#define __Tr069ParameterValueChange_fsm_interface_h_
///////////////////////////////////////////////////////////////////////////////
// System Includes
///////////////////////////////////////////////////////////////////////////////

#include <system/ThreadWithQueue.h>

///////////////////////////////////////////////////////////////////////////////
// Local Includes
///////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////
// Defines
///////////////////////////////////////////////////////////////////////////////

// Definition at end of file
#undef Tr069ParameterValueChangeInterfaceDefinition

namespace tr069
{

/*** WARNING: Code AUTO-GENERATED from Tr069ParameterValueChange.fsm. Do not edit! ***/
class ParameterValueChangeFsmInterface
{
public:
    ParameterValueChangeFsmInterface() {}
    virtual ~ParameterValueChangeFsmInterface() {}
    
    // Actions
    virtual void NewValueChangeTransactionSession(void*) = 0;
    
    // Entry/Exit
    virtual void HmsConnectionEstablishedEntry() = 0;
    virtual void HmsConnectionEstablishedExit() = 0;
    virtual void ActiveNotificationPendingEntry() = 0;
    virtual void ActiveNotificationPendingExit() = 0;
    
    // Guard Conditions
    virtual bool QueryActiveNotifyStillPending(void*) = 0;
    
};
} // -namespace-

// Auto-updating Interface Definition
#define Tr069ParameterValueChangeInterfaceDefinition()  \
    virtual void NewValueChangeTransactionSession(void*); \
    virtual void HmsConnectionEstablishedEntry(); \
    virtual void HmsConnectionEstablishedExit(); \
    virtual void ActiveNotificationPendingEntry(); \
    virtual void ActiveNotificationPendingExit(); \
    virtual bool QueryActiveNotifyStillPending(void*)

#endif // __Tr069ParameterValueChange_fsm_interface_h_

