///////////////////////////////////////////////////////////////////////////////
//
// Tr069AddObject_fsm.h
//
// Autogenerated from Tr069AddObject.fsm
//
// See header file for documentation.
//
// Copyright radisys Limited
//
///////////////////////////////////////////////////////////////////////////////

#ifndef __Tr069AddObject_fsm_h_
#define __Tr069AddObject_fsm_h_
///////////////////////////////////////////////////////////////////////////////
// System Includes
///////////////////////////////////////////////////////////////////////////////

#include <list>
#include <deque>
#include <system/Trace.h>

///////////////////////////////////////////////////////////////////////////////
// Local Includes
///////////////////////////////////////////////////////////////////////////////

#include "Tr069AddObject_fsm_interface.h"

using namespace tr069;

namespace tr069
{

/*** WARNING: Code AUTO-GENERATED from Tr069AddObject.fsm. Do not edit! ***/
class AddObjectFsm
{
public:

    AddObjectFsm(
        AddObjectFsmInterface & interfaceClass,
        bool traceEnabled = false,
        const char * name = "AddObjectFsm"
        );
    virtual ~AddObjectFsm();

    void InjectAddObject(shared_ptr<RpcAddObject> event);
    void InjectMibCreateObjectCnf(shared_ptr<MibCreateObjectCnf> event);
    std::string ToString() const
    {
        std::string returnedString(mName);

        if(mState)
        {
            returnedString += ".";
            returnedString += mState->mName;
        }

        return returnedString;
    }

    void Rename( const std::string & newName)
    {
        if(mFsmTraceEnabled)
        {
        	TRACE_PRINTF("%s.-: Renamed to %s", mName.c_str(), newName.c_str() );
        }
        mName = newName;
    }

    void SetFsmTraceEnable( bool traceEnable = true ) { mFsmTraceEnabled = traceEnable; }

    void TracePoint( const char * s )
    {
        if(mFsmTraceEnabled)
        {
        	TRACE_PRINTF("%s.%u: %s", mName.c_str(), mEventCounter, s );
        }
    }

private:
    typedef enum EventId_tag
    {
        FSM_EVENT_AddObject,
        FSM_EVENT_MibCreateObjectCnf,
        NUMBER_OF_INJECTABLE_EVENTS
    } EventId;

    typedef enum EventType_tag
    {
        FSM_EVENT_TYPE_shared_ptr_LT_RpcAddObject_GT_,
        FSM_EVENT_TYPE_shared_ptr_LT_MibCreateObjectCnf_GT_,
        NUMBER_OF_EVENT_TYPES
    } EventType;

    class FsmEvent
    {
    public:
        FsmEvent( EventType eventType ) :
            mEventType(eventType) {}
        virtual ~FsmEvent(){}

        EventType mEventType;
    };

    class FsmEvent_shared_ptr_LT_RpcAddObject_GT_ : public FsmEvent
    {
    public:
        FsmEvent_shared_ptr_LT_RpcAddObject_GT_( shared_ptr<RpcAddObject> event ) :
            FsmEvent(FSM_EVENT_TYPE_shared_ptr_LT_RpcAddObject_GT_),
            mEvent(event) {}
        ~FsmEvent_shared_ptr_LT_RpcAddObject_GT_() {}
    	shared_ptr<RpcAddObject> mEvent;
    };

    class FsmEvent_shared_ptr_LT_MibCreateObjectCnf_GT_ : public FsmEvent
    {
    public:
        FsmEvent_shared_ptr_LT_MibCreateObjectCnf_GT_( shared_ptr<MibCreateObjectCnf> event ) :
            FsmEvent(FSM_EVENT_TYPE_shared_ptr_LT_MibCreateObjectCnf_GT_),
            mEvent(event) {}
        ~FsmEvent_shared_ptr_LT_MibCreateObjectCnf_GT_() {}
    	shared_ptr<MibCreateObjectCnf> mEvent;
    };

    void Enqueue( EventId eventId, shared_ptr<FsmEvent> fsmEvent );

    class State;
    typedef std::deque< State * > StateHistory;

    class State
    {
    public:
        State(AddObjectFsm & fsm, const char * name ) :
            mFsm(fsm),
            mName(name){}
        virtual ~State(){}

        virtual void Inject( EventId eventId, shared_ptr<FsmEvent> fsmData ) { RSYS_ASSERT_PRINTF(false,"Cannot inject in state %s.", mName.c_str()); }
        virtual bool RunToCompletion() { RSYS_ASSERT_PRINTF(false,"RunToCompletion failure in state %s.", mName.c_str()); return false; };
        virtual bool DeferEvent( EventId ) const { RSYS_ASSERT_PRINTF(false,"Cannot defer in state %s.", mName.c_str()); return false; }

        virtual void Entry()
        {
            RSYS_ASSERT( mFsm.mState == GetSuperstate() );

            UpdateHistoryUponEntry();

            if(mFsm.mFsmTraceEnabled) { TRACE_PRINTF("%s.%u: %s (entry) ", mFsm.mName.c_str(), mFsm.mEventCounter, mName.c_str() ); }

            InterfaceEntryMethod();

            mFsm.mState = this;
        }

        virtual void Exit()
        {
            RSYS_ASSERT( mFsm.mState == this);

            UpdateHistoryUponExit();

            if(mFsm.mFsmTraceEnabled) { TRACE_PRINTF("%s.%u: %s (exit) ", mFsm.mName.c_str(), mFsm.mEventCounter, mName.c_str() ); }

            InterfaceExitMethod();

            mFsm.mState =  GetSuperstate();
        }

        AddObjectFsm& mFsm;
        std::string mName;
        virtual State * GetSuperstate() const { return NULL; }
        virtual void  InterfaceEntryMethod() {}
        virtual void  InterfaceExitMethod() {}
        virtual void  UpdateHistoryUponExit() { mFsm.mCurrentStateTransitionExitsList.push_front( mFsm.mState ); }
        virtual void  UpdateHistoryUponEntry() { mFsm.mCurrentStateTransitionExitsList.clear(); }
    };

    class SimpleState : public State
    {
    public:
        SimpleState(AddObjectFsm & fsm, const char * name) :
            State(fsm, name){}
        virtual ~SimpleState(){}

        void Inject( EventId eventId, shared_ptr<FsmEvent> fsmData );
        virtual bool RunToCompletion() { return true; }

        virtual bool DeferEvent( EventId ) const { return false; }
        virtual void InjectAddObject( shared_ptr<RpcAddObject> eventData) { EventConsumed(FSM_EVENT_AddObject); }
        virtual void InjectMibCreateObjectCnf( shared_ptr<MibCreateObjectCnf> eventData) { EventConsumed(FSM_EVENT_MibCreateObjectCnf); }

    private:
        void EventConsumed( EventId queuedEventId )
        {
            if(mFsm.mFsmTraceEnabled) { TRACE_PRINTF("%s.%u: %s consumed %s", mFsm.mName.c_str(), mFsm.mEventCounter, mName.c_str(), mEventName[queuedEventId] ); }
        }
    };

    class Idle : public SimpleState
    {
    public:
        Idle(AddObjectFsm & fsm) :
            SimpleState(fsm, "Idle") {}
        virtual ~Idle(){}

        void InterfaceEntryMethod( void ) { mFsm.mInterface.IdleEntry();}
        virtual void InjectAddObject( shared_ptr<RpcAddObject> eventData);
    };

    class AddObjectInProgress : public SimpleState
    {
    public:
        AddObjectInProgress(AddObjectFsm & fsm) :
            SimpleState(fsm, "AddObjectInProgress") {}
        virtual ~AddObjectInProgress(){}

        bool DeferEvent( EventId ) const ;
        virtual void InjectMibCreateObjectCnf( shared_ptr<MibCreateObjectCnf> eventData);
    };

    class Superstate : public State
    {
    public:
        Superstate(AddObjectFsm & fsm, const char * name) :
            State(fsm, name)
        { }
        virtual ~Superstate()
        { }
    };

    class SuperstateWithInitialState : public Superstate
    {
    public:
        SuperstateWithInitialState(AddObjectFsm & fsm, const char * name) :
            Superstate(fsm, name) {}
        virtual ~SuperstateWithInitialState() {}

        virtual bool RunToCompletion() = 0;
    };

    class QueuedFsmEvent
    {
    public:
        QueuedFsmEvent( EventId eventId, shared_ptr<FsmEvent> fsmEvent) :
            mId(eventId),
            mFsmEvent(fsmEvent){}
        ~QueuedFsmEvent(){}

        EventId mId;
        shared_ptr<FsmEvent> mFsmEvent;
    };

    AddObjectFsmInterface & mInterface;
    bool mFsmTraceEnabled;
    std::string mName;
    State * mState;
    Idle mIdle;
    AddObjectInProgress mAddObjectInProgress;
    std::list< shared_ptr<QueuedFsmEvent> > mfsmEventQueue;
    bool mFsmInjectInProgress;
    unsigned mEventCounter;
    StateHistory mCurrentStateTransitionExitsList;
    static const char * mEventName[NUMBER_OF_INJECTABLE_EVENTS];

};

} // -namespace-

#endif // __Tr069AddObject_fsm_interface_h_

