///////////////////////////////////////////////////////////////////////////////
//
// Tr069SetParameterValue_fsm.h
//
// Autogenerated from Tr069SetParameterValue.fsm
//
// See header file for documentation.
//
// Copyright radisys Limited
//
///////////////////////////////////////////////////////////////////////////////

#ifndef __Tr069SetParameterValue_fsm_h_
#define __Tr069SetParameterValue_fsm_h_
///////////////////////////////////////////////////////////////////////////////
// System Includes
///////////////////////////////////////////////////////////////////////////////

#include <list>
#include <deque>
#include <system/Trace.h>

///////////////////////////////////////////////////////////////////////////////
// Local Includes
///////////////////////////////////////////////////////////////////////////////

#include "Tr069SetParameterValue_fsm_interface.h"

using namespace tr069;

namespace tr069
{

/*** WARNING: Code AUTO-GENERATED from Tr069SetParameterValue.fsm. Do not edit! ***/
class SpvFsm
{
public:

    SpvFsm(
        SpvFsmInterface & interfaceClass,
        bool traceEnabled = false,
        const char * name = "SpvFsm"
        );
    virtual ~SpvFsm();

    void Entry();

    void InjectSetParameterValueRequest(shared_ptr<RpcSetParameterValue> event);
    void InjectDataModelVerifyConfirm(shared_ptr<DataModelVerifyCnf> event);
    void InjectMibVerifyConfirm(shared_ptr<MibValidateAttributesCnf> event);
    std::string ToString() const
    {
        std::string returnedString(mName);

        if(mState)
        {
            returnedString += ".";
            returnedString += mState->mName;
        }

        return returnedString;
    }

    void SetFsmTraceEnable( bool traceEnable = true ) { mFsmTraceEnabled = traceEnable; }

    void TracePoint( const char * s )
    {
        if(mFsmTraceEnabled)
        {
        	TRACE_PRINTF("%s.%u: %s", mName.c_str(), mEventCounter, s );
        }
    }

private:
    typedef enum EventId_tag
    {
        FSM_EVENT_SetParameterValueRequest,
        FSM_EVENT_DataModelVerifyConfirm,
        FSM_EVENT_MibVerifyConfirm,
        NUMBER_OF_INJECTABLE_EVENTS
    } EventId;

    typedef enum EventType_tag
    {
        FSM_EVENT_TYPE_shared_ptr_LT_RpcSetParameterValue_GT_,
        FSM_EVENT_TYPE_shared_ptr_LT_DataModelVerifyCnf_GT_,
        FSM_EVENT_TYPE_shared_ptr_LT_MibValidateAttributesCnf_GT_,
        FSM_EVENT_TYPE_void_STAR_,
        NUMBER_OF_EVENT_TYPES
    } EventType;

    class FsmEvent
    {
    public:
        FsmEvent( EventType eventType ) :
            mEventType(eventType) {}
        virtual ~FsmEvent(){}

        EventType mEventType;
    };

    class FsmEvent_shared_ptr_LT_RpcSetParameterValue_GT_ : public FsmEvent
    {
    public:
        FsmEvent_shared_ptr_LT_RpcSetParameterValue_GT_( shared_ptr<RpcSetParameterValue> event ) :
            FsmEvent(FSM_EVENT_TYPE_shared_ptr_LT_RpcSetParameterValue_GT_),
            mEvent(event) {}
        ~FsmEvent_shared_ptr_LT_RpcSetParameterValue_GT_() {}
    	shared_ptr<RpcSetParameterValue> mEvent;
    };

    class FsmEvent_shared_ptr_LT_DataModelVerifyCnf_GT_ : public FsmEvent
    {
    public:
        FsmEvent_shared_ptr_LT_DataModelVerifyCnf_GT_( shared_ptr<DataModelVerifyCnf> event ) :
            FsmEvent(FSM_EVENT_TYPE_shared_ptr_LT_DataModelVerifyCnf_GT_),
            mEvent(event) {}
        ~FsmEvent_shared_ptr_LT_DataModelVerifyCnf_GT_() {}
    	shared_ptr<DataModelVerifyCnf> mEvent;
    };

    class FsmEvent_shared_ptr_LT_MibValidateAttributesCnf_GT_ : public FsmEvent
    {
    public:
        FsmEvent_shared_ptr_LT_MibValidateAttributesCnf_GT_( shared_ptr<MibValidateAttributesCnf> event ) :
            FsmEvent(FSM_EVENT_TYPE_shared_ptr_LT_MibValidateAttributesCnf_GT_),
            mEvent(event) {}
        ~FsmEvent_shared_ptr_LT_MibValidateAttributesCnf_GT_() {}
    	shared_ptr<MibValidateAttributesCnf> mEvent;
    };

    class FsmEvent_void_STAR_ : public FsmEvent
    {
    public:
        FsmEvent_void_STAR_( void* event ) :
            FsmEvent(FSM_EVENT_TYPE_void_STAR_),
            mEvent(event) {}
        ~FsmEvent_void_STAR_() {}
    	void* mEvent;
    };

    void Enqueue( EventId eventId, shared_ptr<FsmEvent> fsmEvent );

    class State;
    typedef std::deque< State * > StateHistory;

    class State
    {
    public:
        State(SpvFsm & fsm, const char * name ) :
            mFsm(fsm),
            mName(name){}
        virtual ~State(){}

        virtual void Inject( EventId eventId, shared_ptr<FsmEvent> fsmData ) { RSYS_ASSERT_PRINTF(false,"Cannot inject in state %s.", mName.c_str()); }
        virtual bool RunToCompletion() { RSYS_ASSERT_PRINTF(false,"RunToCompletion failure in state %s.", mName.c_str()); return false; };
        virtual bool DeferEvent( EventId ) const { RSYS_ASSERT_PRINTF(false,"Cannot defer in state %s.", mName.c_str()); return false; }

        virtual void Entry()
        {
            RSYS_ASSERT( mFsm.mState == GetSuperstate() );

            UpdateHistoryUponEntry();

            if(mFsm.mFsmTraceEnabled) { TRACE_PRINTF("%s.%u: %s (entry) ", mFsm.mName.c_str(), mFsm.mEventCounter, mName.c_str() ); }

            InterfaceEntryMethod();

            mFsm.mState = this;
        }

        virtual void Exit()
        {
            RSYS_ASSERT( mFsm.mState == this);

            UpdateHistoryUponExit();

            if(mFsm.mFsmTraceEnabled) { TRACE_PRINTF("%s.%u: %s (exit) ", mFsm.mName.c_str(), mFsm.mEventCounter, mName.c_str() ); }

            InterfaceExitMethod();

            mFsm.mState =  GetSuperstate();
        }

        SpvFsm& mFsm;
        std::string mName;
        virtual State * GetSuperstate() const { return NULL; }
        virtual void  InterfaceEntryMethod() {}
        virtual void  InterfaceExitMethod() {}
        virtual void  UpdateHistoryUponExit() { mFsm.mCurrentStateTransitionExitsList.push_front( mFsm.mState ); }
        virtual void  UpdateHistoryUponEntry() { mFsm.mCurrentStateTransitionExitsList.clear(); }
    };

    class SimpleState : public State
    {
    public:
        SimpleState(SpvFsm & fsm, const char * name) :
            State(fsm, name){}
        virtual ~SimpleState(){}

        void Inject( EventId eventId, shared_ptr<FsmEvent> fsmData );
        virtual bool RunToCompletion() { return true; }

        virtual bool DeferEvent( EventId ) const { return false; }
        virtual void InjectSetParameterValueRequest( shared_ptr<RpcSetParameterValue> eventData) { EventConsumed(FSM_EVENT_SetParameterValueRequest); }
        virtual void InjectDataModelVerifyConfirm( shared_ptr<DataModelVerifyCnf> eventData) { EventConsumed(FSM_EVENT_DataModelVerifyConfirm); }
        virtual void InjectMibVerifyConfirm( shared_ptr<MibValidateAttributesCnf> eventData) { EventConsumed(FSM_EVENT_MibVerifyConfirm); }

    private:
        void EventConsumed( EventId queuedEventId )
        {
            if(mFsm.mFsmTraceEnabled) { TRACE_PRINTF("%s.%u: %s consumed %s", mFsm.mName.c_str(), mFsm.mEventCounter, mName.c_str(), mEventName[queuedEventId] ); }
        }
    };

    class AwaitSet : public SimpleState
    {
    public:
        AwaitSet(SpvFsm & fsm) :
            SimpleState(fsm, "AwaitSet") {}
        virtual ~AwaitSet(){}

        virtual void InjectSetParameterValueRequest( shared_ptr<RpcSetParameterValue> eventData);
    };

    class AwaitDataModelVerifyCnf : public SimpleState
    {
    public:
        AwaitDataModelVerifyCnf(SpvFsm & fsm) :
            SimpleState(fsm, "AwaitDataModelVerifyCnf") {}
        virtual ~AwaitDataModelVerifyCnf(){}

        void InterfaceEntryMethod( void ) { mFsm.mInterface.AwaitDataModelVerifyCnfEntry();}
        void InterfaceExitMethod( void ) {  mFsm.mInterface.AwaitDataModelVerifyCnfExit();}
        bool DeferEvent( EventId ) const ;
        State * GetSuperstate() const { return &mFsm.mSetting; }
        virtual void InjectDataModelVerifyConfirm( shared_ptr<DataModelVerifyCnf> eventData);
    };

    class AwaitMibVerifyCnf : public SimpleState
    {
    public:
        AwaitMibVerifyCnf(SpvFsm & fsm) :
            SimpleState(fsm, "AwaitMibVerifyCnf") {}
        virtual ~AwaitMibVerifyCnf(){}

        void InterfaceEntryMethod( void ) { mFsm.mInterface.AwaitMibVerifyCnfEntry();}
        void InterfaceExitMethod( void ) {  mFsm.mInterface.AwaitMibVerifyCnfExit();}
        bool DeferEvent( EventId ) const ;
        State * GetSuperstate() const { return &mFsm.mSetting; }
        virtual void InjectMibVerifyConfirm( shared_ptr<MibValidateAttributesCnf> eventData);
    };

    class Superstate : public State
    {
    public:
        Superstate(SpvFsm & fsm, const char * name) :
            State(fsm, name)
        { }
        virtual ~Superstate()
        { }
    };

    class SuperstateWithInitialState : public Superstate
    {
    public:
        SuperstateWithInitialState(SpvFsm & fsm, const char * name) :
            Superstate(fsm, name) {}
        virtual ~SuperstateWithInitialState() {}

        virtual bool RunToCompletion() = 0;
    };

    class Setting : public SuperstateWithInitialState
    {
    public:
        Setting(SpvFsm & fsm) :
            SuperstateWithInitialState(fsm, "Setting") {}
        virtual ~Setting(){}

    void InterfaceEntryMethod( void ) { mFsm.mInterface.SettingEntry();}
    void InterfaceExitMethod( void ) { mFsm.mInterface.SettingExit();}

    private:
        bool RunToCompletion( void )
        {
            // Guard condition
            if( mFsm.mInterface.QueryEmptySet())
            {
                mFsm.TracePoint( "QueryEmptySet? (true)" );

                mFsm.mSetSuccess.Entry();
            }
            else
            {
                mFsm.mAwaitDataModelVerifyCnf.Entry();
            }

            return false;
        }
    };

    class ExitPoint : public State
    {
    public:
        ExitPoint(SpvFsm & fsm, const char * name) :
            State(fsm, name) {}
        virtual ~ExitPoint(){}
        virtual void Entry() = 0;
        virtual void Exit()
        {
            RSYS_ASSERT( mFsm.mState == this);

            if(mFsm.mFsmTraceEnabled) { TRACE_PRINTF("%s.%u: %s (exit) ", mFsm.mName.c_str(), mFsm.mEventCounter, mName.c_str() ); }

            mFsm.mState =  GetSuperstate();
        }
        virtual void  UpdateHistoryUponExit() {}
        virtual void  UpdateHistoryUponEntry() {}
    };

    class SetFail : public ExitPoint
    {
    public:
        SetFail(SpvFsm & fsm) :
            ExitPoint(fsm, "SetFail") {}
        virtual ~SetFail(){}

        void Entry(); 

    private:
        State * GetSuperstate() const { return &mFsm.mSetting; }
    };

    class SetSuccess : public ExitPoint
    {
    public:
        SetSuccess(SpvFsm & fsm) :
            ExitPoint(fsm, "SetSuccess") {}
        virtual ~SetSuccess(){}

        void Entry(); 

    private:
        State * GetSuperstate() const { return &mFsm.mSetting; }
    };

    class QueuedFsmEvent
    {
    public:
        QueuedFsmEvent( EventId eventId, shared_ptr<FsmEvent> fsmEvent) :
            mId(eventId),
            mFsmEvent(fsmEvent){}
        ~QueuedFsmEvent(){}

        EventId mId;
        shared_ptr<FsmEvent> mFsmEvent;
    };

    SpvFsmInterface & mInterface;
    bool mFsmTraceEnabled;
    std::string mName;
    State * mState;
    AwaitSet mAwaitSet;
    Setting mSetting;
    SetFail mSetFail;
    SetSuccess mSetSuccess;
    AwaitDataModelVerifyCnf mAwaitDataModelVerifyCnf;
    AwaitMibVerifyCnf mAwaitMibVerifyCnf;
    std::list< shared_ptr<QueuedFsmEvent> > mfsmEventQueue;
    bool mFsmInjectInProgress;
    unsigned mEventCounter;
    StateHistory mCurrentStateTransitionExitsList;
    static const char * mEventName[NUMBER_OF_INJECTABLE_EVENTS];

};

} // -namespace-

#endif // __Tr069SetParameterValue_fsm_interface_h_

