///////////////////////////////////////////////////////////////////////////////
//
// Tr069ParameterValueChange_fsm.h
//
// Autogenerated from Tr069ParameterValueChange.fsm
//
// See header file for documentation.
//
// Copyright radisys Limited
//
///////////////////////////////////////////////////////////////////////////////

#ifndef __Tr069ParameterValueChange_fsm_h_
#define __Tr069ParameterValueChange_fsm_h_
///////////////////////////////////////////////////////////////////////////////
// System Includes
///////////////////////////////////////////////////////////////////////////////

#include <list>
#include <deque>
#include <system/Trace.h>

///////////////////////////////////////////////////////////////////////////////
// Local Includes
///////////////////////////////////////////////////////////////////////////////

#include "Tr069ParameterValueChange_fsm_interface.h"

using namespace tr069;

namespace tr069
{

/*** WARNING: Code AUTO-GENERATED from Tr069ParameterValueChange.fsm. Do not edit! ***/
class ParameterValueChangeFsm
{
public:

    ParameterValueChangeFsm(
        ParameterValueChangeFsmInterface & interfaceClass,
        bool traceEnabled = false,
        const char * name = "ParameterValueChangeFsm"
        );
    virtual ~ParameterValueChangeFsm();

    void Entry();

    void InjectHmsConnection(void* event);
    void InjectHmsDisconnection(void* event);
    void InjectActiveNotify(void* event);
    void InjectTimerExpiry(void* event);
    std::string ToString() const
    {
        std::string returnedString(mName);

        if(mState)
        {
            returnedString += ".";
            returnedString += mState->mName;
        }

        return returnedString;
    }

    void Rename( const std::string & newName)
    {
        if(mFsmTraceEnabled)
        {
        	TRACE_PRINTF("%s.-: Renamed to %s", mName.c_str(), newName.c_str() );
        }
        mName = newName;
    }

    void SetFsmTraceEnable( bool traceEnable = true ) { mFsmTraceEnabled = traceEnable; }

    void TracePoint( const char * s )
    {
        if(mFsmTraceEnabled)
        {
        	TRACE_PRINTF("%s.%u: %s", mName.c_str(), mEventCounter, s );
        }
    }

private:
    typedef enum EventId_tag
    {
        FSM_EVENT_HmsConnection,
        FSM_EVENT_HmsDisconnection,
        FSM_EVENT_ActiveNotify,
        FSM_EVENT_TimerExpiry,
        NUMBER_OF_INJECTABLE_EVENTS
    } EventId;

    typedef enum EventType_tag
    {
        FSM_EVENT_TYPE_void_STAR_,
        NUMBER_OF_EVENT_TYPES
    } EventType;

    class FsmEvent
    {
    public:
        FsmEvent( EventType eventType ) :
            mEventType(eventType) {}
        virtual ~FsmEvent(){}

        EventType mEventType;
    };

    class FsmEvent_void_STAR_ : public FsmEvent
    {
    public:
        FsmEvent_void_STAR_( void* event ) :
            FsmEvent(FSM_EVENT_TYPE_void_STAR_),
            mEvent(event) {}
        ~FsmEvent_void_STAR_() {}
    	void* mEvent;
    };

    void Enqueue( EventId eventId, shared_ptr<FsmEvent> fsmEvent );

    class State;
    typedef std::deque< State * > StateHistory;

    class State
    {
    public:
        State(ParameterValueChangeFsm & fsm, const char * name ) :
            mFsm(fsm),
            mName(name){}
        virtual ~State(){}

        virtual void Inject( EventId eventId, shared_ptr<FsmEvent> fsmData ) { RSYS_ASSERT_PRINTF(false,"Cannot inject in state %s.", mName.c_str()); }
        virtual bool RunToCompletion() { RSYS_ASSERT_PRINTF(false,"RunToCompletion failure in state %s.", mName.c_str()); return false; };
        virtual bool DeferEvent( EventId ) const { RSYS_ASSERT_PRINTF(false,"Cannot defer in state %s.", mName.c_str()); return false; }

        virtual void Entry()
        {
            RSYS_ASSERT( mFsm.mState == GetSuperstate() );

            UpdateHistoryUponEntry();

            if(mFsm.mFsmTraceEnabled) { TRACE_PRINTF("%s.%u: %s (entry) ", mFsm.mName.c_str(), mFsm.mEventCounter, mName.c_str() ); }

            InterfaceEntryMethod();

            mFsm.mState = this;
        }

        virtual void Exit()
        {
            RSYS_ASSERT( mFsm.mState == this);

            UpdateHistoryUponExit();

            if(mFsm.mFsmTraceEnabled) { TRACE_PRINTF("%s.%u: %s (exit) ", mFsm.mName.c_str(), mFsm.mEventCounter, mName.c_str() ); }

            InterfaceExitMethod();

            mFsm.mState =  GetSuperstate();
        }

        ParameterValueChangeFsm& mFsm;
        std::string mName;
        virtual State * GetSuperstate() const { return NULL; }
        virtual void  InterfaceEntryMethod() {}
        virtual void  InterfaceExitMethod() {}
        virtual void  UpdateHistoryUponExit() { mFsm.mCurrentStateTransitionExitsList.push_front( mFsm.mState ); }
        virtual void  UpdateHistoryUponEntry() { mFsm.mCurrentStateTransitionExitsList.clear(); }
    };

    class SimpleState : public State
    {
    public:
        SimpleState(ParameterValueChangeFsm & fsm, const char * name) :
            State(fsm, name){}
        virtual ~SimpleState(){}

        void Inject( EventId eventId, shared_ptr<FsmEvent> fsmData );
        virtual bool RunToCompletion() { return true; }

        virtual bool DeferEvent( EventId ) const { return false; }
        virtual void InjectHmsConnection( void* eventData) { EventConsumed(FSM_EVENT_HmsConnection); }
        virtual void InjectHmsDisconnection( void* eventData) { EventConsumed(FSM_EVENT_HmsDisconnection); }
        virtual void InjectActiveNotify( void* eventData) { EventConsumed(FSM_EVENT_ActiveNotify); }
        virtual void InjectTimerExpiry( void* eventData) { EventConsumed(FSM_EVENT_TimerExpiry); }

    private:
        void EventConsumed( EventId queuedEventId )
        {
            if(mFsm.mFsmTraceEnabled) { TRACE_PRINTF("%s.%u: %s consumed %s", mFsm.mName.c_str(), mFsm.mEventCounter, mName.c_str(), mEventName[queuedEventId] ); }
        }
    };

    class NotConnectedToHms : public SimpleState
    {
    public:
        NotConnectedToHms(ParameterValueChangeFsm & fsm) :
            SimpleState(fsm, "NotConnectedToHms") {}
        virtual ~NotConnectedToHms(){}

        virtual void InjectHmsConnection( void* eventData);
    };

    class Idle : public SimpleState
    {
    public:
        Idle(ParameterValueChangeFsm & fsm) :
            SimpleState(fsm, "Idle") {}
        virtual ~Idle(){}

        State * GetSuperstate() const { return &mFsm.mHmsConnectionEstablished; }
        virtual void InjectHmsDisconnection( void* eventData);
        virtual void InjectActiveNotify( void* eventData);
    };

    class ActiveNotificationPending : public SimpleState
    {
    public:
        ActiveNotificationPending(ParameterValueChangeFsm & fsm) :
            SimpleState(fsm, "ActiveNotificationPending") {}
        virtual ~ActiveNotificationPending(){}

        void InterfaceEntryMethod( void ) { mFsm.mInterface.ActiveNotificationPendingEntry();}
        void InterfaceExitMethod( void ) {  mFsm.mInterface.ActiveNotificationPendingExit();}
        State * GetSuperstate() const { return &mFsm.mHmsConnectionEstablished; }
        virtual void InjectHmsDisconnection( void* eventData);
        virtual void InjectTimerExpiry( void* eventData);
    };

    class Superstate : public State
    {
    public:
        Superstate(ParameterValueChangeFsm & fsm, const char * name) :
            State(fsm, name)
        { }
        virtual ~Superstate()
        { }
    };

    class SuperstateWithInitialState : public Superstate
    {
    public:
        SuperstateWithInitialState(ParameterValueChangeFsm & fsm, const char * name) :
            Superstate(fsm, name) {}
        virtual ~SuperstateWithInitialState() {}

        virtual bool RunToCompletion() = 0;
    };

    class HmsConnectionEstablished : public SuperstateWithInitialState
    {
    public:
        HmsConnectionEstablished(ParameterValueChangeFsm & fsm) :
            SuperstateWithInitialState(fsm, "HmsConnectionEstablished") {}
        virtual ~HmsConnectionEstablished(){}

    void InterfaceEntryMethod( void ) { mFsm.mInterface.HmsConnectionEstablishedEntry();}
    void InterfaceExitMethod( void ) { mFsm.mInterface.HmsConnectionEstablishedExit();}

    private:
        bool RunToCompletion( void )
        {
            {
                mFsm.mIdle.Entry();
            }

            return false;
        }
    };

    class QueuedFsmEvent
    {
    public:
        QueuedFsmEvent( EventId eventId, shared_ptr<FsmEvent> fsmEvent) :
            mId(eventId),
            mFsmEvent(fsmEvent){}
        ~QueuedFsmEvent(){}

        EventId mId;
        shared_ptr<FsmEvent> mFsmEvent;
    };

    ParameterValueChangeFsmInterface & mInterface;
    bool mFsmTraceEnabled;
    std::string mName;
    State * mState;
    NotConnectedToHms mNotConnectedToHms;
    HmsConnectionEstablished mHmsConnectionEstablished;
    Idle mIdle;
    ActiveNotificationPending mActiveNotificationPending;
    std::list< shared_ptr<QueuedFsmEvent> > mfsmEventQueue;
    bool mFsmInjectInProgress;
    unsigned mEventCounter;
    StateHistory mCurrentStateTransitionExitsList;
    static const char * mEventName[NUMBER_OF_INJECTABLE_EVENTS];

};

} // -namespace-

#endif // __Tr069ParameterValueChange_fsm_interface_h_

