///////////////////////////////////////////////////////////////////////////////
//
// Tr069DeleteObject_fsm_interface.h
//
// Autogenerated from Tr069DeleteObject.fsm
//
// Fsm Interface Class
//
// Copyright Radisys Limited
//
///////////////////////////////////////////////////////////////////////////////

#ifndef __Tr069DeleteObject_fsm_interface_h_
#define __Tr069DeleteObject_fsm_interface_h_
///////////////////////////////////////////////////////////////////////////////
// System Includes
///////////////////////////////////////////////////////////////////////////////

#include <system/ThreadWithQueue.h>

///////////////////////////////////////////////////////////////////////////////
// Local Includes
///////////////////////////////////////////////////////////////////////////////

#include "Tr069DeleteObjectTypes.h"

///////////////////////////////////////////////////////////////////////////////
// Defines
///////////////////////////////////////////////////////////////////////////////

// Definition at end of file
#undef Tr069DeleteObjectInterfaceDefinition

namespace tr069
{

/*** WARNING: Code AUTO-GENERATED from Tr069DeleteObject.fsm. Do not edit! ***/
class DeleteObjectFsmActionSendDeleteMibObjectReq
{
public:
    DeleteObjectFsmActionSendDeleteMibObjectReq() {}
    virtual ~DeleteObjectFsmActionSendDeleteMibObjectReq() {}

    typedef enum Outcome_tag
    {
        FSM_ACTION_SUCCESS,
        FSM_ACTION_DELETE_OBJECT_NOT_SUPPORTED,
        FSM_ACTION_MAX_ENTRIES_EXCEEDED,
    } Outcome;

    virtual Outcome SendDeleteMibObjectReq(shared_ptr<RpcDeleteObject>) = 0;
};

/*** WARNING: Code AUTO-GENERATED from Tr069DeleteObject.fsm. Do not edit! ***/
class DeleteObjectFsmInterface :
    public DeleteObjectFsmActionSendDeleteMibObjectReq
{
public:
    DeleteObjectFsmInterface() {}
    virtual ~DeleteObjectFsmInterface() {}
    
    // Actions
    virtual void SendDeleteObjectResponse(shared_ptr<MibDeleteObjectCnf>) = 0;
    
    // Entry/Exit
    virtual void IdleEntry() = 0;
    
    // Guard Conditions
    
};
} // -namespace-

// Auto-updating Interface Definition
#define Tr069DeleteObjectInterfaceDefinition()  \
    virtual DeleteObjectFsmActionSendDeleteMibObjectReq::Outcome SendDeleteMibObjectReq(shared_ptr<RpcDeleteObject>); \
    virtual void SendDeleteObjectResponse(shared_ptr<MibDeleteObjectCnf>); \
    virtual void IdleEntry()

#endif // __Tr069DeleteObject_fsm_interface_h_

