///////////////////////////////////////////////////////////////////////////////
//
// Tr069CwmpConnection_fsm_interface.h
//
// Autogenerated from Tr069CwmpConnection.fsm
//
// Fsm Interface Class
//
// Copyright Radisys Limited
//
///////////////////////////////////////////////////////////////////////////////

#ifndef __Tr069CwmpConnection_fsm_interface_h_
#define __Tr069CwmpConnection_fsm_interface_h_
///////////////////////////////////////////////////////////////////////////////
// System Includes
///////////////////////////////////////////////////////////////////////////////

#include <system/ThreadWithQueue.h>

///////////////////////////////////////////////////////////////////////////////
// Local Includes
///////////////////////////////////////////////////////////////////////////////

#include "Tr069ServerConnectionFsmTypes.h"

///////////////////////////////////////////////////////////////////////////////
// Defines
///////////////////////////////////////////////////////////////////////////////

// Definition at end of file
#undef Tr069CwmpConnectionInterfaceDefinition

namespace tr069
{

/*** WARNING: Code AUTO-GENERATED from Tr069CwmpConnection.fsm. Do not edit! ***/
class CwmpConnectionFsmInterface
{
public:
    CwmpConnectionFsmInterface() {}
    virtual ~CwmpConnectionFsmInterface() {}
    
    // Actions
    virtual void StartInitialTransactionSession(shared_ptr<TransactionSessionCommand>) = 0;
    virtual void StartInitialTransactionSession(void*) = 0;
    virtual void StartDelayTimerForInitialTransactionSession(void*) = 0;
    virtual void RecordTransactionSession(shared_ptr<TransactionSessionCommand>) = 0;
    virtual void RecordTransactionSessionResult(shared_ptr<TransactionSessionComplete>) = 0;
    virtual void SendLocked(shared_ptr<Shutdown>) = 0;
    virtual void SendLocked(shared_ptr<TransactionSessionComplete>) = 0;
    
    // Entry/Exit
    virtual void HmsConnectionProhibitedEntry() = 0;
    virtual void AwaitInitialTransactionSessionEntry() = 0;
    virtual void AwaitInitialTransactionSessionExit() = 0;
    virtual void IdleEntry() = 0;
    virtual void AwaitTransportCnfEntry() = 0;
    virtual void TransactionSessionInProgressEntry() = 0;
    virtual void TransactionSessionInProgressExit() = 0;
    virtual void ShuttingDownWaitingForTransactionSessionCompletionEntry() = 0;
    virtual void TerminateEntry() = 0;
    
    // Guard Conditions
    virtual bool QueryIsTr069Enabled(shared_ptr<HmsModifyReq>) = 0;
    virtual bool QueryIsInitialTransactionSession(shared_ptr<TransactionSessionCommand>) = 0;
    virtual bool QueryFapRebooting(shared_ptr<TransactionSessionComplete>) = 0;
    virtual bool QueryTransportOk(shared_ptr<TransportCnf>) = 0;
    virtual bool QueryIsReconnectSecGw(shared_ptr<HmsModifyReq>) = 0;
    virtual bool QueryStartInitialTransactionSession(shared_ptr<TransactionSessionCommand>) = 0;
    
};
} // -namespace-

// Auto-updating Interface Definition
#define Tr069CwmpConnectionInterfaceDefinition()  \
    virtual void StartInitialTransactionSession(shared_ptr<TransactionSessionCommand>); \
    virtual void StartInitialTransactionSession(void*); \
    virtual void StartDelayTimerForInitialTransactionSession(void*); \
    virtual void RecordTransactionSession(shared_ptr<TransactionSessionCommand>); \
    virtual void RecordTransactionSessionResult(shared_ptr<TransactionSessionComplete>); \
    virtual void SendLocked(shared_ptr<Shutdown>); \
    virtual void SendLocked(shared_ptr<TransactionSessionComplete>); \
    virtual void HmsConnectionProhibitedEntry(); \
    virtual void AwaitInitialTransactionSessionEntry(); \
    virtual void AwaitInitialTransactionSessionExit(); \
    virtual void IdleEntry(); \
    virtual void AwaitTransportCnfEntry(); \
    virtual void TransactionSessionInProgressEntry(); \
    virtual void TransactionSessionInProgressExit(); \
    virtual void ShuttingDownWaitingForTransactionSessionCompletionEntry(); \
    virtual void TerminateEntry(); \
    virtual bool QueryIsTr069Enabled(shared_ptr<HmsModifyReq>); \
    virtual bool QueryIsInitialTransactionSession(shared_ptr<TransactionSessionCommand>); \
    virtual bool QueryFapRebooting(shared_ptr<TransactionSessionComplete>); \
    virtual bool QueryTransportOk(shared_ptr<TransportCnf>); \
    virtual bool QueryIsReconnectSecGw(shared_ptr<HmsModifyReq>); \
    virtual bool QueryStartInitialTransactionSession(shared_ptr<TransactionSessionCommand>)

#endif // __Tr069CwmpConnection_fsm_interface_h_

