///////////////////////////////////////////////////////////////////////////////
//
// Tr069Reboot_fsm_interface.h
//
// Autogenerated from Tr069Reboot.fsm
//
// Fsm Interface Class
//
// Copyright radisys Limited
//
///////////////////////////////////////////////////////////////////////////////

#ifndef __Tr069Reboot_fsm_interface_h_
#define __Tr069Reboot_fsm_interface_h_
///////////////////////////////////////////////////////////////////////////////
// System Includes
///////////////////////////////////////////////////////////////////////////////

#include <system/ThreadWithQueue.h>

///////////////////////////////////////////////////////////////////////////////
// Local Includes
///////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////
// Defines
///////////////////////////////////////////////////////////////////////////////

// Definition at end of file
#undef Tr069RebootInterfaceDefinition

namespace tr069
{

/*** WARNING: Code AUTO-GENERATED from Tr069Reboot.fsm. Do not edit! ***/
class RebootFsmInterface
{
public:
    RebootFsmInterface() {}
    virtual ~RebootFsmInterface() {}
    
    // Actions
    virtual void ImmediateReboot(void*) = 0;
    
    // Entry/Exit
    virtual void RebootingEntry() = 0;
    virtual void DelaySecGwDisconnectEntry() = 0;
    virtual void DelaySecGwDisconnectExit() = 0;
    virtual void SecGwDisconnectEntry() = 0;
    virtual void SecGwDisconnectExit() = 0;
    
    // Guard Conditions
    virtual bool QueryOperational() = 0;
    
};
} // -namespace-

// Auto-updating Interface Definition
#define Tr069RebootInterfaceDefinition()  \
    virtual void ImmediateReboot(void*); \
    virtual void RebootingEntry(); \
    virtual void DelaySecGwDisconnectEntry(); \
    virtual void DelaySecGwDisconnectExit(); \
    virtual void SecGwDisconnectEntry(); \
    virtual void SecGwDisconnectExit(); \
    virtual bool QueryOperational()

#endif // __Tr069Reboot_fsm_interface_h_

