///////////////////////////////////////////////////////////////////////////////
//
//Tr069AddObject_fsm.cpp
//
// Autogenerated from Tr069AddObject.fsm
//
// See header file for documentation.
//
// Copyright radisys Limited
//
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// System Includes
///////////////////////////////////////////////////////////////////////////////

#include <stdio.h>
#include <stdlib.h>
#include <sstream>
#include <iostream>
#include <system/Trace.h>

///////////////////////////////////////////////////////////////////////////////
// Local Includes
///////////////////////////////////////////////////////////////////////////////

#include "Tr069AddObject_fsm.h"

using namespace std;

///////////////////////////////////////////////////////////////////////////////
// Static Data
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Constants
///////////////////////////////////////////////////////////////////////////////

using namespace tr069;

namespace tr069
{

/*** WARNING: Code AUTO-GENERATED from Tr069AddObject.fsm. Do not edit! ***/
AddObjectFsm::AddObjectFsm(
    AddObjectFsmInterface & interfaceClass,
    bool traceEnabled,
    const char * name 
    ) :
    mInterface(interfaceClass),
    mFsmTraceEnabled(traceEnabled),
    mName(name),
    mState(NULL),
    mIdle(*this ),
    mAddObjectInProgress(*this ),
    mfsmEventQueue(),
    mFsmInjectInProgress(false),
    mEventCounter(0)
{
    // Initial State
    mIdle.Entry();

    if(NULL != mState)
    {
       while( !mState->RunToCompletion() )
       {
          continue;
       }
    }
}

/*** WARNING: Code AUTO-GENERATED from Tr069AddObject.fsm. Do not edit! ***/
AddObjectFsm::~AddObjectFsm()
{
    RSYS_ASSERT_PRINTF(!mFsmInjectInProgress, "AddObjectFsm deleted while event-inject in progress.");

    mfsmEventQueue.clear();
    mCurrentStateTransitionExitsList.clear();
}

/*** WARNING: Code AUTO-GENERATED from Tr069AddObject.fsm. Do not edit! ***/
void AddObjectFsm::InjectAddObject(shared_ptr<RpcAddObject> event)
{
    shared_ptr<FsmEvent> fsmEvent(new FsmEvent_shared_ptr_LT_RpcAddObject_GT_(event));
    Enqueue( AddObjectFsm::FSM_EVENT_AddObject, fsmEvent);
}
/*** WARNING: Code AUTO-GENERATED from Tr069AddObject.fsm. Do not edit! ***/
void AddObjectFsm::InjectMibCreateObjectCnf(shared_ptr<MibCreateObjectCnf> event)
{
    shared_ptr<FsmEvent> fsmEvent(new FsmEvent_shared_ptr_LT_MibCreateObjectCnf_GT_(event));
    Enqueue( AddObjectFsm::FSM_EVENT_MibCreateObjectCnf, fsmEvent);
}
/*** WARNING: Code AUTO-GENERATED from Tr069AddObject.fsm. Do not edit! ***/
void AddObjectFsm::Enqueue( EventId eventId, shared_ptr<FsmEvent> fsmEvent )
{
    RSYS_ASSERT(eventId < NUMBER_OF_INJECTABLE_EVENTS);

    // Reentrancy Protection is NOT intended to make thread-safe
    shared_ptr<QueuedFsmEvent>  qEvent(new QueuedFsmEvent(eventId, fsmEvent));
    mfsmEventQueue.push_back(qEvent);

    if(!mFsmInjectInProgress)
    {
        mFsmInjectInProgress = true;

        list< shared_ptr<QueuedFsmEvent> >::iterator event = mfsmEventQueue.begin();

        while( event != mfsmEventQueue.end() )
        {
            RSYS_ASSERT(*event);
            RSYS_ASSERT(mState);

            EventId queuedEventId = (*event)->mId;

            RSYS_ASSERT(queuedEventId < NUMBER_OF_INJECTABLE_EVENTS);

            if( !mState->DeferEvent( queuedEventId ) )
            {
                ++mEventCounter;

                if(mFsmTraceEnabled) { TRACE_PRINTF("%s.%u: %s <--(%s)-- ", mName.c_str(), mEventCounter, mState->mName.c_str(), mEventName[queuedEventId] ); }

                mState->Inject(queuedEventId, (*event)->mFsmEvent);

                while( !mState->RunToCompletion() )
                {
                    continue;
                }

                mfsmEventQueue.erase(event);
                event = mfsmEventQueue.begin();
            }
            else
            {
                if(mFsmTraceEnabled) { TRACE_PRINTF("%s.-: %s (%s deferred)", mName.c_str(), mState->mName.c_str(), mEventName[queuedEventId] ); };
                event++;
            }
        }

        mFsmInjectInProgress = false;
    }
    else
    {
        if(mFsmTraceEnabled) { TRACE_PRINTF("%s.-: (%s enqueued)", mName.c_str(), mEventName[eventId] ); }
    }
}

/*** WARNING: Code AUTO-GENERATED from Tr069AddObject.fsm. Do not edit! ***/
const char * AddObjectFsm::mEventName[NUMBER_OF_INJECTABLE_EVENTS] =
{
    "AddObject",
    "MibCreateObjectCnf",
};

/*** WARNING: Code AUTO-GENERATED from Tr069AddObject.fsm. Do not edit! ***/
void AddObjectFsm::SimpleState::Inject(
    EventId eventId,
    shared_ptr<FsmEvent> fsmEvent
    )
{
    RSYS_ASSERT(eventId < NUMBER_OF_INJECTABLE_EVENTS);

    switch(eventId)
    {
        case AddObjectFsm::FSM_EVENT_AddObject:
        {
            RSYS_ASSERT(FSM_EVENT_TYPE_shared_ptr_LT_RpcAddObject_GT_ == fsmEvent->mEventType);
            shared_ptr<FsmEvent_shared_ptr_LT_RpcAddObject_GT_> event = dynamic_pointer_cast<FsmEvent_shared_ptr_LT_RpcAddObject_GT_>(fsmEvent);
            InjectAddObject(event->mEvent);
        }
        break;

        case AddObjectFsm::FSM_EVENT_MibCreateObjectCnf:
        {
            RSYS_ASSERT(FSM_EVENT_TYPE_shared_ptr_LT_MibCreateObjectCnf_GT_ == fsmEvent->mEventType);
            shared_ptr<FsmEvent_shared_ptr_LT_MibCreateObjectCnf_GT_> event = dynamic_pointer_cast<FsmEvent_shared_ptr_LT_MibCreateObjectCnf_GT_>(fsmEvent);
            InjectMibCreateObjectCnf(event->mEvent);
        }
        break;

        default:
            RSYS_ASSERT(false);
            break;
    }
}

/*** WARNING: Code AUTO-GENERATED from Tr069AddObject.fsm. Do not edit! ***/
void AddObjectFsm::Idle::InjectAddObject(
    shared_ptr<RpcAddObject> event
    )
{
    {
        mFsm.mState->Exit();
        mFsm.TracePoint( "Action SendCreateMibObjectReq" );

        switch( mFsm.mInterface.SendCreateMibObjectReq(event))
        {
            case AddObjectFsmActionSendCreateMibObjectReq::FSM_ACTION_SUCCESS:
            {
                mFsm.TracePoint( "SendCreateMibObjectReq=SUCCESS" );

                mFsm.mAddObjectInProgress.Entry();
            }
            break;

            case AddObjectFsmActionSendCreateMibObjectReq::FSM_ACTION_ADD_OBJECT_NOT_SUPPORTED:
            {
                mFsm.TracePoint( "SendCreateMibObjectReq=ADD_OBJECT_NOT_SUPPORTED" );

                mFsm.mIdle.Entry();
            }
            return;

            case AddObjectFsmActionSendCreateMibObjectReq::FSM_ACTION_MAX_ENTRIES_EXCEEDED:
            {
                mFsm.TracePoint( "SendCreateMibObjectReq=MAX_ENTRIES_EXCEEDED" );

                mFsm.mIdle.Entry();
            }
            return;
        }

    }
}

// Event MibCreateObjectCnf not handled in state Idle

// State Idle has no deferred events.

// Event AddObject deferred in state AddObjectInProgress

/*** WARNING: Code AUTO-GENERATED from Tr069AddObject.fsm. Do not edit! ***/
void AddObjectFsm::AddObjectInProgress::InjectMibCreateObjectCnf(
    shared_ptr<MibCreateObjectCnf> event
    )
{
    {
        mFsm.mState->Exit();
        mFsm.TracePoint( "Action SendAddObjectResponse" );

        mFsm.mInterface.SendAddObjectResponse(event);

        mFsm.mIdle.Entry();
    }
}

/*** WARNING: Code AUTO-GENERATED from Tr069AddObject.fsm. Do not edit! ***/
bool AddObjectFsm::AddObjectInProgress::DeferEvent( EventId eventId ) const
{
    switch( eventId )
    {
        case AddObjectFsm::FSM_EVENT_AddObject:
            return true;


        default:
            return false;
    }
}

} // -namespace-

