///////////////////////////////////////////////////////////////////////////////
//
// SerialisationIds.h
//
// Contains all our serialisation IDs so it is easier to manage their
// uniqueness.
//
// Copyright Radisys Limited
//
///////////////////////////////////////////////////////////////////////////////

#if (!defined(__SerialisationIds_h_) || \
     defined(ENUM_GENERATE_STRINGS) || \
     defined(ENUM_GENERATE_TABLE) || \
     defined(SERID_GENERATE))

#if (!defined(ENUM_GENERATE_STRINGS) && !defined(ENUM_GENERATE_TABLE) && !defined(SERID_GENERATE))
    #define __SerialisationIds_h_
#endif

///////////////////////////////////////////////////////////////////////////////
// System Includes
///////////////////////////////////////////////////////////////////////////////

#ifndef SERID_GENERATE

// Map to standard EnumToString definitions
#include <system/EnumToString.h>

#define SERID_ENUM_ELEMENT_VAL(sERiD, cLASS, nUM)  ENUM_ELEMENT_VAL(sERiD, nUM)
#define SERID_ENUM_ELEMENT(sERiD, clASS)           ENUM_ELEMENT(sERiD)

#endif

///////////////////////////////////////////////////////////////////////////////
// Typedefs
///////////////////////////////////////////////////////////////////////////////

/**
 * Enumeration of serialisation IDs.  Many of these are used to identify
 * messages in the system. Note that these are serialised in 16 bits, so don't make anything require
 * more than this or it will all fall down in a steaming heap of dung.
 *
 * Macro nastiness allows you to use e.g. SerialisationIdToString(SERIALISATION_ID_REGISTER_ENTITY_REQ)
 */
ENUM_START(SerialisationId)
{
    /**
     * SetParameterAttributes
     */
    SERID_ENUM_ELEMENT_VAL(SERIALISATION_ID_SET_PARAMETER_ATTRIBUTE, SetParameterAttribute, 21) //< DO NOT CHANGE THIS VALUE!  SetParameterAttribute objects are serialised to NV.

    /**
     * Alarm event.
     */
    SERID_ENUM_ELEMENT_VAL(SERIALISATION_ID_ALARM_EVENT, AlarmEvent, 22) //< DO NOT CHANGE THIS VALUE!  AlarmEvent objects are serialised to NV.

    /**
     * KPIs
     */
    SERID_ENUM_ELEMENT_VAL(SERIALISATION_ID_KPI_GROUP, KpiGroup, 23) //< DO NOT CHANGE THIS VALUE!  KpiGroup objects are serialised to NV.
    SERID_ENUM_ELEMENT(SERIALISATION_ID_KPI_READ_REQ, KpiReadReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_KPI_READ_CNF, KpiReadCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_KPI_CONFIGURE_REQ, KpiConfigureReq)
    //ENUM_ELEMENT(SERIALISATION_ID_KPI_CONFIGURE_CNF)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_KPI_REGISTER_REQ, KpiRegisterReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_KPI_COLL_REQ, KpiCollectionReq )
    SERID_ENUM_ELEMENT(SERIALISATION_ID_L2TIMER_NOTIFY, L2TimerNotify) 

    /**
     * Misc serialisable classes.
     */
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FAP_ID, FapId)

    /**
     * General management messages.
     *
     * DO NOT CHANGE THE FIXED VALUES BELOW!
     * These values form part of the external API required for split-system operation.
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_MGMT_BASE, 0x0800)
    SERID_ENUM_ELEMENT_VAL(SERIALISATION_ID_REGISTER_ENTITY_REQ, RegisterEntityReq, 0x0801)
    SERID_ENUM_ELEMENT_VAL(SERIALISATION_ID_REGISTER_ENTITY_CNF, RegisterEntityCnf, 0x0802)
    SERID_ENUM_ELEMENT_VAL(SERIALISATION_ID_MF_SET_ADMIN_STATE_REQ, MfSetAdminStateReq, 0x0803)
    SERID_ENUM_ELEMENT_VAL(SERIALISATION_ID_MF_SET_ADMIN_STATE_CNF, MfSetAdminStateCnf, 0x0804)
    SERID_ENUM_ELEMENT_VAL(SERIALISATION_ID_MF_OP_STATE_INFORM_IND, MfOpStateInformInd, 0x0805)
    SERID_ENUM_ELEMENT_VAL(SERIALISATION_ID_MESSAGING_ROUTE_IND, MessagingRouteInd, 0x0806)
    SERID_ENUM_ELEMENT_VAL(SERIALISATION_ID_OAM_ACTION_REQ, OamActionReq, 0x0807)
    SERID_ENUM_ELEMENT_VAL(SERIALISATION_ID_OAM_ACTION_CNF, OamActionCnf, 0x0808)
    SERID_ENUM_ELEMENT_VAL(SERIALISATION_ID_REQUEST_START_IND, RequestStartInd, 0x0809)
    SERID_ENUM_ELEMENT_VAL(SERIALISATION_ID_REQUEST_START_RSP, RequestStartRsp, 0x080A)

    /**
     * Mib Parameter types
     */
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_ATTRIBUTE_VALUE_U32, MibAttributeValueU32)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_ATTRIBUTE_VALUE_U32ARRAY, MibAttributeValueU32Array)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_ATTRIBUTE_VALUE_S32, MibAttributeValueS32)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_ATTRIBUTE_VALUE_S32ARRAY, MibAttributeValueS32Array)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_ATTRIBUTE_VALUE_STRING, MibAttributeValueString)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_ATTRIBUTE_VALUE_STRINGARRAY, MibAttributeValueStringArray)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_ATTRIBUTE_VALUES, MibAttributeValues)

    /**
     * Other MIB classes.
     */
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_DN, MibDN)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_RDN, MibRDN)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_ATTR_VALIDATION_FAILURES, MibAttrValidationFailures)

    /**
     * MIB Messaging
     */
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_CREATE_OBJECT_REQ, MibCreateObjectReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_CREATE_OBJECT_CNF, MibCreateObjectCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_DELETE_OBJECT_REQ, MibDeleteObjectReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_DELETE_OBJECT_CNF, MibDeleteObjectCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_VALIDATE_ATTRIBUTES_REQ, MibValidateAttributesReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_VALIDATE_ATTRIBUTES_CNF, MibValidateAttributesCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_SET_ATTRIBUTES_REQ, MibSetAttributesReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_SET_ATTRIBUTES_CNF, MibSetAttributesCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_GET_ATTRIBUTES_REQ, MibSetAttributesReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_GET_ATTRIBUTES_CNF, MibGetAttributesCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_DELETE_ATTRIBUTES_REQ, MibDeleteAttributesReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_DELETE_ATTRIBUTES_CNF, MibDeleteAttributesCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_SUBSCRIBE_ATTRIBUTES_REQ, MibSubscribeAttributesReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_SUBSCRIBE_ATTRIBUTES_CNF, MibSubscribeAttributesCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_SUBSCRIBE_ATTRIBUTES_IND, MibSubscribeAttributesInd)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_SUBSCRIBE_ATTRIBUTES_DELETE_IND, MibSubscribeAttributesDeleteInd)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_UNSUBSCRIBE_REQ, MibUnsubscribeReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_MIB_UNSUBSCRIBE_CNF, MibUnsubscribeCnf)

    /**
     * Tracing.
     */
    SERID_ENUM_ELEMENT(SERIALISATION_ID_SET_TRACE_MASKS_REQ, SetTraceMasksReq)

    /**
     * FTP
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_FTP_BASE, 0x900)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FTP_REQ, FtpReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FTP_CNF, FtpCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FTP_COMPLETE_IND, FtpCompleteInd)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FTP_ABORT, FtpAbort)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_UPLOAD_LOG_REQ,UploadLogReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_AUTONOMOUS_TRANSFER_COMP,AutonomousTransferComp)

    // Deprecated...
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FTP_GET_REQ, FtpGetReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FTP_GET_CNF, FtpGetCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FTP_PUT_REQ, FtpPutReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FTP_PUT_CNF, FtpPutCnf)
    // ...end deprecated.

    /**
     * Software Update
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_SW_UPDATE_BASE, 0x980)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_SW_UPDATE_REQ, ApplyUpdateReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_SW_UPDATE_CNF, ApplyUpdateCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_SW_INSTALL_REQ, InstallUpdateReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_SW_INSTALL_CNF, InstallUpdateCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_SW_ACTIVATE_REQ, ActivateUpdateReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_SW_ACTIVATE_CNF, ActivateUpdateCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_SW_REVERT_REQ, RevertUpdateReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_SW_REVERT_CNF, RevertUpdateCnf)

    /**
     * CPHY Messaging.
     * Starts at 0x00001000
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_CPHY_BASE, 0x1000)

    /* CPHY Mode Independent Messages */
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_HW_CONFIG_REQ, CPhyHwConfigReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_HW_CONFIG_CNF, CPhyHwConfigCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_MODE_CHANGE_REQ, CPhyModeChangeReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_MODE_CHANGE_CNF, CPhyModeChangeCnf)

    /* CPHY REM WCDMA Messages */
    SERID_ENUM_ELEMENT_VAL(SERIALISATION_ID_CPHY_REM_FIND_CELL_REQ, CPhyRemWcdmaFindCellReq, 0x1100)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_REM_FIND_CELL_CNF, CPhyRemWcdmaFindCellCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_REM_WCDMA_COARSE_FREQ_LOCK_REQ, CPhyRemWcdmaCoarseFreqLockReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_REM_WCDMA_COARSE_FREQ_LOCK_CNF, CPhyRemWcdmaCoarseFreqLockCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_REM_WCDMA_FREQ_OFFSET_MEAS_REQ, CPhyRemWcdmaFreqOffsetMeasReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_REM_WCDMA_FREQ_OFFSET_MEAS_CNF, CPhyRemWcdmaFreqOffsetMeasCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_REM_SIB_DECODE_REQ, CPhyRemSibDecodeReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_REM_SIB_DECODE_IND, CPhyRemSibDecodeInd)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_REM_SIB_DECODE_CNF, CPhyRemSibDecodeCnf)
    /* Adding messages for qc_cl_changes*/
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_REM_SIB_DECODE_COMPLETE, CPhyRemSibDecodeComplete)
    /* Adding messages for TFCS freq-sync */
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NLM_COSC_REQ, CPhyNlmCoscReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NLM_COSC_CNF, CPhyNlmCoscCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NLM_ERR_IND, CPhyNlmErrInd)

    /* CPHY Node B Messages */
    SERID_ENUM_ELEMENT_VAL(SERIALISATION_ID_CPHY_NODEB_CONFIG_REQ, CPhyNodeBConfigReq, 0x1200)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_CONFIG_CNF, CPhyNodeBConfigCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_TX_ENABLE_REQ, CPhyNodeBTxEnableReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_TX_ENABLE_CNF, CPhyNodeBTxEnableCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_TX_DPCH_ENABLE_REQ, CPhyNodeBTxDpchEnableReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_TX_DPCH_ENABLE_CNF, CPhyNodeBTxDpchEnableCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_STAT_IND, CPhyNodeBStatInd)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_COMPRESSED_MODE_REQ, CPhyNodeBCompressedModeReq)
    //SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_COMPRESSED_MODE_CNF)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_CCTRCH_SETUP_REQ, CPhyNodeBCctrchSetupReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_CCTRCH_REMOVE_REQ, CPhyNodeBCctrchRemoveReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_CCTRCH_REMOVE_CNF, CPhyNodeBCctrchRemoveCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_CCTRCH_CNF, CPhyNodeBCctrchCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_PCH_ADD_REQ, CPhyNodeBPchAddReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_PCH_ADD_CNF, CPhyNodeBPchAddCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_PCH_REMOVE_REQ, CPhyNodeBPchRemoveReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_PCH_REMOVE_CNF, CPhyNodeBPchRemoveCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_SCCPCH_CONFIG_REQ, CPhyNodeBSccpchConfigReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_SCCPCH_CONFIG_CNF, CPhyNodeBSccpchConfigCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_SYNC_IND, CPhyNodeBSyncInd)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_OUT_OF_SYNC_IND, CPhyNodeBOutOfSyncInd)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_RACH_CONFIG_REQ, CPhyNodeBRachConfigReq)
    //SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_RACH_CONFIG_CNF)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_NODEB_SIB_MESSAGE, CPhyNodeBSibMessage)

    /* CPHY REM GSM Messages */
    SERID_ENUM_ELEMENT_VAL(SERIALISATION_ID_CPHY_REM_GSM_RSSI_SCAN_REQ, CPhyRemGsmRssiScanReq, 0x1400)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_REM_GSM_RSSI_SCAN_CNF, CPhyRemGsmRssiScanCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_REM_GSM_FIND_CELL_REQ, CPhyRemGsmFindCellReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_REM_GSM_FIND_CELL_CNF, CPhyRemGsmFindCellCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_REM_GSM_BCCH_DECODE_IND, CPhyRemGsmBcchDecodeInd)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_REM_GSM_STOP_BCCH_DECODE_REQ, CPhyRemGsmStopBcchDecodeReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CPHY_REM_GSM_STOP_BCCH_DECODE_CNF, CPhyRemGsmStopBcchDecodeCnf)

    /* CARB messages */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_CARB_BASE, 0x1500)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CARB_OSC_DAC_WRITE_REQ, CarbOscDacWriteReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CARB_LED_SET_REQ, CarbLedSetReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CARB_TEMPERATURE_REQ, CarbTemperatureReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CARB_TEMPERATURE_CNF, CarbTemperatureCnf)

    /**
     * CRLC Messaging.
     * Starts at 0x00002000
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_CRLC_BASE, 0x2000)

    /**
     * CMAC Messaging.
     * Starts at 0x00003000
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_CMAC_BASE, 0x2100)

    /**
     * REM Messaging
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_REM_BASE, 0x3000)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_REM_SCAN_REQ, RemScanReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_REM_SCAN_CNF, RemScanCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_GSM_REM_SCAN_REQ, GsmRemScanReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_GSM_REM_SCAN_CNF, GsmRemScanCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_STOP_REM_SCAN_REQ, StopRemScanReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_REM_REQ, RemReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_REM_CNF, RemCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_REM_GSM_REM_DAC_ESTIMATE_IND, RemGsmRemDACEstimateInd)
    /* Adding messages for TFCS freq-sync */
    SERID_ENUM_ELEMENT(SERIALISATION_ID_NLM_COSC_REQ, NlmCoscReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_NLM_COSC_CNF, NlmCoscCnf)

    /**
     * RLC Messaging.
     * Starts at 0x00005000
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_RLC_BASE, 0x4000)

    /**
     * Media management messages.
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_MEDIA_BASE, 0x4100)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_IU_PS_ROUTE_MGMT, IuPsRouteMgmtMessage)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_IU_CS_ROUTE_MGMT, IuCsRouteMgmtMessage)
    //ENUM_ELEMENT(SERIALISATION_ID_CN_CS_USER_PLANE_SIM_ROUTE_MGMT)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CS_UP_INITIALISATION_FAILURE, IuCsUpInitialisationFailure)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CS_UP_INITIALISATION_SUCCESS, IuCsUpInitialisationSuccess)

    /**
     * Connection Orientated Messaging
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_COM_BASE, 0x4200)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_COM_CONNECTION_REQ, MessagingConnectionReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_COM_CONNECTION_CONF, MessagingConnectionConf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_COM_CONNECTION_REF, MessagingConnectionRef)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_COM_RELEASE_REQ, MessagingReleaseReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_COM_RELEASE_CONF, MessagingReleaseConf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_COM_DATA_IND, MessagingDataInd)
    /* Always leave this as the last of the _ID_COM_ messages */
    ENUM_ELEMENT(SERIALISATION_ID_COM_END_OF_COM_MESSAGES)

    /**
     * For backward compatibility with NAS Comms
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_NAS_COMMS_BASE, 0x4300)

    /**
     * Network syncronisation control messages
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_FNTP_BASE, 0x4400)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FNTP_GET_FREQUENCY_OFFSET_REQ, FNTPGetFrequencyOffsetReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FNTP_GET_FREQUENCY_OFFSET_CNF, FNTPGetFrequencyOffsetCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FNTP_GET_FREQUENCY_OFFSET_IND, FNTPGetFrequencyOffsetInd)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FNTP_INIT_REQ, FNTPInitReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FNTP_INIT_CNF, FNTPInitCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FNTP_SET_SAMPLE_MODE_REQ, FNTPSetSampleModeReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FNTP_SET_SAMPLE_MODE_CNF, FNTPSetSampleModeCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FNTP_IS_ALIVE_IND, FNTPIsAliveInd)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FREQ_SYNC_IS_ALIVE_IND, FreqSyncIsAliveInd)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_FREQ_SYNC_SET_FAKE_DAC, FreqSyncSetFakeDAC)

    /**
     * RRC messaging, replacements for old NASAppPayload based messages above
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_RRC_BASE, 0x4500)

    /**
     * CLI
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_CLI_BASE, 0x4600)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CLI_EXECUTE_CMD_REQ, CliExecuteCmdReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CLI_EXECUTE_CMD_IND, CliExecuteCmdInd)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CLI_EXECUTE_CMD_PROGRESS_IND, CliExecuteCmdProgressInd)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_CLI_EXECUTE_CMD_CNF, CliExecuteCmdCnf)

    /**
     * Watchdog
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_WATCHDOG_BASE, 0x4700)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_WATCHDOG_ADD_PID_REQ, WatchdogAddPidReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_WATCHDOG_REMOVE_PID_REQ, WatchdogRemovePidReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_WATCHDOG_KICK_REQ, WatchdogKickReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_WATCHDOG_KICK_STOP_REQ, WatchdogKickStopReq)

    /**
     * IKE
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_IKE_BASE, 0x4800)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_IKE_TUNNEL_CREATE_REQ, IkeTunnelCreateReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_IKE_TUNNEL_CREATE_CNF, IkeTunnelCreateCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_IKE_TUNNEL_DELETE_REQ, IkeTunnelDeleteReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_IKE_TUNNEL_DELETE_CNF, IkeTunnelDeleteCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_IKE_TUNNEL_CONNECT_IND, IkeTunnelConnectInd)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_IKE_TUNNEL_DISCONNECT_IND, IkeTunnelDisconnectInd)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_HW_CRYPTO_AVAILABLE_IND, HwCryptoAvailableInd)

    /**
     * TENPIN
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_TENPIN_BASE, 0x4900)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_TENPIN_FIREWALL_OPEN_REQ, TenpinFirewallOpenReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_TENPIN_FIREWALL_OPEN_CNF, TenpinFirewallOpenCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_TENPIN_FIREWALL_CLOSE_REQ, TenpinFirewallCloseReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_TENPIN_FIREWALL_CLOSE_CNF, TenpinFirewallCloseCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_TENPIN_SIGNATURE_VERIFY_REQ, TenpinSignatureVerifyReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_TENPIN_SIGNATURE_VERIFY_CNF, TenpinSignatureVerifyCnf)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_TENPIN_DNS_SERVER_ADD_REQ, TenpinDnsServerAddReq)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_TENPIN_DNS_SERVER_ADD_CNF, TenpinDnsServerAddCnf)

    /**
     * CRRC
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_CRRC_BASE, 0x4a00)

    /**
     * RRM
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_RRM_BASE, 0x4b00)

    /**
     * Presence Indication
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_CIU_BASE, 0x4c00)

    /**
     * LED status notification
     */
    ENUM_ELEMENT_VAL(SERIALISATION_ID_OAM_BASE, 0x00005000)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_OAM_LED_STATE_INFORM, OamLedStateInformInd)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_ENODEB_INIT_CONFIG_COMPLETE, InitConfigComplete)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_UPDATE_EUTRAINUSE_CELLLIST, UpdateInUseEutraCellList)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_UPDATE_UTRAINUSE_CELLLIST, UpdateInUseUtraCellList)
    SERID_ENUM_ELEMENT(SERIALISATION_ID_EVENT_NOTIFY, EventNotify)

    /**
     * REM Serialization Id
     */
    
#ifdef LTE_REM 
     SERID_ENUM_ELEMENT(SERIALISATION_ID_REM_OAM_ABORT_SCAN, CRemOamAbortScanCmd)
     SERID_ENUM_ELEMENT(SERIALISATION_ID_REM_OAM_START_SCAN, CRemOamStartScanCmd)
     SERID_ENUM_ELEMENT(SERIALISATION_ID_REM_SON_START_CARRIER_EXPRESS_SCAN, CRemSonStartCarrExpScan)
     SERID_ENUM_ELEMENT(SERIALISATION_ID_REM_SON_START_PCI_EXPRESS_SCAN, CRemSonStartPciExpScan)
     SERID_ENUM_ELEMENT(SERIALISATION_ID_REM_SCAN_STATUS, CRemScanStatus)
    // SERID_ENUM_ELEMENT(SERIALISATION_ID_REM_LTE_SCAN_RESULT, CRemLteScanResult)
    // SERID_ENUM_ELEMENT(SERIALISATION_ID_REM_WCDMA_SCAN_RESULT, CRemWcdmaScanResult)
     SERID_ENUM_ELEMENT(SERIALISATION_ID_REM_SON_CARRIER_SCAN_RESULT, CRemSonCarrScanResult)
     SERID_ENUM_ELEMENT(SERIALISATION_ID_REM_SON_PCI_SCAN_RESULT, CRemSonPciScanResult)
#endif

     ENUM_ELEMENT_VAL(SERIALISATION_ID_INVALID, 0xffff)
}
ENUM_END(SerialisationId)

#endif
