///////////////////////////////////////////////////////////////////////////////
//
// Led_fsm_interface.h
//
// Autogenerated from led.fsm
//
// Fsm Interface Class
//
// Copyright radisys Limited
//
///////////////////////////////////////////////////////////////////////////////

#ifndef __Led_fsm_interface_h_
#define __Led_fsm_interface_h_
///////////////////////////////////////////////////////////////////////////////
// System Includes
///////////////////////////////////////////////////////////////////////////////

#include <system/ThreadWithQueue.h>

///////////////////////////////////////////////////////////////////////////////
// Local Includes
///////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////
// Defines
///////////////////////////////////////////////////////////////////////////////

// Definition at end of file
#undef LedInterfaceDefinition

namespace Led
{

/*** WARNING: Code AUTO-GENERATED from led.fsm. Do not edit! ***/
class LedFsmInterface
{
public:
    LedFsmInterface() {}
    virtual ~LedFsmInterface() {}
    
    // Actions
    
    // Entry/Exit
    virtual void InitialStateEntry() = 0;
    virtual void WrongTemperatureEntry() = 0;
    virtual void FapErrorEntry() = 0;
    virtual void PowerOnSelfTestEntry() = 0;
    virtual void ConnectToServerEntry() = 0;
    virtual void NoConnectionToServerEntry() = 0;
    virtual void NotOperationalEntry() = 0;
    virtual void OperationalErrorEntry() = 0;
    virtual void OperationalEntry() = 0;
    
    // Guard Conditions
    
};
} // -namespace-

// Auto-updating Interface Definition
#define LedInterfaceDefinition()  \
    virtual void InitialStateEntry(); \
    virtual void WrongTemperatureEntry(); \
    virtual void FapErrorEntry(); \
    virtual void PowerOnSelfTestEntry(); \
    virtual void ConnectToServerEntry(); \
    virtual void NoConnectionToServerEntry(); \
    virtual void NotOperationalEntry(); \
    virtual void OperationalErrorEntry(); \
    virtual void OperationalEntry()

#endif // __Led_fsm_interface_h_

