###############################################################################
#
# Makefile Options:
#
#  make [clean]
#
# Copyright radisys Limited
#
###############################################################################

TOP = $(shell pwd)/../../../../..

TARGET_NAME = oam-unittest

#CPP_SRCS = 

vpath %.cpp ..

INCLUDE_PATHS = \
  $(TOP)/apps/fap

include $(TOP)/makefrags/unittest_sharedlibrary.mk
