#!/bin/sh

cd /dbx/trace
# Include kernel messages by popular demand
cp /var/log/messages env_messages.txt 2>/dev/null
tar -cvf previous.tar /dbx/trace/*.txt
gzip previous.tar
mkdir -p /mnt/log
mv previous.tar.gz /mnt/log/previous.tar.gz
rm -f env_messages.txt
sync
reboot
