#!/bin/sh

APP_FILES="watchdogd oam mib-firkler rrc rrm iu l2 l1 cs-user-plane ps-user-plane ntp-client post-office pc-rem-cl rem-test-app rem-app oam-rem tr069 tenpin service-api sw-update clogd  gps "

for APP_FILE in $APP_FILES
do
  echo " Killing $APP_FILE ..."
  killall $APP_FILE 2> /dev/null
done
