#!/bin/sh
# make install SUBDIRS="nanohttp libcsoap"

./configure --build=i686-pc-linux \
            --host=mipsel-unknown-linux-gnu \
            --with-endianness=little \
            --enable-shared=no \
            --prefix=`pwd`/../../libs/bin/csoap/hbs2-4/mipsel-unknown-linux-gnu \
            --with-xml-prefix=`pwd`/../../libs/bin/libxml2-2.7.2/hbs2-4/mipsel-unknown-linux-gnu \
            CC=mipsel-unknown-linux-gnu-gcc \
            AR=mipsel-unknown-linux-gnu-ar
