#!/bin/sh

#Compilation script for building libsoap-1.1.0
########################################################################################
make SUBDIRS="nanohttp libcsoap"

make install SUBDIRS="nanohttp libcsoap"
########################################################################################
