#!/bin/sh

##########################################################################################
make clean SUBDIRS="nanohttp libcsoap"
echo "************************************************"
CROSS_COMPILER=$1
echo $CROSS_COMPILER
echo "************************************************"
./configure --build=i686-pc-linux \
            --host=$CROSS_COMPILER \
            --with-endianness=little \
            --enable-shared=no \
            --prefix=`pwd`/../../libs/bin/csoap/hbs2-4/$CROSS_COMPILER \
            --with-xml-prefix=`pwd`/../../libs/bin/libxml2/hbs2-4/$CROSS_COMPILER \
            --with-ssl --enable-static\
            --prefix=`pwd`/../openssl-0.9.8/openssl-0.9.8rl/\
            CC=$CROSS_COMPILER-gcc \
            AR=$CROSS_COMPILER-ar \
##########################################################################################
