///////////////////////////////////////////////////////////////////////////////
//
// Cli_fsm_interface.h
//
// Autogenerated from Cli.fsm
//
// Fsm Interface Class
//
// Copyright Radisys Limited
//
///////////////////////////////////////////////////////////////////////////////

#ifndef __Cli_fsm_interface_h_
#define __Cli_fsm_interface_h_
///////////////////////////////////////////////////////////////////////////////
// System Includes
///////////////////////////////////////////////////////////////////////////////

#include <system/ThreadWithQueue.h>

///////////////////////////////////////////////////////////////////////////////
// Local Includes
///////////////////////////////////////////////////////////////////////////////

#include "CliFsmTypes.h"


/*** WARNING: Code AUTO-GENERATED from Cli.fsm. Do not edit! ***/
class CommandLineFsmInterface
{
public:
    CommandLineFsmInterface() {}
    virtual ~CommandLineFsmInterface() {}
    
    // Actions
    virtual void FeedbackStopReason(shared_ptr<std::string>) = 0;
    virtual void FeedbackProgress(shared_ptr<CliExecuteCmdProgressInd>) = 0;
    virtual void FeedbackResponse(shared_ptr<CliExecuteCmdInd>) = 0;
    virtual void FeedbackCompletionResult(shared_ptr<CliExecuteCmdCnf>) = 0;
    virtual void FeedbackCommandRejected(shared_ptr<CliCommand>) = 0;
    virtual void FeedbackTimeout(void*) = 0;
    virtual void SendCommandReq(shared_ptr<CliCommand>) = 0;
    
    // Entry/Exit
    virtual void AwaitCommandEntry() = 0;
    virtual void AwaitCommandExit() = 0;
    virtual void UserIoThreadRunningEntry() = 0;
    virtual void UserIoThreadRunningExit() = 0;
    virtual void CommandInProgressEntry() = 0;
    virtual void CommandInProgressExit() = 0;
    virtual void QuittingEntry() = 0;
    
    // Guard Conditions
    virtual bool QueryQuitCommanded(shared_ptr<CliCommand>) = 0;
    virtual bool QueryCommandEmpty(shared_ptr<CliCommand>) = 0;
    virtual bool CommandLineParser(shared_ptr<CliCommand>) = 0;
    
};

#endif // __Cli_fsm_interface_h_

